function build_w08_models()
% BUILD_W08_MODELS  8주차 모델 두 개를 만든다.
%
%   W08_0_offline : Gazebo 없이 도는 틸팅 추진기 + 배분 + DP
%   W08_1_vrx     : 같은 제어기를 VRX 와 연결한 것
%
%   실행 전에 반드시 >> W08_setup 을 먼저 실행할 것.
%
%   신호 흐름 (좌 -> 우)
%     DPRef -> DPCtrl -> Alloc -> Thrusters -> MotionModel(+Env) -> 로깅

    here = fileparts(mfilename('fullpath'));
    addpath(fullfile(here, '..', '..', '_tools'));
    cd(here);

    if evalin('base', '~exist(''T_pinv'',''var'')')
        error('먼저 W08_setup 을 실행하십시오.');
    end

    build_offline();
    build_vrx();
    % 최상위 배치 — autorouting 에 맡기지 않고 규칙대로 직접 놓는다.
    % check_lines 의 일곱 항목이 전부 0 이 합격선 (references/line-routing.md)
    lay_chain('W08_0_offline', ...
              {'DPRef','WaveFilter','DPCtrl','Alloc','Thrusters','Env','MotionModel'}, ...
              'Boxes', {'Animate','Logging'}, 'Wrap', 2);
    lay_chain('W08_1_vrx', ...
              {'DPRef','WaveFilter','DPCtrl','Alloc','Thrusters','PoseSubscriber'}, ...
              'Boxes', {'CmdPublisher','Animate','Logging'}, 'Wrap', 2);

    %  색 — 역할표는 _tools/gnc_roles.m 하나뿐이다. 빌더는 부르기만 한다
    for mm = {'W08_0_offline','W08_1_vrx'}
        m = mm{1}; load_system(m);
        paint_roles(m);
        check_colour(m);
        mss_style(m); save_system(m); check_lines(m, false); export_diagram(m);
        close_system(m, 0);
    end

    fprintf('\n완료. 생성된 모델:\n');
    d = dir('*.slx');
    for k = 1:numel(d), fprintf('  %s\n', d(k).name); end
end

% =====================================================================
% 공통 헬퍼
% =====================================================================
function fresh(m)
    if bdIsLoaded(m), close_system(m, 0); end
    if isfile([m '.slx']), delete([m '.slx']); end
    new_system(m); load_system(m);
end

function setSolver(m, stopTime)
    set_param(m, 'SolverType','Fixed-step', 'SolverName','ode4', ...
                 'FixedStep','Ts_ctrl', 'StopTime',stopTime, 'SimulationMode','normal');
end

function setFcn(sys, path, code)
    add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/' path]);
    S = sfroot; B = S.find('Path', [sys '/' path], '-isa','Stateflow.EMChart');
    fpos = get_param([sys '/' path], 'Position');
    B.Script = code;
    set_param([sys '/' path], 'Position', fpos);    % 포트 위치를 저장 뒤와 같게 (사선 방지)
end

function C(m, name, value, x, y)
    add_block('simulink/Sources/Constant', [m '/' name], ...
              'Value', value, 'Position', [x y x+95 y+30]);
end

function F(m, tag, sfx, x, y)
    add_block('simulink/Signal Routing/From', [m '/Fr_' tag '_' sfx], ...
              'Position', [x y x+70 y+25], 'GotoTag', tag);
end

function G(m, tag, x, y)
    add_block('simulink/Signal Routing/Goto', [m '/Go_' tag], ...
              'Position', [x y x+80 y+25], 'GotoTag', tag, 'TagVisibility','global');
end

function note(m, tag, txt, x, y)
    add_block('built-in/Note', [m '/' tag], 'Position',[x y x y], 'Text', txt);
end

% =====================================================================
% 1단 · DP 목표값
function mk_inputs(ss, in, nSig, cfg, dly, clk)
% 단계 입력 만들기 — 신호는 포트로, 설정은 상수로, 상태는 지연으로.
%
%   IN    함수 인자 순서 그대로의 이름 목록. **블록 이름도 이것을 쓴다**
%         뒤의 배선 코드가 이름으로 잇기 때문에 바꾸지 않는다
%   NSIG  바깥에서 들어오는 신호. 개수(앞에서부터) 또는 이름 목록 {'nu'}
%   CFG   {이름, 값}            설정값 -> 상자 안의 Constant
%   DLY   {이름, 출력포트, 초기값}  상태  -> 상자 안의 Unit Delay + 태그
%   CLK   비우지 않으면 그 이름의 블록을 Digital Clock 으로 만든다
%
%   설정값을 최상위에 두면 상수 열이 신호 사슬 앞을 가리고, 상태 되먹임을
%   최상위에 두면 화면을 가로지르는 선이 생긴다. 둘 다 상자 안의 일이다.
if nargin < 6, clk = ''; end

%  숫자면 '앞에서부터 그만큼', 이름 목록이면 그 이름들만 In1 으로 만든다.
%  [2] 같은 1원소 배열은 isscalar 가 참이라 개수와 구별되지 않는다 — 이름을 쓴다.
if iscell(nSig)
    [~, idx] = ismember(nSig, in);
else
    idx = 1:nSig;
end
for p = 1:numel(idx)
    k = idx(p);
    add_block('simulink/Sources/In1', [ss '/' in{k}], ...
              'Position',[40 60+(p-1)*70 75 90+(p-1)*70], 'Port', num2str(p));
end
if ~isempty(clk)
    add_block('simulink/Sources/Digital Clock', [ss '/' clk], ...
              'Position',[40 300 90 330], 'SampleTime','Ts_ctrl');
end
for k = 1:size(cfg,1)
    add_block('simulink/Sources/Constant', [ss '/' cfg{k,1}], ...
              'Position',[40 400+(k-1)*70 130 430+(k-1)*70], 'Value', cfg{k,2});
end
for k = 1:size(dly,1)
    nm = dly{k,1};
    %  블록 이름을 in{} 과 같게 둔다. 그래야 뒤의 배선이 그대로 통한다
    add_block('simulink/Discrete/Unit Delay', [ss '/' nm], ...
              'Position',[240 700+(k-1)*90 315 740+(k-1)*90], ...
              'SampleTime','Ts_ctrl', 'InitialCondition', dly{k,3});
    add_block('simulink/Signal Routing/From', [ss '/Fr_' nm], ...
              'Position',[110 709+(k-1)*90 180 731+(k-1)*90], 'GotoTag', ['s_' nm]);
    add_line(ss, ['Fr_' nm '/1'], [nm '/1'], 'autorouting','on');
end
end

% ---------------------------------------------------------------------
function mk_state_out(ss, fcn, dly)
%MK_STATE_OUT  상태 출력을 태그로 걸어 지연 블록이 받게 한다.
%   상자 밖으로 나가지 않는 값이므로 출력 포트를 만들지 않는다.
for k = 1:size(dly,1)
    nm = dly{k,1};
    add_block('simulink/Signal Routing/Goto', [ss '/Go_' nm], ...
              'Position',[560 709+(k-1)*90 640 731+(k-1)*90], ...
              'GotoTag', ['s_' nm], 'TagVisibility','local');
    add_line(ss, sprintf('%s/%d', fcn, dly{k,2}), ['Go_' nm '/1'], 'autorouting','on');
end
end

% =====================================================================
% 1단 · DP 목표값 (스케줄 + 레퍼런스 모델)
% =====================================================================
function addDPRef(m, x, y)
    ss = [m '/DPRef'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+160 y+120]);

    in  = {'t','mode','tbl','eta0','pre','rpar'};
    cfg = {'mode','dp_mode'; 'tbl','dp_step'; ...
           'eta0','[dp_N0; dp_E0; dp_PSI0]'; ...
           'rpar','[dp_ref_on; dp_vmax; tau_ref; Ts_ctrl]'};
    dly = {'pre',2,'[dp_N0; dp_E0; dp_PSI0]'};
    mk_inputs(ss, in, 0, cfg, dly, 't');

    setFcn(ss, 'Sched', [ ...
'function [eta_d, snew, eta_raw] = Sched(t, mode, tbl, eta0, pre, rpar)'  newline ...
'%#codegen'                                                              newline ...
'% DP setpoint scheduler and REFERENCE MODEL.'                           newline ...
'%'                                                                      newline ...
'%   mode 0 : hold the initial setpoint'                                 newline ...
'%   mode 1 : step through the table  [t  N  E  psi_deg]'                newline ...
'%'                                                                      newline ...
'% A raw step demand is never given to a DP controller. The vessel'      newline ...
'% cannot move at any speed, so a step makes the controller ask for a'   newline ...
'% force the thrusters cannot deliver, and the loop saturates.'          newline ...
'% A reference model turns the step into a feasible trajectory. Here a'  newline ...
'% saturated proportional law is used:'                                  newline ...
'%     v = (eta_raw - eta_d)/tau_ref,   |v| <= v_max'                    newline ...
'% Far from the target the setpoint moves at the constant speed v_max;'  newline ...
'% close to it the approach becomes exponential with time constant'      newline ...
'% tau_ref, so there is no corner at arrival.'                           newline ...
'% Fossen (2011) calls this the reference model; every DP system has'    newline ...
'% one.'                                                                 newline ...
'%'                                                                      newline ...
'% rpar = [on; vx; vy; vPsi; tau_ref; Ts]'                               newline ...
''                                                                       newline ...
'eta_raw = eta0;'                                                        newline ...
'if mode > 0.5'                                                          newline ...
'    n = size(tbl,1);'                                                   newline ...
'    for i = 1:n'                                                        newline ...
'        if t >= tbl(i,1)'                                               newline ...
'            eta_raw = [tbl(i,2); tbl(i,3); tbl(i,4)*pi/180];'           newline ...
'        end'                                                            newline ...
'    end'                                                                newline ...
'end'                                                                    newline ...
''                                                                       newline ...
'if rpar(1) < 0.5'                                                       newline ...
'    eta_d = eta_raw;  snew = eta_raw;'                                   newline ...
'    return'                                                             newline ...
'end'                                                                    newline ...
''                                                                       newline ...
'vmax = rpar(2:4);  tr = rpar(5);  Ts = rpar(6);'                        newline ...
'snew = pre;'                                                            newline ...
'for i = 1:3'                                                            newline ...
'    d = eta_raw(i) - pre(i);'                                           newline ...
'    if i == 3, d = atan2(sin(d), cos(d)); end'                          newline ...
'    v = d/tr;'                                                          newline ...
'    if v >  vmax(i), v =  vmax(i); end'                                 newline ...
'    if v < -vmax(i), v = -vmax(i); end'                                 newline ...
'    snew(i) = pre(i) + v*Ts;'                                           newline ...
'end'                                                                    newline ...
'snew(3) = atan2(sin(snew(3)), cos(snew(3)));'                           newline ...
'eta_d = snew;']);
    set_param([ss '/Sched'],'Position',[180 70 360 480]);

    out = {'eta_d','snew','eta_raw'};
    for k = [1 3]
        add_block('simulink/Sinks/Out1', [ss '/' out{k}], ...
                  'Position',[440 100+(k-1)*90 475 130+(k-1)*90], 'Port', num2str(1+(k>1)));
        add_line(ss, sprintf('Sched/%d',k), [out{k} '/1'], 'autorouting','on');
    end
    for k = 1:numel(in)
        add_line(ss, [in{k} '/1'], sprintf('Sched/%d',k), 'autorouting','on');
    end
    mk_state_out(ss, 'Sched', dly);
    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 1.5단 · 파랑 필터
% =====================================================================
function addWaveFilter(m, x, y)
    ss = [m '/WaveFilter'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+170 y+140]);

    in  = {'eta','nu','pre','par'};
    cfg = {'par','[filt_on; w_filt; Ts_ctrl]'};
    dly = {'pre',3,'[0;0;0;0;0;0]'};
    mk_inputs(ss, in, 2, cfg, dly);

    setFcn(ss, 'Filt', [ ...
'function [eta_f, nu_f, snew] = Filt(eta, nu, pre, par)'                 newline ...
'%#codegen'                                                              newline ...
'% Wave filtering for dynamic positioning.'                              newline ...
'%'                                                                      newline ...
'% First order wave loads make the vessel oscillate at the wave'         newline ...
'% frequency. That motion cannot be counteracted — trying to do so'      newline ...
'% only wears out the thrusters. A DP system therefore feeds the'        newline ...
'% controller with the LOW FREQUENCY part of the motion only.'           newline ...
'% Fossen (2011) 11.4.1 uses a passive observer; here a first order'     newline ...
'% low pass with a cut-off well below the wave frequency is enough to'   newline ...
'% show the effect.'                                                     newline ...
'%'                                                                      newline ...
'% par = [on; wf; Ts]'                                                   newline ...
''                                                                       newline ...
'on = par(1); wf = par(2); Ts = par(3);'                                 newline ...
'z  = [eta; nu];'                                                        newline ...
'if on < 0.5'                                                            newline ...
'    eta_f = eta;  nu_f = nu;  snew = z;'                                newline ...
'    return'                                                             newline ...
'end'                                                                    newline ...
'a = Ts*wf/(1 + Ts*wf);'                                                 newline ...
'snew = pre + a*(z - pre);'                                              newline ...
'% heading must be filtered on the difference, not the raw angle'        newline ...
'd3 = atan2(sin(eta(3) - pre(3)), cos(eta(3) - pre(3)));'                newline ...
'snew(3) = pre(3) + a*d3;'                                               newline ...
'snew(3) = atan2(sin(snew(3)), cos(snew(3)));'                           newline ...
'eta_f = snew(1:3);'                                                     newline ...
'nu_f  = snew(4:6);']);
    set_param([ss '/Filt'],'Position',[220 70 400 330]);

    out = {'eta_f','nu_f','snew'};
    for k = 1:2
        add_block('simulink/Sinks/Out1', [ss '/' out{k}], ...
                  'Position',[440 100+(k-1)*90 475 130+(k-1)*90], 'Port', num2str(k));
        add_line(ss, sprintf('Filt/%d',k), [out{k} '/1'], 'autorouting','on');
    end
    for k = 1:numel(in)
        add_line(ss, [in{k} '/1'], sprintf('Filt/%d',k), 'autorouting','on');
    end
    mk_state_out(ss, 'Filt', dly);
    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 2단 · DP 제어기 (3자유도 PID)
% =====================================================================
function addDPCtrl(m, x, y)
    ss = [m '/DPCtrl'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+190 y+220]);

    in  = {'eta_d','eta','nu','Ipre','par'};
    cfg = {'par','[diag(Kp_dp); diag(Kd_dp); diag(Ki_dp); i_max; Ts_ctrl]'};
    dly = {'Ipre',2,'[0;0;0]'};
    mk_inputs(ss, in, 3, cfg, dly);

    setFcn(ss, 'PID3', [ ...
'function [tau, Inew, eta_e] = PID3(eta_d, eta, nu, Ipre, par)'          newline ...
'%#codegen'                                                              newline ...
'% 3-DOF dynamic positioning controller (Fossen 2011, 12.2.10).'         newline ...
'%'                                                                      newline ...
'%   eta   = [N; E; psi]      position and heading in NED'               newline ...
'%   nu    = [u; v; r]        velocity in BODY'                          newline ...
'%   tau   = -J(psi)'' * (Kp*eta_e + Ki*I) - Kd*nu'                      newline ...
'%'                                                                      newline ...
'% The transpose of the rotation matrix turns a NED position error into' newline ...
'% a BODY force. Damping is taken on BODY velocity directly, so no'      newline ...
'% derivative of the error is needed (same idea as the P-D heading'      newline ...
'% controller of week 7).'                                               newline ...
'%'                                                                      newline ...
'% par = [Kp(1:3); Kd(1:3); Ki(1:3); imax(1:3); Ts]'                     newline ...
''                                                                       newline ...
'Kp = par(1:3);  Kd = par(4:6);  Ki = par(7:9);'                         newline ...
'im = par(10:12); Ts = par(13);'                                         newline ...
''                                                                       newline ...
'e = eta - eta_d;'                                                       newline ...
'e(3) = atan2(sin(e(3)), cos(e(3)));      % smallest signed angle'       newline ...
''                                                                       newline ...
'psi = eta(3);'                                                          newline ...
'J = [ cos(psi), -sin(psi), 0;'                                          newline ...
'      sin(psi),  cos(psi), 0;'                                          newline ...
'             0,         0, 1];'                                         newline ...
''                                                                       newline ...
'% integral state with clamping (anti-windup)'                           newline ...
'Inew = Ipre + Ts*e;'                                                    newline ...
'for i = 1:3'                                                            newline ...
'    lim = im(i)/max(Ki(i), 1e-9);'                                      newline ...
'    if Inew(i) >  lim, Inew(i) =  lim; end'                             newline ...
'    if Inew(i) < -lim, Inew(i) = -lim; end'                             newline ...
'end'                                                                    newline ...
''                                                                       newline ...
'tau = -J'' * ( Kp.*e + Ki.*Inew ) - Kd.*nu;'                            newline ...
'eta_e = e;']);
    set_param([ss '/PID3'],'Position',[220 70 420 400]);

    %  출력 포트 1 tau, 2 eta_e, 3 Inew (적분 상태 — 과제 ④ 에서 적분항 K_i*Inew 를 본다)
    out  = {'tau','Inew','eta_e'};
    port = [1 3 2];
    for k = 1:3
        add_block('simulink/Sinks/Out1', [ss '/' out{k} '_o'], ...
                  'Position',[440 100+(k-1)*90 475 130+(k-1)*90], 'Port', num2str(port(k)));
        add_line(ss, sprintf('PID3/%d',k), [out{k} '_o/1'], 'autorouting','on');
    end
    for k = 1:numel(in)
        add_line(ss, [in{k} '/1'], sprintf('PID3/%d',k), 'autorouting','on');
    end
    mk_state_out(ss, 'PID3', dly);
    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 3단 · 추력 배분
% =====================================================================
function addAlloc(m, x, y)
    ss = [m '/Alloc'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+190 y+180]);

    in  = {'tau','Tp','lim'};
    cfg = {'Tp','T_pinv'; 'lim','[F_max; del_max; alloc_mode]'};
    mk_inputs(ss, in, 1, cfg, {});

    setFcn(ss, 'Allocate', [ ...
'function [Tcmd, Dcmd, sat] = Allocate(tau, Tp, lim)'                     newline ...
'%#codegen'                                                               newline ...
'% Thrust allocation for two azimuth (rotatable) thrusters.'              newline ...
'% Fossen (2011) 12.3.4 — constrained control allocation for azimuth'     newline ...
'% thrusters, solved with the EXTENDED THRUST VECTOR.'                    newline ...
'%'                                                                       newline ...
'% Step 1  f = pinv(T_e) * tau       f = [FxL FyL FxR FyR]'''             newline ...
'%         Because the thruster force is written in Cartesian components,' newline ...
'%         T_e is CONSTANT and its pseudo-inverse can be precomputed.'    newline ...
'%         There is no singular configuration to worry about.'            newline ...
'%'                                                                       newline ...
'% Step 2  Cartesian -> polar   T = |f_i|,  delta = atan2(Fy, Fx)'        newline ...
'%'                                                                       newline ...
'% Step 3  map the demand into the mechanical sector |delta| <= 45 deg'   newline ...
'%           |d| <=  45  : use as is'                                     newline ...
'%           |d| >  135  : REVERSE thrust, d -> d -+ 180'                 newline ...
'%           otherwise   : dead zone, no thrust can be produced'          newline ...
'%'                                                                       newline ...
'% Step 4  saturate the magnitude at F_max'                               newline ...
'%'                                                                       newline ...
'% lim = [F_max; delta_max; mode]'                                        newline ...
'%   mode 1 : dead zone   — demands inside the forbidden sector are'      newline ...
'%            dropped. Simple, but the realised tau is then wrong.'       newline ...
'%   mode 2 : clamp       — the angle is pushed to the nearest sector'     newline ...
'%            edge and the magnitude is scaled by cos of the angle'       newline ...
'%            error, so the useful component is kept.'                    newline ...
''                                                                        newline ...
'f = Tp * tau;'                                                           newline ...
'Fmax = lim(1);  dmax = lim(2);  mode = lim(3);'                          newline ...
''                                                                        newline ...
'Tcmd = zeros(2,1);  Dcmd = zeros(2,1);  sat = 0;'                        newline ...
'for i = 1:2'                                                             newline ...
'    fx = f(2*i-1);  fy = f(2*i);'                                        newline ...
'    Ti = sqrt(fx*fx + fy*fy);'                                           newline ...
'    di = atan2(fy, fx);'                                                 newline ...
'    ad = abs(di);'                                                       newline ...
'    if ad <= dmax'                                                       newline ...
'        To = Ti;   Do = di;'                                             newline ...
'    elseif ad >= pi - dmax'                                              newline ...
'        To = -Ti;  Do = di - sign(di)*pi;    % reverse thrust'           newline ...
'    elseif mode < 1.5'                                                   newline ...
'        To = 0;    Do = 0;                   % dead zone'                newline ...
'        sat = sat + 1;'                                                  newline ...
'    else'                                                                newline ...
'        % clamp to the nearest edge of the reachable sector'             newline ...
'        if ad <= pi/2'                                                   newline ...
'            Do = sign(di)*dmax;      To =  Ti*cos(ad - dmax);'           newline ...
'        else'                                                            newline ...
'            Do = -sign(di)*dmax;        To = -Ti*cos(pi - dmax - ad);'   newline ...
'            Do = atan2(sin(Do), cos(Do));'                               newline ...
'        end'                                                             newline ...
'        sat = sat + 1;'                                                  newline ...
'    end'                                                                 newline ...
'    if To >  Fmax, To =  Fmax; sat = sat + 1; end'                       newline ...
'    if To < -Fmax, To = -Fmax; sat = sat + 1; end'                       newline ...
'    Tcmd(i) = To;  Dcmd(i) = Do;'                                        newline ...
'end']);
    set_param([ss '/Allocate'],'Position',[220 70 420 320]);

    out = {'Tcmd','Dcmd','sat'};
    for k = 1:numel(out)
        add_block('simulink/Sinks/Out1', [ss '/' out{k}], ...
                  'Position',[520 80+(k-1)*90 555 110+(k-1)*90], 'Port', num2str(k));
        add_line(ss, sprintf('Allocate/%d',k), [out{k} '/1'], 'autorouting','on');
    end
    for k = 1:numel(in)
        add_line(ss, [in{k} '/1'], sprintf('Allocate/%d',k), 'autorouting','on');
    end
    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 4단 · 추진기 (모터 + 방위 서보)
% =====================================================================
function addThrusters(m, x, y)
    ss = [m '/Thrusters'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+190 y+180]);

    in  = {'Tcmd','Dcmd','Tpre','Dpre','par'};
    cfg = {'par','[Ts_ctrl; tau_n; tau_del; del_rate]'};
    dly = {'Tpre',1,'[0;0]'; 'Dpre',2,'[0;0]'};
    mk_inputs(ss, in, 2, cfg, dly);

    setFcn(ss, 'Act', [ ...
'function [Tact, Dact, f] = Act(Tcmd, Dcmd, Tpre, Dpre, par)'            newline ...
'%#codegen'                                                              newline ...
'% Actuator dynamics of an azimuth thruster.'                            newline ...
'%   thrust  : first order lag, time constant tau_n'                     newline ...
'%   azimuth : first order lag (tau_del) whose angular RATE is capped'   newline ...
'%             at rate_max. A real pod cannot snap to a new angle.'      newline ...
'% par = [Ts; tau_n; tau_del; rate_max]'                                 newline ...
''                                                                       newline ...
'Ts = par(1); tn = par(2); td = par(3); rmax = par(4);'                  newline ...
''                                                                       newline ...
'Tact = Tpre + (Ts/tn)*(Tcmd - Tpre);'                                   newline ...
''                                                                       newline ...
'Dact = Dpre;'                                                           newline ...
'for i = 1:2'                                                            newline ...
'    dd = Dcmd(i) - Dpre(i);'                                            newline ...
'    dd = atan2(sin(dd), cos(dd));           % shortest way round'       newline ...
'    step = (Ts/td)*dd;                      % first order lag ...'      newline ...
'    lim  = rmax*Ts;                         % ... whose RATE is capped'  newline ...
'    if step >  lim, step =  lim; end'                                   newline ...
'    if step < -lim, step = -lim; end'                                   newline ...
'    Dact(i) = Dpre(i) + step;'                                          newline ...
'end'                                                                    newline ...
''                                                                       newline ...
'% back to Cartesian components in BODY'                                 newline ...
'f = [ Tact(1)*cos(Dact(1));'                                            newline ...
'      Tact(1)*sin(Dact(1));'                                            newline ...
'      Tact(2)*cos(Dact(2));'                                            newline ...
'      Tact(2)*sin(Dact(2)) ];']);
    set_param([ss '/Act'],'Position',[220 70 420 380]);

    out = {'Tact','Dact','f'};
    for k = 1:numel(out)
        add_block('simulink/Sinks/Out1', [ss '/' out{k}], ...
                  'Position',[440 100+(k-1)*90 475 130+(k-1)*90], 'Port', num2str(k));
        add_line(ss, sprintf('Act/%d',k), [out{k} '/1'], 'autorouting','on');
    end
    for k = 1:numel(in)
        add_line(ss, [in{k} '/1'], sprintf('Act/%d',k), 'autorouting','on');
    end
    mk_state_out(ss, 'Act', dly);
    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 5단 · 외란 (바람 + 파랑)
% =====================================================================
function addEnv(m, x, y)
    ss = [m '/Env'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+190 y+180]);

    in  = {'t','nu','psi','wpar','wvpar'};
    cfg = {'wpar','[wind_on; wind_speed; wind_dir; rho_air; A_Fw; A_Lw; L_oa; c_x; c_y; c_n]'; ...
           'wvpar','[wave_on; k_wave; wave_dir; lw_arm; wave_par(:,1); wave_par(:,2); wave_par(:,3)]'};
    mk_inputs(ss, in, {'nu'}, cfg, {}, 't');   % nu 만 신호. t 는 시계, psi 는 아래에서 만든다

    %  psi 는 eta 에서 뽑는다. 최상위에 Selector 를 두면 태그 열을 관통한다
    add_block('simulink/Sources/In1', [ss '/eta_in'], ...
              'Position',[40 200 75 230], 'Port','2');
    add_block('simulink/Signal Routing/Selector', [ss '/psi'], ...
              'Position',[150 195 200 235]);
    set_param([ss '/psi'],'NumberOfDimensions','1', ...
              'IndexOptions','Index vector (dialog)','Indices','3', ...
              'InputPortWidth','3');
    add_line(ss, 'eta_in/1', 'psi/1', 'autorouting','on');

    setFcn(ss, 'Dist', [ ...
'function [tau_env, tau_w, tau_v] = Dist(t, nu, psi, wpar, wvpar)'       newline ...
'%#codegen'                                                              newline ...
'% Environmental loads in BODY axes.'                                    newline ...
'%'                                                                      newline ...
'% WIND  — Jin et al. (2025) Eq. (11)-(19); Fossen (2011) 8.1'           newline ...
'%   relative wind in BODY :'                                            newline ...
'%     u_rw = u + Vw cos(beta_w - psi)   beta_w = direction wind COMES FROM'                                  newline ...
'%     v_rw = v + Vw sin(beta_w - psi)   (Fossen uses going-to, hence minus)'                                  newline ...
'%   q     = 0.5 rho_a Vrw^2'                                            newline ...
'%   tau_w = q * [ CX*AFw ; CY*ALw ; CN*ALw*L ]'                         newline ...
'%   CX = -cx cos(g), CY = +cy sin(g), CN = cn sin(2g)   (Fossen 8.21)'                  newline ...
'%'                                                                      newline ...
'% WAVE  — first order approximation. Component amplitudes come from a'  newline ...
'%   Bretschneider spectrum (Jin et al. Eq. (21)-(25)); the force is'    newline ...
'%   taken proportional to the surface elevation with a single gain.'    newline ...
'%   This is an approximation, not a diffraction calculation.'           newline ...
'%'                                                                      newline ...
'% wpar  = [on; Vw; beta_w; rho_a; AFw; ALw; L; cx; cy; cn]'             newline ...
'% wvpar = [on; k_wave; theta_m; arm; w1..wn; A1..An; p1..x_n]'           newline ...
''                                                                       newline ...
'u = nu(1); v = nu(2);'                                                  newline ...
'tau_w = zeros(3,1);'                                                    newline ...
'if wpar(1) > 0.5'                                                       newline ...
'    Vw = wpar(2); bw = wpar(3); rho = wpar(4);'                         newline ...
'    AF = wpar(5); AL = wpar(6); L = wpar(7);'                           newline ...
'    cx = wpar(8); cy = wpar(9); cn = wpar(10);'                         newline ...
'    urw = u + Vw*cos(bw - psi);'                                        newline ...
'    vrw = v + Vw*sin(bw - psi);'                                        newline ...
'    Vrw = sqrt(urw*urw + vrw*vrw);'                                     newline ...
'    g   = -atan2(vrw, urw);'                                            newline ...
'    q   = 0.5*rho*Vrw*Vrw;'                                             newline ...
'    tau_w = q * [ -cx*cos(g)*AF;'                                       newline ...
'                   cy*sin(g)*AL;'                                       newline ...
'                   cn*sin(2*g)*AL*L ];'                                 newline ...
'end'                                                                    newline ...
''                                                                       newline ...
'tau_v = zeros(3,1);'                                                    newline ...
'if wvpar(1) > 0.5'                                                      newline ...
'    kw = wvpar(2); th = wvpar(3); arm = wvpar(4);'                      newline ...
'    n  = (numel(wvpar) - 4)/3;'                                         newline ...
'    zeta = 0;'                                                          newline ...
'    for i = 1:n'                                                        newline ...
'        wi = wvpar(4+i);'                                               newline ...
'        Ai = wvpar(4+n+i);'                                             newline ...
'        pi_i = wvpar(4+2*n+i);'                                         newline ...
'        zeta = zeta + Ai*sin(wi*t + pi_i);'                             newline ...
'    end'                                                                newline ...
'    rel = th - psi;                          % wave direction in BODY'  newline ...
'    Fw  = kw*zeta;'                                                     newline ...
'    tau_v = [ Fw*cos(rel); Fw*sin(rel); arm*Fw*sin(rel) ];'             newline ...
'end'                                                                    newline ...
''                                                                       newline ...
'tau_env = tau_w + tau_v;']);
    set_param([ss '/Dist'],'Position',[220 70 420 420]);

    out = {'tau_env','tau_w','tau_v'};
    for k = 1:numel(out)
        add_block('simulink/Sinks/Out1', [ss '/' out{k}], ...
                  'Position',[520 80+(k-1)*90 555 110+(k-1)*90], 'Port', num2str(k));
        add_line(ss, sprintf('Dist/%d',k), [out{k} '/1'], 'autorouting','on');
    end
    for k = 1:numel(in)
        add_line(ss, [in{k} '/1'], sprintf('Dist/%d',k), 'autorouting','on');
    end
    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 6단 · 운동모델
% =====================================================================
function addMotionModel(m, x, y)
    ss = [m '/MotionModel'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+200 y+180]);

    in  = {'f','tau_env','Te','par'};
    cfg = {'Te','T_e'; 'par','plant_par'};
    mk_inputs(ss, in, 2, cfg, {});

    setFcn(ss, 'EOM', [ ...
'function [xdot, tau_thr] = EOM(s, f, tau_env, Te, p)'                   newline ...
'%#codegen'                                                              newline ...
'% 3-DOF WAM-V equations of motion, NED — same coefficients as weeks'    newline ...
'% 7 to 9 (taken from the Gazebo VRX plugins).'                          newline ...
'% The only change is the input: the thruster force now has a sway'      newline ...
'% component, so all three degrees of freedom are actuated.'             newline ...
'%   s = [u v r N E psi]'''                                              newline ...
'%   p = [m Izz Xu Xuu Yv Yvv Nr Nrr]'''                                 newline ...
''                                                                       newline ...
'u = s(1); v = s(2); r = s(3); psi = s(6);'                              newline ...
'mm=p(1); Izz=p(2); Xu=p(3); Xuu=p(4); Yv=p(5); Yvv=p(6);'               newline ...
'Nr=p(7); Nrr=p(8);'                                                     newline ...
''                                                                       newline ...
'tau_thr = Te*f;                 % [X; Y; N] from the thrusters'         newline ...
'tau     = tau_thr + tau_env;'                                           newline ...
''                                                                       newline ...
'Dx = (Xu + Xuu*abs(u))*u;'                                              newline ...
'Dy = (Yv + Yvv*abs(v))*v;'                                              newline ...
'Dn = (Nr + Nrr*abs(r))*r;'                                              newline ...
''                                                                       newline ...
'du = (tau(1) - Dx)/mm + v*r;    % rigid-body Coriolis'                  newline ...
'dv = (tau(2) - Dy)/mm - u*r;'                                           newline ...
'dr = (tau(3) - Dn)/Izz;'                                                newline ...
''                                                                       newline ...
'xdot = [du; dv; dr;'                                                    newline ...
'        u*cos(psi) - v*sin(psi);'                                       newline ...
'        u*sin(psi) + v*cos(psi);'                                       newline ...
'        r];']);
    set_param([ss '/EOM'],'Position',[220 60 420 380]);

    add_block('simulink/Continuous/Integrator', [ss '/Integ'], ...
              'Position', [480 180 530 230], 'InitialCondition','x0');

    setFcn(ss, 'States', [ ...
'function [eta, nu, U, beta] = States(s)'                    newline ...
'%#codegen'                                                  newline ...
'nu   = s(1:3);'                                             newline ...
'eta  = s(4:6);'                                             newline ...
'U    = sqrt(s(1)*s(1) + s(2)*s(2));'                        newline ...
'beta = atan2(s(2), s(1));']);
    set_param([ss '/States'],'Position',[600 120 750 300]);

    out = {'eta','nu','U','beta','tau_thr'};
    for k = 1:numel(out)
        add_block('simulink/Sinks/Out1', [ss '/' out{k}], ...
                  'Position',[830 90+(k-1)*70 870 120+(k-1)*70], 'Port', num2str(k));
    end
    for k = 1:4
        add_line(ss, sprintf('States/%d',k), [out{k} '/1'], 'autorouting','on');
    end
    add_line(ss,'EOM/2','tau_thr/1','autorouting','on');

    for k = 1:numel(in)
        add_line(ss, [in{k} '/1'], sprintf('EOM/%d', k+1), 'autorouting','on');
    end
    add_line(ss,'EOM/1','Integ/1','autorouting','on');
    add_line(ss,'Integ/1','States/1','autorouting','on');
    % 상태 되먹임 — 화면을 가로지르는 대신 태그로 건너뛴다
    drop_tag(ss, 'Integ', 1, 'x_state', 280);
    b = port_xy(ss, 'EOM', 'Inport', 1);
    add_block('simulink/Signal Routing/From', [ss '/Fr_x_state'], ...
              'Position', [60 b(2)-11 130 b(2)+11], 'GotoTag','x_state');
    add_line(ss, 'Fr_x_state/1', 'EOM/1');
    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 실시간 그림
% =====================================================================
function addAnimate(m, x, y)
% 실시간 그림 — 포트 없는 서브시스템 하나로 묶는다.
%
%   **인자 순서 = 아래 태그 순서 + t + en** 이다 (add_animate_box 규약).
%   W08_animate(eta, eta_d, eta_raw, Dact, Tact, t) 와 같아야 한다.
%   태그를 더하거나 순서를 바꾸면 그리는 함수의 인자도 함께 고칠 것.
%
%   eta_raw(계단 목표)를 함께 넘기는 이유 — 왼쪽 칸에 "시킨 곳"과 "지금 좇는
%   곳"을 둘 다 찍기 위해서다. 다섯 태그 모두 wireFront 가 이미 최상위에 건
%   Goto 이므로 **새 가지를 치지 않는다** (5주차에 가지를 쳤다가 본선이 사선이
%   되어 배선 검사가 걸린 적이 있다).
    add_animate_box(m, {'eta','eta_d','eta_raw','Dact','Tact'}, ...
                    'W08_animate', '', [x y], 'Ts_ctrl');
end

% =====================================================================
% 로깅
% =====================================================================
function addLogging(m, x, y)
% 로깅 — 포트 없는 서브시스템 하나로 묶는다. W08_plot.m 이 이 변수들을 읽는다.
    sig = {'eta','eta_d','eta_raw','eta_f','nu','eta_e','tau_cmd','tau_thr','tau_env', ...
           'Tact','Dact','sat','U','beta','I_dp'};
    add_logging_box(m, sig, sig, [x y], 'Ts_ctrl');
end

% =====================================================================
% 앞단 배선 — 두 모델이 공유한다
%   설정값과 상태 지연은 각 상자 안에 있다. 최상위에 남는 것은 신호뿐이다.
% =====================================================================
function wireFront(m)
    % --- 1단 · 목표값 : 입력이 없다. 시계와 표가 상자 안에 있다 ----------
    addDPRef(m, 400, 60);
    G(m,'eta_d',   620, 100);
    G(m,'eta_raw', 620, 160);
    add_line(m,'DPRef/1','Go_eta_d/1','autorouting','on');
    add_line(m,'DPRef/2','Go_eta_raw/1','autorouting','on');

    % --- 1.5단 · 파랑 필터 ---------------------------------------------
    addWaveFilter(m, 300, 400);
    F(m,'eta','f', 200, 420);
    F(m,'nu','f',  200, 470);
    add_line(m,'Fr_eta_f/1','WaveFilter/1','autorouting','on');
    add_line(m,'Fr_nu_f/1', 'WaveFilter/2','autorouting','on');
    G(m,'eta_f', 520, 420);
    G(m,'nu_f',  520, 470);
    add_line(m,'WaveFilter/1','Go_eta_f/1','autorouting','on');
    add_line(m,'WaveFilter/2','Go_nu_f/1','autorouting','on');

    % --- 2단 · 제어기 ---------------------------------------------------
    addDPCtrl(m, 620, 60);
    F(m,'eta_d','c', 540, 80);
    F(m,'eta_f','c', 540, 140);
    F(m,'nu_f','c',  540, 200);
    add_line(m,'Fr_eta_d_c/1','DPCtrl/1','autorouting','on');
    add_line(m,'Fr_eta_f_c/1','DPCtrl/2','autorouting','on');
    add_line(m,'Fr_nu_f_c/1', 'DPCtrl/3','autorouting','on');
    G(m,'tau_cmd', 860, 100);
    G(m,'eta_e',   860, 160);
    add_line(m,'DPCtrl/1','Go_tau_cmd/1','autorouting','on');
    add_line(m,'DPCtrl/2','Go_eta_e/1','autorouting','on');
    G(m,'I_dp',    860, 220);
    add_line(m,'DPCtrl/3','Go_I_dp/1','autorouting','on');

    % --- 3단 · 추력배분 -------------------------------------------------
    addAlloc(m, 1020, 60);
    F(m,'tau_cmd','a', 940, 80);
    add_line(m,'Fr_tau_cmd_a/1','Alloc/1','autorouting','on');
    G(m,'Tcmd', 1260, 100);
    G(m,'Dcmd', 1260, 160);
    G(m,'sat',  1260, 220);
    add_line(m,'Alloc/1','Go_Tcmd/1','autorouting','on');
    add_line(m,'Alloc/2','Go_Dcmd/1','autorouting','on');
    add_line(m,'Alloc/3','Go_sat/1','autorouting','on');

    % --- 4단 · 추진기 ---------------------------------------------------
    addThrusters(m, 1420, 60);
    F(m,'Tcmd','t', 1340, 80);
    F(m,'Dcmd','t', 1340, 140);
    add_line(m,'Fr_Tcmd_t/1','Thrusters/1','autorouting','on');
    add_line(m,'Fr_Dcmd_t/1','Thrusters/2','autorouting','on');
    G(m,'Tact', 1680, 100);
    G(m,'Dact', 1680, 160);
    G(m,'fthr', 1680, 220);
    add_line(m,'Thrusters/1','Go_Tact/1','autorouting','on');
    add_line(m,'Thrusters/2','Go_Dact/1','autorouting','on');
    add_line(m,'Thrusters/3','Go_fthr/1','autorouting','on');
end
% =====================================================================
function build_offline()
    m = 'W08_0_offline'; fresh(m);
    setSolver(m, 'T_end');

    wireFront(m);

    % --- 외란 : 바람·파랑. 설정값은 상자 안에 있다 -----------------------
    addEnv(m, 1820, 460);
    F(m,'nu','e',  1740, 540);
    F(m,'eta','e', 1740, 600);
    add_line(m,'Fr_nu_e/1', 'Env/1','autorouting','on');
    add_line(m,'Fr_eta_e/1','Env/2','autorouting','on');
    G(m,'tau_env', 2080, 500);
    add_line(m,'Env/1','Go_tau_env/1','autorouting','on');

    % --- 운동모델 -------------------------------------------------------
    addMotionModel(m, 2200, 60);
    F(m,'fthr','p',   2110, 80);
    F(m,'tau_env','p',2110, 140);
    add_line(m,'Fr_fthr_p/1','MotionModel/1','autorouting','on');
    add_line(m,'Fr_tau_env_p/1','MotionModel/2','autorouting','on');

    tags = {'eta','nu','U','beta','tau_thr'};
    for k = 1:numel(tags)
        G(m, tags{k}, 2470, 80+(k-1)*55);
        add_line(m, sprintf('MotionModel/%d',k), ['Go_' tags{k} '/1'], 'autorouting','on');
    end


    addAnimate(m, 2200, 560);
    addLogging(m, 2800, 60);

    note(m,'n1', ['W08 실습 C·D  —  오프라인 DP (Gazebo 불필요)' newline ...
        'DPRef -> WaveFilter -> DPCtrl -> Alloc -> Thrusters -> MotionModel(+Env)' newline ...
        '후방 2기가 ±45° 로 돌아가므로 3자유도가 모두 제어된다.' newline ...
        '바람·파랑 외란은 이 모델에서만 넣을 수 있다.' newline ...
        '실행 전 >> W08_setup'], 40, -140);

    save_system(m); close_system(m);
    fprintf('  W08_0_offline  생성\n');
end
% VRX 모델
% =====================================================================
function build_vrx()
    m = 'W08_1_vrx'; fresh(m);
    load_system('ros2lib');
    setSolver(m, 'T_end');

    wireFront(m);
    % --- 추력·각도 발행 : 네 토픽을 한 상자에 -----------------------------
    addCmdPub(m, [1820 60]);

    % --- 구독 + 항법 : 한 상자에 -----------------------------------------
    navCode = [ ...
'function [eta, nu, U, beta] = Nav(ex, ey, qx, qy, qz, qw, bx, by, wz, org_x, org_y)' newline ...
'%#codegen'                                                                 newline ...
'% Gazebo/ROS uses ENU with a body frame of x-forward, y-LEFT, z-UP.'       newline ...
'% Marine control uses NED with x-forward, y-STARBOARD, z-DOWN.'            newline ...
'% 첫 메시지가 도착하기 전에는 Subscribe 가 0 으로 채운 버스를 낸다.'       newline ...
'% 그대로 쓰면 위치가 스폰 원점만큼(약 568 m) 튀어 로그 첫 점이 망가진다.'  newline ...
'if ex == 0 && ey == 0'                                                     newline ...
'    eta = zeros(3,1); nu = zeros(3,1); U = 0; beta = 0;'                   newline ...
'    return'                                                                newline ...
'end'                                                                       newline ...
'x_n = ey - org_x;'                                                           newline ...
'y_n = ex - org_y;'                                                           newline ...
'yaw_enu = atan2(2*(qw*qz + qx*qy), 1 - 2*(qy*qy + qz*qz));'                newline ...
'p   = pi/2 - yaw_enu;'                                                     newline ...
'psi = atan2(sin(p), cos(p));'                                              newline ...
'u = bx;  v = -by;  r = -wz;'                                               newline ...
'eta  = [x_n; y_n; psi];'                                                     newline ...
'nu   = [u; v; r];'                                                         newline ...
'U    = sqrt(u*u + v*v);'                                                   newline ...
'beta = atan2(v, u);'];

    add_pose_subscriber(m, [2180 670], ...
        '/wamv/sensors/position/ground_truth_odometry', 'Ts_ctrl', navCode, ...
        {'eta','nu','U','beta'});

    tags = {'eta','nu','U','beta'};
    for k = 1:numel(tags)
        G(m, tags{k}, 2420, 680+(k-1)*45);
        add_line(m, sprintf('PoseSubscriber/%d',k), ['Go_' tags{k} '/1'], 'autorouting','on');
    end

    % VRX 에는 외란 모델을 넣지 않는다 — 바람은 world 가 만든다
    C(m,'ZeroEnv','[0;0;0]', 2420, 900);
    G(m,'tau_env', 2560, 900);
    add_line(m,'ZeroEnv/1','Go_tau_env/1','autorouting','on');
    C(m,'ZeroThr','[0;0;0]', 2420, 1060);
    G(m,'tau_thr', 2560, 1060);
    add_line(m,'ZeroThr/1','Go_tau_thr/1','autorouting','on');

    addAnimate(m, 2200, 1000);
    addLogging(m, 2800, 60);

    note(m,'n1', ['W08 실습 E  —  VRX 연동 (Gazebo 필요)' newline ...
        'DPRef -> DPCtrl -> Alloc -> Thrusters -> Gazebo -> Navigation' newline ...
        '추력은 thrusters/*/thrust, 방위각은 thrusters/*/pos 로 발행한다.' newline ...
        '제어기·배분·게인은 W08_0_offline 과 완전히 같다.' newline ...
        '외란은 world 선택으로 준다 (바람 있는 world).' newline ...
        '실행: >> W08_setup  ->  >> W08_vrx_run'], 40, -160);

    save_system(m); close_system(m);
    fprintf('  W08_1_vrx      생성\n');
end

function addCmdPub(m, pos)
% 추력·방위각 발행을 한 상자에. 입출력 포트가 없다 — 안에서 태그로 받는다.
%
%   좌·우 추진기마다 추력 하나와 방위각 하나, 모두 네 토픽을 발행한다.
%   토픽 하나에 블록 네 개(Selector·Blank·Assign·Publish)가 필요하므로
%   최상위에 펼치면 열여섯 블록이다. 그 열여섯이 알려 주는 것은
%   "추력과 각도를 Gazebo 로 보낸다" 한 문장뿐이다.
    s = add_subsys(m, 'CmdPublisher', [pos(1) pos(2) pos(1)+160 pos(2)+90], ...
                   {}, {}, gnc_colour('ros'));

    side = {'left','right'};
    tag  = {'L','R'};
    for i = 1:2
        for j = 1:2
            if j == 1, what = 'thrust'; src = 'Tact'; else, what = 'pos'; src = 'Dact'; end
            nm = [upper(what(1)) tag{i}];
            y  = 100 + ((i-1)*2 + (j-1))*200;

            add_block('simulink/Signal Routing/From', [s '/Fr_' nm], ...
                      'Position',[60 y-11 130 y+11], 'GotoTag', src);
            add_block('simulink/Signal Routing/Selector', [s '/Sel' nm], ...
                      'Position',[200 y-20 250 y+20]);
            set_param([s '/Sel' nm],'NumberOfDimensions','1', ...
                      'IndexOptions','Index vector (dialog)','Indices', num2str(i), ...
                      'InputPortWidth','2');
            add_block('ros2lib/Blank Message', [s '/Blank' nm], ...
                      'Position',[340 y-60 440 y-20]);
            set_param([s '/Blank' nm], 'entityType','std_msgs/Float64', ...
                      'messageType','std_msgs/Float64', 'SampleTime','Ts_ctrl');
            add_block('simulink/Signal Routing/Bus Assignment', [s '/Asg' nm], ...
                      'Position',[520 y-60 600 y+20]);
            set_param([s '/Asg' nm], 'AssignedSignals','data');
            add_block('ros2lib/Publish', [s '/Pub' nm], ...
                      'Position',[700 y-40 820 y]);
            set_param([s '/Pub' nm], 'topicSource','Specify your own', ...
                      'topic', ['/wamv/thrusters/' side{i} '/' what], ...
                      'messageType','std_msgs/Float64');

            add_line(s, ['Fr_' nm '/1'],   ['Sel' nm '/1'],  'autorouting','on');
            add_line(s, ['Blank' nm '/1'], ['Asg' nm '/1'],  'autorouting','on');
            if j == 2
                % VRX 의 pos 는 Gazebo 의 ENU 선체계(x 전방, y 좌현) 기준 관절각이다.
                % 이 모델의 delta 는 NED 선체계(y 우현) 기준이므로 부호가 반대다.
                % 이 Gain 을 빼면 횡방향·요 되먹임의 부호가 뒤집혀 DP 가 발산한다.
                % (2026-09-17 배선 정리 때 한 번 빠졌다 — 오프라인 대조로는 안 잡힌다)
                add_block('simulink/Math Operations/Gain', [s '/Neg' nm], ...
                          'Gain','-1', 'Position',[400 y+20 440 y+50]);
                add_line(s, ['Sel' nm '/1'], ['Neg' nm '/1'], 'autorouting','on');
                add_line(s, ['Neg' nm '/1'], ['Asg' nm '/2'], 'autorouting','on');
            else
                add_line(s, ['Sel' nm '/1'], ['Asg' nm '/2'], 'autorouting','on');
            end
            add_line(s, ['Asg' nm '/1'],   ['Pub' nm '/1'],  'autorouting','on');
        end
    end

    add_block('built-in/Note', [s '/note'], 'Position', [60 900], 'Text', sprintf([ ...
        '발행 — 이 상자는 입출력 포트가 없다. Tact·Dact 를 태그로 받는다.\n' ...
        '  /wamv/thrusters/left/thrust    좌현 추력  [N]\n' ...
        '  /wamv/thrusters/left/pos       좌현 방위각 [rad]\n' ...
        '  /wamv/thrusters/right/thrust   우현 추력\n' ...
        '  /wamv/thrusters/right/pos      우현 방위각\n' ...
        '\n' ...
        'Selector 가 2원소 벡터에서 자기 쪽 하나를 골라낸다.\n' ...
        'pos 앞의 Gain(-1) — VRX 관절각은 ENU 선체계(y 좌현) 기준이라 부호가 반대다.']));
end
