function build_w08_models()
% BUILD_W08_MODELS  8주차 Simulink 모델 2개를 생성한다.
%
%     W08_0_offline.slx   오프라인 WAM-V 로이터링 — Gazebo 없이 돈다
%     W08_1_vrx.slx       VRX 연동 — 운동모델만 Gazebo 로 바뀐다
%
%   7주차와 GNC 골격이 똑같다. 바뀐 것은 1단(유도)뿐이다.
%
%   LoiterVF → TurnCount → Inner Loop → Thrusters → 운동모델
%   (벡터필드)  (회전수)     (7주차와 동일)
%
%   유도법칙 출처
%     W. Jung, S. Lim, D. Lee, H. Bang,
%     "Unmanned Aircraft Vector Field Path Following with Arrival Angle Control"
%     식 (9)  극좌표 벡터필드,  식 (13) 침로 명령
%   구현 참고
%     UGV_WpFollowingAndLoitering/MILS/UGV_Control_StateFlow_260529.slx
%       의 KAIST_CircularVF, calculate_turns
%
%   모델이 깨졌을 때 이 스크립트를 다시 돌리면 복구된다.
%   실행 전에 반드시 >> W08_setup 을 먼저 실행할 것.

    here = fileparts(mfilename('fullpath'));
    cd(here);

    if evalin('base', '~exist(''r_d'',''var'')')
        error('먼저 W08_setup 을 실행하십시오.');
    end

    build_offline();
    build_vrx();


    % 배치와 색을 정리한다. 선은 직선 또는 직각으로만 다시 그린다.
    slxList = dir('*.slx');
    for k = 1:numel(slxList)
        [~, mName] = fileparts(slxList(k).name);
        try, tidy_layout(mName); tidy_layout(mName); catch, end
    end
    fprintf('\n완료. 생성된 모델:\n');
    d = dir('W08_*.slx');
    for k = 1:numel(d), fprintf('  %s\n', d(k).name); end
end

% =====================================================================
% 공통 헬퍼
% =====================================================================
function fresh(m)
    try, close_system(m, 0); catch, end
    if exist([m '.slx'],'file'), delete([m '.slx']); end
    new_system(m);
end

function setFcn(sys, path, code)
    S  = sfroot;
    ch = S.find('-isa','Stateflow.EMChart','Path',[sys '/' path]);
    ch.Script = code;
end

function C(m, name, value, x, y)
    add_block('simulink/Sources/Constant', [m '/' name], ...
              'Position', [x y x+95 y+30], 'Value', value);
end

function F(m, tag, sfx, x, y)
    add_block('simulink/Signal Routing/From', [m '/Fr_' tag '_' sfx], ...
              'Position', [x y x+70 y+25], 'GotoTag', tag);
end

function G(m, tag, x, y)
    add_block('simulink/Signal Routing/Goto', [m '/Go_' tag], ...
              'Position', [x y x+80 y+25], 'GotoTag', tag);
end

function note(m, tag, txt, x, y)
    add_block('built-in/Note', [m '/' tag], 'Position',[x y x y], 'Text', txt);
end

% =====================================================================
% 1단 · LOITER GUIDANCE — 벡터필드
% =====================================================================
function addGuidance(m, x, y)
    % --- 시나리오: 시간에 따라 방향·속도·반경을 바꾼다 ---
    add_block('simulink/Sources/Digital Clock', [m '/Clk'], ...
              'Position', [x-190 y+330 x-140 y+360], 'SampleTime','Ts_ctrl');
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [m '/Schedule'], 'Position', [x-100 y+240 x+40 y+400]);
    setFcn(m, 'Schedule', [ ...
'function [pc, vd, rd] = Schedule(t, pc0, v0, rd0, use)'                newline ...
'%#codegen'                                                             newline ...
'% Change the loiter direction, speed and radius while the model runs.' newline ...
'% Direction is set by the SIGN of pc, speed by vd, radius by rd.'      newline ...
'if use < 0.5'                                                          newline ...
'    pc = pc0;   vd = v0;       rd = rd0;'                              newline ...
'elseif t < 150'                                                        newline ...
'    pc = pc0;   vd = v0;       rd = rd0;        % as configured'       newline ...
'elseif t < 300'                                                        newline ...
'    pc = -pc0;  vd = v0;       rd = rd0;        % reverse direction'   newline ...
'elseif t < 450'                                                        newline ...
'    pc = -pc0;  vd = v0*1.6;   rd = rd0;        % faster'              newline ...
'else'                                                                  newline ...
'    pc = -pc0;  vd = v0*1.6;   rd = rd0*0.6;    % tighter circle'      newline ...
'end']);

    % --- 벡터필드 유도 ---
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [m '/LoiterVF'], 'Position', [x+200 y x+380 y+220]);
    setFcn(m, 'LoiterVF', [ ...
'function [psi_ref, r, theta, vfN, vfE] = LoiterVF(pn, pe, cn, ce, rd, vd, pc, beta, kcrab)' newline ...
'%#codegen'                                                                newline ...
'% Circular-orbit vector field guidance.'                                  newline ...
'%   Jung, Lim, Lee, Bang, "Unmanned Aircraft Vector Field Path Following' newline ...
'%   with Arrival Angle Control", eq. (9) and (13).'                       newline ...
'%'                                                                        newline ...
'%   rd  desired orbit radius [m]'                                         newline ...
'%   vd  desired speed [m/s]'                                              newline ...
'%   pc  shaping parameter.  SIGN sets the turn direction:'                newline ...
'%         pc > 0  clockwise,   pc < 0  counter-clockwise'                 newline ...
'%       A smaller |pc| pulls the vehicle harder onto the circle.'         newline ...
''                                                                         newline ...
'dn = pn - cn;'                                                            newline ...
'de = pe - ce;'                                                            newline ...
''                                                                         newline ...
'r     = sqrt(dn*dn + de*de);      % distance from the centre'             newline ...
'theta = atan2(de, dn);            % bearing of the vehicle from centre'   newline ...
'if r < 1e-6, r = 1e-6; end        % the centre itself is singular'        newline ...
''                                                                         newline ...
'% eq. (9): the field written in polar components'                         newline ...
'N = sqrt((r - rd)^2 + (pc*r)^2);'                                         newline ...
'if N < 1e-9, N = 1e-9; end'                                               newline ...
'r_dot   = -vd * (r - rd) / N;     % radial     : closes the gap'          newline ...
'rth_dot =  vd * pc * r   / N;     % tangential : goes round'              newline ...
''                                                                         newline ...
'% polar -> NED. The magnitude of this vector is always vd.'               newline ...
'vfN = r_dot*cos(theta) - rth_dot*sin(theta);'                             newline ...
'vfE = r_dot*sin(theta) + rth_dot*cos(theta);'                             newline ...
''                                                                         newline ...
'% eq. (13): the field gives a COURSE, i.e. a velocity direction.'         newline ...
'% The boat can only be told a HEADING. In a turn the two differ by'       newline ...
'% the crab angle beta, and that difference shows up as a radius error.'   newline ...
'%   kcrab = 0  command the field angle directly (the paper form)'         newline ...
'%   kcrab = 1  subtract beta so the VELOCITY lines up with the field'     newline ...
'chi_d   = atan2(vfE, vfN);'                                               newline ...
'p       = chi_d - kcrab*beta;'                                            newline ...
'psi_ref = atan2(sin(p), cos(p));']);

    % --- 회전수 세기 + 임무 종료 ---
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [m '/TurnCount'], 'Position', [x+470 y+260 x+660 y+470]);
    setFcn(m, 'TurnCount', [ ...
'function [turns, gate, th_out, acc_out, armed] = TurnCount( ...'          newline ...
'         theta, r, rd, req, th_prev, acc_prev, armed_prev)'               newline ...
'%#codegen'                                                                newline ...
'% Count how many times the boat has gone round, then stop it.'            newline ...
'% Same idea as calculate_turns in the UGV Stateflow example: start'       newline ...
'% counting only after the boat has actually reached the circle,'          newline ...
'% otherwise the approach leg would be counted as part of a lap.'          newline ...
''                                                                         newline ...
'tol = 0.05*rd + 1;                % how close counts as "on the circle"'  newline ...
'th_out = theta;'                                                          newline ...
''                                                                         newline ...
'if armed_prev < 0.5'                                                      newline ...
'    acc_out = 0;'                                                         newline ...
'    if abs(r - rd) <= tol'                                                newline ...
'        armed = 1;                % reached the circle, start counting'   newline ...
'    else'                                                                 newline ...
'        armed = 0;'                                                       newline ...
'    end'                                                                  newline ...
'else'                                                                     newline ...
'    armed = 1;'                                                           newline ...
'    d = theta - th_prev;'                                                 newline ...
'    d = atan2(sin(d), cos(d));    % wrap: +pi to -pi must not count'      newline ...
'    acc_out = acc_prev + d;'                                              newline ...
'end'                                                                      newline ...
''                                                                         newline ...
'turns = abs(acc_out) / (2*pi);'                                           newline ...
''                                                                         newline ...
'% req = 0 means keep going forever'                                       newline ...
'if (req > 0) && (turns >= req)'                                           newline ...
'    gate = 0;                     % mission done, stop the boat'          newline ...
'else'                                                                     newline ...
'    gate = 1;'                                                            newline ...
'end']);

    d = {'ThDly','AccDly','ArmDly'};
    ic = {'0','0','0'};
    for k = 1:3
        add_block('simulink/Discrete/Unit Delay', [m '/' d{k}], ...
                  'Position', [x+520 y+520+(k-1)*50 x+595 y+555+(k-1)*50], ...
                  'InitialCondition', ic{k}, 'SampleTime','Ts_ctrl');
    end
    add_line(m,'TurnCount/3','ThDly/1','autorouting','on');
    add_line(m,'TurnCount/4','AccDly/1','autorouting','on');
    add_line(m,'TurnCount/5','ArmDly/1','autorouting','on');
    add_line(m,'ThDly/1', 'TurnCount/5','autorouting','on');
    add_line(m,'AccDly/1','TurnCount/6','autorouting','on');
    add_line(m,'ArmDly/1','TurnCount/7','autorouting','on');
end

% =====================================================================
% 2단 · INNER LOOP — 7주차와 완전히 같다
% =====================================================================
function addInnerLoop(m, x, y)
    ss = [m '/InnerLoop'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+190 y+170]);

    in = {'psi_ref','gate','u_ref','psi','r','u'};
    for k = 1:numel(in)
        add_block('simulink/Sources/In1', [ss '/' in{k}], ...
                  'Position', [40 60+(k-1)*80 75 60+(k-1)*80+30], 'Port', num2str(k));
    end

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/HeadingErr'], 'Position', [200 60 340 130]);
    setFcn(ss, 'HeadingErr', [ ...
'function e = HeadingErr(psi_ref, psi)'                          newline ...
'%#codegen'                                                      newline ...
'% Shortest signed angle, wrapped to [-pi, pi).'                 newline ...
'd = psi_ref - psi;'                                             newline ...
'e = atan2(sin(d), cos(d));']);

    add_block('simulink/Math Operations/Gain', [ss '/Kp_psi'], ...
              'Position', [410 60 460 100], 'Gain','Kp_psi');
    add_block('simulink/Math Operations/Gain', [ss '/Kd_rate'], ...
              'Position', [410 240 460 280], 'Gain','-Kd_psi');
    add_block('simulink/Math Operations/Sum', [ss '/SumN'], ...
              'Position', [560 110 590 150], 'Inputs','++');
    add_block('simulink/Discontinuities/Saturation', [ss '/SatN'], ...
              'Position', [650 110 690 150], ...
              'UpperLimit','2*F_max*half_beam', 'LowerLimit','-2*F_max*half_beam');

    add_line(ss,'psi_ref/1','HeadingErr/1','autorouting','on');
    add_line(ss,'psi/1',    'HeadingErr/2','autorouting','on');
    add_line(ss,'HeadingErr/1','Kp_psi/1','autorouting','on');
    add_line(ss,'r/1',        'Kd_rate/1','autorouting','on');
    add_line(ss,'Kp_psi/1', 'SumN/1','autorouting','on');
    add_line(ss,'Kd_rate/1','SumN/2','autorouting','on');
    add_line(ss,'SumN/1','SatN/1','autorouting','on');

    add_block('simulink/Math Operations/Product', [ss '/Gate'], ...
              'Position', [200 380 235 420]);
    add_block('simulink/Math Operations/Sum', [ss '/SurgeErr'], ...
              'Position', [300 385 330 415], 'Inputs','+-');
    add_block('simulink/Continuous/PID Controller', [ss '/PI_u'], ...
              'Position', [400 370 490 430]);
    set_param([ss '/PI_u'], 'Controller','PI', ...
        'TimeDomain','Discrete-time', 'SampleTime','Ts_ctrl', ...
        'P','Kp_u', 'I','Ki_u', 'LimitOutput','on', ...
        'UpperSaturationLimit','2*F_max', 'LowerSaturationLimit','-2*F_max', ...
        'AntiWindupMode','clamping');

    add_line(ss,'u_ref/1','Gate/1','autorouting','on');
    add_line(ss,'gate/1', 'Gate/2','autorouting','on');
    add_line(ss,'Gate/1','SurgeErr/1','autorouting','on');
    add_line(ss,'u/1',   'SurgeErr/2','autorouting','on');
    add_line(ss,'SurgeErr/1','PI_u/1','autorouting','on');

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/Alloc'], 'Position', [760 230 910 340]);
    setFcn(ss, 'Alloc', [ ...
'function [FL, FR] = Alloc(X, N, half_beam, Fmax)'                newline ...
'%#codegen'                                                       newline ...
'% Differential thrust allocation for two aft thrusters.'         newline ...
'FL = X/2 + N/(2*half_beam);'                                     newline ...
'FR = X/2 - N/(2*half_beam);'                                     newline ...
'if FL >  Fmax, FL =  Fmax; end'                                  newline ...
'if FL < -Fmax, FL = -Fmax; end'                                  newline ...
'if FR >  Fmax, FR =  Fmax; end'                                  newline ...
'if FR < -Fmax, FR = -Fmax; end']);

    add_block('simulink/Sources/Constant', [ss '/HB'], ...
              'Position', [620 460 710 490], 'Value','half_beam');
    add_block('simulink/Sources/Constant', [ss '/FM'], ...
              'Position', [620 510 710 540], 'Value','F_max');
    add_block('simulink/Sinks/Out1', [ss '/FL'], 'Position',[980 250 1015 280], 'Port','1');
    add_block('simulink/Sinks/Out1', [ss '/FR'], 'Position',[980 310 1015 340], 'Port','2');

    add_line(ss,'PI_u/1','Alloc/1','autorouting','on');
    add_line(ss,'SatN/1','Alloc/2','autorouting','on');
    add_line(ss,'HB/1',  'Alloc/3','autorouting','on');
    add_line(ss,'FM/1',  'Alloc/4','autorouting','on');
    add_line(ss,'Alloc/1','FL/1','autorouting','on');
    add_line(ss,'Alloc/2','FR/1','autorouting','on');

    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 3단 · THRUSTERS — 7주차와 완전히 같다
% =====================================================================
function addThrusters(m, x, y)
    ss = [m '/Thrusters'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+170 y+120]);

    add_block('simulink/Sources/In1', [ss '/FL_cmd'], 'Position',[40 60 75 90],  'Port','1');
    add_block('simulink/Sources/In1', [ss '/FR_cmd'], 'Position',[40 140 75 170],'Port','2');

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/F2n'], 'Position', [170 70 320 160]);
    setFcn(ss, 'F2n', [ ...
'function n_cmd = F2n(FL, FR, k, n_max)'                              newline ...
'%#codegen'                                                           newline ...
'% Inverse propeller law:  F = k*n*|n|  ->  n = sign(F)*sqrt(|F|/k)'  newline ...
'F = [FL; FR];'                                                       newline ...
'n_cmd = zeros(2,1);'                                                 newline ...
'for i = 1:2'                                                         newline ...
'    ni = sign(F(i)) * sqrt(abs(F(i))/k);'                            newline ...
'    if ni >  n_max, ni =  n_max; end'                                newline ...
'    if ni < -n_max, ni = -n_max; end'                                newline ...
'    n_cmd(i) = ni;'                                                  newline ...
'end']);

    add_block('simulink/Sources/Constant', [ss '/Kp'], ...
              'Position',[40 250 130 280], 'Value','k_prop');
    add_block('simulink/Sources/Constant', [ss '/Nm'], ...
              'Position',[40 300 130 330], 'Value','n_max');

    add_block('simulink/Discrete/Discrete Transfer Fcn', [ss '/MotorLag'], ...
              'Position',[380 85 500 145]);
    set_param([ss '/MotorLag'], 'Numerator','Ts_ctrl/tau_n', ...
              'Denominator','[1, Ts_ctrl/tau_n - 1]', 'SampleTime','Ts_ctrl');

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/n2F'], 'Position', [560 70 700 160]);
    setFcn(ss, 'n2F', [ ...
'function [FL, FR] = n2F(n, k)'                                  newline ...
'%#codegen'                                                      newline ...
'% Forward propeller law. Thrust is quadratic in shaft speed.'   newline ...
'FL = k * n(1) * abs(n(1));'                                     newline ...
'FR = k * n(2) * abs(n(2));']);

    add_block('simulink/Sinks/Out1', [ss '/FL'], 'Position',[780 70 815 100], 'Port','1');
    add_block('simulink/Sinks/Out1', [ss '/FR'], 'Position',[780 130 815 160],'Port','2');
    add_block('simulink/Sinks/Out1', [ss '/n'],  'Position',[780 190 815 220],'Port','3');

    add_line(ss,'FL_cmd/1','F2n/1','autorouting','on');
    add_line(ss,'FR_cmd/1','F2n/2','autorouting','on');
    add_line(ss,'Kp/1','F2n/3','autorouting','on');
    add_line(ss,'Nm/1','F2n/4','autorouting','on');
    add_line(ss,'F2n/1','MotorLag/1','autorouting','on');
    add_line(ss,'MotorLag/1','n2F/1','autorouting','on');
    add_line(ss,'Kp/1','n2F/2','autorouting','on');
    add_line(ss,'n2F/1','FL/1','autorouting','on');
    add_line(ss,'n2F/2','FR/1','autorouting','on');
    add_line(ss,'MotorLag/1','n/1','autorouting','on');

    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 4단 · MOTION MODEL — 7주차와 완전히 같다
% =====================================================================
function addMotionModel(m, x, y)
    ss = [m '/MotionModel'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+210 y+200]);

    in = {'FL','FR','p'};
    for k = 1:numel(in)
        add_block('simulink/Sources/In1', [ss '/' in{k}], ...
                  'Position', [40 60+(k-1)*70 75 60+(k-1)*70+30], 'Port', num2str(k));
    end

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/EOM'], 'Position', [200 60 380 240]);
    setFcn(ss, 'EOM', [ ...
'function xdot = EOM(s, FL, FR, p)'                                      newline ...
'%#codegen'                                                              newline ...
'% 3-DOF WAM-V equations of motion, NED.'                                newline ...
'% Coefficients come straight from the Gazebo VRX plugins.'              newline ...
'%   s = [u v r N E psi]'''                                              newline ...
'%   p = [m Izz Xu Xuu Yv Yvv Nr Nrr half_beam]'''                       newline ...
'u = s(1); v = s(2); r = s(3); psi = s(6);'                              newline ...
'm=p(1); Izz=p(2); Xu=p(3); Xuu=p(4); Yv=p(5); Yvv=p(6);'                newline ...
'Nr=p(7); Nrr=p(8); b_half=p(9);'                                        newline ...
''                                                                       newline ...
'X = FL + FR;'                                                           newline ...
'N = (FL - FR)*b_half;'                                                  newline ...
''                                                                       newline ...
'Dx = (Xu + Xuu*abs(u))*u;'                                              newline ...
'Dy = (Yv + Yvv*abs(v))*v;'                                              newline ...
'Dn = (Nr + Nrr*abs(r))*r;'                                              newline ...
''                                                                       newline ...
'du = (X - Dx)/m + v*r;'                                                 newline ...
'dv = (  - Dy)/m - u*r;'                                                 newline ...
'dr = (N - Dn)/Izz;'                                                     newline ...
''                                                                       newline ...
'xdot = [du; dv; dr;'                                                    newline ...
'        u*cos(psi) - v*sin(psi);'                                       newline ...
'        u*sin(psi) + v*cos(psi);'                                       newline ...
'        r];']);

    add_block('simulink/Continuous/Integrator', [ss '/Integ'], ...
              'Position', [450 130 500 180], 'InitialCondition','x0');

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/States'], 'Position', [570 60 720 260]);
    setFcn(ss, 'States', [ ...
'function [pn, pe, psi, u, r, beta, chi, U] = States(s)'    newline ...
'%#codegen'                                                 newline ...
'u = s(1); v = s(2); r = s(3);'                             newline ...
'pn = s(4); pe = s(5); psi = s(6);'                         newline ...
'U    = sqrt(u*u + v*v);'                                   newline ...
'beta = atan2(v, u);'                                       newline ...
'c    = psi + beta;'                                        newline ...
'chi  = atan2(sin(c), cos(c));']);

    out = {'pn','pe','psi','u','r','beta','chi','U'};
    for k = 1:numel(out)
        add_block('simulink/Sinks/Out1', [ss '/' out{k}], ...
                  'Position', [800 60+(k-1)*45 840 60+(k-1)*45+30], 'Port', num2str(k));
        add_line(ss, sprintf('States/%d',k), [out{k} '/1'], 'autorouting','on');
    end
    for k = 1:3
        add_line(ss, [in{k} '/1'], sprintf('EOM/%d', k+1), 'autorouting','on');
    end
    add_line(ss,'EOM/1','Integ/1','autorouting','on');
    add_line(ss,'Integ/1','States/1','autorouting','on');
    add_line(ss,'Integ/1','EOM/1','autorouting','on');
end

% =====================================================================
% 5단 · ANIMATE
% =====================================================================
function addAnimate(m, x, y)
    F(m,'pn','v',  x, y);
    F(m,'pe','v',  x, y+40);
    F(m,'psi','v', x, y+80);
    F(m,'turns','v', x, y+120);
    add_block('simulink/Sources/Digital Clock', [m '/Clk2'], ...
              'Position', [x y+160 x+50 y+190], 'SampleTime','Ts_ctrl');
    C(m,'Anim','animate', x, y+210);

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [m '/Animate'], 'Position', [x+150 y x+300 y+220]);
    setFcn(m, 'Animate', [ ...
'function ok = Animate(pn, pe, psi, turns, t, en)'                     newline ...
'%#codegen'                                                            newline ...
'% Live plot. MATLAB Function blocks cannot draw, so the plotting'     newline ...
'% routine is declared extrinsic and called as plain MATLAB.'          newline ...
'coder.extrinsic(''W08_animate'');'                                    newline ...
'ok = 1;'                                                              newline ...
'if en > 0.5'                                                          newline ...
'    W08_animate(pn, pe, psi, turns, t);'                              newline ...
'end']);

    add_block('simulink/Sinks/Terminator', [m '/AnimEnd'], ...
              'Position', [x+350 y+95 x+375 y+120]);

    add_line(m,'Fr_pn_v/1',   'Animate/1','autorouting','on');
    add_line(m,'Fr_pe_v/1',   'Animate/2','autorouting','on');
    add_line(m,'Fr_psi_v/1',  'Animate/3','autorouting','on');
    add_line(m,'Fr_turns_v/1','Animate/4','autorouting','on');
    add_line(m,'Clk2/1', 'Animate/5','autorouting','on');
    add_line(m,'Anim/1', 'Animate/6','autorouting','on');
    add_line(m,'Animate/1','AnimEnd/1','autorouting','on');
end

% =====================================================================
% 앞단 배선 (두 모델 공통)
% =====================================================================
function wireFront(m)
    F(m,'pn','a', 40,  65);
    F(m,'pe','a', 40, 110);
    C(m,'Cn','center_north', 40, 155);
    C(m,'Ce','center_east',  40, 200);
    C(m,'Rd0','r_d',         40, 300);
    C(m,'Pc0','p_c',         40, 345);
    C(m,'V0','u_ref',        40, 390);
    C(m,'Sch','use_schedule',40, 435);
    C(m,'Req','required_turns', 40, 490);

    add_line(m,'Clk/1', 'Schedule/1','autorouting','on');
    add_line(m,'Pc0/1', 'Schedule/2','autorouting','on');
    add_line(m,'V0/1',  'Schedule/3','autorouting','on');
    add_line(m,'Rd0/1', 'Schedule/4','autorouting','on');
    add_line(m,'Sch/1', 'Schedule/5','autorouting','on');

    add_line(m,'Fr_pn_a/1','LoiterVF/1','autorouting','on');
    add_line(m,'Fr_pe_a/1','LoiterVF/2','autorouting','on');
    add_line(m,'Cn/1','LoiterVF/3','autorouting','on');
    add_line(m,'Ce/1','LoiterVF/4','autorouting','on');
    add_line(m,'Schedule/3','LoiterVF/5','autorouting','on');   % rd
    add_line(m,'Schedule/2','LoiterVF/6','autorouting','on');   % vd
    add_line(m,'Schedule/1','LoiterVF/7','autorouting','on');   % pc
    F(m,'beta','g', 40, 245);
    C(m,'Kcr','crab_comp', 40, 545);
    add_line(m,'Fr_beta_g/1','LoiterVF/8','autorouting','on');
    add_line(m,'Kcr/1',      'LoiterVF/9','autorouting','on');

    add_line(m,'LoiterVF/3','TurnCount/1','autorouting','on');  % theta
    add_line(m,'LoiterVF/2','TurnCount/2','autorouting','on');  % r
    add_line(m,'Schedule/3','TurnCount/3','autorouting','on');  % rd
    add_line(m,'Req/1',     'TurnCount/4','autorouting','on');

    % 로깅·애니메이션용 태그
    G(m,'psi_ref', 640, 60);
    G(m,'r_dist',  640, 100);
    G(m,'theta',   640, 140);
    G(m,'turns',   760, 300);
    G(m,'gate',    760, 340);
    G(m,'u_cmd',   640, 460);
    add_line(m,'LoiterVF/1','Go_psi_ref/1','autorouting','on');
    add_line(m,'LoiterVF/2','Go_r_dist/1','autorouting','on');
    add_line(m,'LoiterVF/3','Go_theta/1','autorouting','on');
    add_line(m,'TurnCount/1','Go_turns/1','autorouting','on');
    add_line(m,'TurnCount/2','Go_gate/1','autorouting','on');
    add_line(m,'Schedule/2', 'Go_u_cmd/1','autorouting','on');
    G(m,'vfN', 640, 180);
    G(m,'vfE', 640, 220);
    add_line(m,'LoiterVF/4','Go_vfN/1','autorouting','on');
    add_line(m,'LoiterVF/5','Go_vfE/1','autorouting','on');

    % 내부루프 입력
    F(m,'psi','b', 780, 560);
    F(m,'r',  'b', 780, 600);
    F(m,'u',  'b', 780, 640);
    add_line(m,'LoiterVF/1','InnerLoop/1','autorouting','on');
    add_line(m,'TurnCount/2','InnerLoop/2','autorouting','on');
    add_line(m,'Schedule/2', 'InnerLoop/3','autorouting','on');
    add_line(m,'Fr_psi_b/1','InnerLoop/4','autorouting','on');
    add_line(m,'Fr_r_b/1',  'InnerLoop/5','autorouting','on');
    add_line(m,'Fr_u_b/1',  'InnerLoop/6','autorouting','on');
end

% =====================================================================
% 로깅
% =====================================================================
function addLogging(m, x, y)
    sig = {'pn','pe','psi','psi_ref','r_dist','theta','turns','gate','u','u_cmd','beta','FL','FR','n','vfN','vfE'};
    tag = {'pn','pe','psi','psi_ref','r_dist','theta','turns','gate','u','u_cmd','beta','FL','FR','nprop','vfN','vfE'};
    for k = 1:numel(sig)
        yy = y + (k-1)*55;
        F(m, tag{k}, 'log', x, yy+3);
        b = [m '/log_' sig{k}];
        add_block('simulink/Sinks/To Workspace', b, ...
                  'Position', [x+130 yy x+230 yy+30]);
        set_param(b, 'VariableName', ['log_' sig{k}], ...
                     'SaveFormat','Timeseries', 'SampleTime','Ts_ctrl');
        add_line(m, ['Fr_' tag{k} '_log/1'], ['log_' sig{k} '/1'], 'autorouting','on');
    end
end

% =====================================================================
% 오프라인 모델
% =====================================================================
function build_offline()
    m = 'W08_0_offline'; fresh(m);
    set_param(m, 'SolverType','Fixed-step', 'SolverName','ode4', ...
                 'FixedStep','Ts_ctrl', 'StopTime','800', 'SimulationMode','normal');

    addGuidance(m, 250, 60);
    addInnerLoop(m, 1000, 560);
    wireFront(m);
    addThrusters(m, 1300, 570);
    addMotionModel(m, 1620, 560);

    C(m,'Par','[m_usv; Izz; Xu; Xuu; Yv; Yvv; Nr; Nrr; half_beam]', 1300, 760);
    add_line(m,'InnerLoop/1','Thrusters/1','autorouting','on');
    add_line(m,'InnerLoop/2','Thrusters/2','autorouting','on');
    add_line(m,'Thrusters/1','MotionModel/1','autorouting','on');
    add_line(m,'Thrusters/2','MotionModel/2','autorouting','on');
    add_line(m,'Par/1',      'MotionModel/3','autorouting','on');

    G(m,'FL', 1500, 800);  G(m,'FR', 1500, 840);  G(m,'nprop', 1500, 880);
    add_line(m,'Thrusters/1','Go_FL/1','autorouting','on');
    add_line(m,'Thrusters/2','Go_FR/1','autorouting','on');
    add_line(m,'Thrusters/3','Go_nprop/1','autorouting','on');

    tags = {'pn','pe','psi','u','r','beta','chi','U'};
    for k = 1:numel(tags)
        G(m, tags{k}, 1900, 560+(k-1)*40);
        add_line(m, sprintf('MotionModel/%d',k), ['Go_' tags{k} '/1'], 'autorouting','on');
    end

    addAnimate(m, 1900, 920);
    addLogging(m, 2350, 60);

    note(m,'n1', ['W08 실습 A  —  오프라인 WAM-V 로이터링 (Gazebo 불필요)' newline ...
        'LoiterVF -> TurnCount -> Inner Loop -> Thrusters -> 운동모델' newline ...
        '유도만 7주차와 다르다. 나머지는 그대로다.' newline ...
        '실행 전 >> W08_setup'], 250, -100);

    save_system(m); close_system(m);
    fprintf('  W08_0_offline  생성\n');
end

% =====================================================================
% VRX 연동 모델
% =====================================================================
function build_vrx()
    m = 'W08_1_vrx'; fresh(m);
    load_system('ros2lib');
    set_param(m, 'SolverType','Fixed-step', 'SolverName','FixedStepDiscrete', ...
                 'FixedStep','Ts_ctrl', 'StopTime','inf', 'SimulationMode','normal');

    addGuidance(m, 250, 60);
    addInnerLoop(m, 1000, 560);
    wireFront(m);
    addThrusters(m, 1300, 570);

    addThrusterPublisher(m, 'left',  'L', 1600, 480);
    addThrusterPublisher(m, 'right', 'R', 1600, 660);
    add_line(m,'InnerLoop/1','Thrusters/1','autorouting','on');
    add_line(m,'InnerLoop/2','Thrusters/2','autorouting','on');
    add_line(m,'Thrusters/1','AsgL/2','autorouting','on');
    add_line(m,'Thrusters/2','AsgR/2','autorouting','on');

    G(m,'FL', 1500, 850);  G(m,'FR', 1500, 890);  G(m,'nprop', 1500, 930);
    add_line(m,'Thrusters/1','Go_FL/1','autorouting','on');
    add_line(m,'Thrusters/2','Go_FR/1','autorouting','on');
    add_line(m,'Thrusters/3','Go_nprop/1','autorouting','on');

    add_block('ros2lib/Subscribe', [m '/OdomSub'], 'Position',[1600 980 1730 1040]);
    set_param([m '/OdomSub'], 'topicSource','Specify your own', ...
        'topic','/wamv/sensors/position/ground_truth_odometry', ...
        'messageType','nav_msgs/Odometry', 'sampleTime','Ts_ctrl');

    add_block('simulink/Signal Routing/Bus Selector', [m '/Sel'], ...
              'Position',[1790 960 1840 1090]);
    set_param([m '/Sel'], 'OutputSignals', ...
        ['pose.pose.position.x,pose.pose.position.y,' ...
         'pose.pose.orientation.x,pose.pose.orientation.y,' ...
         'pose.pose.orientation.z,pose.pose.orientation.w,' ...
         'twist.twist.linear.x,twist.twist.linear.y,twist.twist.angular.z']);

    add_block('simulink/Sinks/Display', [m '/IsNew'], 'Position',[1790 900 1870 930]);
    add_line(m,'OdomSub/1','IsNew/1','autorouting','on');
    add_line(m,'OdomSub/2','Sel/1','autorouting','on');

    C(m,'OrgN','origin_north', 1790, 1150);
    C(m,'OrgE','origin_east',  1790, 1195);

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [m '/Nav'], 'Position',[1960 950 2130 1170]);
    setFcn(m, 'Nav', [ ...
'function [pn, pe, psi, u, r, beta, chi, U] = Nav(ex, ey, qx, qy, qz, qw, bx, by, wz, orgN, orgE)' newline ...
'%#codegen'                                                                 newline ...
'% Gazebo/ROS uses ENU with a body frame of x-forward, y-LEFT, z-UP.'       newline ...
'% Marine control uses NED with x-forward, y-STARBOARD, z-DOWN.'            newline ...
'% 첫 메시지가 도착하기 전에는 Subscribe 가 0 으로 채운 버스를 낸다.'       newline ...
'% 그대로 쓰면 위치가 스폰 원점만큼(약 568 m) 튀어 로그 첫 점이 망가진다.'  newline ...
'if ex == 0 && ey == 0'                                                     newline ...
'    pn = 0; pe = 0; psi = 0; u = 0; r = 0; beta = 0; chi = 0; U = 0;'      newline ...
'    return'                                                                newline ...
'end'                                                                       newline ...
'pn = ey - orgN;'                                                           newline ...
'pe = ex - orgE;'                                                           newline ...
'yaw_enu = atan2(2*(qw*qz + qx*qy), 1 - 2*(qy*qy + qz*qz));'                newline ...
'p   = pi/2 - yaw_enu;'                                                     newline ...
'psi = atan2(sin(p), cos(p));'                                              newline ...
'u = bx;'                                                                   newline ...
'v = -by;'                                                                  newline ...
'r = -wz;'                                                                  newline ...
'U    = sqrt(u*u + v*v);'                                                   newline ...
'beta = atan2(v, u);'                                                       newline ...
'c    = psi + beta;'                                                        newline ...
'chi  = atan2(sin(c), cos(c));']);

    for k = 1:9
        add_line(m, sprintf('Sel/%d',k), sprintf('Nav/%d',k), 'autorouting','on');
    end
    add_line(m,'OrgN/1','Nav/10','autorouting','on');
    add_line(m,'OrgE/1','Nav/11','autorouting','on');

    tags = {'pn','pe','psi','u','r','beta','chi','U'};
    for k = 1:numel(tags)
        G(m, tags{k}, 2200, 950+(k-1)*40);
        add_line(m, sprintf('Nav/%d',k), ['Go_' tags{k} '/1'], 'autorouting','on');
    end

    addAnimate(m, 2200, 1320);
    addLogging(m, 2650, 60);

    note(m,'n1', ['W08 실습 C  —  VRX 연동 로이터링' newline ...
        '유도·내부루프·추진기·게인은 W08_0_offline 과 완전히 같다.' newline ...
        '운동모델만 Gazebo 로 바뀐다.' newline ...
        '실행 전: (1) W08_setup  (2) VRX 기동  (3) 페이싱을 RTF 에 맞출 것'], 250, -110);

    save_system(m); close_system(m);
    fprintf('  W08_1_vrx      생성\n');
end

function addThrusterPublisher(m, side, tag, x, y)
    add_block('ros2lib/Blank Message', [m '/Blank' tag], ...
              'Position', [x y+70 x+100 y+110]);
    set_param([m '/Blank' tag], 'entityType','std_msgs/Float64', ...
              'messageType','std_msgs/Float64', 'SampleTime','Ts_ctrl');
    add_block('simulink/Signal Routing/Bus Assignment', [m '/Asg' tag], ...
              'Position', [x+160 y x+220 y+115]);
    set_param([m '/Asg' tag], 'AssignedSignals','data');
    add_block('ros2lib/Publish', [m '/Pub' tag], ...
              'Position', [x+290 y+35 x+390 y+75]);
    set_param([m '/Pub' tag], 'topicSource','Specify your own', ...
              'topic', ['/wamv/thrusters/' side '/thrust'], ...
              'messageType','std_msgs/Float64');
    add_line(m, ['Blank' tag '/1'], ['Asg' tag '/1'], 'autorouting','on');
    add_line(m, ['Asg'   tag '/1'], ['Pub' tag '/1'], 'autorouting','on');
end
