function build_w07_models()
% BUILD_W07_MODELS  7주차 Simulink 모델 2개를 생성한다.
%
%     W07_0_offline.slx   오프라인 WAM-V — Gazebo 없이 돈다. 조류 실험용
%     W07_1_vrx.slx       VRX 연동 — 운동모델만 Gazebo 로 바뀐다
%
%   실제 GNC 루프 순서대로 왼쪽에서 오른쪽으로 배치된다.
%
%   Guidance → Inner Loop → Thrusters → 운동모델 → Navigation
%   (유도)      (헤딩 P-D +   (프로펠러   (플랜트)    (상태 산출)
%               속도 PI +      + 모터)
%               추력배분)
%       ↑            ↑                                    |
%       └── Goto/From 태그로 되먹임 ─────────────────────────┘
%
%   구조는 MSS 툴박스의 demoOtterUSVHeadingControl_P_D_Waypoint.slx 를 따른다.
%     - 유도는 psi_ref (선수각) 를 낸다.  침로각이 아니다
%     - 헤딩 제어는 P-D 요각속도 되먹임:  tau_N = Kp*ssa(psi_ref-psi) - Kd*r
%       오차를 미분하지 않으므로 웨이포인트 전환 때 미분 킥이 없다
%     - 속도 제어는 u (surge velocity) 되먹임.  U = sqrt(u^2+v^2) 가 아니다
%
%   두 모델은 유도부·내부루프·게인이 전부 같다. 다른 것은 두 가지뿐이다.
%     1) 운동모델 : MATLAB Function (VRX 와 같은 계수)  vs  Gazebo 실물
%     2) 조류     : 오프라인만 가능. VRX 에는 해류 플러그인이 없다
%
%   모델이 깨졌을 때 이 스크립트를 다시 돌리면 복구된다.
%   실행 전에 반드시 >> W07_setup 을 먼저 실행할 것.

    here = fileparts(mfilename('fullpath'));
    addpath(fullfile(here, '..', '..', '_tools'));
    cd(here);

    if evalin('base', '~exist(''wp_north'',''var'')')
        error('먼저 W07_setup 을 실행하십시오.');
    end

    build_offline();
    build_vrx();

    % 최상위 배치 — autorouting 에 맡기지 않고 규칙대로 직접 놓는다.
    % 겹침·블록관통 0, 꺾임 1회가 합격선이다 (references/line-routing.md)
    chain = {'Guidance','InnerLoop','Thrusters','MotionModel'};
    %  Wrap — 사슬을 몇 칸에서 접을지. 도면이 정사각형에 가까울수록 같은 픽셀 안에
    %  크게 보인다. 값은 주차마다 재서 골랐다 (겹침 0 이 되는 것 중 가장 작은 쪽)
    lay_chain('W07_0_offline', chain, 'Boxes', {'Animate','Logging'}, 'Wrap', 2);
    lay_chain('W07_1_vrx', {'Guidance','InnerLoop','Thrusters','CmdPublisher','PoseSubscriber'}, ...
              'Boxes', {'Animate','Logging'}, 'Wrap', 3);
    %  색 — 역할표는 _tools/gnc_roles.m 하나뿐이다. 빌더는 부르기만 한다
    for mm = {'W07_0_offline','W07_1_vrx'}
        m = mm{1}; load_system(m);
        paint_roles(m);
        check_colour(m);
        mss_style(m); save_system(m); close_system(m, 0);
        %  선 정리 — 포트가 늘면 전에 비어 있던 통로가 막힌다. 지적 0 까지
        settle_links(m);
        load_system(m); check_lines(m, false); export_diagram(m);
        close_system(m, 0);
    end
    fprintf('\n완료. 생성된 모델:\n');
    d = dir('W07_*.slx');
    for k = 1:numel(d), fprintf('  %s\n', d(k).name); end
end

% =====================================================================
% 공통 헬퍼
% =====================================================================
function fresh(m)
    try, close_system(m, 0); catch, end
    if exist([m '.slx'],'file'), delete([m '.slx']); end
    new_system(m);
end

function setSolver(m, stopTime)
    set_param(m, 'SolverType','Fixed-step', 'SolverName','FixedStepDiscrete', ...
                 'FixedStep','Ts_ctrl', 'StopTime',stopTime, 'SimulationMode','normal');
end

function setFcn(sys, path, code)
    S  = sfroot;
    ch = S.find('-isa','Stateflow.EMChart','Path',[sys '/' path]);
    ch.Script = code;
end

function C(m, name, value, x, y)
    add_block('simulink/Sources/Constant', [m '/' name], ...
              'Position', [x y x+95 y+30], 'Value', value);
end

function note(m, tag, txt, x, y)
    add_block('built-in/Note', [m '/' tag], 'Position',[x y x y], 'Text', txt);
end

% =====================================================================
% 1단 · GUIDANCE
% =====================================================================
function addGuidance(m, x, y)
% 1단 · GUIDANCE — 서브시스템 하나. 웨이포인트와 설정은 **상자 안에** 둔다.
%
%   포트   pn, pe  ->  psi_ref, y_e, x_e, gate
%
%   웨이포인트 배열·Delta·R·mode 는 신호가 아니라 **설정**이다. 최상위에 늘어놓으면
%   상수 여섯 개와 선 여섯 개가 신호 사슬 앞을 가린다. 상자 안에 넣으면 최상위는
%   "위치를 받아 목표 선수각을 낸다" 는 사실만 보여 준다.
%
%   웨이포인트 인덱스 되먹임(IdxDly)도 안에 있다. 유도부 **내부의 기억**이지
%   모델의 되먹임이 아니기 때문이다.
    ss = add_subsys(m, 'Guidance', [x y x+190 y+150], {'pn','pe'}, ...
                    {'psi_ref','y_e','x_e','gate'}, gnc_colour('guidance'));

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/GuidanceLaw'], 'Position', [320 60 500 560]);
    setFcn(ss, 'GuidanceLaw', [ ...
'function [psi_ref, y_e, x_e, wp_idx, gate] = GuidanceLaw(pn, pe, wp_n, wp_e, Delta, R, mode, sw_mode, idx_prev)' newline ...
'%#codegen'                                                                     newline ...
'% Waypoint guidance. Two laws in one block. Both return a HEADING command,'    newline ...
'% following the MSS demo demoOtterUSVHeadingControl_P_D_Waypoint.slx.'         newline ...
'%   mode 1 = atan2 : aim straight at the next waypoint (point chasing)'        newline ...
'%   mode 2 = LOS   : follow the straight line between two waypoints'           newline ...
'% Switching criterion (sw_mode):'                                              newline ...
'%   1 = along-track : d - x_e < R      (MSS / Fossen default, cannot hang)'    newline ...
'%   2 = circle      : distance to the next waypoint <= R'                      newline ...
''                                                                              newline ...
'n = numel(wp_n);'                                                              newline ...
'k = min(max(idx_prev, 1), n-1);        % index of the active leg'              newline ...
''                                                                              newline ...
'xk  = wp_n(k);    yk  = wp_e(k);       % leg start'                            newline ...
'xk1 = wp_n(k+1);  yk1 = wp_e(k+1);     % leg end = next waypoint'              newline ...
''                                                                              newline ...
'% path-tangential angle of the active leg, measured from North'                newline ...
'pi_p = atan2(yk1 - yk, xk1 - xk);'                                             newline ...
''                                                                              newline ...
'% Both errors come out of ONE rotation of (p - p_k) into the path frame.'      newline ...
'% x_e = how far ALONG the leg,  y_e = how far TO THE SIDE of it.'              newline ...
'% Computed the same way for BOTH guidance laws so that the two can be'         newline ...
'% compared with the same yardstick.'                                           newline ...
'x_e =  (pn - xk)*cos(pi_p) + (pe - yk)*sin(pi_p);'                             newline ...
'y_e = -(pn - xk)*sin(pi_p) + (pe - yk)*cos(pi_p);'                             newline ...
''                                                                              newline ...
'if mode == 1'                                                                  newline ...
'    psi_ref = atan2(yk1 - pe, xk1 - pn);'                                      newline ...
'else'                                                                          newline ...
'    psi_ref = pi_p - atan(y_e / Delta);'                                       newline ...
'end'                                                                           newline ...
''                                                                              newline ...
'% --- waypoint switching ---------------------------------------------'        newline ...
'% d is the leg length, so d - x_e is the along-track distance REMAINING.'      newline ...
'% The circle test is always the stricter of the two, because'                  newline ...
'%     distance = sqrt((d - x_e)^2 + y_e^2) >= d - x_e'                         newline ...
'% A boat blown wide of a waypoint never enters that circle, and a mission'     newline ...
'% that waits for it waits for ever. The along-track test cannot hang.'         newline ...
'd = sqrt((xk1 - xk)^2 + (yk1 - yk)^2);'                                        newline ...
'if sw_mode == 1'                                                               newline ...
'    reached = (d - x_e) < R;'                                                  newline ...
'else'                                                                          newline ...
'    reached = sqrt((xk1 - pn)^2 + (yk1 - pe)^2) <= R;'                         newline ...
'end'                                                                           newline ...
''                                                                              newline ...
'if reached && (k < n-1)'                                                       newline ...
'    wp_idx = k + 1;'                                                           newline ...
'else'                                                                          newline ...
'    wp_idx = k;'                                                               newline ...
'end'                                                                           newline ...
''                                                                              newline ...
'% mission finished? gate = 0 brings the boat to a stop.'                       newline ...
'% Without it the boat would follow the last leg forever.'                      newline ...
'if (k == n-1) && reached'                                                      newline ...
'    gate = 0;'                                                                 newline ...
'else'                                                                          newline ...
'    gate = 1;'                                                                 newline ...
'end']);

    % 설정값 — 신호가 아니다. row_feed 가 각자 포트 높이로 옮겨 붙인다
    cfg = {'wp_n','wp_north'; 'wp_e','wp_east'; 'Delta','Delta'; ...
           'R','R_LOS'; 'mode','guidance_mode'; 'sw_mode','sw_mode'};
    for k = 1:size(cfg,1)
        add_block('simulink/Sources/Constant', [ss '/' cfg{k,1}], ...
                  'Position', [130 100+(k-1)*60 205 100+(k-1)*60+30], 'Value', cfg{k,2});
    end
    set_param([ss '/pn'], 'Position', [160 100 190 114]);
    set_param([ss '/pe'], 'Position', [160 160 190 174]);
    row_feed(ss, 'GuidanceLaw', {'pn','pe','wp_n','wp_e','Delta','R','mode','sw_mode',''});

    % --- 9번 입력: 한 스텝 전의 웨이포인트 인덱스 ------------------------
    q = port_xy(ss, 'GuidanceLaw', 'Inport', 9);
    add_block('simulink/Discrete/Unit Delay', [ss '/IdxDly'], ...
              'Position', [230 q(2)-20 300 q(2)+20], ...
              'InitialCondition','1', 'SampleTime','Ts_ctrl');
    add_block('simulink/Signal Routing/From', [ss '/Fr_wp_idx'], ...
              'Position', [130 q(2)-11 200 q(2)+11], 'GotoTag','wp_idx');
    add_line(ss, 'Fr_wp_idx/1', 'IdxDly/1');      % 직선
    add_line(ss, 'IdxDly/1', 'GuidanceLaw/9');    % 직선

    % --- 출력: 본선 네 개는 포트로 -------------------------------------
    outs = {'psi_ref',1; 'y_e',2; 'x_e',3; 'gate',5};
    for k = 1:size(outs,1)
        q = port_xy(ss, 'GuidanceLaw', 'Outport', outs{k,2});
        set_param([ss '/' outs{k,1}], 'Position', [700 q(2)-7 730 q(2)+7]);
        add_line(ss, sprintf('GuidanceLaw/%d', outs{k,2}), [outs{k,1} '/1']);
    end

    % 인덱스는 밖으로 나가지 않는다. 태그로 걸어 위의 IdxDly 가 받는다
    drop_tag(ss, 'GuidanceLaw', 4, 'wp_idx', 120);

    add_block('built-in/Note', [ss '/note'], 'Position', [130 700], 'Text', sprintf([ ...
        '유도 — 위치를 받아 목표 선수각을 낸다.\n' ...
        '  mode = 1  atan2 : 다음 웨이포인트를 곧장 겨눈다\n' ...
        '  mode = 2  LOS   : 두 웨이포인트를 잇는 직선을 따라간다\n' ...
        '\n' ...
        '전환 판정 sw_mode\n' ...
        '  1  경로 방향 : d - x_e < R   (MSS 기본값. 밀려나도 멈추지 않는다)\n' ...
        '  2  수락 원   : 다음 웨이포인트까지 직선거리 <= R\n' ...
        '\n' ...
        'wp_idx 는 밖으로 나가지 않는다. 지금 몇 번째 구간을 달리는지를\n' ...
        '유도부가 스스로 기억하는 값이라, 한 스텝 지연을 거쳐 자기에게 되돌아온다.\n' ...
        '이 지연이 없으면 대수 루프가 되어 모델이 컴파일되지 않는다.']));
end
% =====================================================================
% 2단 · INNER LOOP — 헤딩 P-D + 속도 PI + 추력배분
% =====================================================================
function addInnerLoop(m, x, y)
    ss = [m '/InnerLoop'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+190 y+170]);

    in = {'psi_ref','gate','psi','r','u'};
    for k = 1:numel(in)
        add_block('simulink/Sources/In1', [ss '/' in{k}], ...
                  'Position', [40 60+(k-1)*80 75 60+(k-1)*80+30], 'Port', num2str(k));
    end

    % 목표 속도는 신호가 아니라 설정이다. 상자 안에 둔다
    add_block('simulink/Sources/Constant', [ss '/u_ref'], ...
              'Position', [40 380 130 410], 'Value','u_ref');

    % ---------- 헤딩 제어 : tau_N = Kp*ssa(psi_ref - psi) - Kd*r ----------
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/HeadingErr'], 'Position', [200 60 340 130]);
    setFcn(ss, 'HeadingErr', [ ...
'function e = HeadingErr(psi_ref, psi)'                          newline ...
'%#codegen'                                                      newline ...
'% Shortest signed angle (ssa). Without it a command of 179 deg' newline ...
'% against a heading of -179 deg reads as a 358 deg error and'   newline ...
'% the boat turns the long way round.'                           newline ...
'd = psi_ref - psi;'                                             newline ...
'e = atan2(sin(d), cos(d));']);

    add_block('simulink/Math Operations/Gain', [ss '/Kp_psi'], ...
              'Position', [410 60 460 100], 'Gain','Kp_psi');

    % D 항을 만드는 두 가지 방법. d_mode 로 고른다.
    %   d_mode = 1  요각속도 되먹임   -Kd*r          (기본. 미분 킥이 없다)
    %   d_mode = 2  오차 미분         +Kd*de/dt      (9주차 비교 실험용)
    add_block('simulink/Math Operations/Gain', [ss '/Kd_rate'], ...
              'Position', [410 300 460 340], 'Gain','-Kd_psi');
    add_block('simulink/Discrete/Discrete Derivative', [ss '/dedt'], ...
              'Position', [400 180 470 240]);
    set_param([ss '/dedt'], 'gainval','Kd_psi');
    add_block('simulink/Sources/Constant', [ss '/DM'], ...
              'Position', [400 400 490 430], 'Value','d_mode');
    add_block('simulink/Signal Routing/Switch', [ss '/Dsel'], ...
              'Position', [540 190 580 330]);
    set_param([ss '/Dsel'], 'Criteria','u2 >= Threshold', 'Threshold','1.5');

    add_block('simulink/Math Operations/Sum', [ss '/SumN'], ...
              'Position', [640 110 670 150], 'Inputs','++');
    add_block('simulink/Discontinuities/Saturation', [ss '/SatN'], ...
              'Position', [720 110 760 150], ...
              'UpperLimit','2*F_max*half_beam', 'LowerLimit','-2*F_max*half_beam');

    add_line(ss,'psi_ref/1','HeadingErr/1','autorouting','on');
    add_line(ss,'psi/1',    'HeadingErr/2','autorouting','on');
    add_line(ss,'HeadingErr/1','Kp_psi/1','autorouting','on');
    add_line(ss,'HeadingErr/1','dedt/1','autorouting','on');
    add_line(ss,'r/1',        'Kd_rate/1','autorouting','on');
    add_line(ss,'dedt/1',   'Dsel/1','autorouting','on');
    add_line(ss,'DM/1',     'Dsel/2','autorouting','on');
    add_line(ss,'Kd_rate/1','Dsel/3','autorouting','on');
    add_line(ss,'Kp_psi/1','SumN/1','autorouting','on');
    add_line(ss,'Dsel/1',  'SumN/2','autorouting','on');
    add_line(ss,'SumN/1','SatN/1','autorouting','on');

    % ---------- 속도 제어 : u 되먹임 PI ----------
    add_block('simulink/Math Operations/Product', [ss '/Gate'], ...
              'Position', [200 380 235 420]);
    add_block('simulink/Math Operations/Sum', [ss '/SurgeErr'], ...
              'Position', [300 385 330 415], 'Inputs','+-');
    add_block('simulink/Continuous/PID Controller', [ss '/PI_u'], ...
              'Position', [400 370 490 430]);
    set_param([ss '/PI_u'], 'Controller','PI', ...
        'TimeDomain','Discrete-time', 'SampleTime','Ts_ctrl', ...
        'P','Kp_u', 'I','Ki_u', ...
        'LimitOutput','on', ...
        'UpperSaturationLimit','2*F_max', 'LowerSaturationLimit','-2*F_max', ...
        'AntiWindupMode','clamping');

    add_line(ss,'u_ref/1','Gate/1','autorouting','on');
    add_line(ss,'gate/1', 'Gate/2','autorouting','on');
    add_line(ss,'Gate/1','SurgeErr/1','autorouting','on');
    add_line(ss,'u/1',   'SurgeErr/2','autorouting','on');
    add_line(ss,'SurgeErr/1','PI_u/1','autorouting','on');

    % ---------- 추력배분 ----------
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/Alloc'], 'Position', [730 230 880 340]);
    setFcn(ss, 'Alloc', [ ...
'function [FL, FR] = Alloc(X, N, half_beam, Fmax)'                newline ...
'%#codegen'                                                       newline ...
'% Differential thrust allocation for two aft thrusters.'         newline ...
'%   X = FL + FR              surge force [N]'                    newline ...
'%   N = (FL - FR)*half_beam  yaw moment  [N*m]'                  newline ...
'FL = X/2 + N/(2*half_beam);'                                     newline ...
'FR = X/2 - N/(2*half_beam);'                                     newline ...
'if FL >  Fmax, FL =  Fmax; end'                                  newline ...
'if FL < -Fmax, FL = -Fmax; end'                                  newline ...
'if FR >  Fmax, FR =  Fmax; end'                                  newline ...
'if FR < -Fmax, FR = -Fmax; end']);

    add_block('simulink/Sources/Constant', [ss '/HB'], ...
              'Position', [600 460 690 490], 'Value','half_beam');
    add_block('simulink/Sources/Constant', [ss '/FM'], ...
              'Position', [600 510 690 540], 'Value','F_max');

    add_block('simulink/Sinks/Out1', [ss '/FL'], 'Position',[960 250 995 280], 'Port','1');
    add_block('simulink/Sinks/Out1', [ss '/FR'], 'Position',[960 310 995 340], 'Port','2');

    add_line(ss,'PI_u/1','Alloc/1','autorouting','on');
    add_line(ss,'SatN/1','Alloc/2','autorouting','on');
    add_line(ss,'HB/1',  'Alloc/3','autorouting','on');
    add_line(ss,'FM/1',  'Alloc/4','autorouting','on');
    add_line(ss,'Alloc/1','FL/1','autorouting','on');
    add_line(ss,'Alloc/2','FR/1','autorouting','on');

    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 3단 · THRUSTERS — 프로펠러 + 모터 모델
%   VRX 의 추진기 플러그인은 뉴턴을 받아 추력을 즉시 낸다.
%   실제 모터는 회전수 한계도 있고 응답 지연도 있다.
%   MSS otter.m 과 같은 프로펠러 법칙을 여기에 붙인다.
%
%     F_cmd -> n_cmd = sign(F)*sqrt(|F|/k) -> 포화 -> 1차 지연 -> n
%           -> F = k*n*|n|
%
%   같은 단을 두 모델에 똑같이 넣으므로 오프라인과 VRX 가 계속 일치한다.
% =====================================================================
function addThrusters(m, x, y)
    ss = [m '/Thrusters'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+170 y+120]);

    add_block('simulink/Sources/In1', [ss '/FL_cmd'], 'Position',[40 60 75 90],  'Port','1');
    add_block('simulink/Sources/In1', [ss '/FR_cmd'], 'Position',[40 140 75 170],'Port','2');

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/F2n'], 'Position', [170 70 320 160]);
    setFcn(ss, 'F2n', [ ...
'function n_cmd = F2n(FL, FR, k, n_max)'                              newline ...
'%#codegen'                                                           newline ...
'% Inverse propeller law: turn a demanded thrust into a shaft speed.' newline ...
'%   F = k*n*|n|   ->   n = sign(F)*sqrt(|F|/k)'                      newline ...
'% Saturation happens on SPEED, not on force. That is what a real'    newline ...
'% motor limits.'                                                     newline ...
'F = [FL; FR];'                                                       newline ...
'n_cmd = zeros(2,1);'                                                 newline ...
'for i = 1:2'                                                         newline ...
'    ni = sign(F(i)) * sqrt(abs(F(i))/k);'                            newline ...
'    if ni >  n_max, ni =  n_max; end'                                newline ...
'    if ni < -n_max, ni = -n_max; end'                                newline ...
'    n_cmd(i) = ni;'                                                  newline ...
'end']);

    add_block('simulink/Sources/Constant', [ss '/Kp'], ...
              'Position',[40 250 130 280], 'Value','k_prop');
    add_block('simulink/Sources/Constant', [ss '/Nm'], ...
              'Position',[40 300 130 330], 'Value','n_max');

    % 모터 1차 지연  n/n_cmd = a/(z-(1-a)),  a = Ts/tau
    add_block('simulink/Discrete/Discrete Transfer Fcn', [ss '/MotorLag'], ...
              'Position',[380 85 500 145]);
    set_param([ss '/MotorLag'], 'Numerator','Ts_ctrl/tau_n', ...
              'Denominator','[1, Ts_ctrl/tau_n - 1]', 'SampleTime','Ts_ctrl');

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/n2F'], 'Position', [560 70 700 160]);
    setFcn(ss, 'n2F', [ ...
'function [FL, FR] = n2F(n, k)'                                  newline ...
'%#codegen'                                                      newline ...
'% Forward propeller law. Note the |n| : thrust is quadratic in' newline ...
'% shaft speed, so a rate limit on n is NOT a rate limit on F.'  newline ...
'FL = k * n(1) * abs(n(1));'                                     newline ...
'FR = k * n(2) * abs(n(2));']);

    add_block('simulink/Sinks/Out1', [ss '/FL'], 'Position',[780 70 815 100], 'Port','1');
    add_block('simulink/Sinks/Out1', [ss '/FR'], 'Position',[780 130 815 160],'Port','2');
    add_block('simulink/Sinks/Out1', [ss '/n'],  'Position',[780 190 815 220],'Port','3');

    add_line(ss,'FL_cmd/1','F2n/1','autorouting','on');
    add_line(ss,'FR_cmd/1','F2n/2','autorouting','on');
    add_line(ss,'Kp/1','F2n/3','autorouting','on');
    add_line(ss,'Nm/1','F2n/4','autorouting','on');
    add_line(ss,'F2n/1','MotorLag/1','autorouting','on');
    add_line(ss,'MotorLag/1','n2F/1','autorouting','on');
    add_line(ss,'Kp/1','n2F/2','autorouting','on');
    add_line(ss,'n2F/1','FL/1','autorouting','on');
    add_line(ss,'n2F/2','FR/1','autorouting','on');
    add_line(ss,'MotorLag/1','n/1','autorouting','on');

    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 4단 · MOTION MODEL — 운동방정식 + 연속 적분 + 상태 산출을 한 블록에
%   VRX 모델에서 Gazebo 가 하는 일과 정확히 같은 자리를 차지한다.
%   두 모델의 최상위 구조가 이 블록 하나만 빼고 똑같아진다.
% =====================================================================
function addMotionModel(m, x, y)
    ss = [m '/MotionModel'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+210 y+200]);

    % EOM 의 2~6번 입력 순서. 앞의 둘만 신호이고 나머지 셋은 설정이다
    in = {'FL','FR','V_c','beta_c','p'};
    for k = 1:2
        add_block('simulink/Sources/In1', [ss '/' in{k}], ...
                  'Position', [40 60+(k-1)*70 75 60+(k-1)*70+30], 'Port', num2str(k));
    end

    % 조류와 선체 계수는 신호가 아니라 설정이다. 상자 안에 둔다.
    % 최상위에 두면 상수 세 개와 선 세 개가 운동모델 앞을 가린다.
    cfg = {'V_c','current_speed'; 'beta_c','beta_c'; ...
           'p','[m_usv; Izz; Xu; Xuu; Yv; Yvv; Nr; Nrr; half_beam]'};
    for k = 1:3
        add_block('simulink/Sources/Constant', [ss '/' cfg{k,1}], ...
                  'Position', [40 220+(k-1)*70 130 220+(k-1)*70+30], 'Value', cfg{k,2});
    end
    % ---- 운동방정식 (미분) ----
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/EOM'], 'Position', [200 60 380 260]);
    setFcn(ss, 'EOM', [ ...
'function xdot = EOM(s, FL, FR, V_c, beta_c, p)'                         newline ...
'%#codegen'                                                              newline ...
'% 3-DOF WAM-V equations of motion, NED.'                                newline ...
'% Coefficients come straight from the Gazebo VRX plugins:'              newline ...
'%   drag       : SimpleHydrodynamics  (Xu Xuu Yv Yvv Nr Nrr)'           newline ...
'%   mass       : wamv_base.urdf.xacro (180 kg hull + engines)'          newline ...
'%   added mass : zero in VRX (xDotU = yDotV = nDotR = 0)'               newline ...
'% Ocean current exists only here. Gazebo has no current plugin.'        newline ...
'%   s = [u v r N E psi]'''                                              newline ...
'%   p = [m Izz Xu Xuu Yv Yvv Nr Nrr half_beam]'''                       newline ...
''                                                                       newline ...
'u = s(1); v = s(2); r = s(3); psi = s(6);'                              newline ...
'm=p(1); Izz=p(2); Xu=p(3); Xuu=p(4); Yv=p(5); Yvv=p(6);'                newline ...
'Nr=p(7); Nrr=p(8); b_half=p(9);'                                        newline ...
''                                                                       newline ...
'% current in the body frame -> velocity relative to the water'          newline ...
'u_c = V_c*cos(beta_c - psi);'                                           newline ...
'v_c = V_c*sin(beta_c - psi);'                                           newline ...
'u_r = u - u_c;'                                                         newline ...
'v_r = v - v_c;'                                                         newline ...
''                                                                       newline ...
'% differential thrust -> surge force and yaw moment'                    newline ...
'X = FL + FR;'                                                           newline ...
'N = (FL - FR)*b_half;'                                                  newline ...
''                                                                       newline ...
'% drag acts on the velocity relative to the water'                      newline ...
'Dx = (Xu + Xuu*abs(u_r))*u_r;'                                          newline ...
'Dy = (Yv + Yvv*abs(v_r))*v_r;'                                          newline ...
'Dn = (Nr + Nrr*abs(r))*r;'                                              newline ...
''                                                                       newline ...
'du = (X - Dx)/m + v*r;      % rigid-body Coriolis'                      newline ...
'dv = (  - Dy)/m - u*r;'                                                 newline ...
'dr = (N - Dn)/Izz;'                                                     newline ...
''                                                                       newline ...
'xdot = [du; dv; dr;'                                                    newline ...
'        u*cos(psi) - v*sin(psi);   % kinematics use absolute velocity'  newline ...
'        u*sin(psi) + v*cos(psi);'                                       newline ...
'        r];']);

    % ---- 연속 적분기 ----
    add_block('simulink/Continuous/Integrator', [ss '/Integ'], ...
              'Position', [450 130 500 180], 'InitialCondition','x0');

    % ---- 상태 -> 항법량 ----
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/States'], 'Position', [570 60 720 260]);
    setFcn(ss, 'States', [ ...
'function [pn, pe, psi, u, r, beta, chi, U] = States(s)'    newline ...
'%#codegen'                                                 newline ...
'% Pick the navigation quantities out of the state vector.' newline ...
'% In the VRX model this job is done by the Nav block,'     newline ...
'% which also has to convert ENU to NED.'                   newline ...
'u = s(1); v = s(2); r = s(3);'                             newline ...
'pn = s(4); pe = s(5); psi = s(6);'                         newline ...
'U    = sqrt(u*u + v*v);      % speed over ground'          newline ...
'beta = atan2(v, u);          % crab angle'                 newline ...
'c    = psi + beta;           % course angle'               newline ...
'chi  = atan2(sin(c), cos(c));']);

    % --- 배치 : 한 줄에 EOM -> 1/s -> States. 포트 높이를 읽어서 맞춘다 ----
    ROW = 340;
    set_param([ss '/EOM'],    'Position', [280 100 460 580]);
    set_param([ss '/Integ'],  'Position', [560 ROW-15 590 ROW+15]);
    set_param([ss '/States'], 'Position', [680 100 840 580]);

    % 2~6번 입력(추력 둘 + 설정 셋)을 각자 포트 높이로 옮겨 직선으로 잇는다
    row_feed(ss, 'EOM', [{''}, in]);

    add_line(ss, 'EOM/1',   'Integ/1');
    add_line(ss, 'Integ/1', 'States/1');

    % 상태 되먹임 — 적분기 출력이 자기 미분식으로 돌아간다.
    % 화면을 가로지르는 대신 태그로 건너뛴다. 되먹임은 늘 이렇게 처리한다
    drop_tag(ss, 'Integ', 1, 'x_state', 280);
    b = port_xy(ss, 'EOM', 'Inport', 1);
    add_block('simulink/Signal Routing/From', [ss '/Fr_x_state'], ...
              'Position', [180 b(2)-11 250 b(2)+11], 'GotoTag','x_state');
    add_line(ss, 'Fr_x_state/1', 'EOM/1');

    % 출력 포트를 States 의 포트 높이에 맞춘다 -> 여덟 선이 전부 직선
    out = {'pn','pe','psi','u','r','beta','chi','U'};
    for k = 1:numel(out)
        q = port_xy(ss, 'States', 'Outport', k);
        add_block('simulink/Sinks/Out1', [ss '/' out{k}], ...
                  'Position', [940 q(2)-7 970 q(2)+7], 'Port', num2str(k));
        add_line(ss, sprintf('States/%d',k), [out{k} '/1']);
    end
end

% =====================================================================
% 5단 · ANIMATE — 시뮬레이션이 도는 동안 실시간으로 그린다
%   MATLAB Function 블록은 원래 그림을 못 그린다.
%   coder.extrinsic 으로 선언하면 컴파일하지 않고 MATLAB 함수를 그대로 부른다.
%   실제 그리기는 W07_animate.m 이 한다.
% =====================================================================
function addAnimate(m, x, y)
% 실시간 그림 — 포트 없는 서브시스템 하나로 묶는다.
% 공용 도구 _tools/add_animate_box.m 이 안을 채운다.
    add_animate_box(m, {'pn','pe','psi'}, 'W07_animate', '', [x y], 'Ts_ctrl');
end

% =====================================================================
% 설정 상수 + 유도/내부루프 입력 배선 (두 모델 공통)
% =====================================================================
function wireFront(m)
% 유도·내부루프의 되먹임 입력 배선 (두 모델 공통)
%
%   설정값(웨이포인트·Delta·R·mode·u_ref)은 각 서브시스템 **안에** 있다.
%   최상위에 남는 것은 **되먹임 다섯 개**뿐이다 — 그것이 이 모델이 하는 일이다.
    F(m,'pn','a', 40,  65);
    F(m,'pe','a', 40, 110);

    add_line(m,'Fr_pn_a/1','Guidance/1','autorouting','on');
    add_line(m,'Fr_pe_a/1','Guidance/2','autorouting','on');

    % 유도 출력에 로깅용 Goto 를 붙인다 (본선은 그대로 InnerLoop 로 간다)
    G(m,'psi_ref', 560,  70);
    G(m,'y_e',     560, 110);
    G(m,'x_e',     560, 150);
    G(m,'gate',    560, 190);
    add_line(m,'Guidance/1','Go_psi_ref/1','autorouting','on');
    add_line(m,'Guidance/2','Go_y_e/1','autorouting','on');
    add_line(m,'Guidance/3','Go_x_e/1','autorouting','on');
    add_line(m,'Guidance/4','Go_gate/1','autorouting','on');

    % 2단 입력: 자세·속도 되먹임
    F(m,'psi','b', 560, 360);
    F(m,'r',  'b', 560, 400);
    F(m,'u',  'b', 560, 440);

    add_line(m,'Guidance/1','InnerLoop/1','autorouting','on');
    add_line(m,'Guidance/4','InnerLoop/2','autorouting','on');
    add_line(m,'Fr_psi_b/1','InnerLoop/3','autorouting','on');
    add_line(m,'Fr_r_b/1',  'InnerLoop/4','autorouting','on');
    add_line(m,'Fr_u_b/1',  'InnerLoop/5','autorouting','on');
end

function F(m, tag, sfx, x, y)
    add_block('simulink/Signal Routing/From', [m '/Fr_' tag '_' sfx], ...
              'Position', [x y x+70 y+25], 'GotoTag', tag);
end

function G(m, tag, x, y)
    add_block('simulink/Signal Routing/Goto', [m '/Go_' tag], ...
              'Position', [x y x+80 y+25], 'GotoTag', tag, 'TagVisibility','global');
end

function wireThrusterGotos(m, x, y)
    t = {'FL','FR','nprop'};
    for k = 1:3
        G(m, t{k}, x, y+(k-1)*40);
        add_line(m, sprintf('Thrusters/%d',k), ['Go_' t{k} '/1'], 'autorouting','on');
    end
end

function wireNavGotos(m, x, y)
% Nav 출력을 전부 Goto 태그로 내보낸다.
% 되먹임 선과 로깅 선이 화면을 가로지르지 않게 하는 표준 방법이다.
    tags = {'pn','pe','psi','u','r','beta','chi','U'};
    for k = 1:numel(tags)
        G(m, tags{k}, x, y+(k-1)*40);
        add_line(m, sprintf('Nav/%d',k), ['Go_' tags{k} '/1'], 'autorouting','on');
    end
end

% =====================================================================
% 실습 A — 오프라인 모델
% =====================================================================
function build_offline()
    m = 'W07_0_offline'; fresh(m);
    % 운동모델을 연속 적분기로 풀기 때문에 ode4 (4차 룽게쿠타) 를 쓴다.
    % 제어기·유도·추진기는 Ts_ctrl 로 도는 이산 블록이다 (하이브리드 구성).
    set_param(m, 'SolverType','Fixed-step', 'SolverName','ode4', ...
                 'FixedStep','Ts_ctrl', 'StopTime','600', 'SimulationMode','normal');

    addGuidance(m, 250, 60);
    addInnerLoop(m, 720, 280);
    wireFront(m);
    addThrusters(m, 1000, 290);
    wireThrusterGotos(m, 1230, 290);

    % --- 4단 · 운동모델 (운동방정식 + 연속 적분 + 상태 산출) --------------

    addMotionModel(m, 1450, 280);

    add_line(m,'Thrusters/1','MotionModel/1','autorouting','on');
    add_line(m,'Thrusters/2','MotionModel/2','autorouting','on');

    add_line(m,'InnerLoop/1','Thrusters/1','autorouting','on');
    add_line(m,'InnerLoop/2','Thrusters/2','autorouting','on');

    % --- 되먹임 태그 + 로깅 ---------------------------------------------
    tags = {'pn','pe','psi','u','r','beta','chi','U'};
    for k = 1:numel(tags)
        G(m, tags{k}, 1760, 280+(k-1)*40);
        add_line(m, sprintf('MotionModel/%d',k), ['Go_' tags{k} '/1'], 'autorouting','on');
    end
    addAnimate(m, 1760, 650);
    addLogging(m, 2250, 60);

    note(m,'n1', ['W07 실습 A  —  오프라인 WAM-V (Gazebo 불필요)' newline ...
        'Guidance -> Inner Loop -> Thrusters -> 운동모델' newline ...
        '조류 실험은 이 모델에서만 가능하다.' newline ...
        '실행 전 >> W07_setup'], 250, -90);

    save_system(m); close_system(m);
    fprintf('  W07_0_offline  생성\n');
end

% =====================================================================
% 실습 B — VRX 연동 모델
% =====================================================================
function build_vrx()
    m = 'W07_1_vrx'; fresh(m);
    load_system('ros2lib');
    setSolver(m, 'inf');

    addGuidance(m, 250, 60);
    addInnerLoop(m, 720, 280);
    wireFront(m);
    addThrusters(m, 1000, 290);
    wireThrusterGotos(m, 1230, 620);

    % --- 4단 · 추력 발행 (운동모델 = Gazebo) -----------------------------
    add_cmd_publisher(m, [1300 260], ...
        {'/wamv/thrusters/left/thrust','/wamv/thrusters/right/thrust'}, 'Ts_ctrl');
    add_line(m,'InnerLoop/1','Thrusters/1','autorouting','on');
    add_line(m,'InnerLoop/2','Thrusters/2','autorouting','on');
    add_line(m,'Thrusters/1','CmdPublisher/1','autorouting','on');
    add_line(m,'Thrusters/2','CmdPublisher/2','autorouting','on');

    % --- 5단 · 항법 (ENU -> NED 변환) -----------------------------------
    navCode = [ ...
'function [pn, pe, psi, u, r, beta, chi, U] = Nav(ex, ey, qx, qy, qz, qw, bx, by, wz, orgN, orgE)' newline ...
'%#codegen'                                                                 newline ...
'% Gazebo/ROS uses ENU with a body frame of x-forward, y-LEFT, z-UP.'       newline ...
'% Marine control uses NED with a body frame of x-forward, y-STARBOARD.'    newline ...
'% Position :  N = y_ENU,  E = x_ENU'                                       newline ...
'% Heading  :  psi_NED = pi/2 - yaw_ENU'                                    newline ...
'% Body vel :  u = bx,  v = -by,  r = -wz    (y and z flip sign)'           newline ...
''                                                                          newline ...
'% 첫 메시지가 도착하기 전에는 Subscribe 가 0 으로 채운 버스를 낸다.'       newline ...
'% 그대로 쓰면 위치가 스폰 원점만큼(약 568 m) 튀어 로그 첫 점이 망가진다.'  newline ...
'if ex == 0 && ey == 0'                                                     newline ...
'    pn = 0; pe = 0; psi = 0; u = 0; r = 0; beta = 0; chi = 0; U = 0;'      newline ...
'    return'                                                                newline ...
'end'                                                                       newline ...
'pn = ey - orgN;    % north, relative to the spawn point'                   newline ...
'pe = ex - orgE;    % east'                                                 newline ...
''                                                                          newline ...
'yaw_enu = atan2(2*(qw*qz + qx*qy), 1 - 2*(qy*qy + qz*qz));'                newline ...
'p   = pi/2 - yaw_enu;'                                                     newline ...
'psi = atan2(sin(p), cos(p));'                                              newline ...
''                                                                          newline ...
'u = bx;'                                                                   newline ...
'v = -by;'                                                                  newline ...
'r = -wz;'                                                                  newline ...
''                                                                          newline ...
'U    = sqrt(u*u + v*v);'                                                   newline ...
'beta = atan2(v, u);          % crab angle'                                 newline ...
'c    = psi + beta;'                                                        newline ...
'chi  = atan2(sin(c), cos(c));'];

    add_pose_subscriber(m, [1660 620], ...
        '/wamv/sensors/position/ground_truth_odometry', 'Ts_ctrl', navCode, ...
        {'pn','pe','psi','u','r','beta','chi','U'});

    % 항법 출력을 전부 Goto 태그로 내보낸다
    tags = {'pn','pe','psi','u','r','beta','chi','U'};
    for k = 1:numel(tags)
        G(m, tags{k}, 1980, 620+(k-1)*45);
        add_line(m, sprintf('PoseSubscriber/%d',k), ['Go_' tags{k} '/1'], 'autorouting','on');
    end

    addAnimate(m, 2080, 1100);
    addLogging(m, 2400, 60);

    note(m,'n1', ['W07 실습 B  —  VRX 연동 (Gazebo 필요)' newline ...
        'Guidance -> Inner Loop -> Thrusters -> Gazebo -> Navigation' newline ...
        '유도부·내부루프·추진기·게인은 W07_0_offline 과 완전히 같다.' newline ...
        '운동모델만 Gazebo 로 바뀐다.' newline ...
        '실행 전: (1) W07_setup  (2) VRX 기동  (3) 페이싱을 RTF 에 맞출 것'], 250, -90);

    save_system(m); close_system(m);
    fprintf('  W07_1_vrx      생성\n');
end

% ---------------------------------------------------------------------
% 추력 발행 3종 세트 (6주차와 동일)
% ---------------------------------------------------------------------
function addThrusterPublisher(m, side, tag, x, y)
    add_block('ros2lib/Blank Message', [m '/Blank' tag], ...
              'Position', [x y+70 x+100 y+110]);
    set_param([m '/Blank' tag], 'entityType','std_msgs/Float64', ...
              'messageType','std_msgs/Float64', 'SampleTime','Ts_ctrl');
    add_block('simulink/Signal Routing/Bus Assignment', [m '/Asg' tag], ...
              'Position', [x+160 y x+220 y+115]);
    set_param([m '/Asg' tag], 'AssignedSignals','data');
    add_block('ros2lib/Publish', [m '/Pub' tag], ...
              'Position', [x+290 y+35 x+390 y+75]);
    set_param([m '/Pub' tag], 'topicSource','Specify your own', ...
              'topic', ['/wamv/thrusters/' side '/thrust'], ...
              'messageType','std_msgs/Float64');
    add_line(m, ['Blank' tag '/1'], ['Asg' tag '/1'], 'autorouting','on');
    add_line(m, ['Asg'   tag '/1'], ['Pub' tag '/1'], 'autorouting','on');
end

% ---------------------------------------------------------------------
% 로깅 — W07_plot.m 이 읽는다
% ---------------------------------------------------------------------
function addLogging(m, x, y)
% 로깅 — 포트 없는 서브시스템 하나로 묶는다. W07_plot.m 이 이 변수들을 읽는다.
%   신호 이름 = Goto 태그 이름 (n 만 nprop 태그를 쓴다)
    sig = {'pn','pe','psi','psi_ref','y_e','x_e','beta','chi','u','r','U','gate','FL','FR','n'};
    tag = {'pn','pe','psi','psi_ref','y_e','x_e','beta','chi','u','r','U','gate','FL','FR','nprop'};
    add_logging_box(m, sig, tag, [x y], 'Ts_ctrl');
end
