function build_w07_models()
% BUILD_W07_MODELS  7주차 Simulink 모델 2개를 생성한다.
%
%     W07_0_offline.slx   오프라인 WAM-V — Gazebo 없이 돈다. 조류 실험용
%     W07_1_vrx.slx       VRX 연동 — 운동모델만 Gazebo 로 바뀐다
%
%   실제 GNC 루프 순서대로 왼쪽에서 오른쪽으로 배치된다.
%
%   Guidance → Inner Loop → Thrusters → 운동모델 → Navigation
%   (유도)      (헤딩 P-D +   (프로펠러   (플랜트)    (상태 산출)
%               속도 PI +      + 모터)
%               추력배분)
%       ↑            ↑                                    |
%       └── Goto/From 태그로 되먹임 ─────────────────────────┘
%
%   구조는 MSS 툴박스의 demoOtterUSVHeadingControl_P_D_Waypoint.slx 를 따른다.
%     - 유도는 psi_ref (선수각) 를 낸다.  침로각이 아니다
%     - 헤딩 제어는 P-D 요각속도 되먹임:  tau_N = Kp*ssa(psi_ref-psi) - Kd*r
%       오차를 미분하지 않으므로 웨이포인트 전환 때 미분 킥이 없다
%     - 속도 제어는 u (surge velocity) 되먹임.  U = sqrt(u^2+v^2) 가 아니다
%
%   두 모델은 유도부·내부루프·게인이 전부 같다. 다른 것은 두 가지뿐이다.
%     1) 운동모델 : MATLAB Function (VRX 와 같은 계수)  vs  Gazebo 실물
%     2) 조류     : 오프라인만 가능. VRX 에는 해류 플러그인이 없다
%
%   모델이 깨졌을 때 이 스크립트를 다시 돌리면 복구된다.
%   실행 전에 반드시 >> W07_setup 을 먼저 실행할 것.

    here = fileparts(mfilename('fullpath'));
    cd(here);

    if evalin('base', '~exist(''wp_north'',''var'')')
        error('먼저 W07_setup 을 실행하십시오.');
    end

    build_offline();
    build_vrx();


    % 배치와 색을 정리한다. 선은 직선 또는 직각으로만 다시 그린다.
    slxList = dir('*.slx');
    for k = 1:numel(slxList)
        [~, mName] = fileparts(slxList(k).name);
        try, tidy_layout(mName); tidy_layout(mName); catch, end
    end
    fprintf('\n완료. 생성된 모델:\n');
    d = dir('W07_*.slx');
    for k = 1:numel(d), fprintf('  %s\n', d(k).name); end
end

% =====================================================================
% 공통 헬퍼
% =====================================================================
function fresh(m)
    try, close_system(m, 0); catch, end
    if exist([m '.slx'],'file'), delete([m '.slx']); end
    new_system(m);
end

function setSolver(m, stopTime)
    set_param(m, 'SolverType','Fixed-step', 'SolverName','FixedStepDiscrete', ...
                 'FixedStep','Ts_ctrl', 'StopTime',stopTime, 'SimulationMode','normal');
end

function setFcn(sys, path, code)
    S  = sfroot;
    ch = S.find('-isa','Stateflow.EMChart','Path',[sys '/' path]);
    ch.Script = code;
end

function C(m, name, value, x, y)
    add_block('simulink/Sources/Constant', [m '/' name], ...
              'Position', [x y x+95 y+30], 'Value', value);
end

function note(m, tag, txt, x, y)
    add_block('built-in/Note', [m '/' tag], 'Position',[x y x y], 'Text', txt);
end

% =====================================================================
% 1단 · GUIDANCE
% =====================================================================
function addGuidance(m, x, y)
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [m '/Guidance'], 'Position', [x y x+190 y+200]);
    setFcn(m, 'Guidance', [ ...
'function [psi_ref, y_e, wp_idx, gate] = Guidance(pn, pe, wp_n, wp_e, Delta, R, mode, idx_prev)' newline ...
'%#codegen'                                                                     newline ...
'% Waypoint guidance. Two laws in one block. Both return a HEADING command,'    newline ...
'% following the MSS demo demoOtterUSVHeadingControl_P_D_Waypoint.slx.'         newline ...
'%   mode 1 = atan2 : aim straight at the next waypoint (point chasing)'        newline ...
'%   mode 2 = LOS   : follow the straight line between two waypoints'           newline ...
''                                                                              newline ...
'n = numel(wp_n);'                                                              newline ...
'k = min(max(idx_prev, 1), n-1);        % index of the active leg'              newline ...
''                                                                              newline ...
'xk  = wp_n(k);    yk  = wp_e(k);       % leg start'                            newline ...
'xk1 = wp_n(k+1);  yk1 = wp_e(k+1);     % leg end = next waypoint'              newline ...
''                                                                              newline ...
'% path-tangential angle of the active leg'                                     newline ...
'pi_p = atan2(yk1 - yk, xk1 - xk);'                                             newline ...
''                                                                              newline ...
'% cross-track error. Computed the same way for BOTH modes so that the two'     newline ...
'% guidance laws can be compared with the same yardstick.'                      newline ...
'y_e = -(pn - xk)*sin(pi_p) + (pe - yk)*cos(pi_p);'                             newline ...
''                                                                              newline ...
'if mode == 1'                                                                  newline ...
'    psi_ref = atan2(yk1 - pe, xk1 - pn);'                                      newline ...
'else'                                                                          newline ...
'    psi_ref = pi_p - atan(y_e / Delta);'                                       newline ...
'end'                                                                           newline ...
''                                                                              newline ...
'% waypoint switching: circle of acceptance'                                    newline ...
'd_next = sqrt((xk1 - pn)^2 + (yk1 - pe)^2);'                                   newline ...
'if (d_next <= R) && (k < n-1)'                                                 newline ...
'    wp_idx = k + 1;'                                                           newline ...
'else'                                                                          newline ...
'    wp_idx = k;'                                                               newline ...
'end'                                                                           newline ...
''                                                                              newline ...
'% mission finished? gate = 0 brings the boat to a stop.'                       newline ...
'% Without it the boat would follow the last leg forever.'                      newline ...
'if (k == n-1) && (d_next <= R)'                                                newline ...
'    gate = 0;'                                                                 newline ...
'else'                                                                          newline ...
'    gate = 1;'                                                                 newline ...
'end']);

    add_block('simulink/Discrete/Unit Delay', [m '/IdxDelay'], ...
              'Position', [x+55 y+250 x+130 y+285], ...
              'InitialCondition','1', 'SampleTime','Ts_ctrl');
    add_line(m, 'Guidance/3', 'IdxDelay/1', 'autorouting','on');
    add_line(m, 'IdxDelay/1', 'Guidance/8', 'autorouting','on');
end

% =====================================================================
% 2단 · INNER LOOP — 헤딩 P-D + 속도 PI + 추력배분
% =====================================================================
function addInnerLoop(m, x, y)
    ss = [m '/InnerLoop'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+190 y+170]);

    in = {'psi_ref','gate','u_ref','psi','r','u'};
    for k = 1:numel(in)
        add_block('simulink/Sources/In1', [ss '/' in{k}], ...
                  'Position', [40 60+(k-1)*80 75 60+(k-1)*80+30], 'Port', num2str(k));
    end

    % ---------- 헤딩 제어 : tau_N = Kp*ssa(psi_ref - psi) - Kd*r ----------
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/HeadingErr'], 'Position', [200 60 340 130]);
    setFcn(ss, 'HeadingErr', [ ...
'function e = HeadingErr(psi_ref, psi)'                          newline ...
'%#codegen'                                                      newline ...
'% Shortest signed angle (ssa). Without it a command of 179 deg' newline ...
'% against a heading of -179 deg reads as a 358 deg error and'   newline ...
'% the boat turns the long way round.'                           newline ...
'd = psi_ref - psi;'                                             newline ...
'e = atan2(sin(d), cos(d));']);

    add_block('simulink/Math Operations/Gain', [ss '/Kp_psi'], ...
              'Position', [410 60 460 100], 'Gain','Kp_psi');

    % D 항을 만드는 두 가지 방법. d_mode 로 고른다.
    %   d_mode = 1  요각속도 되먹임   -Kd*r          (기본. 미분 킥이 없다)
    %   d_mode = 2  오차 미분         +Kd*de/dt      (9주차 비교 실험용)
    add_block('simulink/Math Operations/Gain', [ss '/Kd_rate'], ...
              'Position', [410 300 460 340], 'Gain','-Kd_psi');
    add_block('simulink/Discrete/Discrete Derivative', [ss '/dedt'], ...
              'Position', [400 180 470 240]);
    set_param([ss '/dedt'], 'gainval','Kd_psi');
    add_block('simulink/Sources/Constant', [ss '/DM'], ...
              'Position', [400 400 490 430], 'Value','d_mode');
    add_block('simulink/Signal Routing/Switch', [ss '/Dsel'], ...
              'Position', [540 190 580 330]);
    set_param([ss '/Dsel'], 'Criteria','u2 >= Threshold', 'Threshold','1.5');

    add_block('simulink/Math Operations/Sum', [ss '/SumN'], ...
              'Position', [640 110 670 150], 'Inputs','++');
    add_block('simulink/Discontinuities/Saturation', [ss '/SatN'], ...
              'Position', [720 110 760 150], ...
              'UpperLimit','2*F_max*half_beam', 'LowerLimit','-2*F_max*half_beam');

    add_line(ss,'psi_ref/1','HeadingErr/1','autorouting','on');
    add_line(ss,'psi/1',    'HeadingErr/2','autorouting','on');
    add_line(ss,'HeadingErr/1','Kp_psi/1','autorouting','on');
    add_line(ss,'HeadingErr/1','dedt/1','autorouting','on');
    add_line(ss,'r/1',        'Kd_rate/1','autorouting','on');
    add_line(ss,'dedt/1',   'Dsel/1','autorouting','on');
    add_line(ss,'DM/1',     'Dsel/2','autorouting','on');
    add_line(ss,'Kd_rate/1','Dsel/3','autorouting','on');
    add_line(ss,'Kp_psi/1','SumN/1','autorouting','on');
    add_line(ss,'Dsel/1',  'SumN/2','autorouting','on');
    add_line(ss,'SumN/1','SatN/1','autorouting','on');

    % ---------- 속도 제어 : u 되먹임 PI ----------
    add_block('simulink/Math Operations/Product', [ss '/Gate'], ...
              'Position', [200 380 235 420]);
    add_block('simulink/Math Operations/Sum', [ss '/SurgeErr'], ...
              'Position', [300 385 330 415], 'Inputs','+-');
    add_block('simulink/Continuous/PID Controller', [ss '/PI_u'], ...
              'Position', [400 370 490 430]);
    set_param([ss '/PI_u'], 'Controller','PI', ...
        'TimeDomain','Discrete-time', 'SampleTime','Ts_ctrl', ...
        'P','Kp_u', 'I','Ki_u', ...
        'LimitOutput','on', ...
        'UpperSaturationLimit','2*F_max', 'LowerSaturationLimit','-2*F_max', ...
        'AntiWindupMode','clamping');

    add_line(ss,'u_ref/1','Gate/1','autorouting','on');
    add_line(ss,'gate/1', 'Gate/2','autorouting','on');
    add_line(ss,'Gate/1','SurgeErr/1','autorouting','on');
    add_line(ss,'u/1',   'SurgeErr/2','autorouting','on');
    add_line(ss,'SurgeErr/1','PI_u/1','autorouting','on');

    % ---------- 추력배분 ----------
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/Alloc'], 'Position', [730 230 880 340]);
    setFcn(ss, 'Alloc', [ ...
'function [FL, FR] = Alloc(X, N, half_beam, Fmax)'                newline ...
'%#codegen'                                                       newline ...
'% Differential thrust allocation for two aft thrusters.'         newline ...
'%   X = FL + FR              surge force [N]'                    newline ...
'%   N = (FL - FR)*half_beam  yaw moment  [N*m]'                  newline ...
'FL = X/2 + N/(2*half_beam);'                                     newline ...
'FR = X/2 - N/(2*half_beam);'                                     newline ...
'if FL >  Fmax, FL =  Fmax; end'                                  newline ...
'if FL < -Fmax, FL = -Fmax; end'                                  newline ...
'if FR >  Fmax, FR =  Fmax; end'                                  newline ...
'if FR < -Fmax, FR = -Fmax; end']);

    add_block('simulink/Sources/Constant', [ss '/HB'], ...
              'Position', [600 460 690 490], 'Value','half_beam');
    add_block('simulink/Sources/Constant', [ss '/FM'], ...
              'Position', [600 510 690 540], 'Value','F_max');

    add_block('simulink/Sinks/Out1', [ss '/FL'], 'Position',[960 250 995 280], 'Port','1');
    add_block('simulink/Sinks/Out1', [ss '/FR'], 'Position',[960 310 995 340], 'Port','2');

    add_line(ss,'PI_u/1','Alloc/1','autorouting','on');
    add_line(ss,'SatN/1','Alloc/2','autorouting','on');
    add_line(ss,'HB/1',  'Alloc/3','autorouting','on');
    add_line(ss,'FM/1',  'Alloc/4','autorouting','on');
    add_line(ss,'Alloc/1','FL/1','autorouting','on');
    add_line(ss,'Alloc/2','FR/1','autorouting','on');

    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 3단 · THRUSTERS — 프로펠러 + 모터 모델
%   VRX 의 추진기 플러그인은 뉴턴을 받아 추력을 즉시 낸다.
%   실제 모터는 회전수 한계도 있고 응답 지연도 있다.
%   MSS otter.m 과 같은 프로펠러 법칙을 여기에 붙인다.
%
%     F_cmd -> n_cmd = sign(F)*sqrt(|F|/k) -> 포화 -> 1차 지연 -> n
%           -> F = k*n*|n|
%
%   같은 단을 두 모델에 똑같이 넣으므로 오프라인과 VRX 가 계속 일치한다.
% =====================================================================
function addThrusters(m, x, y)
    ss = [m '/Thrusters'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+170 y+120]);

    add_block('simulink/Sources/In1', [ss '/FL_cmd'], 'Position',[40 60 75 90],  'Port','1');
    add_block('simulink/Sources/In1', [ss '/FR_cmd'], 'Position',[40 140 75 170],'Port','2');

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/F2n'], 'Position', [170 70 320 160]);
    setFcn(ss, 'F2n', [ ...
'function n_cmd = F2n(FL, FR, k, n_max)'                              newline ...
'%#codegen'                                                           newline ...
'% Inverse propeller law: turn a demanded thrust into a shaft speed.' newline ...
'%   F = k*n*|n|   ->   n = sign(F)*sqrt(|F|/k)'                      newline ...
'% Saturation happens on SPEED, not on force. That is what a real'    newline ...
'% motor limits.'                                                     newline ...
'F = [FL; FR];'                                                       newline ...
'n_cmd = zeros(2,1);'                                                 newline ...
'for i = 1:2'                                                         newline ...
'    ni = sign(F(i)) * sqrt(abs(F(i))/k);'                            newline ...
'    if ni >  n_max, ni =  n_max; end'                                newline ...
'    if ni < -n_max, ni = -n_max; end'                                newline ...
'    n_cmd(i) = ni;'                                                  newline ...
'end']);

    add_block('simulink/Sources/Constant', [ss '/Kp'], ...
              'Position',[40 250 130 280], 'Value','k_prop');
    add_block('simulink/Sources/Constant', [ss '/Nm'], ...
              'Position',[40 300 130 330], 'Value','n_max');

    % 모터 1차 지연  n/n_cmd = a/(z-(1-a)),  a = Ts/tau
    add_block('simulink/Discrete/Discrete Transfer Fcn', [ss '/MotorLag'], ...
              'Position',[380 85 500 145]);
    set_param([ss '/MotorLag'], 'Numerator','Ts_ctrl/tau_n', ...
              'Denominator','[1, Ts_ctrl/tau_n - 1]', 'SampleTime','Ts_ctrl');

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/n2F'], 'Position', [560 70 700 160]);
    setFcn(ss, 'n2F', [ ...
'function [FL, FR] = n2F(n, k)'                                  newline ...
'%#codegen'                                                      newline ...
'% Forward propeller law. Note the |n| : thrust is quadratic in' newline ...
'% shaft speed, so a rate limit on n is NOT a rate limit on F.'  newline ...
'FL = k * n(1) * abs(n(1));'                                     newline ...
'FR = k * n(2) * abs(n(2));']);

    add_block('simulink/Sinks/Out1', [ss '/FL'], 'Position',[780 70 815 100], 'Port','1');
    add_block('simulink/Sinks/Out1', [ss '/FR'], 'Position',[780 130 815 160],'Port','2');
    add_block('simulink/Sinks/Out1', [ss '/n'],  'Position',[780 190 815 220],'Port','3');

    add_line(ss,'FL_cmd/1','F2n/1','autorouting','on');
    add_line(ss,'FR_cmd/1','F2n/2','autorouting','on');
    add_line(ss,'Kp/1','F2n/3','autorouting','on');
    add_line(ss,'Nm/1','F2n/4','autorouting','on');
    add_line(ss,'F2n/1','MotorLag/1','autorouting','on');
    add_line(ss,'MotorLag/1','n2F/1','autorouting','on');
    add_line(ss,'Kp/1','n2F/2','autorouting','on');
    add_line(ss,'n2F/1','FL/1','autorouting','on');
    add_line(ss,'n2F/2','FR/1','autorouting','on');
    add_line(ss,'MotorLag/1','n/1','autorouting','on');

    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 4단 · MOTION MODEL — 운동방정식 + 연속 적분 + 상태 산출을 한 블록에
%   VRX 모델에서 Gazebo 가 하는 일과 정확히 같은 자리를 차지한다.
%   두 모델의 최상위 구조가 이 블록 하나만 빼고 똑같아진다.
% =====================================================================
function addMotionModel(m, x, y)
    ss = [m '/MotionModel'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+210 y+200]);

    in = {'FL','FR','V_c','beta_c','p'};
    for k = 1:numel(in)
        add_block('simulink/Sources/In1', [ss '/' in{k}], ...
                  'Position', [40 60+(k-1)*70 75 60+(k-1)*70+30], 'Port', num2str(k));
    end

    % ---- 운동방정식 (미분) ----
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/EOM'], 'Position', [200 60 380 260]);
    setFcn(ss, 'EOM', [ ...
'function xdot = EOM(s, FL, FR, V_c, beta_c, p)'                         newline ...
'%#codegen'                                                              newline ...
'% 3-DOF WAM-V equations of motion, NED.'                                newline ...
'% Coefficients come straight from the Gazebo VRX plugins:'              newline ...
'%   drag       : SimpleHydrodynamics  (Xu Xuu Yv Yvv Nr Nrr)'           newline ...
'%   mass       : wamv_base.urdf.xacro (180 kg hull + engines)'          newline ...
'%   added mass : zero in VRX (xDotU = yDotV = nDotR = 0)'               newline ...
'% Ocean current exists only here. Gazebo has no current plugin.'        newline ...
'%   s = [u v r N E psi]'''                                              newline ...
'%   p = [m Izz Xu Xuu Yv Yvv Nr Nrr half_beam]'''                       newline ...
''                                                                       newline ...
'u = s(1); v = s(2); r = s(3); psi = s(6);'                              newline ...
'm=p(1); Izz=p(2); Xu=p(3); Xuu=p(4); Yv=p(5); Yvv=p(6);'                newline ...
'Nr=p(7); Nrr=p(8); b_half=p(9);'                                        newline ...
''                                                                       newline ...
'% current in the body frame -> velocity relative to the water'          newline ...
'u_c = V_c*cos(beta_c - psi);'                                           newline ...
'v_c = V_c*sin(beta_c - psi);'                                           newline ...
'u_r = u - u_c;'                                                         newline ...
'v_r = v - v_c;'                                                         newline ...
''                                                                       newline ...
'% differential thrust -> surge force and yaw moment'                    newline ...
'X = FL + FR;'                                                           newline ...
'N = (FL - FR)*b_half;'                                                  newline ...
''                                                                       newline ...
'% drag acts on the velocity relative to the water'                      newline ...
'Dx = (Xu + Xuu*abs(u_r))*u_r;'                                          newline ...
'Dy = (Yv + Yvv*abs(v_r))*v_r;'                                          newline ...
'Dn = (Nr + Nrr*abs(r))*r;'                                              newline ...
''                                                                       newline ...
'du = (X - Dx)/m + v*r;      % rigid-body Coriolis'                      newline ...
'dv = (  - Dy)/m - u*r;'                                                 newline ...
'dr = (N - Dn)/Izz;'                                                     newline ...
''                                                                       newline ...
'xdot = [du; dv; dr;'                                                    newline ...
'        u*cos(psi) - v*sin(psi);   % kinematics use absolute velocity'  newline ...
'        u*sin(psi) + v*cos(psi);'                                       newline ...
'        r];']);

    % ---- 연속 적분기 ----
    add_block('simulink/Continuous/Integrator', [ss '/Integ'], ...
              'Position', [450 130 500 180], 'InitialCondition','x0');

    % ---- 상태 -> 항법량 ----
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/States'], 'Position', [570 60 720 260]);
    setFcn(ss, 'States', [ ...
'function [pn, pe, psi, u, r, beta, chi, U] = States(s)'    newline ...
'%#codegen'                                                 newline ...
'% Pick the navigation quantities out of the state vector.' newline ...
'% In the VRX model this job is done by the Nav block,'     newline ...
'% which also has to convert ENU to NED.'                   newline ...
'u = s(1); v = s(2); r = s(3);'                             newline ...
'pn = s(4); pe = s(5); psi = s(6);'                         newline ...
'U    = sqrt(u*u + v*v);      % speed over ground'          newline ...
'beta = atan2(v, u);          % crab angle'                 newline ...
'c    = psi + beta;           % course angle'               newline ...
'chi  = atan2(sin(c), cos(c));']);

    out = {'pn','pe','psi','u','r','beta','chi','U'};
    for k = 1:numel(out)
        add_block('simulink/Sinks/Out1', [ss '/' out{k}], ...
                  'Position', [800 60+(k-1)*45 840 60+(k-1)*45+30], 'Port', num2str(k));
        add_line(ss, sprintf('States/%d',k), [out{k} '/1'], 'autorouting','on');
    end

    for k = 1:5
        add_line(ss, [in{k} '/1'], sprintf('EOM/%d', k+1), 'autorouting','on');
    end
    add_line(ss,'EOM/1','Integ/1','autorouting','on');
    add_line(ss,'Integ/1','States/1','autorouting','on');
    add_line(ss,'Integ/1','EOM/1','autorouting','on');
end

% =====================================================================
% 5단 · ANIMATE — 시뮬레이션이 도는 동안 실시간으로 그린다
%   MATLAB Function 블록은 원래 그림을 못 그린다.
%   coder.extrinsic 으로 선언하면 컴파일하지 않고 MATLAB 함수를 그대로 부른다.
%   실제 그리기는 W07_animate.m 이 한다.
% =====================================================================
function addAnimate(m, x, y)
    add_block('simulink/Sources/Digital Clock', [m '/Clk'], ...
              'Position', [x y+120 x+50 y+150], 'SampleTime','Ts_ctrl');
    C(m,'Anim','animate', x, y+180);

    F(m,'pn','v',  x, y);
    F(m,'pe','v',  x, y+40);
    F(m,'psi','v', x, y+80);

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [m '/Animate'], 'Position', [x+150 y x+300 y+190]);
    setFcn(m, 'Animate', [ ...
'function ok = Animate(pn, pe, psi, t, en)'                            newline ...
'%#codegen'                                                            newline ...
'% Live plot of the boat and the waypoints while the model runs.'      newline ...
'% MATLAB Function blocks cannot plot, so the drawing function is'     newline ...
'% declared extrinsic: Simulink calls plain MATLAB instead of'         newline ...
'% generating code for it.'                                            newline ...
'coder.extrinsic(''W07_animate'');'                                    newline ...
'ok = 1;'                                                              newline ...
'if en > 0.5'                                                          newline ...
'    W07_animate(pn, pe, psi, t);'                                     newline ...
'end']);

    add_block('simulink/Sinks/Terminator', [m '/AnimEnd'], ...
              'Position', [x+350 y+80 x+375 y+105]);

    add_line(m, ['Fr_pn_v/1'],  'Animate/1','autorouting','on');
    add_line(m, ['Fr_pe_v/1'],  'Animate/2','autorouting','on');
    add_line(m, ['Fr_psi_v/1'], 'Animate/3','autorouting','on');
    add_line(m, 'Clk/1',  'Animate/4','autorouting','on');
    add_line(m, 'Anim/1', 'Animate/5','autorouting','on');
    add_line(m, 'Animate/1','AnimEnd/1','autorouting','on');
end

% =====================================================================
% 설정 상수 + 유도/내부루프 입력 배선 (두 모델 공통)
% =====================================================================
function wireFront(m)
% 1단 입력: 설정 상수 + 위치 되먹임
    F(m,'pn','a', 40,  65);
    F(m,'pe','a', 40, 110);
    C(m,'WPN','wp_north',      40, 155);
    C(m,'WPE','wp_east',       40, 200);
    C(m,'Dlt','Delta',         40, 245);
    C(m,'Rsw','R_LOS',         40, 290);
    C(m,'Mode','guidance_mode',40, 335);

    add_line(m,'Fr_pn_a/1','Guidance/1','autorouting','on');
    add_line(m,'Fr_pe_a/1','Guidance/2','autorouting','on');
    add_line(m,'WPN/1', 'Guidance/3','autorouting','on');
    add_line(m,'WPE/1', 'Guidance/4','autorouting','on');
    add_line(m,'Dlt/1', 'Guidance/5','autorouting','on');
    add_line(m,'Rsw/1', 'Guidance/6','autorouting','on');
    add_line(m,'Mode/1','Guidance/7','autorouting','on');

    % 유도 출력에 로깅용 Goto 를 붙인다 (본선은 그대로 InnerLoop 로 간다)
    G(m,'psi_ref', 560,  70);
    G(m,'y_e',     560, 110);
    G(m,'gate',    560, 150);
    add_line(m,'Guidance/1','Go_psi_ref/1','autorouting','on');
    add_line(m,'Guidance/2','Go_y_e/1','autorouting','on');
    add_line(m,'Guidance/4','Go_gate/1','autorouting','on');

    % 2단 입력: 속도 지령 + 자세·속도 되먹임
    C(m,'URef','u_ref',   560, 300);
    F(m,'psi','b', 560, 360);
    F(m,'r',  'b', 560, 400);
    F(m,'u',  'b', 560, 440);

    add_line(m,'Guidance/1','InnerLoop/1','autorouting','on');
    add_line(m,'Guidance/4','InnerLoop/2','autorouting','on');
    add_line(m,'URef/1',    'InnerLoop/3','autorouting','on');
    add_line(m,'Fr_psi_b/1','InnerLoop/4','autorouting','on');
    add_line(m,'Fr_r_b/1',  'InnerLoop/5','autorouting','on');
    add_line(m,'Fr_u_b/1',  'InnerLoop/6','autorouting','on');
end

function F(m, tag, sfx, x, y)
    add_block('simulink/Signal Routing/From', [m '/Fr_' tag '_' sfx], ...
              'Position', [x y x+70 y+25], 'GotoTag', tag);
end

function G(m, tag, x, y)
    add_block('simulink/Signal Routing/Goto', [m '/Go_' tag], ...
              'Position', [x y x+80 y+25], 'GotoTag', tag);
end

function wireThrusterGotos(m, x, y)
    t = {'FL','FR','nprop'};
    for k = 1:3
        G(m, t{k}, x, y+(k-1)*40);
        add_line(m, sprintf('Thrusters/%d',k), ['Go_' t{k} '/1'], 'autorouting','on');
    end
end

function wireNavGotos(m, x, y)
% Nav 출력을 전부 Goto 태그로 내보낸다.
% 되먹임 선과 로깅 선이 화면을 가로지르지 않게 하는 표준 방법이다.
    tags = {'pn','pe','psi','u','r','beta','chi','U'};
    for k = 1:numel(tags)
        G(m, tags{k}, x, y+(k-1)*40);
        add_line(m, sprintf('Nav/%d',k), ['Go_' tags{k} '/1'], 'autorouting','on');
    end
end

% =====================================================================
% 실습 A — 오프라인 모델
% =====================================================================
function build_offline()
    m = 'W07_0_offline'; fresh(m);
    % 운동모델을 연속 적분기로 풀기 때문에 ode4 (4차 룽게쿠타) 를 쓴다.
    % 제어기·유도·추진기는 Ts_ctrl 로 도는 이산 블록이다 (하이브리드 구성).
    set_param(m, 'SolverType','Fixed-step', 'SolverName','ode4', ...
                 'FixedStep','Ts_ctrl', 'StopTime','600', 'SimulationMode','normal');

    addGuidance(m, 250, 60);
    addInnerLoop(m, 720, 280);
    wireFront(m);
    addThrusters(m, 1000, 290);
    wireThrusterGotos(m, 1230, 290);

    % --- 4단 · 운동모델 (운동방정식 + 연속 적분 + 상태 산출) --------------
    C(m,'Vc','current_speed', 1230, 470);
    C(m,'BetaC','beta_c',     1230, 520);
    C(m,'Par','[m_usv; Izz; Xu; Xuu; Yv; Yvv; Nr; Nrr; half_beam]', 1230, 570);

    addMotionModel(m, 1450, 280);

    add_line(m,'Thrusters/1','MotionModel/1','autorouting','on');
    add_line(m,'Thrusters/2','MotionModel/2','autorouting','on');
    add_line(m,'Vc/1',       'MotionModel/3','autorouting','on');
    add_line(m,'BetaC/1',    'MotionModel/4','autorouting','on');
    add_line(m,'Par/1',      'MotionModel/5','autorouting','on');

    add_line(m,'InnerLoop/1','Thrusters/1','autorouting','on');
    add_line(m,'InnerLoop/2','Thrusters/2','autorouting','on');

    % --- 되먹임 태그 + 로깅 ---------------------------------------------
    tags = {'pn','pe','psi','u','r','beta','chi','U'};
    for k = 1:numel(tags)
        G(m, tags{k}, 1760, 280+(k-1)*40);
        add_line(m, sprintf('MotionModel/%d',k), ['Go_' tags{k} '/1'], 'autorouting','on');
    end
    addAnimate(m, 1760, 650);
    addLogging(m, 2250, 60);

    note(m,'n1', ['W07 실습 A  —  오프라인 WAM-V (Gazebo 불필요)' newline ...
        'Guidance -> Inner Loop -> Thrusters -> 운동모델' newline ...
        '조류 실험은 이 모델에서만 가능하다.' newline ...
        '실행 전 >> W07_setup'], 250, -90);

    save_system(m); close_system(m);
    fprintf('  W07_0_offline  생성\n');
end

% =====================================================================
% 실습 B — VRX 연동 모델
% =====================================================================
function build_vrx()
    m = 'W07_1_vrx'; fresh(m);
    load_system('ros2lib');
    setSolver(m, 'inf');

    addGuidance(m, 250, 60);
    addInnerLoop(m, 720, 280);
    wireFront(m);
    addThrusters(m, 1000, 290);
    wireThrusterGotos(m, 1230, 620);

    % --- 4단 · 운동모델 = Gazebo ---------------------------------------
    addThrusterPublisher(m, 'left',  'L', 1300, 200);
    addThrusterPublisher(m, 'right', 'R', 1300, 380);
    add_line(m,'InnerLoop/1','Thrusters/1','autorouting','on');
    add_line(m,'InnerLoop/2','Thrusters/2','autorouting','on');
    add_line(m,'Thrusters/1','AsgL/2','autorouting','on');
    add_line(m,'Thrusters/2','AsgR/2','autorouting','on');

    add_block('ros2lib/Subscribe', [m '/OdomSub'], 'Position',[1300 700 1430 760]);
    set_param([m '/OdomSub'], 'topicSource','Specify your own', ...
        'topic','/wamv/sensors/position/ground_truth_odometry', ...
        'messageType','nav_msgs/Odometry', 'sampleTime','Ts_ctrl');

    add_block('simulink/Signal Routing/Bus Selector', [m '/Sel'], ...
              'Position',[1490 680 1540 810]);
    set_param([m '/Sel'], 'OutputSignals', ...
        ['pose.pose.position.x,pose.pose.position.y,' ...
         'pose.pose.orientation.x,pose.pose.orientation.y,' ...
         'pose.pose.orientation.z,pose.pose.orientation.w,' ...
         'twist.twist.linear.x,twist.twist.linear.y,twist.twist.angular.z']);

    add_block('simulink/Sinks/Display', [m '/IsNew'], 'Position',[1490 620 1570 650]);
    add_line(m,'OdomSub/1','IsNew/1','autorouting','on');
    add_line(m,'OdomSub/2','Sel/1','autorouting','on');

    % --- 5단 · 항법 (ENU -> NED 변환) -----------------------------------
    C(m,'OrgN','origin_north', 1490, 870);
    C(m,'OrgE','origin_east',  1490, 920);

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [m '/Nav'], 'Position',[1660 670 1830 890]);
    setFcn(m, 'Nav', [ ...
'function [pn, pe, psi, u, r, beta, chi, U] = Nav(ex, ey, qx, qy, qz, qw, bx, by, wz, orgN, orgE)' newline ...
'%#codegen'                                                                 newline ...
'% Gazebo/ROS uses ENU with a body frame of x-forward, y-LEFT, z-UP.'       newline ...
'% Marine control uses NED with a body frame of x-forward, y-STARBOARD.'    newline ...
'% Position :  N = y_ENU,  E = x_ENU'                                       newline ...
'% Heading  :  psi_NED = pi/2 - yaw_ENU'                                    newline ...
'% Body vel :  u = bx,  v = -by,  r = -wz    (y and z flip sign)'           newline ...
''                                                                          newline ...
'% 첫 메시지가 도착하기 전에는 Subscribe 가 0 으로 채운 버스를 낸다.'       newline ...
'% 그대로 쓰면 위치가 스폰 원점만큼(약 568 m) 튀어 로그 첫 점이 망가진다.'  newline ...
'if ex == 0 && ey == 0'                                                     newline ...
'    pn = 0; pe = 0; psi = 0; u = 0; r = 0; beta = 0; chi = 0; U = 0;'      newline ...
'    return'                                                                newline ...
'end'                                                                       newline ...
'pn = ey - orgN;    % north, relative to the spawn point'                   newline ...
'pe = ex - orgE;    % east'                                                 newline ...
''                                                                          newline ...
'yaw_enu = atan2(2*(qw*qz + qx*qy), 1 - 2*(qy*qy + qz*qz));'                newline ...
'p   = pi/2 - yaw_enu;'                                                     newline ...
'psi = atan2(sin(p), cos(p));'                                              newline ...
''                                                                          newline ...
'u = bx;'                                                                   newline ...
'v = -by;'                                                                  newline ...
'r = -wz;'                                                                  newline ...
''                                                                          newline ...
'U    = sqrt(u*u + v*v);'                                                   newline ...
'beta = atan2(v, u);          % crab angle'                                 newline ...
'c    = psi + beta;'                                                        newline ...
'chi  = atan2(sin(c), cos(c));']);

    for k = 1:9
        add_line(m, sprintf('Sel/%d',k), sprintf('Nav/%d',k), 'autorouting','on');
    end
    add_line(m,'OrgN/1','Nav/10','autorouting','on');
    add_line(m,'OrgE/1','Nav/11','autorouting','on');

    wireNavGotos(m, 1890, 670);
    addAnimate(m, 2080, 700);
    addLogging(m, 2080, 60);

    note(m,'n1', ['W07 실습 B  —  VRX 연동 (Gazebo 필요)' newline ...
        'Guidance -> Inner Loop -> Thrusters -> Gazebo -> Navigation' newline ...
        '유도부·내부루프·추진기·게인은 W07_0_offline 과 완전히 같다.' newline ...
        '운동모델만 Gazebo 로 바뀐다.' newline ...
        '실행 전: (1) W07_setup  (2) VRX 기동  (3) 페이싱을 RTF 에 맞출 것'], 250, -90);

    save_system(m); close_system(m);
    fprintf('  W07_1_vrx      생성\n');
end

% ---------------------------------------------------------------------
% 추력 발행 3종 세트 (6주차와 동일)
% ---------------------------------------------------------------------
function addThrusterPublisher(m, side, tag, x, y)
    add_block('ros2lib/Blank Message', [m '/Blank' tag], ...
              'Position', [x y+70 x+100 y+110]);
    set_param([m '/Blank' tag], 'entityType','std_msgs/Float64', ...
              'messageType','std_msgs/Float64', 'SampleTime','Ts_ctrl');
    add_block('simulink/Signal Routing/Bus Assignment', [m '/Asg' tag], ...
              'Position', [x+160 y x+220 y+115]);
    set_param([m '/Asg' tag], 'AssignedSignals','data');
    add_block('ros2lib/Publish', [m '/Pub' tag], ...
              'Position', [x+290 y+35 x+390 y+75]);
    set_param([m '/Pub' tag], 'topicSource','Specify your own', ...
              'topic', ['/wamv/thrusters/' side '/thrust'], ...
              'messageType','std_msgs/Float64');
    add_line(m, ['Blank' tag '/1'], ['Asg' tag '/1'], 'autorouting','on');
    add_line(m, ['Asg'   tag '/1'], ['Pub' tag '/1'], 'autorouting','on');
end

% ---------------------------------------------------------------------
% 로깅 — W07_plot.m 이 읽는다
% ---------------------------------------------------------------------
function addLogging(m, x, y)
% 모든 로깅은 From 태그로 받는다. 긴 선이 생기지 않는다.
%   신호 이름  =  Goto 태그 이름 (n 만 nprop 태그를 쓴다)
    sig = {'pn','pe','psi','psi_ref','y_e','beta','chi','u','r','U','gate','FL','FR','n'};
    tag = {'pn','pe','psi','psi_ref','y_e','beta','chi','u','r','U','gate','FL','FR','nprop'};
    for k = 1:numel(sig)
        yy = y + (k-1)*55;
        F(m, tag{k}, 'log', x, yy+3);
        b = [m '/log_' sig{k}];
        add_block('simulink/Sinks/To Workspace', b, ...
                  'Position', [x+130 yy x+230 yy+30]);
        set_param(b, 'VariableName', ['log_' sig{k}], ...
                     'SaveFormat','Timeseries', 'SampleTime','Ts_ctrl');
        add_line(m, ['Fr_' tag{k} '_log/1'], ['log_' sig{k} '/1'], 'autorouting','on');
    end
end
