function build_w06_models()
% BUILD_W06_MODELS  6주차 Simulink 예제 모델 7개를 생성한다.
%
%   이 스크립트를 실행하면 아래 모델이 이 폴더에 만들어진다.
%     W06_1_straight.slx          직진
%     W06_2_turn.slx              시간에 따라 직진 -> 우선회 -> 좌선회
%     W06_3_heading.slx           헤딩 제어 (outer)
%     W06_4_inner_loop.slx        속도 + 헤딩 제어 (inner loop 완성)
%     W06_5_offline.slx           2단계 시나리오를 운동방정식으로
%     W06_3_heading_offline.slx   3단계와 같은 제어기, Gazebo 대신 운동방정식
%     W06_4_inner_loop_offline.slx 4단계와 같은 제어기, Gazebo 대신 운동방정식
%
%   3·4단계는 오프라인 쌍둥이가 있다. 제어기 · 배분기 블록은 같은 함수로 만든다.
%   바뀌는 것은 두 자리뿐이다.
%     VRX      : OdomSub -> Sel -> Quat2Yaw  ...  Alloc -> Blank/Asg/Pub (x2)
%     오프라인 : MotionModel (psi, r, u)     ...  Alloc -> MotionModel
%
%   모델이 깨졌을 때 이 스크립트를 다시 돌리면 원래대로 복구된다.
%
%   전제
%     - MATLAB R2024b + Simulink + ROS Toolbox
%     - VRX 가 ground_truth_odometry 를 발행하도록 설정되어 있을 것
%       (강의자료 6주차 B절 참조)

    here = fileparts(mfilename('fullpath'));
    addpath(fullfile(here, '..', '..', '_tools'));
    cd(here);
    load_system('ros2lib');

    build_straight();
    build_turn();
    build_heading(false);
    build_inner_loop(false);
    build_offline();
    build_heading(true);
    build_inner_loop(true);


    % 배치와 색을 정리한다. 선은 직선 또는 직각으로만 다시 그린다.
    % dir 의 문자 클래스는 Windows 에서 먹지 않는다. 목록을 받아 이름으로 거른다
    slxList = dir('W06_*.slx');
    slxList = slxList(~cellfun(@isempty, regexp({slxList.name}, '^W06_[1-5]_', 'once')));   % 오프라인 쌍둥이 포함
    for k = 1:numel(slxList)
        [~, mName] = fileparts(slxList(k).name);
        try

            tidy_model(mName);

            paint_roles(mName);        % 역할표는 _tools/gnc_roles.m 하나뿐이다

            check_colour(mName);

            export_model_pngs(mName);

        catch e, warning(e.message); end
    end
    fprintf('\n완료. 생성된 모델:\n');
    d = dir('W06_*.slx');
    for k = 1:numel(d), fprintf('  %s\n', d(k).name); end
end

% =====================================================================
% 공통 헬퍼
% =====================================================================
function addThrusterPublisher(m, side, tag, x, y)
% 추력 발행 3종 세트: Blank Message -> Bus Assignment -> Publish
    add_block('ros2lib/Blank Message', [m '/Blank' tag], ...
              'Position', [x y+70 x+100 y+110]);
    set_param([m '/Blank' tag], 'entityType','std_msgs/Float64', ...
              'messageType','std_msgs/Float64', 'SampleTime','0.05');
    add_block('simulink/Signal Routing/Bus Assignment', [m '/Asg' tag], ...
              'Position', [x+160 y x+220 y+115]);
    set_param([m '/Asg' tag], 'AssignedSignals','data');
    add_block('ros2lib/Publish', [m '/Pub' tag], ...
              'Position', [x+290 y+35 x+390 y+75]);
    set_param([m '/Pub' tag], 'topicSource','Specify your own', ...
              'topic', ['/wamv/thrusters/' side '/thrust'], ...
              'messageType','std_msgs/Float64');
    add_line(m, ['Blank' tag '/1'], ['Asg' tag '/1'], 'autorouting','on');
    add_line(m, ['Asg'   tag '/1'], ['Pub' tag '/1'], 'autorouting','on');
end

function setSolver(m)
    set_param(m, 'SolverType','Fixed-step', 'SolverName','FixedStepDiscrete', ...
                 'FixedStep','0.05', 'StopTime','inf', 'SimulationMode','normal');
end

function setFcn(m, name, code)
    S  = sfroot;
    ch = S.find('-isa','Stateflow.EMChart','Path',[m '/' name]);
    ch.Script = code;
end

function note(m, txt, x, y)
    add_block('built-in/Note', [m '/note'], ...
              'Position', [x y x y], 'Text', txt);
end

function fresh(m)
    try, close_system(m, 0); catch, end
    if exist([m '.slx'],'file'), delete([m '.slx']); end
    new_system(m);
end

% =====================================================================
% 1단계 — 직진
% =====================================================================
function build_straight()
    m = 'W06_1_straight'; fresh(m);

    add_block('simulink/Sources/Constant', [m '/FL'], ...
              'Value','200', 'Position',[40 95 100 125]);
    add_block('simulink/Sources/Constant', [m '/FR'], ...
              'Value','200', 'Position',[40 275 100 305]);

    addThrusterPublisher(m, 'left',  'L', 200, 60);
    addThrusterPublisher(m, 'right', 'R', 200, 240);

    add_line(m,'FL/1','AsgL/2','autorouting','on');
    add_line(m,'FR/1','AsgR/2','autorouting','on');

    setSolver(m);
    note(m, sprintf(['[1단계] 직진\n' ...
        '좌우 추력을 같은 값(200 N)으로 발행한다.\n' ...
        'FL 과 FR 값을 바꿔 보고 배가 어떻게 반응하는지 관찰할 것.']), 40, 400);
    save_system(m); close_system(m,0);
    fprintf('  [OK] %s\n', m);
end

% =====================================================================
% 2단계 — 직진 / 우선회 / 좌선회
% =====================================================================
function build_turn()
    m = 'W06_2_turn'; fresh(m);

    add_block('simulink/Sources/Digital Clock', [m '/Clock'], ...
              'SampleTime','0.05', 'Position',[40 185 100 215]);
    add_block('simulink/User-Defined Functions/MATLAB Function', [m '/Scenario'], ...
              'Position',[150 165 280 235]);
    setFcn(m, 'Scenario', [ ...
        'function [FL, FR] = Scenario(t)' newline ...
        '%#codegen' newline ...
        '% Time-based thrust scenario [N]' newline ...
        'if t < 20' newline ...
        '    FL = 200;  FR = 200;   % go straight' newline ...
        'elseif t < 40' newline ...
        '    FL = 300;  FR =  50;   % turn starboard (right)' newline ...
        'elseif t < 60' newline ...
        '    FL =  50;  FR = 300;   % turn port (left)' newline ...
        'else' newline ...
        '    FL = 0;    FR = 0;     % stop' newline ...
        'end' newline]);

    addThrusterPublisher(m, 'left',  'L', 360, 60);
    addThrusterPublisher(m, 'right', 'R', 360, 240);

    add_line(m,'Clock/1','Scenario/1','autorouting','on');
    add_line(m,'Scenario/1','AsgL/2','autorouting','on');
    add_line(m,'Scenario/2','AsgR/2','autorouting','on');

    setSolver(m);
    set_param(m,'StopTime','80');
    note(m, sprintf(['[2단계] 직진 -> 우선회 -> 좌선회\n' ...
        '0~20s 직진 / 20~40s 우선회 / 40~60s 좌선회 / 60s~ 정지\n' ...
        '좌현 추력이 크면 뱃머리가 오른쪽으로 돈다.']), 40, 400);
    save_system(m); close_system(m,0);
    fprintf('  [OK] %s\n', m);
end

% =====================================================================
% 상태 읽기 블록 (3·4단계 공통)
% =====================================================================
function addOdomReader(m, withSpeed)
    add_block('ros2lib/Subscribe', [m '/OdomSub'], 'Position',[40 40 160 100]);
    set_param([m '/OdomSub'], 'topicSource','Specify your own', ...
              'topic','/wamv/sensors/position/ground_truth_odometry', ...
              'messageType','nav_msgs/Odometry', 'sampleTime','0.05');

    sig = ['pose.pose.orientation.x,pose.pose.orientation.y,' ...
           'pose.pose.orientation.z,pose.pose.orientation.w'];
    if withSpeed
        sig = [sig ',twist.twist.linear.x'];
    end
    %  요각속도는 **항상** 뽑는다. 헤딩 제어의 D 항이 이 값을 쓴다.
    %  맨 뒤에 붙이므로 앞의 포트 번호는 그대로다.
    sig = [sig ',twist.twist.angular.z'];
    iWz = 5 + double(withSpeed);

    add_block('simulink/Signal Routing/Bus Selector', [m '/Sel'], ...
              'Position',[210 40 220 140]);
    set_param([m '/Sel'], 'OutputSignals', sig);
    add_line(m,'OdomSub/2','Sel/1','autorouting','on');

    add_block('simulink/User-Defined Functions/MATLAB Function', [m '/Quat2Yaw'], ...
              'Position',[280 40 400 110]);
    setFcn(m, 'Quat2Yaw', [ ...
        'function [psi_ned, r] = Quat2Yaw(qx, qy, qz, qw, wz)' newline ...
        '%#codegen' newline ...
        '% ROS quaternion (ENU body) -> NED heading [rad] and yaw rate [rad/s]' newline ...
        'yaw_enu = atan2(2*(qw*qz + qx*qy), 1 - 2*(qy*qy + qz*qz));' newline ...
        'psi = pi/2 - yaw_enu;' newline ...
        'psi_ned = atan2(sin(psi), cos(psi));   % wrap to [-pi, pi]' newline ...
        '' newline ...
        '% psi_ned = pi/2 - yaw_enu  ->  d(psi_ned)/dt = -d(yaw_enu)/dt.' newline ...
        '% ENU is z-up and NED is z-down, so the turn direction flips.' newline ...
        'r = -wz;' newline]);
    for k = 1:4
        add_line(m, sprintf('Sel/%d',k), sprintf('Quat2Yaw/%d',k), 'autorouting','on');
    end
    add_line(m, sprintf('Sel/%d',iWz), 'Quat2Yaw/5', 'autorouting','on');
end

% =====================================================================
% 헤딩 제어기 (3·4단계 공통) — 독립 모듈 하나
% =====================================================================
function addHeadingCtrl(m, x, y)
% 헤딩 제어기를 **서브시스템 하나**로 만든다. 밖에서는 이 상자만 보인다.
%
%   입력  psi_ref [rad]    목표 선수각
%         psi     [rad]    지금 선수각
%         r       [rad/s]  지금 요각속도 (NED)
%   출력  N       [N*m]    요 모멘트 지령
%
%   제어식 — P 는 오차에, D 는 **요각속도에 직접**
%
%       N = Kp * ssa(psi_ref - psi)  -  Kd * r
%
%   왜 오차를 미분하지 않는가
%       e = psi_ref - psi 이므로 de/dt = d(psi_ref)/dt - r 이고, 목표가 가만히
%       있는 동안에는 de/dt = -r 이다. 즉 -Kd*r 과 +Kd*de/dt 는 **같은 값**이다.
%       다만 목표가 계단으로 바뀌는 순간 de/dt 는 크게 튀고(미분 킥), r 은 배의
%       실제 회전이라 튀지 않는다. 같은 값을 더 얌전한 신호로 얻는 셈이다.
%
%   왜 마이너스인가
%       D 항은 **브레이크**다. 배가 왼쪽으로 돌고 있으면(r < 0) 그 회전을 멈추는
%       방향으로 모멘트를 내야 하므로 부호가 반대여야 한다. 마이너스를 빼면
%       감쇠가 Nr + Kd 에서 Nr - Kd 로 줄어 오버슈트가 커진다 (Kd = 400 에서 17 %,
%       6주차 1-7절·W06_heading_sign). 2차 항력 Nrr 이 버텨 발산까지는 가지 않는다.
%
%   MSS 툴박스의 demoOtterUSVHeadingControl 도 같은 구조다 (Fossen). 그쪽 D 항은
%   Kp*Td*(r_d - r) 인데, 목표 각속도 r_d = 0 이면 -Kp*Td*r 이다.

    s = add_subsys(m, 'HeadingCtrl', [x y x+150 y+90], ...
                   {'psi_ref','psi','r'}, {'N'}, gnc_colour('control'));

    add_block('simulink/User-Defined Functions/MATLAB Function', [s '/HeadingErr'], ...
              'Position',[200 60 340 130]);
    setFcn(s, 'HeadingErr', [ ...
        'function e = HeadingErr(psi_ref, psi)' newline ...
        '%#codegen' newline ...
        '% Shortest signed angle, wrapped to [-pi, pi]' newline ...
        'd = psi_ref - psi;' newline ...
        'e = atan2(sin(d), cos(d));' newline]);

    add_block('simulink/Math Operations/Gain', [s '/Kp_psi'], ...
              'Gain','800', 'Position',[420 80 470 110]);
    add_block('simulink/Math Operations/Gain', [s '/Kd_rate'], ...
              'Gain','-400', 'Position',[420 220 470 250]);
    add_block('simulink/Math Operations/Sum', [s '/SumN'], ...
              'Inputs','++', 'Position',[550 95 580 125]);
    add_block('simulink/Discontinuities/Saturation', [s '/SatN'], ...
              'UpperLimit','500', 'LowerLimit','-500', ...
              'Position',[650 95 690 125]);

    add_line(s,'psi_ref/1','HeadingErr/1','autorouting','on');
    add_line(s,'psi/1',    'HeadingErr/2','autorouting','on');
    add_line(s,'r/1',      'Kd_rate/1','autorouting','on');
    add_line(s,'HeadingErr/1','Kp_psi/1','autorouting','on');
    add_line(s,'Kp_psi/1', 'SumN/1','autorouting','on');
    add_line(s,'Kd_rate/1','SumN/2','autorouting','on');
    add_line(s,'SumN/1',   'SatN/1','autorouting','on');
    add_line(s,'SatN/1',   'N/1','autorouting','on');

    note(s, sprintf(['헤딩 제어기 — P 는 오차에, D 는 요각속도에\n' ...
        '\n' ...
        '    N = Kp * ssa(psi_ref - psi)  -  Kd * r\n' ...
        '\n' ...
        '마이너스는 브레이크다. 돌고 있는 방향의 반대로 모멘트를 낸다.\n' ...
        '빼면 감쇠가 Nr - Kd 로 줄어 오버슈트가 커진다 (Kd = 400 에서 17 %%).\n' ...
        '\n' ...
        '목표가 가만히 있으면 de/dt = -r 이므로 오차 미분과 값이 같다.\n' ...
        '다만 목표가 계단으로 바뀔 때 de/dt 는 튀고 r 은 튀지 않는다.\n' ...
        '\n' ...
        'Kp = 800, Kd = 400.  근거는 6주차 1-7절 극배치.']), 200, 330);
end

% =====================================================================
% 배분기 (3·4단계 공통) — 차동 추력배분 + 포화
% =====================================================================
function addAllocator(m, x, y)
    add_block('simulink/User-Defined Functions/MATLAB Function', [m '/Alloc'], ...
              'Position',[x y x+140 y+70]);
    setFcn(m, 'Alloc', [ ...
        'function [FL, FR] = Alloc(X, N)' newline ...
        '%#codegen' newline ...
        '% Differential thrust allocation for the 2-thruster WAM-V' newline ...
        '%   X : surge force  [N]' newline ...
        '%   N : yaw moment   [N*m], positive turns to starboard' newline ...
        'B_half = 1.027135;      % half distance between thrusters [m]' newline ...
        'Fmax   = 250;           % thrust limit per thruster [N]' newline ...
        'FL = X/2 + N/(2*B_half);' newline ...
        'FR = X/2 - N/(2*B_half);' newline ...
        'FL = max(min(FL, Fmax), -Fmax);' newline ...
        'FR = max(min(FR, Fmax), -Fmax);' newline]);
end

% =====================================================================
% 오프라인 운동모델 (3·4단계 쌍둥이 공통) — Gazebo 자리를 대신한다
%   입력 FL, FR [N]   출력 psi [rad], r [rad/s], u [m/s]
%   식과 계수는 3주차 1-8 절 · W03_0_offline 과 같다.
%   초기 선수각은 VRX 스폰과 같게 32.7 deg (3주차 3-1 좌표 검산)
% =====================================================================
function addMotionModel(m, x, y)
    s = add_subsys(m, 'MotionModel', [x y x+150 y+110], ...
                   {'FL','FR'}, {'psi','r','u'}, gnc_colour('plant'));
    add_block('simulink/User-Defined Functions/MATLAB Function', [s '/EOM'], ...
              'Position',[200 40 340 160]);
    setFcn(s, 'EOM', [ ...
'function xdot = EOM(s, FL, FR)'                                        newline ...
'%#codegen'                                                             newline ...
'% 3-DOF WAM-V equations of motion, NED (3주차 1-8 절).'                  newline ...
'%   s = [u v r x_n y_n psi]'''                                          newline ...
'm = 211;  Izz = 653;  Xu = 100;  Xuu = 150;  Yv = 100;  Yvv = 100;'    newline ...
'Nr = 800;  Nrr = 800;  b_half = 1.027135;'                             newline ...
'u = s(1); v = s(2); r = s(3); psi = s(6);'                             newline ...
'X = FL + FR;'                                                          newline ...
'N = (FL - FR)*b_half;'                                                 newline ...
'du = (X - (Xu + Xuu*abs(u))*u)/m + v*r;'                               newline ...
'dv = (  - (Yv + Yvv*abs(v))*v)/m - u*r;'                               newline ...
'dr = (N - (Nr + Nrr*abs(r))*r)/Izz;'                                   newline ...
'xdot = [du; dv; dr;'                                                   newline ...
'        u*cos(psi) - v*sin(psi);'                                      newline ...
'        u*sin(psi) + v*cos(psi);'                                      newline ...
'        r];']);
    add_block('simulink/Continuous/Integrator', [s '/Integ'], ...
              'Position',[400 80 440 120], 'InitialCondition','[0;0;0;0;0;32.7*pi/180]');
    add_block('simulink/User-Defined Functions/MATLAB Function', [s '/States'], ...
              'Position',[500 40 620 160]);
    setFcn(s, 'States', [ ...
'function [psi, r, u] = States(s)'                                      newline ...
'%#codegen'                                                             newline ...
'% Quat2Yaw 와 같은 출력 — 선수각은 [-pi, pi] 로 접는다'                   newline ...
'psi = atan2(sin(s(6)), cos(s(6)));'                                    newline ...
'r = s(3);'                                                             newline ...
'u = s(1);']);
    add_line(s,'FL/1','EOM/2','autorouting','on');
    add_line(s,'FR/1','EOM/3','autorouting','on');
    add_line(s,'EOM/1','Integ/1','autorouting','on');
    add_line(s,'Integ/1','EOM/1','autorouting','on');
    add_line(s,'Integ/1','States/1','autorouting','on');
    add_line(s,'States/1','psi/1','autorouting','on');
    add_line(s,'States/2','r/1','autorouting','on');
    add_line(s,'States/3','u/1','autorouting','on');
end

function setSolverOffline(m)
    % 연속 적분기가 있으므로 ode4. 스텝은 VRX 모델과 같은 0.05 s
    set_param(m, 'SolverType','Fixed-step', 'SolverName','ode4', ...
                 'FixedStep','0.05', 'StopTime','40', 'SimulationMode','normal');
end

function addLog(m, src, name, x, y)
    % To Workspace — W06_step_compare 가 VRX 와 오프라인을 같은 이름으로 꺼낸다
    b = [m '/log_' name];
    add_block('simulink/Sinks/To Workspace', b, 'Position',[x y x+90 y+26]);
    set_param(b, 'VariableName',['log_' name], 'SaveFormat','Timeseries', 'SampleTime','0.05');
    add_line(m, src, ['log_' name '/1'], 'autorouting','on');
end

% =====================================================================
% 3단계 — 헤딩 제어  (offline = true 이면 오프라인 쌍둥이)
% =====================================================================
function build_heading(offline)
    if offline
        m = 'W06_3_heading_offline'; fresh(m);
        addMotionModel(m, 780, 200);
        sPsi = 'MotionModel/1';  sR = 'MotionModel/2';
    else
        m = 'W06_3_heading'; fresh(m);
        addOdomReader(m, false);
        sPsi = 'Quat2Yaw/1';  sR = 'Quat2Yaw/2';
    end

    add_block('simulink/Sources/Constant', [m '/psi_ref_deg'], ...
              'Value','45', 'Position',[40 200 130 230]);
    add_block('simulink/Math Operations/Gain', [m '/deg2rad'], ...
              'Gain','pi/180', 'Position',[160 200 200 230]);
    addHeadingCtrl(m, 300, 185);

    add_block('simulink/Sources/Constant', [m '/X_const'], ...
              'Value','300', 'Position',[430 300 510 330]);

    addAllocator(m, 570, 210);
    add_line(m,'X_const/1','Alloc/1','autorouting','on');
    add_line(m,'HeadingCtrl/1','Alloc/2','autorouting','on');
    add_line(m,'psi_ref_deg/1','deg2rad/1','autorouting','on');
    add_line(m,'deg2rad/1', 'HeadingCtrl/1','autorouting','on');
    add_line(m,sPsi,'HeadingCtrl/2','autorouting','on');
    add_line(m,sR,  'HeadingCtrl/3','autorouting','on');

    if offline
        add_line(m,'Alloc/1','MotionModel/1','autorouting','on');
        add_line(m,'Alloc/2','MotionModel/2','autorouting','on');
    else
        addThrusterPublisher(m, 'left',  'L', 780, 150);
        addThrusterPublisher(m, 'right', 'R', 780, 320);
        add_line(m,'Alloc/1','AsgL/2','autorouting','on');
        add_line(m,'Alloc/2','AsgR/2','autorouting','on');
    end

    % 관찰용
    add_block('simulink/Sinks/Scope', [m '/Scope_psi'], 'Position',[430 60 480 110]);
    set_param([m '/Scope_psi'],'NumInputPorts','2');
    add_line(m,sPsi,'Scope_psi/1','autorouting','on');
    add_line(m,'deg2rad/1','Scope_psi/2','autorouting','on');
    addLog(m, sPsi, 'psi', 1000, 60);
    addLog(m, 'Alloc/1', 'FL', 1000, 110);
    addLog(m, 'Alloc/2', 'FR', 1000, 160);

    if offline
        setSolverOffline(m);
        note(m, sprintf(['[3단계 오프라인] 헤딩 제어 — Gazebo 대신 운동방정식\n' ...
            'W06_3_heading 과 HeadingCtrl · Alloc 이 같은 함수로 만들어졌다.\n' ...
            'OdomSub/Quat2Yaw 와 Publish 자리에 MotionModel 하나가 있다.\n' ...
            '초기 선수각 32.7 deg 는 VRX 스폰과 같다. 40 초가 1 초 안쪽에 끝난다.\n' ...
            '비교: >> W06_step_compare(3)']), 40, 470);
        save_system(m); close_system(m,0);
        fprintf('  [OK] %s\n', m);
        return
    end
    setSolver(m);
    note(m, sprintf(['[3단계] 헤딩 제어\n' ...
        '목표 선수각(psi_ref_deg)을 바꿔 가며 스텝응답을 본다.\n' ...
        'Scope_psi 에 실제 헤딩과 목표 헤딩이 함께 그려진다.\n' ...
        '\n' ...
        '제어기는 HeadingCtrl 상자 하나다. 더블클릭하면 안이 보인다.\n' ...
        '  N = Kp * ssa(psi_ref - psi)  -  Kd * r\n' ...
        'Kp, Kd 를 조정해 오버슈트와 정정시간을 비교할 것.']), 40, 470);
    save_system(m); close_system(m,0);
    fprintf('  [OK] %s\n', m);
end

% =====================================================================
% 4단계 — 속도 + 헤딩 (inner loop)
% =====================================================================
function build_inner_loop(offline)
    if offline
        m = 'W06_4_inner_loop_offline'; fresh(m);
        addMotionModel(m, 780, 230);
        sPsi = 'MotionModel/1';  sR = 'MotionModel/2';  sU = 'MotionModel/3';
    else
        m = 'W06_4_inner_loop'; fresh(m);
        addOdomReader(m, true);          % twist.twist.linear.x 까지 뽑음
        sPsi = 'Quat2Yaw/1';  sR = 'Quat2Yaw/2';  sU = 'Sel/5';
    end

    % --- 헤딩 루프 ---
    add_block('simulink/Sources/Constant', [m '/psi_ref_deg'], ...
              'Value','45', 'Position',[40 200 130 230]);
    add_block('simulink/Math Operations/Gain', [m '/deg2rad'], ...
              'Gain','pi/180', 'Position',[160 200 200 230]);
    addHeadingCtrl(m, 300, 185);

    % --- 속도 루프 ---
    add_block('simulink/Sources/Constant', [m '/u_ref'], ...
              'Value','1.5', 'Position',[40 320 130 350]);
    add_block('simulink/Math Operations/Sum', [m '/SumU'], ...
              'Inputs','+-', 'Position',[210 320 240 350]);
    add_block('simulink/Discrete/Discrete PID Controller', [m '/PI_u'], ...
              'Position',[290 310 370 360]);
    set_param([m '/PI_u'], 'Controller','PI', 'P','300', 'I','40', ...
              'SampleTime','0.05', 'LimitOutput','on', ...
              'UpperSaturationLimit','500', 'LowerSaturationLimit','-500', ...
              'AntiWindupMode','clamping');

    addAllocator(m, 570, 240);
    add_line(m,'psi_ref_deg/1','deg2rad/1','autorouting','on');
    add_line(m,'deg2rad/1', 'HeadingCtrl/1','autorouting','on');
    add_line(m,sPsi,'HeadingCtrl/2','autorouting','on');
    add_line(m,sR,  'HeadingCtrl/3','autorouting','on');
    add_line(m,'u_ref/1','SumU/1','autorouting','on');
    add_line(m,sU,'SumU/2','autorouting','on');
    add_line(m,'SumU/1','PI_u/1','autorouting','on');
    add_line(m,'PI_u/1','Alloc/1','autorouting','on');
    add_line(m,'HeadingCtrl/1','Alloc/2','autorouting','on');

    if offline
        add_line(m,'Alloc/1','MotionModel/1','autorouting','on');
        add_line(m,'Alloc/2','MotionModel/2','autorouting','on');
    else
        addThrusterPublisher(m, 'left',  'L', 780, 180);
        addThrusterPublisher(m, 'right', 'R', 780, 350);
        add_line(m,'Alloc/1','AsgL/2','autorouting','on');
        add_line(m,'Alloc/2','AsgR/2','autorouting','on');
    end

    % 관찰용
    add_block('simulink/Sinks/Scope', [m '/Scope_u'], 'Position',[430 60 480 110]);
    set_param([m '/Scope_u'],'NumInputPorts','2');
    add_line(m,sU,'Scope_u/1','autorouting','on');
    add_line(m,'u_ref/1','Scope_u/2','autorouting','on');

    add_block('simulink/Sinks/Scope', [m '/Scope_psi'], 'Position',[430 120 480 170]);
    set_param([m '/Scope_psi'],'NumInputPorts','2');
    add_line(m,sPsi,'Scope_psi/1','autorouting','on');
    add_line(m,'deg2rad/1','Scope_psi/2','autorouting','on');
    addLog(m, sPsi, 'psi', 1000, 60);
    addLog(m, sU,   'u',   1000, 110);
    addLog(m, 'Alloc/1', 'FL', 1000, 160);
    addLog(m, 'Alloc/2', 'FR', 1000, 210);

    if offline
        setSolverOffline(m);
        note(m, sprintf(['[4단계 오프라인] 속도 + 헤딩 — Gazebo 대신 운동방정식\n' ...
            'W06_4_inner_loop 과 HeadingCtrl · PI_u · Alloc 이 같은 함수로 만들어졌다.\n' ...
            'OdomSub/Sel/Quat2Yaw 와 Publish 자리에 MotionModel 하나가 있다.\n' ...
            '초기 선수각 32.7 deg (VRX 스폰), 초기 속도 0.\n' ...
            '비교: >> W06_step_compare(4)']), 40, 500);
        save_system(m); close_system(m,0);
        fprintf('  [OK] %s\n', m);
        return
    end
    setSolver(m);
    note(m, sprintf(['[4단계] 속도 + 헤딩 (inner loop)\n' ...
        'u_ref [m/s] 와 psi_ref_deg [deg] 를 각각 바꿔 가며 응답을 본다.\n' ...
        '속도는 ground_truth_odometry 의 twist.twist.linear.x 를 그대로 쓴다.\n' ...
        '\n' ...
        '제어기는 상자 두 개다 — HeadingCtrl (요 모멘트), PI_u (전진력).\n' ...
        'HeadingCtrl 의 D 항은 요각속도 r 을 직접 되먹인다 (-Kd*r).\n' ...
        'PI_u 는 안티와인드업(clamping)이 켜져 있다.']), 40, 500);
    save_system(m); close_system(m,0);
    fprintf('  [OK] %s\n', m);
end

% =====================================================================
% 5단계 · 오프라인 WAM-V — Gazebo 없이 같은 실험을 한다
%
%   앞의 네 모델은 추력을 ROS 2 토픽으로 내보내고 Gazebo 가 배를 움직였다.
%   이 모델은 그 자리에 WAM-V 운동방정식을 직접 넣는다.
%   시나리오 블록은 2단계(W06_2_turn)와 글자 하나까지 같다.
%   바뀌는 것은 뒷단뿐이다.
%
%     W06_2_turn    : Scenario -> Blank/Assign/Publish -> Gazebo
%     W06_5_offline : Scenario -> MotorLag -> MotionModel -> Scope
% =====================================================================
function build_offline()
    m = 'W06_5_offline'; fresh(m);

    % --- 1단 · 시나리오 (2단계와 같은 코드) ---------------------------
    add_block('simulink/Sources/Digital Clock', [m '/Clock'], ...
              'SampleTime','0.05', 'Position',[40 185 100 215]);
    add_block('simulink/User-Defined Functions/MATLAB Function', [m '/Scenario'], ...
              'Position',[150 165 280 235]);
    setFcn(m, 'Scenario', [ ...
        'function [FL, FR] = Scenario(t)' newline ...
        '%#codegen' newline ...
        '% Time-based thrust scenario [N] - identical to W06_2_turn' newline ...
        'if t < 20' newline ...
        '    FL = 200;  FR = 200;   % go straight' newline ...
        'elseif t < 40' newline ...
        '    FL = 300;  FR =  50;   % turn starboard (right)' newline ...
        'elseif t < 60' newline ...
        '    FL =  50;  FR = 300;   % turn port (left)' newline ...
        'else' newline ...
        '    FL = 0;    FR = 0;     % stop' newline ...
        'end' newline]);

    % --- 2단 · 추진기 (모터 1차 지연) ---------------------------------
    add_block('simulink/Signal Routing/Mux', [m '/MuxF'], ...
              'Inputs','2', 'Position',[340 175 345 225]);
    add_block('simulink/Discrete/Discrete Transfer Fcn', [m '/MotorLag'], ...
              'Position',[400 175 520 225]);
    set_param([m '/MotorLag'], 'Numerator','0.05/0.30', ...
              'Denominator','[1, 0.05/0.30 - 1]', 'SampleTime','0.05');

    % --- 3단 · WAM-V 운동모델 -----------------------------------------
    add_block('simulink/User-Defined Functions/MATLAB Function', [m '/EOM'], ...
              'Position',[580 140 760 260]);
    setFcn(m, 'EOM', [ ...
'function xdot = EOM(s, F)'                                              newline ...
'%#codegen'                                                              newline ...
'% 3-DOF WAM-V equations of motion in NED.'                              newline ...
'% Every coefficient below is taken from the Gazebo VRX plugins, so'     newline ...
'% this model and the simulator answer the same question the same way.'  newline ...
'%   drag : wamv_gazebo_dynamics_plugin.xacro (SimpleHydrodynamics)'     newline ...
'%   mass : 211 kg = 180 hull + 2x15 engines + 2x0.5 propellers'         newline ...
'%   added mass is zero in VRX (xDotU = yDotV = nDotR = 0)'              newline ...
'%   s = [u v r N E psi]    F = [FL; FR]'                                newline ...
''                                                                       newline ...
'mm  = 211;    Izz = 653;'                                               newline ...
'Xu  = 100;    Xuu = 150;'                                               newline ...
'Yv  = 100;    Yvv = 100;'                                               newline ...
'Nr  = 800;    Nrr = 800;'                                               newline ...
'b   = 1.027135;          % half beam of the aft thrusters [m]'          newline ...
''                                                                       newline ...
'u = s(1); v = s(2); r = s(3); psi = s(6);'                              newline ...
''                                                                       newline ...
'% differential thrust -> surge force and yaw moment'                    newline ...
'X = F(1) + F(2);'                                                       newline ...
'N = (F(1) - F(2))*b;'                                                   newline ...
''                                                                       newline ...
'Dx = (Xu + Xuu*abs(u))*u;'                                              newline ...
'Dy = (Yv + Yvv*abs(v))*v;'                                              newline ...
'Dn = (Nr + Nrr*abs(r))*r;'                                              newline ...
''                                                                       newline ...
'du = (X - Dx)/mm + v*r;     % rigid-body Coriolis'                      newline ...
'dv = (  - Dy)/mm - u*r;'                                                newline ...
'dr = (N - Dn)/Izz;'                                                     newline ...
''                                                                       newline ...
'xdot = [du; dv; dr;'                                                    newline ...
'        u*cos(psi) - v*sin(psi);'                                       newline ...
'        u*sin(psi) + v*cos(psi);'                                       newline ...
'        r];']);

    add_block('simulink/Continuous/Integrator', [m '/Integ'], ...
              'Position',[820 175 870 225], 'InitialCondition','[0;0;0;0;0;0]');

    add_block('simulink/User-Defined Functions/MATLAB Function', [m '/States'], ...
              'Position',[930 130 1080 270]);
    setFcn(m, 'States', [ ...
'function [x_n, y_n, psi_deg, u, r_deg] = States(s)'          newline ...
'%#codegen'                                                 newline ...
'% Pull the numbers we want to look at out of the state.'   newline ...
'x_n = s(4);'                                                newline ...
'y_n = s(5);'                                                newline ...
'psi_deg = s(6)*180/pi;'                                    newline ...
'u  = s(1);'                                                newline ...
'r_deg = s(3)*180/pi;']);

    % --- 4단 · 관찰 -----------------------------------------------------
    add_block('simulink/Sinks/Scope', [m '/Scope_u'],   'Position',[1160 100 1200 140]);
    add_block('simulink/Sinks/Scope', [m '/Scope_psi'], 'Position',[1160 180 1200 220]);
    add_block('simulink/Sinks/XY Graph', [m '/Track'],  'Position',[1160 270 1220 330]);
    set_param([m '/Track'],'xmin','-20','xmax','120','ymin','-40','ymax','60');

    nm = {'x_n','y_n','psi','u','r'};
    for k = 1:numel(nm)
        b = [m '/log_' nm{k}];
        add_block('simulink/Sinks/To Workspace', b, ...
                  'Position',[1160 380+(k-1)*50 1260 410+(k-1)*50]);
        set_param(b,'VariableName',['log_' nm{k}], ...
                    'SaveFormat','Timeseries','SampleTime','0.05');
    end

    % --- 배선 -----------------------------------------------------------
    add_line(m, 'Clock/1', 'Scenario/1', 'autorouting','on');
    add_line(m, 'Scenario/1', 'MuxF/1', 'autorouting','on');
    add_line(m, 'Scenario/2', 'MuxF/2', 'autorouting','on');
    add_line(m, 'MuxF/1', 'MotorLag/1', 'autorouting','on');
    add_line(m, 'MotorLag/1', 'EOM/2', 'autorouting','on');
    add_line(m, 'EOM/1', 'Integ/1', 'autorouting','on');
    add_line(m, 'Integ/1', 'EOM/1', 'autorouting','on');
    add_line(m, 'Integ/1', 'States/1', 'autorouting','on');
    add_line(m, 'States/4', 'Scope_u/1', 'autorouting','on');
    add_line(m, 'States/3', 'Scope_psi/1', 'autorouting','on');
    add_line(m, 'States/2', 'Track/1', 'autorouting','on');     % y (동쪽) 를 가로축으로
    add_line(m, 'States/1', 'Track/2', 'autorouting','on');     % x (북쪽) 를 세로축으로
    for k = 1:numel(nm)
        add_line(m, sprintf('States/%d',k), ['log_' nm{k} '/1'], 'autorouting','on');
    end

    set_param(m, 'SolverType','Fixed-step', 'SolverName','ode4', ...
                 'FixedStep','0.05', 'StopTime','80', 'SimulationMode','normal');
    note(m, sprintf(['[5단계] 오프라인 WAM-V — Gazebo 없이 같은 실험\n' ...
        '시나리오 블록은 2단계(W06_2_turn)와 완전히 같다.\n' ...
        '뒤에 Publish 대신 WAM-V 운동방정식이 붙어 있다.\n' ...
        '0~20s 직진 / 20~40s 우선회 / 40~60s 좌선회 / 60s~ 정지\n' ...
        '계수는 전부 Gazebo VRX 플러그인에서 가져온 값이다.\n' ...
        '실행 뒤 >> W06_offline_plot 으로 그림을 본다.']), 40, 660);
    save_system(m); close_system(m,0);
    fprintf('  [OK] %s\n', m);
end
