function build_w08_models()
% BUILD_W08_MODELS  8주차 Simulink 모델 2개를 생성한다.
%
%     W08_0_offline.slx   오프라인 WAM-V 로이터링 — Gazebo 없이 돈다
%     W08_1_vrx.slx       VRX 연동 — 운동모델만 Gazebo 로 바뀐다
%
%   7주차와 GNC 골격이 똑같다. 바뀐 것은 1단(유도)뿐이다.
%
%   LoiterVF → TurnCount → Inner Loop → Thrusters → 운동모델
%   (벡터필드)  (회전수)     (7주차와 동일)
%
%   유도법칙 출처
%     W. Jung, S. Lim, D. Lee, H. Bang,
%     "Unmanned Aircraft Vector Field Path Following with Arrival Angle Control"
%     식 (9)  극좌표 벡터필드,  식 (13) 침로 명령
%   구현 참고
%     UGV_WpFollowingAndLoitering/MILS/UGV_Control_StateFlow_260529.slx
%       의 KAIST_CircularVF, calculate_turns
%
%   모델이 깨졌을 때 이 스크립트를 다시 돌리면 복구된다.
%   실행 전에 반드시 >> W08_setup 을 먼저 실행할 것.

    here = fileparts(mfilename('fullpath'));
    addpath(fullfile(here, '..', '..', '_tools'));
    cd(here);

    if evalin('base', '~exist(''r_d'',''var'')')
        error('먼저 W08_setup 을 실행하십시오.');
    end

    build_offline();
    build_vrx();
    % 최상위 배치 — autorouting 에 맡기지 않고 규칙대로 직접 놓는다.
    % check_lines 의 일곱 항목이 전부 0 이 합격선 (references/line-routing.md)
    %  Wrap — 사슬을 접는 칸 수. 겹침 0 이 되는 것 중 가장 작은 쪽을 재서 골랐다
    lay_chain('W08_0_offline', {'Guidance','InnerLoop','Thrusters','MotionModel'}, ...
              'Boxes', {'Animate','Logging'}, 'Wrap', 2);
    lay_chain('W08_1_vrx', {'Guidance','InnerLoop','Thrusters','CmdPublisher','PoseSubscriber'}, ...
              'Boxes', {'Animate','Logging'}, 'Wrap', 3);

    %  색 — 역할표는 _tools/gnc_roles.m 하나뿐이다. 빌더는 부르기만 한다
    for mm = {'W08_0_offline','W08_1_vrx'}
        m = mm{1}; load_system(m);
        paint_roles(m);
        check_colour(m);
        mss_style(m); save_system(m); check_lines(m, false); export_diagram(m);
        close_system(m, 0);
    end
    fprintf('\n완료. 생성된 모델:\n');
    d = dir('W08_*.slx');
    for k = 1:numel(d), fprintf('  %s\n', d(k).name); end
end

% =====================================================================
% 공통 헬퍼
% =====================================================================
function fresh(m)
    try, close_system(m, 0); catch, end
    if exist([m '.slx'],'file'), delete([m '.slx']); end
    new_system(m);
end

function setFcn(sys, path, code)
    S  = sfroot;
    fpos = get_param([sys '/' path], 'Position');   % 포트가 생기며 블록이 멋대로 자란다
    ch = S.find('-isa','Stateflow.EMChart','Path',[sys '/' path]);
    ch.Script = code;
    set_param([sys '/' path], 'Position', fpos);    % 다시 놓아야 포트 위치가 저장 뒤와 같아진다 (사선 방지)
end

function C(m, name, value, x, y)
    add_block('simulink/Sources/Constant', [m '/' name], ...
              'Position', [x y x+95 y+30], 'Value', value);
end

function F(m, tag, sfx, x, y)
    add_block('simulink/Signal Routing/From', [m '/Fr_' tag '_' sfx], ...
              'Position', [x y x+70 y+25], 'GotoTag', tag);
end

function G(m, tag, x, y)
    add_block('simulink/Signal Routing/Goto', [m '/Go_' tag], ...
              'Position', [x y x+80 y+25], 'GotoTag', tag, 'TagVisibility','global');
end

function note(m, tag, txt, x, y)
    add_block('built-in/Note', [m '/' tag], 'Position',[x y x y], 'Text', txt);
end

% =====================================================================
% 1단 · LOITER GUIDANCE — 벡터필드
% =====================================================================
function addGuidance(m, x, y)
% 1단 · GUIDANCE — 로이터 유도 전체를 상자 하나로 묶는다.
%
%   포트   x_n, y_n, beta  ->  psi_ref, gate, u_cmd
%
%   안에 들어가는 것
%     Schedule   시간에 따라 방향·속도·반경을 바꾼다 (시나리오)
%     LoiterVF   원 궤도 벡터필드 유도 — 목표 선수각을 낸다
%     TurnCount  몇 바퀴 돌았는지 세고, 다 돌면 배를 세운다
%     설정 상수와 한 스텝 지연 (ThDly · AccDly · ArmDly)
%
%   중심 좌표·반경·회전수 같은 값은 **신호가 아니라 설정**이다. 최상위에 늘어놓으면
%   상수 여덟 개와 선 여덟 개가 신호 사슬 앞을 가린다.
    ss = add_subsys(m, 'Guidance', [x y x+190 y+180], {'x_n','y_n','beta'}, ...
                    {'psi_ref','gate','u_cmd'}, gnc_colour('guidance'));
    % --- 시나리오: 시간에 따라 방향·속도·반경을 바꾼다 ---
    add_block('simulink/Sources/Digital Clock', [ss '/Clk'], ...
              'Position', [x-190 y+330 x-140 y+360], 'SampleTime','Ts_ctrl');
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/Schedule'], 'Position', [x-100 y+240 x+40 y+400]);
    setFcn(ss, 'Schedule', [ ...
'function [pc, vd, rd] = Schedule(t, pc0, v0, rd0, use)'                newline ...
'%#codegen'                                                             newline ...
'% Change the loiter direction, speed and radius while the model runs.' newline ...
'% Direction is set by the SIGN of pc, speed by vd, radius by rd.'      newline ...
'if use < 0.5'                                                          newline ...
'    pc = pc0;   vd = v0;       rd = rd0;'                              newline ...
'elseif t < 150'                                                        newline ...
'    pc = pc0;   vd = v0;       rd = rd0;        % as configured'       newline ...
'elseif t < 300'                                                        newline ...
'    pc = -pc0;  vd = v0;       rd = rd0;        % reverse direction'   newline ...
'elseif t < 450'                                                        newline ...
'    pc = -pc0;  vd = v0*1.6;   rd = rd0;        % faster'              newline ...
'else'                                                                  newline ...
'    pc = -pc0;  vd = v0*1.6;   rd = rd0*0.6;    % tighter circle'      newline ...
'end']);

    % --- 벡터필드 유도 ---
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/LoiterVF'], 'Position', [x+200 y x+380 y+220]);
    setFcn(ss, 'LoiterVF', [ ...
'function [psi_ref, r, theta, vf_x, vf_y] = LoiterVF(x_n, y_n, x_c, y_c, rd, vd, pc, beta, kcrab)' newline ...
'%#codegen'                                                                newline ...
'% Circular-orbit vector field guidance.'                                  newline ...
'%   Jung, Lim, Lee, Bang, "Unmanned Aircraft Vector Field Path Following' newline ...
'%   with Arrival Angle Control", eq. (9) and (13).'                       newline ...
'%'                                                                        newline ...
'%   rd  desired orbit radius [m]'                                         newline ...
'%   vd  desired speed [m/s]'                                              newline ...
'%   pc  shaping parameter.  SIGN sets the turn direction:'                newline ...
'%         pc > 0  clockwise,   pc < 0  counter-clockwise'                 newline ...
'%       A smaller |pc| pulls the vehicle harder onto the circle.'         newline ...
''                                                                         newline ...
'dx = x_n - x_c;'                                                            newline ...
'dy = y_n - y_c;'                                                            newline ...
''                                                                         newline ...
'r     = sqrt(dx*dx + dy*dy);      % distance from the centre'             newline ...
'theta = atan2(dy, dx);            % bearing of the vehicle from centre'   newline ...
'if r < 1e-6, r = 1e-6; end        % the centre itself is singular'        newline ...
''                                                                         newline ...
'% eq. (9): the field written in polar components'                         newline ...
'N = sqrt((r - rd)^2 + (pc*r)^2);'                                         newline ...
'if N < 1e-9, N = 1e-9; end'                                               newline ...
'r_dot   = -vd * (r - rd) / N;     % radial     : closes the gap'          newline ...
'rth_dot =  vd * pc * r   / N;     % tangential : goes round'              newline ...
''                                                                         newline ...
'% polar -> NED. The magnitude of this vector is always vd.'               newline ...
'vf_x = r_dot*cos(theta) - rth_dot*sin(theta);'                             newline ...
'vf_y = r_dot*sin(theta) + rth_dot*cos(theta);'                             newline ...
''                                                                         newline ...
'% eq. (13): the field gives a COURSE, i.e. a velocity direction.'         newline ...
'% The boat can only be told a HEADING. In a turn the two differ by'       newline ...
'% the crab angle beta, and that difference shows up as a radius error.'   newline ...
'%   kcrab = 0  command the field angle directly (the paper form)'         newline ...
'%   kcrab = 1  subtract beta so the VELOCITY lines up with the field'     newline ...
'chi_d   = atan2(vf_y, vf_x);'                                               newline ...
'p       = chi_d - kcrab*beta;'                                            newline ...
'psi_ref = atan2(sin(p), cos(p));']);

    % --- 회전수 세기 + 임무 종료 ---
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/TurnCount'], 'Position', [x+470 y+260 x+660 y+470]);
    setFcn(ss, 'TurnCount', [ ...
'function [turns, gate, th_out, acc_out, armed] = TurnCount( ...'          newline ...
'         theta, r, rd, req, th_prev, acc_prev, armed_prev)'               newline ...
'%#codegen'                                                                newline ...
'% Count how many times the boat has gone round, then stop it.'            newline ...
'% Same idea as calculate_turns in the UGV Stateflow example: start'       newline ...
'% counting only after the boat has actually reached the circle,'          newline ...
'% otherwise the approach leg would be counted as part of a lap.'          newline ...
''                                                                         newline ...
'tol = 0.3*rd;                     % "on the circle": steady radius error is p_c*v*tau (up to ~7 m at p_c = 1), so the band must be wider than that'  newline ...
'th_out = theta;'                                                          newline ...
''                                                                         newline ...
'if armed_prev < 0.5'                                                      newline ...
'    acc_out = 0;'                                                         newline ...
'    if abs(r - rd) <= tol'                                                newline ...
'        armed = 1;                % reached the circle, start counting'   newline ...
'    else'                                                                 newline ...
'        armed = 0;'                                                       newline ...
'    end'                                                                  newline ...
'else'                                                                     newline ...
'    armed = 1;'                                                           newline ...
'    d = theta - th_prev;'                                                 newline ...
'    d = atan2(sin(d), cos(d));    % wrap: +pi to -pi must not count'      newline ...
'    acc_out = acc_prev + d;'                                              newline ...
'end'                                                                      newline ...
''                                                                         newline ...
'turns = abs(acc_out) / (2*pi);'                                           newline ...
''                                                                         newline ...
'% req = 0 means keep going forever'                                       newline ...
'if (req > 0) && (turns >= req)'                                           newline ...
'    gate = 0;                     % mission done, stop the boat'          newline ...
'else'                                                                     newline ...
'    gate = 1;'                                                            newline ...
'end']);

    % TurnCount 의 기억 세 개(각도·누적·무장)는 자기에게 되돌아온다.
    % 화면을 가로지르는 되먹임 선 대신 태그로 건넌다. 되먹임은 늘 이렇게 처리한다.
    d   = {'ThDly','AccDly','ArmDly'};
    tg  = {'th_prev','acc_prev','armed_prev'};
    src = [3 4 5];      % TurnCount 의 출력 포트
    dst = [5 6 7];      % TurnCount 의 입력 포트
    for k = 1:3
        drop_tag(ss, 'TurnCount', src(k), tg{k}, 150 + 60*k);

        q = port_xy(ss, 'TurnCount', 'Inport', dst(k));
        add_block('simulink/Discrete/Unit Delay', [ss '/' d{k}], ...
                  'Position', [x+300 q(2)-20 x+375 q(2)+20], ...
                  'InitialCondition','0', 'SampleTime','Ts_ctrl');
        add_block('simulink/Signal Routing/From', [ss '/Fr_' tg{k}], ...
                  'Position', [x+180 q(2)-11 x+250 q(2)+11], 'GotoTag', tg{k});
        add_line(ss, ['Fr_' tg{k} '/1'], [d{k} '/1']);              % 직선
        add_line(ss, [d{k} '/1'], sprintf('TurnCount/%d', dst(k))); % 직선
    end

    % --- 설정값 — 신호가 아니다. 상자 안에 둔다 ------------------------
    cfg = {'Pc0','p_c',  -170, 420;  'V0','u_ref',  -170, 470; ...
           'Rd0','r_d',  -170, 520;  'Sch','use_schedule', -170, 570; ...
           'Cn','center_north',  30, 620;  'Ce','center_east', 30, 670; ...
           'Kcr','crab_comp',    30, 720;  'Req','required_turns', 30, 770};
    for k = 1:size(cfg,1)
        add_block('simulink/Sources/Constant', [ss '/' cfg{k,1}], ...
                  'Position', [cfg{k,3} cfg{k,4} cfg{k,3}+90 cfg{k,4}+30], ...
                  'Value', cfg{k,2});
    end

    % --- 배선 : Schedule ------------------------------------------------
    add_line(ss,'Clk/1', 'Schedule/1','autorouting','on');
    add_line(ss,'Pc0/1', 'Schedule/2','autorouting','on');
    add_line(ss,'V0/1',  'Schedule/3','autorouting','on');
    add_line(ss,'Rd0/1', 'Schedule/4','autorouting','on');
    add_line(ss,'Sch/1', 'Schedule/5','autorouting','on');

    % --- 배선 : LoiterVF ------------------------------------------------
    add_line(ss,'x_n/1',  'LoiterVF/1','autorouting','on');
    add_line(ss,'y_n/1',  'LoiterVF/2','autorouting','on');
    add_line(ss,'Cn/1',  'LoiterVF/3','autorouting','on');
    add_line(ss,'Ce/1',  'LoiterVF/4','autorouting','on');
    add_line(ss,'Schedule/3','LoiterVF/5','autorouting','on');   % rd
    add_line(ss,'Schedule/2','LoiterVF/6','autorouting','on');   % vd
    add_line(ss,'Schedule/1','LoiterVF/7','autorouting','on');   % pc
    add_line(ss,'beta/1','LoiterVF/8','autorouting','on');
    add_line(ss,'Kcr/1', 'LoiterVF/9','autorouting','on');

    % --- 배선 : TurnCount -----------------------------------------------
    add_line(ss,'LoiterVF/3','TurnCount/1','autorouting','on');  % theta
    add_line(ss,'LoiterVF/2','TurnCount/2','autorouting','on');  % r
    add_line(ss,'Schedule/3','TurnCount/3','autorouting','on');  % rd
    add_line(ss,'Req/1',     'TurnCount/4','autorouting','on');

    % --- 출력 포트 ------------------------------------------------------
    add_line(ss,'LoiterVF/1', 'psi_ref/1','autorouting','on');
    add_line(ss,'TurnCount/2','gate/1','autorouting','on');
    add_line(ss,'Schedule/2', 'u_cmd/1','autorouting','on');

    % --- 로깅용 태그 — 상자 안에서 건다. 최상위에 태그를 늘어놓지 않는다 ---
    tg = {'LoiterVF',1,'psi_ref'; 'LoiterVF',2,'r_dist'; 'LoiterVF',3,'theta'; ...
          'LoiterVF',4,'vf_x';     'LoiterVF',5,'vf_y'; ...
          'TurnCount',1,'turns';  'TurnCount',2,'gate'; 'Schedule',2,'u_cmd'};
    for k = 1:size(tg,1)
        b = [ss '/Go_' tg{k,3}];
        add_block('simulink/Signal Routing/Goto', b, ...
                  'Position', [700 900+(k-1)*45 780 900+(k-1)*45+22], ...
                  'GotoTag', tg{k,3}, 'TagVisibility','global');
        add_line(ss, sprintf('%s/%d', tg{k,1}, tg{k,2}), ['Go_' tg{k,3} '/1'], ...
                 'autorouting','on');
    end

    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 2단 · INNER LOOP — 7주차와 완전히 같다
% =====================================================================
function addInnerLoop(m, x, y)
    ss = [m '/InnerLoop'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+190 y+170]);

    in = {'psi_ref','gate','u_ref','psi','r','u'};
    for k = 1:numel(in)
        add_block('simulink/Sources/In1', [ss '/' in{k}], ...
                  'Position', [40 60+(k-1)*80 75 60+(k-1)*80+30], 'Port', num2str(k));
    end

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/HeadingErr'], 'Position', [200 60 340 130]);
    setFcn(ss, 'HeadingErr', [ ...
'function e = HeadingErr(psi_ref, psi)'                          newline ...
'%#codegen'                                                      newline ...
'% Shortest signed angle, wrapped to [-pi, pi).'                 newline ...
'd = psi_ref - psi;'                                             newline ...
'e = atan2(sin(d), cos(d));']);

    add_block('simulink/Math Operations/Gain', [ss '/Kp_psi'], ...
              'Position', [410 60 460 100], 'Gain','Kp_psi');
    add_block('simulink/Math Operations/Gain', [ss '/Kd_rate'], ...
              'Position', [410 240 460 280], 'Gain','-Kd_psi');
    add_block('simulink/Math Operations/Sum', [ss '/SumN'], ...
              'Position', [560 110 590 150], 'Inputs','++');
    add_block('simulink/Discontinuities/Saturation', [ss '/SatN'], ...
              'Position', [650 110 690 150], ...
              'UpperLimit','2*F_max*half_beam', 'LowerLimit','-2*F_max*half_beam');

    add_line(ss,'psi_ref/1','HeadingErr/1','autorouting','on');
    add_line(ss,'psi/1',    'HeadingErr/2','autorouting','on');
    add_line(ss,'HeadingErr/1','Kp_psi/1','autorouting','on');
    add_line(ss,'r/1',        'Kd_rate/1','autorouting','on');
    add_line(ss,'Kp_psi/1', 'SumN/1','autorouting','on');
    add_line(ss,'Kd_rate/1','SumN/2','autorouting','on');
    add_line(ss,'SumN/1','SatN/1','autorouting','on');

    add_block('simulink/Math Operations/Product', [ss '/Gate'], ...
              'Position', [200 380 235 420]);
    add_block('simulink/Math Operations/Sum', [ss '/SurgeErr'], ...
              'Position', [300 385 330 415], 'Inputs','+-');
    add_block('simulink/Continuous/PID Controller', [ss '/PI_u'], ...
              'Position', [400 370 490 430]);
    set_param([ss '/PI_u'], 'Controller','PI', ...
        'TimeDomain','Discrete-time', 'SampleTime','Ts_ctrl', ...
        'P','Kp_u', 'I','Ki_u', 'LimitOutput','on', ...
        'UpperSaturationLimit','2*F_max', 'LowerSaturationLimit','-2*F_max', ...
        'AntiWindupMode','clamping');

    add_line(ss,'u_ref/1','Gate/1','autorouting','on');
    add_line(ss,'gate/1', 'Gate/2','autorouting','on');
    add_line(ss,'Gate/1','SurgeErr/1','autorouting','on');
    add_line(ss,'u/1',   'SurgeErr/2','autorouting','on');
    add_line(ss,'SurgeErr/1','PI_u/1','autorouting','on');

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/Alloc'], 'Position', [760 230 910 340]);
    setFcn(ss, 'Alloc', [ ...
'function [FL, FR] = Alloc(X, N, half_beam, Fmax)'                newline ...
'%#codegen'                                                       newline ...
'% Differential thrust allocation for two aft thrusters.'         newline ...
'FL = X/2 + N/(2*half_beam);'                                     newline ...
'FR = X/2 - N/(2*half_beam);'                                     newline ...
'if FL >  Fmax, FL =  Fmax; end'                                  newline ...
'if FL < -Fmax, FL = -Fmax; end'                                  newline ...
'if FR >  Fmax, FR =  Fmax; end'                                  newline ...
'if FR < -Fmax, FR = -Fmax; end']);

    add_block('simulink/Sources/Constant', [ss '/HB'], ...
              'Position', [620 460 710 490], 'Value','half_beam');
    add_block('simulink/Sources/Constant', [ss '/FM'], ...
              'Position', [620 510 710 540], 'Value','F_max');
    add_block('simulink/Sinks/Out1', [ss '/FL'], 'Position',[980 250 1015 280], 'Port','1');
    add_block('simulink/Sinks/Out1', [ss '/FR'], 'Position',[980 310 1015 340], 'Port','2');

    add_line(ss,'PI_u/1','Alloc/1','autorouting','on');
    add_line(ss,'SatN/1','Alloc/2','autorouting','on');
    add_line(ss,'HB/1',  'Alloc/3','autorouting','on');
    add_line(ss,'FM/1',  'Alloc/4','autorouting','on');
    add_line(ss,'Alloc/1','FL/1','autorouting','on');
    add_line(ss,'Alloc/2','FR/1','autorouting','on');

    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 3단 · THRUSTERS — 7주차와 완전히 같다
% =====================================================================
function addThrusters(m, x, y)
    ss = [m '/Thrusters'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+170 y+120]);

    add_block('simulink/Sources/In1', [ss '/FL_cmd'], 'Position',[40 60 75 90],  'Port','1');
    add_block('simulink/Sources/In1', [ss '/FR_cmd'], 'Position',[40 140 75 170],'Port','2');

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/F2n'], 'Position', [170 70 320 160]);
    setFcn(ss, 'F2n', [ ...
'function n_cmd = F2n(FL, FR, k, n_max)'                              newline ...
'%#codegen'                                                           newline ...
'% Inverse propeller law:  F = k*n*|n|  ->  n = sign(F)*sqrt(|F|/k)'  newline ...
'F = [FL; FR];'                                                       newline ...
'n_cmd = zeros(2,1);'                                                 newline ...
'for i = 1:2'                                                         newline ...
'    ni = sign(F(i)) * sqrt(abs(F(i))/k);'                            newline ...
'    if ni >  n_max, ni =  n_max; end'                                newline ...
'    if ni < -n_max, ni = -n_max; end'                                newline ...
'    n_cmd(i) = ni;'                                                  newline ...
'end']);

    add_block('simulink/Sources/Constant', [ss '/Kp'], ...
              'Position',[40 250 130 280], 'Value','k_prop');
    add_block('simulink/Sources/Constant', [ss '/Nm'], ...
              'Position',[40 300 130 330], 'Value','n_max');

    add_block('simulink/Discrete/Discrete Transfer Fcn', [ss '/MotorLag'], ...
              'Position',[380 85 500 145]);
    set_param([ss '/MotorLag'], 'Numerator','Ts_ctrl/tau_n', ...
              'Denominator','[1, Ts_ctrl/tau_n - 1]', 'SampleTime','Ts_ctrl');

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/n2F'], 'Position', [560 70 700 160]);
    setFcn(ss, 'n2F', [ ...
'function [FL, FR] = n2F(n, k)'                                  newline ...
'%#codegen'                                                      newline ...
'% Forward propeller law. Thrust is quadratic in shaft speed.'   newline ...
'FL = k * n(1) * abs(n(1));'                                     newline ...
'FR = k * n(2) * abs(n(2));']);

    add_block('simulink/Sinks/Out1', [ss '/FL'], 'Position',[780 70 815 100], 'Port','1');
    add_block('simulink/Sinks/Out1', [ss '/FR'], 'Position',[780 130 815 160],'Port','2');
    add_block('simulink/Sinks/Out1', [ss '/n'],  'Position',[780 190 815 220],'Port','3');

    add_line(ss,'FL_cmd/1','F2n/1','autorouting','on');
    add_line(ss,'FR_cmd/1','F2n/2','autorouting','on');
    add_line(ss,'Kp/1','F2n/3','autorouting','on');
    add_line(ss,'Nm/1','F2n/4','autorouting','on');
    add_line(ss,'F2n/1','MotorLag/1','autorouting','on');
    add_line(ss,'MotorLag/1','n2F/1','autorouting','on');
    add_line(ss,'Kp/1','n2F/2','autorouting','on');
    add_line(ss,'n2F/1','FL/1','autorouting','on');
    add_line(ss,'n2F/2','FR/1','autorouting','on');
    add_line(ss,'MotorLag/1','n/1','autorouting','on');

    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 4단 · MOTION MODEL — 7주차와 완전히 같다
% =====================================================================
function addMotionModel(m, x, y)
    ss = [m '/MotionModel'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+210 y+200]);

    in = {'FL','FR','p'};   % 앞의 둘만 신호. p 는 설정이라 상자 안에 둔다
    for k = 1:2
        add_block('simulink/Sources/In1', [ss '/' in{k}], ...
                  'Position', [40 60+(k-1)*70 75 60+(k-1)*70+30], 'Port', num2str(k));
    end

    % 선체 계수는 신호가 아니라 설정이다. 상자 안에 둔다
    add_block('simulink/Sources/Constant', [ss '/p'], ...
              'Position', [40 220 130 250], ...
              'Value', '[m_usv; Izz; Xu; Xuu; Yv; Yvv; Nr; Nrr; half_beam]');

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/EOM'], 'Position', [200 60 380 240]);
    setFcn(ss, 'EOM', [ ...
'function xdot = EOM(s, FL, FR, p)'                                      newline ...
'%#codegen'                                                              newline ...
'% 3-DOF WAM-V equations of motion, NED.'                                newline ...
'% Coefficients come straight from the Gazebo VRX plugins.'              newline ...
'%   s = [u v r N E psi]'''                                              newline ...
'%   p = [m Izz Xu Xuu Yv Yvv Nr Nrr half_beam]'''                       newline ...
'u = s(1); v = s(2); r = s(3); psi = s(6);'                              newline ...
'm=p(1); Izz=p(2); Xu=p(3); Xuu=p(4); Yv=p(5); Yvv=p(6);'                newline ...
'Nr=p(7); Nrr=p(8); b_half=p(9);'                                        newline ...
''                                                                       newline ...
'X = FL + FR;'                                                           newline ...
'N = (FL - FR)*b_half;'                                                  newline ...
''                                                                       newline ...
'Dx = (Xu + Xuu*abs(u))*u;'                                              newline ...
'Dy = (Yv + Yvv*abs(v))*v;'                                              newline ...
'Dn = (Nr + Nrr*abs(r))*r;'                                              newline ...
''                                                                       newline ...
'du = (X - Dx)/m + v*r;'                                                 newline ...
'dv = (  - Dy)/m - u*r;'                                                 newline ...
'dr = (N - Dn)/Izz;'                                                     newline ...
''                                                                       newline ...
'xdot = [du; dv; dr;'                                                    newline ...
'        u*cos(psi) - v*sin(psi);'                                       newline ...
'        u*sin(psi) + v*cos(psi);'                                       newline ...
'        r];']);

    add_block('simulink/Continuous/Integrator', [ss '/Integ'], ...
              'Position', [450 130 500 180], 'InitialCondition','x0');

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/States'], 'Position', [570 60 720 260]);
    setFcn(ss, 'States', [ ...
'function [x_n, y_n, psi, u, r, beta, chi, U] = States(s)'    newline ...
'%#codegen'                                                 newline ...
'u = s(1); v = s(2); r = s(3);'                             newline ...
'x_n = s(4); y_n = s(5); psi = s(6);'                         newline ...
'U    = sqrt(u*u + v*v);'                                   newline ...
'beta = atan2(v, u);'                                       newline ...
'c    = psi + beta;'                                        newline ...
'chi  = atan2(sin(c), cos(c));']);

    % --- 배치 : 한 줄에 EOM -> 1/s -> States. 포트 높이를 읽어서 맞춘다 ----
    ROW = 340;
    set_param([ss '/EOM'],    'Position', [280 140 460 540]);
    set_param([ss '/Integ'],  'Position', [560 ROW-15 590 ROW+15]);
    set_param([ss '/States'], 'Position', [680 100 840 580]);

    % 2~4번 입력(추력 둘 + 계수)을 각자 포트 높이로 옮겨 직선으로 잇는다
    row_feed(ss, 'EOM', [{''}, in]);

    add_line(ss, 'EOM/1',   'Integ/1');
    add_line(ss, 'Integ/1', 'States/1');

    % 상태 되먹임 — 화면을 가로지르는 대신 태그로 건너뛴다
    drop_tag(ss, 'Integ', 1, 'x_state', 280);
    b = port_xy(ss, 'EOM', 'Inport', 1);
    add_block('simulink/Signal Routing/From', [ss '/Fr_x_state'], ...
              'Position', [180 b(2)-11 250 b(2)+11], 'GotoTag','x_state');
    add_line(ss, 'Fr_x_state/1', 'EOM/1');

    % 출력 포트를 States 의 포트 높이에 맞춘다 -> 여덟 선이 전부 직선
    out = {'x_n','y_n','psi','u','r','beta','chi','U'};
    for k = 1:numel(out)
        q = port_xy(ss, 'States', 'Outport', k);
        add_block('simulink/Sinks/Out1', [ss '/' out{k}], ...
                  'Position', [940 q(2)-7 970 q(2)+7], 'Port', num2str(k));
        add_line(ss, sprintf('States/%d',k), [out{k} '/1']);
    end
end

% =====================================================================
% 5단 · ANIMATE
% =====================================================================
function addAnimate(m, x, y)
% 실시간 그림 — 포트 없는 서브시스템 하나로 묶는다.
    add_animate_box(m, {'x_n','y_n','psi','turns'}, 'W08_animate', '', [x y], 'Ts_ctrl');
end

% =====================================================================
% 앞단 배선 (두 모델 공통)
%   설정값은 각 상자 안에 있다. 최상위에 남는 것은 되먹임뿐이다.
% =====================================================================
function wireFront(m)
    F(m,'x_n','a',   40,  65);
    F(m,'y_n','a',   40, 110);
    F(m,'beta','g', 40, 155);

    add_line(m,'Fr_x_n_a/1',  'Guidance/1','autorouting','on');
    add_line(m,'Fr_y_n_a/1',  'Guidance/2','autorouting','on');
    add_line(m,'Fr_beta_g/1','Guidance/3','autorouting','on');

    % 내부루프 입력 : 유도 출력 셋 + 자세·속도 되먹임 셋
    F(m,'psi','b', 780, 560);
    F(m,'r',  'b', 780, 600);
    F(m,'u',  'b', 780, 640);
    add_line(m,'Guidance/1','InnerLoop/1','autorouting','on');   % psi_ref
    add_line(m,'Guidance/2','InnerLoop/2','autorouting','on');   % gate
    add_line(m,'Guidance/3','InnerLoop/3','autorouting','on');   % u_cmd
    add_line(m,'Fr_psi_b/1','InnerLoop/4','autorouting','on');
    add_line(m,'Fr_r_b/1',  'InnerLoop/5','autorouting','on');
    add_line(m,'Fr_u_b/1',  'InnerLoop/6','autorouting','on');
end

% =====================================================================
% 로깅
% =====================================================================
function addLogging(m, x, y)
% 로깅 — 포트 없는 서브시스템 하나로 묶는다. W08_plot.m 이 이 변수들을 읽는다.
    sig = {'x_n','y_n','psi','psi_ref','r_dist','theta','turns','gate','u','u_cmd','beta','FL','FR','n','vf_x','vf_y'};
    tag = {'x_n','y_n','psi','psi_ref','r_dist','theta','turns','gate','u','u_cmd','beta','FL','FR','nprop','vf_x','vf_y'};
    add_logging_box(m, sig, tag, [x y], 'Ts_ctrl');
end
% =====================================================================
% 오프라인 모델
% =====================================================================
function build_offline()
    m = 'W08_0_offline'; fresh(m);
    set_param(m, 'SolverType','Fixed-step', 'SolverName','ode4', ...
                 'FixedStep','Ts_ctrl', 'StopTime','300', 'SimulationMode','normal');

    addGuidance(m, 250, 60);
    addInnerLoop(m, 1000, 560);
    wireFront(m);
    addThrusters(m, 1300, 570);
    addMotionModel(m, 1620, 560);

    add_line(m,'InnerLoop/1','Thrusters/1','autorouting','on');
    add_line(m,'InnerLoop/2','Thrusters/2','autorouting','on');
    add_line(m,'Thrusters/1','MotionModel/1','autorouting','on');
    add_line(m,'Thrusters/2','MotionModel/2','autorouting','on');

    G(m,'FL', 1500, 800);  G(m,'FR', 1500, 840);  G(m,'nprop', 1500, 880);
    add_line(m,'Thrusters/1','Go_FL/1','autorouting','on');
    add_line(m,'Thrusters/2','Go_FR/1','autorouting','on');
    add_line(m,'Thrusters/3','Go_nprop/1','autorouting','on');

    tags = {'x_n','y_n','psi','u','r','beta','chi','U'};
    for k = 1:numel(tags)
        G(m, tags{k}, 1900, 560+(k-1)*40);
        add_line(m, sprintf('MotionModel/%d',k), ['Go_' tags{k} '/1'], 'autorouting','on');
    end

    addAnimate(m, 1900, 920);
    addLogging(m, 2350, 60);

    note(m,'n1', ['W08 실습 B  —  오프라인 WAM-V 로이터링 (Gazebo 불필요)' newline ...
        'LoiterVF -> TurnCount -> Inner Loop -> Thrusters -> 운동모델' newline ...
        '유도만 7주차와 다르다. 나머지는 그대로다.' newline ...
        '실행 전 >> W08_setup'], 250, -100);

    save_system(m); close_system(m);
    fprintf('  W08_0_offline  생성\n');
end

% =====================================================================
% VRX 연동 모델
% =====================================================================
function build_vrx()
    m = 'W08_1_vrx'; fresh(m);
    load_system('ros2lib');
    set_param(m, 'SolverType','Fixed-step', 'SolverName','FixedStepDiscrete', ...
                 'FixedStep','Ts_ctrl', 'StopTime','inf', 'SimulationMode','normal');

    addGuidance(m, 250, 60);
    addInnerLoop(m, 1000, 560);
    wireFront(m);
    addThrusters(m, 1300, 570);

    % --- 4단 · 추력 발행 (운동모델 = Gazebo) -----------------------------
    add_cmd_publisher(m, [1600 480], ...
        {'/wamv/thrusters/left/thrust','/wamv/thrusters/right/thrust'}, 'Ts_ctrl');
    add_line(m,'InnerLoop/1','Thrusters/1','autorouting','on');
    add_line(m,'InnerLoop/2','Thrusters/2','autorouting','on');
    add_line(m,'Thrusters/1','CmdPublisher/1','autorouting','on');
    add_line(m,'Thrusters/2','CmdPublisher/2','autorouting','on');

    G(m,'FL', 1500, 850);  G(m,'FR', 1500, 890);  G(m,'nprop', 1500, 930);
    add_line(m,'Thrusters/1','Go_FL/1','autorouting','on');
    add_line(m,'Thrusters/2','Go_FR/1','autorouting','on');
    add_line(m,'Thrusters/3','Go_nprop/1','autorouting','on');

    % --- 5단 · 항법 (ENU -> NED 변환) -----------------------------------
    navCode = [ ...
'function [x_n, y_n, psi, u, r, beta, chi, U] = Nav(ex, ey, qx, qy, qz, qw, bx, by, wz, org_x, org_y)' newline ...
'%#codegen'                                                                 newline ...
'% Gazebo/ROS uses ENU with a body frame of x-forward, y-LEFT, z-UP.'       newline ...
'% Marine control uses NED with x-forward, y-STARBOARD, z-DOWN.'            newline ...
'% 첫 메시지가 도착하기 전에는 Subscribe 가 0 으로 채운 버스를 낸다.'       newline ...
'% 그대로 쓰면 위치가 스폰 원점만큼(약 568 m) 튀어 로그 첫 점이 망가진다.'  newline ...
'if ex == 0 && ey == 0'                                                     newline ...
'    x_n = 0; y_n = 0; psi = 0; u = 0; r = 0; beta = 0; chi = 0; U = 0;'      newline ...
'    return'                                                                newline ...
'end'                                                                       newline ...
'x_n = ey - org_x;'                                                           newline ...
'y_n = ex - org_y;'                                                           newline ...
'yaw_enu = atan2(2*(qw*qz + qx*qy), 1 - 2*(qy*qy + qz*qz));'                newline ...
'p   = pi/2 - yaw_enu;'                                                     newline ...
'psi = atan2(sin(p), cos(p));'                                              newline ...
'u = bx;'                                                                   newline ...
'v = -by;'                                                                  newline ...
'r = -wz;'                                                                  newline ...
'U    = sqrt(u*u + v*v);'                                                   newline ...
'beta = atan2(v, u);'                                                       newline ...
'c    = psi + beta;'                                                        newline ...
'chi  = atan2(sin(c), cos(c));'];

    add_pose_subscriber(m, [1960 950], ...
        '/wamv/sensors/position/ground_truth_odometry', 'Ts_ctrl', navCode, ...
        {'x_n','y_n','psi','u','r','beta','chi','U'});

    tags = {'x_n','y_n','psi','u','r','beta','chi','U'};
    for k = 1:numel(tags)
        G(m, tags{k}, 2300, 950+(k-1)*45);
        add_line(m, sprintf('PoseSubscriber/%d',k), ['Go_' tags{k} '/1'], 'autorouting','on');
    end

    addAnimate(m, 2200, 1320);
    addLogging(m, 2650, 60);

    note(m,'n1', ['W08 실습 D  —  VRX 연동 로이터링' newline ...
        'Guidance -> Inner Loop -> Thrusters -> Gazebo -> Navigation' newline ...
        '유도부·내부루프·게인은 W08_0_offline 과 완전히 같다.' newline ...
        '운동모델만 Gazebo 로 바뀐다.' newline ...
        '실행 전: (1) W08_setup  (2) VRX 기동  (3) 페이싱을 RTF 에 맞출 것'], 250, -100);

    save_system(m); close_system(m);
    fprintf('  W08_1_vrx      생성\n');
end

function addThrusterPublisher(m, side, tag, x, y)
    add_block('ros2lib/Blank Message', [m '/Blank' tag], ...
              'Position', [x y+70 x+100 y+110]);
    set_param([m '/Blank' tag], 'entityType','std_msgs/Float64', ...
              'messageType','std_msgs/Float64', 'SampleTime','Ts_ctrl');
    add_block('simulink/Signal Routing/Bus Assignment', [m '/Asg' tag], ...
              'Position', [x+160 y x+220 y+115]);
    set_param([m '/Asg' tag], 'AssignedSignals','data');
    add_block('ros2lib/Publish', [m '/Pub' tag], ...
              'Position', [x+290 y+35 x+390 y+75]);
    set_param([m '/Pub' tag], 'topicSource','Specify your own', ...
              'topic', ['/wamv/thrusters/' side '/thrust'], ...
              'messageType','std_msgs/Float64');
    add_line(m, ['Blank' tag '/1'], ['Asg' tag '/1'], 'autorouting','on');
    add_line(m, ['Asg'   tag '/1'], ['Pub' tag '/1'], 'autorouting','on');
end
