function build_w10_models()
% BUILD_W10_MODELS  10주차 모델 두 개를 만든다.
%
%   W10_0_offline : Gazebo 없이 도는 틸팅 추진기 + 배분 + DP
%   W10_1_vrx     : 같은 제어기를 VRX 와 연결한 것
%
%   실행 전에 반드시 >> W10_setup 을 먼저 실행할 것.
%
%   신호 흐름 (좌 -> 우)
%     DPRef -> DPCtrl -> Alloc -> Thrusters -> MotionModel(+Env) -> 로깅

    here = fileparts(mfilename('fullpath'));
    cd(here);

    if evalin('base', '~exist(''T_pinv'',''var'')')
        error('먼저 W10_setup 을 실행하십시오.');
    end

    build_offline();
    build_vrx();

    % 배치와 색을 정리한다. 선은 직선 또는 직각으로만 다시 그린다.
    slxList = dir('*.slx');
    for k = 1:numel(slxList)
        [~, mName] = fileparts(slxList(k).name);
        try, tidy_layout(mName); tidy_layout(mName); catch, end
    end

    fprintf('\n완료. 생성된 모델:\n');
    d = dir('*.slx');
    for k = 1:numel(d), fprintf('  %s\n', d(k).name); end
end

% =====================================================================
% 공통 헬퍼
% =====================================================================
function fresh(m)
    if bdIsLoaded(m), close_system(m, 0); end
    if isfile([m '.slx']), delete([m '.slx']); end
    new_system(m); load_system(m);
end

function setSolver(m, stopTime)
    set_param(m, 'SolverType','Fixed-step', 'SolverName','ode4', ...
                 'FixedStep','Ts_ctrl', 'StopTime',stopTime, 'SimulationMode','normal');
end

function setFcn(sys, path, code)
    add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/' path]);
    S = sfroot; B = S.find('Path', [sys '/' path], '-isa','Stateflow.EMChart');
    B.Script = code;
end

function C(m, name, value, x, y)
    add_block('simulink/Sources/Constant', [m '/' name], ...
              'Value', value, 'Position', [x y x+95 y+30]);
end

function F(m, tag, sfx, x, y)
    add_block('simulink/Signal Routing/From', [m '/Fr_' tag '_' sfx], ...
              'Position', [x y x+70 y+25], 'GotoTag', tag);
end

function G(m, tag, x, y)
    add_block('simulink/Signal Routing/Goto', [m '/Go_' tag], ...
              'Position', [x y x+80 y+25], 'GotoTag', tag);
end

function note(m, tag, txt, x, y)
    add_block('built-in/Note', [m '/' tag], 'Position',[x y x y], 'Text', txt);
end

% =====================================================================
% 1단 · DP 목표값
% =====================================================================
function addDPRef(m, x, y)
    ss = [m '/DPRef'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+160 y+120]);

    in = {'t','mode','tbl','eta0','pre','rpar'};
    for k = 1:numel(in)
        add_block('simulink/Sources/In1', [ss '/' in{k}], ...
                  'Position',[40 60+(k-1)*70 75 90+(k-1)*70], 'Port', num2str(k));
    end

    setFcn(ss, 'Sched', [ ...
'function [eta_d, snew, eta_raw] = Sched(t, mode, tbl, eta0, pre, rpar)'  newline ...
'%#codegen'                                                              newline ...
'% DP setpoint scheduler and REFERENCE MODEL.'                           newline ...
'%'                                                                      newline ...
'%   mode 0 : hold the initial setpoint'                                 newline ...
'%   mode 1 : step through the table  [t  N  E  psi_deg]'                newline ...
'%'                                                                      newline ...
'% A raw step demand is never given to a DP controller. The vessel'      newline ...
'% cannot move at any speed, so a step makes the controller ask for a'   newline ...
'% force the thrusters cannot deliver, and the loop saturates.'          newline ...
'% A reference model turns the step into a feasible trajectory. Here a'  newline ...
'% saturated proportional law is used:'                                  newline ...
'%     v = (eta_raw - eta_d)/tau_ref,   |v| <= v_max'                    newline ...
'% Far from the target the setpoint moves at the constant speed v_max;'  newline ...
'% close to it the approach becomes exponential with time constant'      newline ...
'% tau_ref, so there is no corner at arrival.'                           newline ...
'% Fossen (2011) calls this the reference model; every DP system has'    newline ...
'% one.'                                                                 newline ...
'%'                                                                      newline ...
'% rpar = [on; vN; vE; vPsi; tau_ref; Ts]'                               newline ...
''                                                                       newline ...
'eta_raw = eta0;'                                                        newline ...
'if mode > 0.5'                                                          newline ...
'    n = size(tbl,1);'                                                   newline ...
'    for i = 1:n'                                                        newline ...
'        if t >= tbl(i,1)'                                               newline ...
'            eta_raw = [tbl(i,2); tbl(i,3); tbl(i,4)*pi/180];'           newline ...
'        end'                                                            newline ...
'    end'                                                                newline ...
'end'                                                                    newline ...
''                                                                       newline ...
'if rpar(1) < 0.5'                                                       newline ...
'    eta_d = eta_raw;  snew = eta_raw;'                                   newline ...
'    return'                                                             newline ...
'end'                                                                    newline ...
''                                                                       newline ...
'vmax = rpar(2:4);  tr = rpar(5);  Ts = rpar(6);'                        newline ...
'snew = pre;'                                                            newline ...
'for i = 1:3'                                                            newline ...
'    d = eta_raw(i) - pre(i);'                                           newline ...
'    if i == 3, d = atan2(sin(d), cos(d)); end'                          newline ...
'    v = d/tr;'                                                          newline ...
'    if v >  vmax(i), v =  vmax(i); end'                                 newline ...
'    if v < -vmax(i), v = -vmax(i); end'                                 newline ...
'    snew(i) = pre(i) + v*Ts;'                                           newline ...
'end'                                                                    newline ...
'snew(3) = atan2(sin(snew(3)), cos(snew(3)));'                           newline ...
'eta_d = snew;']);
    set_param([ss '/Sched'],'Position',[180 70 360 480]);

    out = {'eta_d','snew','eta_raw'};
    for k = 1:numel(out)
        add_block('simulink/Sinks/Out1', [ss '/' out{k}], ...
                  'Position',[440 100+(k-1)*90 475 130+(k-1)*90], 'Port', num2str(k));
        add_line(ss, sprintf('Sched/%d',k), [out{k} '/1'], 'autorouting','on');
    end
    for k = 1:numel(in)
        add_line(ss, [in{k} '/1'], sprintf('Sched/%d',k), 'autorouting','on');
    end
    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 1.5단 · 파랑 필터
% =====================================================================
function addWaveFilter(m, x, y)
    ss = [m '/WaveFilter'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+170 y+140]);

    in = {'eta','nu','pre','par'};
    for k = 1:numel(in)
        add_block('simulink/Sources/In1', [ss '/' in{k}], ...
                  'Position',[40 60+(k-1)*70 75 90+(k-1)*70], 'Port', num2str(k));
    end

    setFcn(ss, 'Filt', [ ...
'function [eta_f, nu_f, snew] = Filt(eta, nu, pre, par)'                 newline ...
'%#codegen'                                                              newline ...
'% Wave filtering for dynamic positioning.'                              newline ...
'%'                                                                      newline ...
'% First order wave loads make the vessel oscillate at the wave'         newline ...
'% frequency. That motion cannot be counteracted — trying to do so'      newline ...
'% only wears out the thrusters. A DP system therefore feeds the'        newline ...
'% controller with the LOW FREQUENCY part of the motion only.'           newline ...
'% Fossen (2011) 11.4.1 uses a passive observer; here a first order'     newline ...
'% low pass with a cut-off well below the wave frequency is enough to'   newline ...
'% show the effect.'                                                     newline ...
'%'                                                                      newline ...
'% par = [on; wf; Ts]'                                                   newline ...
''                                                                       newline ...
'on = par(1); wf = par(2); Ts = par(3);'                                 newline ...
'z  = [eta; nu];'                                                        newline ...
'if on < 0.5'                                                            newline ...
'    eta_f = eta;  nu_f = nu;  snew = z;'                                newline ...
'    return'                                                             newline ...
'end'                                                                    newline ...
'a = Ts*wf/(1 + Ts*wf);'                                                 newline ...
'snew = pre + a*(z - pre);'                                              newline ...
'% heading must be filtered on the difference, not the raw angle'        newline ...
'd3 = atan2(sin(eta(3) - pre(3)), cos(eta(3) - pre(3)));'                newline ...
'snew(3) = pre(3) + a*d3;'                                               newline ...
'snew(3) = atan2(sin(snew(3)), cos(snew(3)));'                           newline ...
'eta_f = snew(1:3);'                                                     newline ...
'nu_f  = snew(4:6);']);
    set_param([ss '/Filt'],'Position',[220 70 400 330]);

    out = {'eta_f','nu_f','snew'};
    for k = 1:numel(out)
        add_block('simulink/Sinks/Out1', [ss '/' out{k}], ...
                  'Position',[500 80+(k-1)*90 535 110+(k-1)*90], 'Port', num2str(k));
        add_line(ss, sprintf('Filt/%d',k), [out{k} '/1'], 'autorouting','on');
    end
    for k = 1:numel(in)
        add_line(ss, [in{k} '/1'], sprintf('Filt/%d',k), 'autorouting','on');
    end
    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 2단 · DP 제어기 (3자유도 PID)
% =====================================================================
function addDPCtrl(m, x, y)
    ss = [m '/DPCtrl'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+190 y+220]);

    in = {'eta_d','eta','nu','Ipre','par'};
    for k = 1:numel(in)
        add_block('simulink/Sources/In1', [ss '/' in{k}], ...
                  'Position',[40 60+(k-1)*70 75 90+(k-1)*70], 'Port', num2str(k));
    end

    setFcn(ss, 'PID3', [ ...
'function [tau, Inew, eta_e] = PID3(eta_d, eta, nu, Ipre, par)'          newline ...
'%#codegen'                                                              newline ...
'% 3-DOF dynamic positioning controller (Fossen 2011, 12.2.10).'         newline ...
'%'                                                                      newline ...
'%   eta   = [N; E; psi]      position and heading in NED'               newline ...
'%   nu    = [u; v; r]        velocity in BODY'                          newline ...
'%   tau   = -J(psi)'' * (Kp*eta_e + Ki*I) - Kd*nu'                      newline ...
'%'                                                                      newline ...
'% The transpose of the rotation matrix turns a NED position error into' newline ...
'% a BODY force. Damping is taken on BODY velocity directly, so no'      newline ...
'% derivative of the error is needed (same idea as the P-D heading'      newline ...
'% controller of week 7).'                                               newline ...
'%'                                                                      newline ...
'% par = [Kp(1:3); Kd(1:3); Ki(1:3); imax(1:3); Ts]'                     newline ...
''                                                                       newline ...
'Kp = par(1:3);  Kd = par(4:6);  Ki = par(7:9);'                         newline ...
'im = par(10:12); Ts = par(13);'                                         newline ...
''                                                                       newline ...
'e = eta - eta_d;'                                                       newline ...
'e(3) = atan2(sin(e(3)), cos(e(3)));      % smallest signed angle'       newline ...
''                                                                       newline ...
'psi = eta(3);'                                                          newline ...
'J = [ cos(psi), -sin(psi), 0;'                                          newline ...
'      sin(psi),  cos(psi), 0;'                                          newline ...
'             0,         0, 1];'                                         newline ...
''                                                                       newline ...
'% integral state with clamping (anti-windup)'                           newline ...
'Inew = Ipre + Ts*e;'                                                    newline ...
'for i = 1:3'                                                            newline ...
'    lim = im(i)/max(Ki(i), 1e-9);'                                      newline ...
'    if Inew(i) >  lim, Inew(i) =  lim; end'                             newline ...
'    if Inew(i) < -lim, Inew(i) = -lim; end'                             newline ...
'end'                                                                    newline ...
''                                                                       newline ...
'tau = -J'' * ( Kp.*e + Ki.*Inew ) - Kd.*nu;'                            newline ...
'eta_e = e;']);
    set_param([ss '/PID3'],'Position',[220 70 420 400]);

    out = {'tau','Inew','eta_e'};
    for k = 1:numel(out)
        add_block('simulink/Sinks/Out1', [ss '/' out{k}], ...
                  'Position',[520 80+(k-1)*90 555 110+(k-1)*90], 'Port', num2str(k));
        add_line(ss, sprintf('PID3/%d',k), [out{k} '/1'], 'autorouting','on');
    end
    for k = 1:numel(in)
        add_line(ss, [in{k} '/1'], sprintf('PID3/%d',k), 'autorouting','on');
    end
    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 3단 · 추력 배분
% =====================================================================
function addAlloc(m, x, y)
    ss = [m '/Alloc'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+190 y+180]);

    in = {'tau','Tp','lim'};
    for k = 1:numel(in)
        add_block('simulink/Sources/In1', [ss '/' in{k}], ...
                  'Position',[40 60+(k-1)*80 75 90+(k-1)*80], 'Port', num2str(k));
    end

    setFcn(ss, 'Allocate', [ ...
'function [Tcmd, Dcmd, sat] = Allocate(tau, Tp, lim)'                     newline ...
'%#codegen'                                                               newline ...
'% Thrust allocation for two azimuth (rotatable) thrusters.'              newline ...
'% Fossen (2011) 12.3.4 — constrained control allocation for azimuth'     newline ...
'% thrusters, solved with the EXTENDED THRUST VECTOR.'                    newline ...
'%'                                                                       newline ...
'% Step 1  f = pinv(T_e) * tau       f = [FxL FyL FxR FyR]'''             newline ...
'%         Because the thruster force is written in Cartesian components,' newline ...
'%         T_e is CONSTANT and its pseudo-inverse can be precomputed.'    newline ...
'%         There is no singular configuration to worry about.'            newline ...
'%'                                                                       newline ...
'% Step 2  Cartesian -> polar   T = |f_i|,  delta = atan2(Fy, Fx)'        newline ...
'%'                                                                       newline ...
'% Step 3  map the demand into the mechanical sector |delta| <= 45 deg'   newline ...
'%           |d| <=  45  : use as is'                                     newline ...
'%           |d| >  135  : REVERSE thrust, d -> d -+ 180'                 newline ...
'%           otherwise   : dead zone, no thrust can be produced'          newline ...
'%'                                                                       newline ...
'% Step 4  saturate the magnitude at F_max'                               newline ...
'%'                                                                       newline ...
'% lim = [F_max; delta_max; mode]'                                        newline ...
'%   mode 1 : dead zone   — demands inside the forbidden sector are'      newline ...
'%            dropped. Simple, but the realised tau is then wrong.'       newline ...
'%   mode 2 : clamp       — the angle is pushed to the nearest sector'     newline ...
'%            edge and the magnitude is scaled by cos of the angle'       newline ...
'%            error, so the useful component is kept.'                    newline ...
''                                                                        newline ...
'f = Tp * tau;'                                                           newline ...
'Fmax = lim(1);  dmax = lim(2);  mode = lim(3);'                          newline ...
''                                                                        newline ...
'Tcmd = zeros(2,1);  Dcmd = zeros(2,1);  sat = 0;'                        newline ...
'for i = 1:2'                                                             newline ...
'    fx = f(2*i-1);  fy = f(2*i);'                                        newline ...
'    Ti = sqrt(fx*fx + fy*fy);'                                           newline ...
'    di = atan2(fy, fx);'                                                 newline ...
'    ad = abs(di);'                                                       newline ...
'    if ad <= dmax'                                                       newline ...
'        To = Ti;   Do = di;'                                             newline ...
'    elseif ad >= pi - dmax'                                              newline ...
'        To = -Ti;  Do = di - sign(di)*pi;    % reverse thrust'           newline ...
'    elseif mode < 1.5'                                                   newline ...
'        To = 0;    Do = 0;                   % dead zone'                newline ...
'        sat = sat + 1;'                                                  newline ...
'    else'                                                                newline ...
'        % clamp to the nearest edge of the reachable sector'             newline ...
'        if ad <= pi/2'                                                   newline ...
'            Do = sign(di)*dmax;      To =  Ti*cos(ad - dmax);'           newline ...
'        else'                                                            newline ...
'            Do = sign(di)*(dmax - pi);  To = -Ti*cos(pi - dmax - ad);'   newline ...
'            Do = atan2(sin(Do), cos(Do));'                               newline ...
'        end'                                                             newline ...
'        sat = sat + 1;'                                                  newline ...
'    end'                                                                 newline ...
'    if To >  Fmax, To =  Fmax; sat = sat + 1; end'                       newline ...
'    if To < -Fmax, To = -Fmax; sat = sat + 1; end'                       newline ...
'    Tcmd(i) = To;  Dcmd(i) = Do;'                                        newline ...
'end']);
    set_param([ss '/Allocate'],'Position',[220 70 420 320]);

    out = {'Tcmd','Dcmd','sat'};
    for k = 1:numel(out)
        add_block('simulink/Sinks/Out1', [ss '/' out{k}], ...
                  'Position',[520 80+(k-1)*90 555 110+(k-1)*90], 'Port', num2str(k));
        add_line(ss, sprintf('Allocate/%d',k), [out{k} '/1'], 'autorouting','on');
    end
    for k = 1:numel(in)
        add_line(ss, [in{k} '/1'], sprintf('Allocate/%d',k), 'autorouting','on');
    end
    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 4단 · 추진기 (모터 + 방위 서보)
% =====================================================================
function addThrusters(m, x, y)
    ss = [m '/Thrusters'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+190 y+180]);

    in = {'Tcmd','Dcmd','Tpre','Dpre','par'};
    for k = 1:numel(in)
        add_block('simulink/Sources/In1', [ss '/' in{k}], ...
                  'Position',[40 60+(k-1)*70 75 90+(k-1)*70], 'Port', num2str(k));
    end

    setFcn(ss, 'Act', [ ...
'function [Tact, Dact, f] = Act(Tcmd, Dcmd, Tpre, Dpre, par)'            newline ...
'%#codegen'                                                              newline ...
'% Actuator dynamics of an azimuth thruster.'                            newline ...
'%   thrust  : first order lag, time constant tau_n'                     newline ...
'%   azimuth : RATE LIMIT first (servo can only turn so fast), then a'   newline ...
'%             first order lag. A real pod cannot snap to a new angle.'  newline ...
'% par = [Ts; tau_n; tau_del; rate_max]'                                 newline ...
''                                                                       newline ...
'Ts = par(1); tn = par(2); td = par(3); rmax = par(4);'                  newline ...
''                                                                       newline ...
'Tact = Tpre + (Ts/tn)*(Tcmd - Tpre);'                                   newline ...
''                                                                       newline ...
'Dact = Dpre;'                                                           newline ...
'for i = 1:2'                                                            newline ...
'    dd = Dcmd(i) - Dpre(i);'                                            newline ...
'    dd = atan2(sin(dd), cos(dd));           % shortest way round'       newline ...
'    lim = rmax*Ts;'                                                     newline ...
'    if dd >  lim, dd =  lim; end'                                       newline ...
'    if dd < -lim, dd = -lim; end'                                       newline ...
'    Dact(i) = Dpre(i) + (Ts/td)*dd;'                                    newline ...
'end'                                                                    newline ...
''                                                                       newline ...
'% back to Cartesian components in BODY'                                 newline ...
'f = [ Tact(1)*cos(Dact(1));'                                            newline ...
'      Tact(1)*sin(Dact(1));'                                            newline ...
'      Tact(2)*cos(Dact(2));'                                            newline ...
'      Tact(2)*sin(Dact(2)) ];']);
    set_param([ss '/Act'],'Position',[220 70 420 380]);

    out = {'Tact','Dact','f'};
    for k = 1:numel(out)
        add_block('simulink/Sinks/Out1', [ss '/' out{k}], ...
                  'Position',[520 80+(k-1)*90 555 110+(k-1)*90], 'Port', num2str(k));
        add_line(ss, sprintf('Act/%d',k), [out{k} '/1'], 'autorouting','on');
    end
    for k = 1:numel(in)
        add_line(ss, [in{k} '/1'], sprintf('Act/%d',k), 'autorouting','on');
    end
    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 5단 · 외란 (바람 + 파랑)
% =====================================================================
function addEnv(m, x, y)
    ss = [m '/Env'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+190 y+180]);

    in = {'t','nu','psi','wpar','wvpar'};
    for k = 1:numel(in)
        add_block('simulink/Sources/In1', [ss '/' in{k}], ...
                  'Position',[40 60+(k-1)*70 75 90+(k-1)*70], 'Port', num2str(k));
    end

    setFcn(ss, 'Dist', [ ...
'function [tau_env, tau_w, tau_v] = Dist(t, nu, psi, wpar, wvpar)'       newline ...
'%#codegen'                                                              newline ...
'% Environmental loads in BODY axes.'                                    newline ...
'%'                                                                      newline ...
'% WIND  — Jin et al. (2025) Eq. (11)-(19); Fossen (2011) 8.1'           newline ...
'%   relative wind in BODY :'                                            newline ...
'%     u_rw = u - Vw cos(beta_w - psi)'                                  newline ...
'%     v_rw = v - Vw sin(beta_w - psi)'                                  newline ...
'%   q     = 0.5 rho_a Vrw^2'                                            newline ...
'%   tau_w = q * [ CX*AFw ; CY*ALw ; CN*ALw*L ]'                         newline ...
'%   CX = -cx cos(g), CY = -cy sin(g), CN = cn sin(2g)'                  newline ...
'%'                                                                      newline ...
'% WAVE  — first order approximation. Component amplitudes come from a'  newline ...
'%   Bretschneider spectrum (Jin et al. Eq. (21)-(25)); the force is'    newline ...
'%   taken proportional to the surface elevation with a single gain.'    newline ...
'%   This is an approximation, not a diffraction calculation.'           newline ...
'%'                                                                      newline ...
'% wpar  = [on; Vw; beta_w; rho_a; AFw; ALw; L; cx; cy; cn]'             newline ...
'% wvpar = [on; k_wave; theta_m; arm; w1..wn; A1..An; p1..pn]'           newline ...
''                                                                       newline ...
'u = nu(1); v = nu(2);'                                                  newline ...
'tau_w = zeros(3,1);'                                                    newline ...
'if wpar(1) > 0.5'                                                       newline ...
'    Vw = wpar(2); bw = wpar(3); rho = wpar(4);'                         newline ...
'    AF = wpar(5); AL = wpar(6); L = wpar(7);'                           newline ...
'    cx = wpar(8); cy = wpar(9); cn = wpar(10);'                         newline ...
'    urw = u - Vw*cos(bw - psi);'                                        newline ...
'    vrw = v - Vw*sin(bw - psi);'                                        newline ...
'    Vrw = sqrt(urw*urw + vrw*vrw);'                                     newline ...
'    g   = -atan2(vrw, urw);'                                            newline ...
'    q   = 0.5*rho*Vrw*Vrw;'                                             newline ...
'    tau_w = q * [ -cx*cos(g)*AF;'                                       newline ...
'                  -cy*sin(g)*AL;'                                       newline ...
'                   cn*sin(2*g)*AL*L ];'                                 newline ...
'end'                                                                    newline ...
''                                                                       newline ...
'tau_v = zeros(3,1);'                                                    newline ...
'if wvpar(1) > 0.5'                                                      newline ...
'    kw = wvpar(2); th = wvpar(3); arm = wvpar(4);'                      newline ...
'    n  = (numel(wvpar) - 4)/3;'                                         newline ...
'    zeta = 0;'                                                          newline ...
'    for i = 1:n'                                                        newline ...
'        wi = wvpar(4+i);'                                               newline ...
'        Ai = wvpar(4+n+i);'                                             newline ...
'        pi_i = wvpar(4+2*n+i);'                                         newline ...
'        zeta = zeta + Ai*sin(wi*t + pi_i);'                             newline ...
'    end'                                                                newline ...
'    rel = th - psi;                          % wave direction in BODY'  newline ...
'    Fw  = kw*zeta;'                                                     newline ...
'    tau_v = [ Fw*cos(rel); Fw*sin(rel); arm*Fw*sin(rel) ];'             newline ...
'end'                                                                    newline ...
''                                                                       newline ...
'tau_env = tau_w + tau_v;']);
    set_param([ss '/Dist'],'Position',[220 70 420 420]);

    out = {'tau_env','tau_w','tau_v'};
    for k = 1:numel(out)
        add_block('simulink/Sinks/Out1', [ss '/' out{k}], ...
                  'Position',[520 80+(k-1)*90 555 110+(k-1)*90], 'Port', num2str(k));
        add_line(ss, sprintf('Dist/%d',k), [out{k} '/1'], 'autorouting','on');
    end
    for k = 1:numel(in)
        add_line(ss, [in{k} '/1'], sprintf('Dist/%d',k), 'autorouting','on');
    end
    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 6단 · 운동모델
% =====================================================================
function addMotionModel(m, x, y)
    ss = [m '/MotionModel'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+200 y+180]);

    in = {'f','tau_env','Te','par'};
    for k = 1:numel(in)
        add_block('simulink/Sources/In1', [ss '/' in{k}], ...
                  'Position',[40 60+(k-1)*80 75 90+(k-1)*80], 'Port', num2str(k));
    end

    setFcn(ss, 'EOM', [ ...
'function [xdot, tau_thr] = EOM(s, f, tau_env, Te, p)'                   newline ...
'%#codegen'                                                              newline ...
'% 3-DOF WAM-V equations of motion, NED — same coefficients as weeks'    newline ...
'% 7 to 9 (taken from the Gazebo VRX plugins).'                          newline ...
'% The only change is the input: the thruster force now has a sway'      newline ...
'% component, so all three degrees of freedom are actuated.'             newline ...
'%   s = [u v r N E psi]'''                                              newline ...
'%   p = [m Izz Xu Xuu Yv Yvv Nr Nrr]'''                                 newline ...
''                                                                       newline ...
'u = s(1); v = s(2); r = s(3); psi = s(6);'                              newline ...
'mm=p(1); Izz=p(2); Xu=p(3); Xuu=p(4); Yv=p(5); Yvv=p(6);'               newline ...
'Nr=p(7); Nrr=p(8);'                                                     newline ...
''                                                                       newline ...
'tau_thr = Te*f;                 % [X; Y; N] from the thrusters'         newline ...
'tau     = tau_thr + tau_env;'                                           newline ...
''                                                                       newline ...
'Dx = (Xu + Xuu*abs(u))*u;'                                              newline ...
'Dy = (Yv + Yvv*abs(v))*v;'                                              newline ...
'Dn = (Nr + Nrr*abs(r))*r;'                                              newline ...
''                                                                       newline ...
'du = (tau(1) - Dx)/mm + v*r;    % rigid-body Coriolis'                  newline ...
'dv = (tau(2) - Dy)/mm - u*r;'                                           newline ...
'dr = (tau(3) - Dn)/Izz;'                                                newline ...
''                                                                       newline ...
'xdot = [du; dv; dr;'                                                    newline ...
'        u*cos(psi) - v*sin(psi);'                                       newline ...
'        u*sin(psi) + v*cos(psi);'                                       newline ...
'        r];']);
    set_param([ss '/EOM'],'Position',[220 60 420 380]);

    add_block('simulink/Continuous/Integrator', [ss '/Integ'], ...
              'Position', [480 180 530 230], 'InitialCondition','x0');

    setFcn(ss, 'States', [ ...
'function [eta, nu, U, beta] = States(s)'                    newline ...
'%#codegen'                                                  newline ...
'nu   = s(1:3);'                                             newline ...
'eta  = s(4:6);'                                             newline ...
'U    = sqrt(s(1)*s(1) + s(2)*s(2));'                        newline ...
'beta = atan2(s(2), s(1));']);
    set_param([ss '/States'],'Position',[600 120 750 300]);

    out = {'eta','nu','U','beta','tau_thr'};
    for k = 1:numel(out)
        add_block('simulink/Sinks/Out1', [ss '/' out{k}], ...
                  'Position',[830 90+(k-1)*70 870 120+(k-1)*70], 'Port', num2str(k));
    end
    for k = 1:4
        add_line(ss, sprintf('States/%d',k), [out{k} '/1'], 'autorouting','on');
    end
    add_line(ss,'EOM/2','tau_thr/1','autorouting','on');

    for k = 1:numel(in)
        add_line(ss, [in{k} '/1'], sprintf('EOM/%d', k+1), 'autorouting','on');
    end
    add_line(ss,'EOM/1','Integ/1','autorouting','on');
    add_line(ss,'Integ/1','States/1','autorouting','on');
    add_line(ss,'Integ/1','EOM/1','autorouting','on');
    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 실시간 그림
% =====================================================================
function addAnimate(m, x, y)
    add_block('simulink/Sources/Digital Clock', [m '/Clk2'], ...
              'Position', [x y+160 x+50 y+190], 'SampleTime','Ts_ctrl');
    C(m,'Anim','animate', x, y+220);

    F(m,'eta','v',   x, y);
    F(m,'eta_d','v', x, y+40);
    F(m,'Dact','v',  x, y+80);
    F(m,'Tact','v',  x, y+120);

    setFcn(m, 'Animate', [ ...
'function ok = Animate(eta, eta_d, Dact, Tact, t, en)'                 newline ...
'%#codegen'                                                            newline ...
'coder.extrinsic(''W10_animate'');'                                    newline ...
'ok = 1;'                                                              newline ...
'if en > 0.5'                                                          newline ...
'    W10_animate(eta, eta_d, Dact, Tact, t);'                          newline ...
'end']);
    set_param([m '/Animate'],'Position',[x+150 y x+300 y+230]);

    add_block('simulink/Sinks/Terminator', [m '/AnimEnd'], ...
              'Position', [x+350 y+100 x+375 y+125]);

    add_line(m,'Fr_eta_v/1',  'Animate/1','autorouting','on');
    add_line(m,'Fr_eta_d_v/1','Animate/2','autorouting','on');
    add_line(m,'Fr_Dact_v/1', 'Animate/3','autorouting','on');
    add_line(m,'Fr_Tact_v/1', 'Animate/4','autorouting','on');
    add_line(m,'Clk2/1','Animate/5','autorouting','on');
    add_line(m,'Anim/1','Animate/6','autorouting','on');
    add_line(m,'Animate/1','AnimEnd/1','autorouting','on');
end

% =====================================================================
% 로깅
% =====================================================================
function addLogging(m, x, y)
    sig = {'eta','eta_d','eta_raw','eta_f','nu','eta_e','tau_cmd','tau_thr','tau_env', ...
           'Tact','Dact','sat','U','beta'};
    for k = 1:numel(sig)
        yy = y + (k-1)*55;
        F(m, sig{k}, 'log', x, yy+3);
        b = [m '/log_' sig{k}];
        add_block('simulink/Sinks/To Workspace', b, 'Position', [x+130 yy x+230 yy+30]);
        set_param(b, 'VariableName', ['log_' sig{k}], ...
                     'SaveFormat','Timeseries', 'SampleTime','Ts_ctrl');
        add_line(m, ['Fr_' sig{k} '_log/1'], ['log_' sig{k} '/1'], 'autorouting','on');
    end
end

% =====================================================================
% 앞단 배선 — 두 모델이 공유한다
% =====================================================================
function wireFront(m)
    % --- 목표값 ---
    add_block('simulink/Sources/Digital Clock', [m '/Clk'], ...
              'Position',[40 40 90 70], 'SampleTime','Ts_ctrl');
    C(m,'DpMode','dp_mode', 40, 110);
    C(m,'DpTbl', 'dp_step', 40, 170);
    C(m,'Eta0',  '[dp_N0; dp_E0; dp_PSI0]', 40, 230);

    C(m,'RefPar','[dp_ref_on; dp_vmax; tau_ref; Ts_ctrl]', 40, 290);
    add_block('simulink/Discrete/Unit Delay', [m '/Rdly'], ...
              'Position',[260 300 305 340], 'SampleTime','Ts_ctrl', ...
              'InitialCondition','[dp_N0; dp_E0; dp_PSI0]');

    addDPRef(m, 400, 60);
    add_line(m,'Clk/1',   'DPRef/1','autorouting','on');
    add_line(m,'DpMode/1','DPRef/2','autorouting','on');
    add_line(m,'DpTbl/1', 'DPRef/3','autorouting','on');
    add_line(m,'Eta0/1',  'DPRef/4','autorouting','on');
    add_line(m,'Rdly/1',  'DPRef/5','autorouting','on');
    add_line(m,'RefPar/1','DPRef/6','autorouting','on');
    add_line(m,'DPRef/2','Rdly/1','autorouting','on');
    G(m,'eta_d',   620, 100);
    G(m,'eta_raw', 620, 160);
    add_line(m,'DPRef/1','Go_eta_d/1','autorouting','on');
    add_line(m,'DPRef/3','Go_eta_raw/1','autorouting','on');

    % --- 파랑 필터 ---
    addWaveFilter(m, 300, 400);
    F(m,'eta','f', 200, 420);
    F(m,'nu','f',  200, 470);
    add_block('simulink/Discrete/Unit Delay', [m '/Fdly'], ...
              'Position',[300 640 345 680], 'SampleTime','Ts_ctrl', ...
              'InitialCondition','[0;0;0;0;0;0]');
    C(m,'FiltPar','[filt_on; w_filt; Ts_ctrl]', 180, 540);
    add_line(m,'Fr_eta_f/1','WaveFilter/1','autorouting','on');
    add_line(m,'Fr_nu_f/1', 'WaveFilter/2','autorouting','on');
    add_line(m,'Fdly/1',    'WaveFilter/3','autorouting','on');
    add_line(m,'FiltPar/1', 'WaveFilter/4','autorouting','on');
    add_line(m,'WaveFilter/3','Fdly/1','autorouting','on');
    G(m,'eta_f', 520, 420);
    G(m,'nu_f',  520, 470);
    add_line(m,'WaveFilter/1','Go_eta_f/1','autorouting','on');
    add_line(m,'WaveFilter/2','Go_nu_f/1','autorouting','on');

    % --- 제어기 ---
    addDPCtrl(m, 620, 60);
    F(m,'eta_d','c', 540, 80);
    F(m,'eta_f','c', 540, 140);
    F(m,'nu_f','c',  540, 200);
    add_block('simulink/Discrete/Unit Delay', [m '/Idly'], ...
              'Position',[620 400 665 440], 'SampleTime','Ts_ctrl', ...
              'InitialCondition','[0;0;0]');
    C(m,'DpPar','[diag(Kp_dp); diag(Kd_dp); diag(Ki_dp); i_max; Ts_ctrl]', 540, 300);

    add_line(m,'Fr_eta_d_c/1','DPCtrl/1','autorouting','on');
    add_line(m,'Fr_eta_f_c/1','DPCtrl/2','autorouting','on');
    add_line(m,'Fr_nu_f_c/1', 'DPCtrl/3','autorouting','on');
    add_line(m,'Idly/1',      'DPCtrl/4','autorouting','on');
    add_line(m,'DpPar/1',     'DPCtrl/5','autorouting','on');
    add_line(m,'DPCtrl/2','Idly/1','autorouting','on');
    G(m,'tau_cmd', 860, 100);
    G(m,'eta_e',   860, 160);
    add_line(m,'DPCtrl/1','Go_tau_cmd/1','autorouting','on');
    add_line(m,'DPCtrl/3','Go_eta_e/1','autorouting','on');

    % --- 배분 ---
    addAlloc(m, 1020, 60);
    F(m,'tau_cmd','a', 940, 80);
    C(m,'Tpinv','T_pinv', 940, 150);
    C(m,'AlLim','[F_max; del_max; alloc_mode]', 940, 210);
    add_line(m,'Fr_tau_cmd_a/1','Alloc/1','autorouting','on');
    add_line(m,'Tpinv/1','Alloc/2','autorouting','on');
    add_line(m,'AlLim/1','Alloc/3','autorouting','on');
    G(m,'Tcmd', 1260, 100);
    G(m,'Dcmd', 1260, 160);
    G(m,'sat',  1260, 220);
    add_line(m,'Alloc/1','Go_Tcmd/1','autorouting','on');
    add_line(m,'Alloc/2','Go_Dcmd/1','autorouting','on');
    add_line(m,'Alloc/3','Go_sat/1','autorouting','on');

    % --- 추진기 ---
    addThrusters(m, 1420, 60);
    F(m,'Tcmd','t', 1340, 80);
    F(m,'Dcmd','t', 1340, 140);
    add_block('simulink/Discrete/Unit Delay', [m '/Tdly'], ...
              'Position',[1420 420 1465 460], 'SampleTime','Ts_ctrl', ...
              'InitialCondition','[0;0]');
    add_block('simulink/Discrete/Unit Delay', [m '/Ddly'], ...
              'Position',[1420 490 1465 530], 'SampleTime','Ts_ctrl', ...
              'InitialCondition','[0;0]');
    C(m,'ActPar','[Ts_ctrl; tau_n; tau_del; del_rate]', 1340, 260);

    add_line(m,'Fr_Tcmd_t/1','Thrusters/1','autorouting','on');
    add_line(m,'Fr_Dcmd_t/1','Thrusters/2','autorouting','on');
    add_line(m,'Tdly/1','Thrusters/3','autorouting','on');
    add_line(m,'Ddly/1','Thrusters/4','autorouting','on');
    add_line(m,'ActPar/1','Thrusters/5','autorouting','on');
    add_line(m,'Thrusters/1','Tdly/1','autorouting','on');
    add_line(m,'Thrusters/2','Ddly/1','autorouting','on');
    G(m,'Tact', 1680, 100);
    G(m,'Dact', 1680, 160);
    G(m,'fthr', 1680, 220);
    add_line(m,'Thrusters/1','Go_Tact/1','autorouting','on');
    add_line(m,'Thrusters/2','Go_Dact/1','autorouting','on');
    add_line(m,'Thrusters/3','Go_fthr/1','autorouting','on');
end

% =====================================================================
% 오프라인 모델
% =====================================================================
function build_offline()
    m = 'W10_0_offline'; fresh(m);
    setSolver(m, 'T_end');

    wireFront(m);

    % --- 외란 ---
    addEnv(m, 1820, 460);
    add_block('simulink/Sources/Digital Clock', [m '/Clk3'], ...
              'Position',[1740 480 1790 510], 'SampleTime','Ts_ctrl');
    F(m,'nu','e',  1740, 540);
    F(m,'psi','e', 1740, 600);
    C(m,'WPar', '[wind_on; wind_speed; wind_dir; rho_air; A_Fw; A_Lw; L_oa; c_x; c_y; c_n]', 1700, 660);
    C(m,'WvPar','[wave_on; k_wave; wave_dir; lw_arm; wave_par(:,1); wave_par(:,2); wave_par(:,3)]', 1700, 720);
    add_line(m,'Clk3/1','Env/1','autorouting','on');
    add_line(m,'Fr_nu_e/1','Env/2','autorouting','on');
    add_line(m,'Fr_psi_e/1','Env/3','autorouting','on');
    add_line(m,'WPar/1','Env/4','autorouting','on');
    add_line(m,'WvPar/1','Env/5','autorouting','on');
    G(m,'tau_env', 2080, 500);
    add_line(m,'Env/1','Go_tau_env/1','autorouting','on');

    % --- 운동모델 ---
    addMotionModel(m, 2200, 60);
    F(m,'fthr','p',   2110, 80);
    F(m,'tau_env','p',2110, 140);
    C(m,'TeC','T_e', 2110, 200);
    C(m,'PlPar','plant_par', 2110, 260);
    add_line(m,'Fr_fthr_p/1','MotionModel/1','autorouting','on');
    add_line(m,'Fr_tau_env_p/1','MotionModel/2','autorouting','on');
    add_line(m,'TeC/1','MotionModel/3','autorouting','on');
    add_line(m,'PlPar/1','MotionModel/4','autorouting','on');

    tags = {'eta','nu','U','beta','tau_thr'};
    for k = 1:numel(tags)
        G(m, tags{k}, 2470, 80+(k-1)*55);
        add_line(m, sprintf('MotionModel/%d',k), ['Go_' tags{k} '/1'], 'autorouting','on');
    end

    % psi 만 따로 뽑아 외란 계산에 쓴다
    F(m,'eta','s', 2470, 400);
    add_block('simulink/Signal Routing/Selector', [m '/PsiSel'], ...
              'Position',[2570 395 2620 435]);
    set_param([m '/PsiSel'],'NumberOfDimensions','1', ...
              'IndexOptions','Index vector (dialog)','Indices','3', ...
              'InputPortWidth','3');
    G(m,'psi', 2680, 400);
    add_line(m,'Fr_eta_s/1','PsiSel/1','autorouting','on');
    add_line(m,'PsiSel/1','Go_psi/1','autorouting','on');

    addAnimate(m, 2200, 560);
    addLogging(m, 2800, 60);

    note(m,'n1', ['W10 실습 A  —  오프라인 DP (Gazebo 불필요)' newline ...
        'DPRef -> DPCtrl -> Alloc -> Thrusters -> MotionModel(+Env)' newline ...
        '후방 2기가 ±45° 로 돌아가므로 3자유도가 모두 제어된다.' newline ...
        '바람·파랑 외란은 이 모델에서만 넣을 수 있다.' newline ...
        '실행 전 >> W10_setup'], 40, -140);

    save_system(m); close_system(m);
    fprintf('  W10_0_offline  생성\n');
end

% =====================================================================
% VRX 모델
% =====================================================================
function build_vrx()
    m = 'W10_1_vrx'; fresh(m);
    load_system('ros2lib');
    setSolver(m, 'T_end');

    wireFront(m);

    % --- 추력·각도 발행 ---
    addPub(m, 'left',  'L', 1, 1820, 60);
    addPub(m, 'right', 'R', 2, 1820, 320);

    % --- 구독 + 항법 ---
    add_block('ros2lib/Subscribe', [m '/OdomSub'], 'Position',[1820 700 1950 760]);
    set_param([m '/OdomSub'], 'topicSource','Specify your own', ...
        'topic','/wamv/sensors/position/ground_truth_odometry', ...
        'messageType','nav_msgs/Odometry', 'sampleTime','Ts_ctrl');

    add_block('simulink/Signal Routing/Bus Selector', [m '/Sel'], ...
              'Position',[2010 680 2060 810]);
    set_param([m '/Sel'], 'OutputSignals', ...
        ['pose.pose.position.x,pose.pose.position.y,' ...
         'pose.pose.orientation.x,pose.pose.orientation.y,' ...
         'pose.pose.orientation.z,pose.pose.orientation.w,' ...
         'twist.twist.linear.x,twist.twist.linear.y,twist.twist.angular.z']);
    add_block('simulink/Sinks/Display', [m '/IsNew'], 'Position',[2010 620 2090 650]);
    add_line(m,'OdomSub/1','IsNew/1','autorouting','on');
    add_line(m,'OdomSub/2','Sel/1','autorouting','on');

    C(m,'OrgN','origin_north', 2010, 870);
    C(m,'OrgE','origin_east',  2010, 930);

    setFcn(m, 'Nav', [ ...
'function [eta, nu, U, beta] = Nav(ex, ey, qx, qy, qz, qw, bx, by, wz, orgN, orgE)' newline ...
'%#codegen'                                                                 newline ...
'% Gazebo/ROS uses ENU with a body frame of x-forward, y-LEFT, z-UP.'       newline ...
'% Marine control uses NED with x-forward, y-STARBOARD, z-DOWN.'            newline ...
'% 첫 메시지가 도착하기 전에는 Subscribe 가 0 으로 채운 버스를 낸다.'       newline ...
'% 그대로 쓰면 위치가 스폰 원점만큼(약 568 m) 튀어 로그 첫 점이 망가진다.'  newline ...
'if ex == 0 && ey == 0'                                                     newline ...
'    eta = zeros(3,1); nu = zeros(3,1); U = 0; beta = 0;'                   newline ...
'    return'                                                                newline ...
'end'                                                                       newline ...
'pn = ey - orgN;'                                                           newline ...
'pe = ex - orgE;'                                                           newline ...
'yaw_enu = atan2(2*(qw*qz + qx*qy), 1 - 2*(qy*qy + qz*qz));'                newline ...
'p   = pi/2 - yaw_enu;'                                                     newline ...
'psi = atan2(sin(p), cos(p));'                                              newline ...
'u = bx;  v = -by;  r = -wz;'                                               newline ...
'eta  = [pn; pe; psi];'                                                     newline ...
'nu   = [u; v; r];'                                                         newline ...
'U    = sqrt(u*u + v*v);'                                                   newline ...
'beta = atan2(v, u);']);
    set_param([m '/Nav'],'Position',[2180 670 2350 890]);

    for k = 1:9
        add_line(m, sprintf('Sel/%d',k), sprintf('Nav/%d',k), 'autorouting','on');
    end
    add_line(m,'OrgN/1','Nav/10','autorouting','on');
    add_line(m,'OrgE/1','Nav/11','autorouting','on');

    tags = {'eta','nu','U','beta'};
    for k = 1:numel(tags)
        G(m, tags{k}, 2420, 680+(k-1)*45);
        add_line(m, sprintf('Nav/%d',k), ['Go_' tags{k} '/1'], 'autorouting','on');
    end

    % VRX 에는 외란 모델을 넣지 않는다 — 바람은 world 가 만든다
    C(m,'ZeroEnv','[0;0;0]', 2420, 900);
    G(m,'tau_env', 2560, 900);
    add_line(m,'ZeroEnv/1','Go_tau_env/1','autorouting','on');
    C(m,'ZeroThr','[0;0;0]', 2420, 960);
    G(m,'tau_thr', 2560, 960);
    add_line(m,'ZeroThr/1','Go_tau_thr/1','autorouting','on');

    addAnimate(m, 2200, 1000);
    addLogging(m, 2800, 60);

    note(m,'n1', ['W10 실습 B  —  VRX 연동 (Gazebo 필요)' newline ...
        'DPRef -> DPCtrl -> Alloc -> Thrusters -> Gazebo -> Navigation' newline ...
        '추력은 thrusters/*/thrust, 방위각은 thrusters/*/pos 로 발행한다.' newline ...
        '제어기·배분·게인은 W10_0_offline 과 완전히 같다.' newline ...
        '외란은 world 선택으로 준다 (바람 있는 world).' newline ...
        '실행: >> W10_setup  ->  >> W10_vrx_run'], 40, -160);

    save_system(m); close_system(m);
    fprintf('  W10_1_vrx      생성\n');
end

function addPub(m, side, tag, idx, x, y)
% 추력 1개 + 방위각 1개를 발행한다
    for j = 1:2
        if j == 1, what = 'thrust'; nm = ['T' tag]; src = 'Tact';
        else,      what = 'pos';    nm = ['D' tag]; src = 'Dact'; end
        yy = y + (j-1)*150;

        F(m, src, [nm '_s'], x-260, yy+20);
        add_block('simulink/Signal Routing/Selector', [m '/Sel' nm], ...
                  'Position',[x-150 yy+15 x-100 yy+55]);
        set_param([m '/Sel' nm],'NumberOfDimensions','1', ...
                  'IndexOptions','Index vector (dialog)','Indices', num2str(idx), ...
                  'InputPortWidth','2');

        add_block('ros2lib/Blank Message', [m '/Blank' nm], ...
                  'Position',[x yy x+100 yy+40]);
        set_param([m '/Blank' nm], 'entityType','std_msgs/Float64', ...
                  'messageType','std_msgs/Float64', 'SampleTime','Ts_ctrl');
        add_block('simulink/Signal Routing/Bus Assignment', [m '/Asg' nm], ...
                  'Position',[x+160 yy x+220 yy+115]);
        set_param([m '/Asg' nm], 'AssignedSignals','data');
        add_block('ros2lib/Publish', [m '/Pub' nm], ...
                  'Position',[x+290 yy+35 x+390 yy+75]);
        set_param([m '/Pub' nm], 'topicSource','Specify your own', ...
                  'topic', ['/wamv/thrusters/' side '/' what], ...
                  'messageType','std_msgs/Float64');

        add_line(m, ['Fr_' src '_' nm '_s/1'], ['Sel' nm '/1'], 'autorouting','on');
        add_line(m, ['Blank' nm '/1'], ['Asg' nm '/1'], 'autorouting','on');
        if j == 1
            add_line(m, ['Sel' nm '/1'], ['Asg' nm '/2'], 'autorouting','on');
        else
            % VRX 의 pos 는 Gazebo 의 ENU 선체계(x 전방, y 좌현) 기준 관절각이다.
            % 이 모델의 delta 는 NED 선체계(y 우현) 기준이므로 부호가 반대다.
            % 이 Gain 을 빼면 횡방향·요 되먹임의 부호가 뒤집혀 DP 가 발산한다.
            add_block('simulink/Math Operations/Gain', [m '/Neg' nm], ...
                      'Gain','-1', 'Position',[x-60 yy+15 x-20 yy+45]);
            add_line(m, ['Sel' nm '/1'], ['Neg' nm '/1'], 'autorouting','on');
            add_line(m, ['Neg' nm '/1'], ['Asg' nm '/2'], 'autorouting','on');
        end
        add_line(m, ['Asg' nm '/1'],   ['Pub' nm '/1'], 'autorouting','on');
    end
end
