function build_w09_models()
% BUILD_W09_MODELS  9주차 Simulink 모델 2개를 생성한다.
%
%     W09_0_offline.slx   오프라인 — Gazebo 없이 돈다
%     W09_1_vrx.slx       VRX 연동
%
%   임무:  웨이포인트 항주  →  지정한 점에서 로이터링  →  다시 웨이포인트
%   이 전환을 Stateflow 상태기계가 관리한다.
%
%   구조
%     WpManager  ─┐
%     LoiterVF   ─┼→ ModeSwitch → Inner Loop → Thrusters → 운동모델
%     TurnCount  ─┤
%     MissionFSM ─┘   (Stateflow)
%
%   7·8주차에서 그대로 가져온 것
%     InnerLoop, Thrusters, MotionModel, Animate, LOS, LoiterVF, TurnCount
%   새로 만든 것
%     MissionFSM (Stateflow), WpManager, ModeSwitch
%
%   실행 전에 반드시 >> W09_setup 을 먼저 실행할 것.

    here = fileparts(mfilename('fullpath'));
    addpath(fullfile(here, '..', '..', '_tools'));
    cd(here);

    if evalin('base', '~exist(''loiter_wp'',''var'')')
        error('먼저 W09_setup 을 실행하십시오.');
    end

    build_offline();
    build_vrx();
    % 최상위 배치 — autorouting 에 맡기지 않고 규칙대로 직접 놓는다.
    % 겹침 0 · 블록관통 0 · 꺾임3회+ 0 이 합격선 (references/line-routing.md)
    lay_chain('W09_0_offline', {'Guidance','Mission','InnerLoop','Thrusters','MotionModel'}, ...
              'Boxes', {'Animate','Logging'}, 'Wrap', 3);
    lay_chain('W09_1_vrx', {'Guidance','Mission','InnerLoop','Thrusters', ...
                            'CmdPublisher','PoseSubscriber'}, ...
              'Boxes', {'Animate','Logging'}, 'Wrap', 2);

    %  색 — 역할표는 _tools/gnc_roles.m 하나뿐이다. 빌더는 부르기만 한다
    for mm = {'W09_0_offline','W09_1_vrx'}
        m = mm{1}; load_system(m);
        paint_roles(m);
        check_colour(m);
        mss_style(m); save_system(m); check_lines(m, false); export_diagram(m);
        close_system(m, 0);
    end
    fprintf('\n완료. 생성된 모델:\n');
    d = dir('W09_*.slx');
    for k = 1:numel(d), fprintf('  %s\n', d(k).name); end
end

% =====================================================================
% 공통 헬퍼
% =====================================================================
function fresh(m)
    try, close_system(m, 0); catch, end
    if exist([m '.slx'],'file'), delete([m '.slx']); end
    new_system(m);
end

function setFcn(sys, path, code)
    S  = sfroot;
    ch = S.find('-isa','Stateflow.EMChart','Path',[sys '/' path]);
    ch.Script = code;
end

function C(m, name, value, x, y)
    add_block('simulink/Sources/Constant', [m '/' name], ...
              'Position', [x y x+95 y+30], 'Value', value);
end

function F(m, tag, sfx, x, y)
    add_block('simulink/Signal Routing/From', [m '/Fr_' tag '_' sfx], ...
              'Position', [x y x+70 y+25], 'GotoTag', tag);
end

function G(m, tag, x, y)
    add_block('simulink/Signal Routing/Goto', [m '/Go_' tag], ...
              'Position', [x y x+80 y+25], 'GotoTag', tag, 'TagVisibility','global');
end

function note(m, tag, txt, x, y)
    add_block('built-in/Note', [m '/' tag], 'Position',[x y x y], 'Text', txt);
end

% =====================================================================
% 1단 · 유도 — 웨이포인트 관리 + LOS + 로이터 벡터필드
% =====================================================================
function addGuidance(m, x, y)
% 1단 · GUIDANCE — 웨이포인트 유도와 로이터 유도를 한 상자에.
%
%   포트   pn, pe, beta, mode  ->  psi_los, psi_lo, at_loiter, at_end, turns
%
%   두 유도법칙이 **동시에** 돈다. 어느 쪽을 쓸지는 미션 상자가 고른다.
%   그래서 유도는 둘 다 계산해 내놓기만 하고, 판단은 하지 않는다.
%
%   안에 들어가는 것
%     WpManager  웨이포인트 관리 + LOS (7주차)
%     LoiterVF   원 궤도 벡터필드   (8주차)
%     TurnCount  몇 바퀴 돌았는지
%     설정 상수와 한 스텝 지연들
    ss = add_subsys(m, 'Guidance', [x y x+190 y+200], ...
                    {'pn','pe','beta','mode'}, ...
                    {'psi_los','psi_lo','at_loiter','at_end','turns'}, ...
                    gnc_colour('guidance'));

    % ---- 웨이포인트 관리 + LOS (7주차 유도를 확장한 것) ----
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/WpManager'], 'Position', [520 50 760 550]);
    setFcn(ss, 'WpManager', [ ...
'function [psi_los, y_e, idx, at_loiter, at_end] = WpManager( ...'          newline ...
'         pn, pe, wp_n, wp_e, Delta, R, loiter_wp, mode, idx_prev)'         newline ...
'%#codegen'                                                                 newline ...
'% Waypoint bookkeeping plus LOS guidance (week 7).'                        newline ...
'%   idx = index of the leg START. The leg runs wp(idx) -> wp(idx+1).'      newline ...
'%   The index only advances while the mission is in waypoint mode,'        newline ...
'%   so a loiter never makes the boat skip a leg.'                          newline ...
''                                                                          newline ...
'n = numel(wp_n);'                                                          newline ...
'k = min(max(idx_prev, 1), n-1);'                                           newline ...
''                                                                          newline ...
'xk  = wp_n(k);    yk  = wp_e(k);'                                          newline ...
'xk1 = wp_n(k+1);  yk1 = wp_e(k+1);'                                        newline ...
''                                                                          newline ...
'pi_p = atan2(yk1 - yk, xk1 - xk);'                                         newline ...
'y_e  = -(pn - xk)*sin(pi_p) + (pe - yk)*cos(pi_p);'                        newline ...
'psi_los = pi_p - atan(y_e / Delta);'                                       newline ...
''                                                                          newline ...
'd_next  = sqrt((xk1 - pn)^2 + (yk1 - pe)^2);'                              newline ...
'reached = d_next <= R;'                                                    newline ...
''                                                                          newline ...
'% arriving at the loiter waypoint, and arriving at the last one'           newline ...
'if reached && ((k+1) == loiter_wp)'                                        newline ...
'    at_loiter = 1;'                                                        newline ...
'else'                                                                      newline ...
'    at_loiter = 0;'                                                        newline ...
'end'                                                                       newline ...
'if reached && (k == n-1)'                                                  newline ...
'    at_end = 1;'                                                           newline ...
'else'                                                                      newline ...
'    at_end = 0;'                                                           newline ...
'end'                                                                       newline ...
''                                                                          newline ...
'% advance only in waypoint mode'                                           newline ...
'if (mode < 1.5) && reached && (k < n-1)'                                   newline ...
'    idx = k + 1;'                                                          newline ...
'else'                                                                      newline ...
'    idx = k;'                                                              newline ...
'end']);

    % 웨이포인트 인덱스는 유도부 안의 기억이다. 태그로 자기에게 되돌린다
    drop_tag(ss, 'WpManager', 3, 'wp_idx', 150);
    q = port_xy(ss, 'WpManager', 'Inport', 9);
    add_block('simulink/Discrete/Unit Delay', [ss '/IdxDly'], ...
              'Position', [x+60 q(2)-20 x+135 q(2)+20], ...
              'InitialCondition','1', 'SampleTime','Ts_ctrl');
    add_block('simulink/Signal Routing/From', [ss '/Fr_wp_idx'], ...
              'Position', [x-60 q(2)-11 x+10 q(2)+11], 'GotoTag','wp_idx');
    add_line(ss, 'Fr_wp_idx/1', 'IdxDly/1');
    add_line(ss, 'IdxDly/1', 'WpManager/9');

    % ---- 로이터 벡터필드 (8주차 그대로) ----
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/LoiterVF'], 'Position', [520 750 760 1250]);
    setFcn(ss, 'LoiterVF', [ ...
'function [psi_lo, r, theta] = LoiterVF(pn, pe, cn, ce, rd, vd, pc, beta, kcrab)' newline ...
'%#codegen'                                                                newline ...
'% Circular-orbit vector field guidance.'                                  newline ...
'%   Jung, Lim, Lee, Bang, "Unmanned Aircraft Vector Field Path Following' newline ...
'%   with Arrival Angle Control", eq. (9) and (13).'                       newline ...
'%   pc > 0 clockwise, pc < 0 counter-clockwise.'                          newline ...
''                                                                         newline ...
'dn = pn - cn;'                                                            newline ...
'de = pe - ce;'                                                            newline ...
'r     = sqrt(dn*dn + de*de);'                                             newline ...
'theta = atan2(de, dn);'                                                   newline ...
'if r < 1e-6, r = 1e-6; end'                                               newline ...
''                                                                         newline ...
'N = sqrt((r - rd)^2 + (pc*r)^2);'                                         newline ...
'if N < 1e-9, N = 1e-9; end'                                               newline ...
'r_dot   = -vd * (r - rd) / N;'                                            newline ...
'rth_dot =  vd * pc * r   / N;'                                            newline ...
''                                                                         newline ...
'vfN = r_dot*cos(theta) - rth_dot*sin(theta);'                             newline ...
'vfE = r_dot*sin(theta) + rth_dot*cos(theta);'                             newline ...
''                                                                         newline ...
'chi_d  = atan2(vfE, vfN);'                                                newline ...
'p      = chi_d - kcrab*beta;'                                             newline ...
'psi_lo = atan2(sin(p), cos(p));']);

    % ---- 회전수 (모드가 로이터일 때만 센다) ----
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/TurnCount'], 'Position', [520 1520 760 1880]);
    setFcn(ss, 'TurnCount', [ ...
'function [turns, th_out, acc_out, armed] = TurnCount( ...'                newline ...
'         theta, r, rd, mode, th_prev, acc_prev, armed_prev)'              newline ...
'%#codegen'                                                                newline ...
'% Count laps, but only while the mission is loitering (mode 2).'          newline ...
'% Leaving loiter mode resets the counter, so a second loiter later'       newline ...
'% starts from zero again.'                                                newline ...
''                                                                         newline ...
'th_out = theta;'                                                          newline ...
''                                                                         newline ...
'if mode < 1.5 || mode > 2.5'                                              newline ...
'    turns = 0; acc_out = 0; armed = 0;'                                   newline ...
'    return'                                                               newline ...
'end'                                                                      newline ...
''                                                                         newline ...
'tol = 0.3*rd;                     % same band as week 8'                                                       newline ...
'if armed_prev < 0.5'                                                      newline ...
'    acc_out = 0;'                                                         newline ...
'    if abs(r - rd) <= tol'                                                newline ...
'        armed = 1;'                                                       newline ...
'    else'                                                                 newline ...
'        armed = 0;'                                                       newline ...
'    end'                                                                  newline ...
'else'                                                                     newline ...
'    armed = 1;'                                                           newline ...
'    d = theta - th_prev;'                                                 newline ...
'    d = atan2(sin(d), cos(d));'                                           newline ...
'    acc_out = acc_prev + d;'                                              newline ...
'end'                                                                      newline ...
'turns = abs(acc_out) / (2*pi);']);

    % TurnCount 의 기억 셋은 자기에게 돌아온다. 태그로 건넌다
    dn  = {'ThDly','AccDly','ArmDly'};
    tg  = {'th_prev','acc_prev','armed_prev'};
    for k = 1:3
        drop_tag(ss, 'TurnCount', k+1, tg{k}, 160 + 60*k);
        q = port_xy(ss, 'TurnCount', 'Inport', k+4);
        add_block('simulink/Discrete/Unit Delay', [ss '/' dn{k}], ...
                  'Position', [x+300 q(2)-20 x+375 q(2)+20], ...
                  'InitialCondition','0', 'SampleTime','Ts_ctrl');
        add_block('simulink/Signal Routing/From', [ss '/Fr_' tg{k}], ...
                  'Position', [x+180 q(2)-11 x+250 q(2)+11], 'GotoTag', tg{k});
        add_line(ss, ['Fr_' tg{k} '/1'], [dn{k} '/1']);
        add_line(ss, [dn{k} '/1'], sprintf('TurnCount/%d', k+4));
    end


    % 입력은 상자 안에서 **태그로 나눠 쓴다.** pn·pe·mode 를 두 함수가 함께 쓰는데,
    % 포트에서 선을 두 갈래로 끌면 그 선이 설정 상수 열을 가로지른다.
    ipt = {'pn','pe','beta','mode'};
    for k = 1:numel(ipt)
        add_block('simulink/Signal Routing/Goto', [ss '/Go_i_' ipt{k}], ...
                  'Position', [160 196+(k-1)*60 240 218+(k-1)*60], ...
                  'GotoTag', ['i_' ipt{k}], 'TagVisibility','local');
        add_line(ss, [ipt{k} '/1'], ['Go_i_' ipt{k} '/1'], 'autorouting','on');
    end

    % --- 설정값 — 신호가 아니다. 상자 안에 둔다 --------------------------
    cfg = {'WPN','wp_north'; 'WPE','wp_east'; 'Dlt','Delta'; 'Rsw','R_LOS'; ...
           'LWP','loiter_wp'; 'LCN','loiter_cn'; 'LCE','loiter_ce'; ...
           'LRD','loiter_radius'; 'LRD2','loiter_radius'; ...
           'URf','u_ref'; 'Pc','p_c'; 'Kcr','crab_comp'};
    for k = 1:size(cfg,1)
        add_block('simulink/Sources/Constant', [ss '/' cfg{k,1}], ...
                  'Position', [330 100+(k-1)*60 405 130+(k-1)*60], 'Value', cfg{k,2});
    end
    fr = {'pn_1','i_pn'; 'pe_1','i_pe'; 'mode_1','i_mode'; ...
          'pn_2','i_pn'; 'pe_2','i_pe'; 'beta_1','i_beta'; 'mode_2','i_mode'};
    for k = 1:size(fr,1)
        add_block('simulink/Signal Routing/From', [ss '/Fr_' fr{k,1}], ...
                  'Position', [330 900+(k-1)*60 400 922+(k-1)*60], 'GotoTag', fr{k,2});
    end

    % --- 배선 -----------------------------------------------------------
    wp = {'Fr_pn_1','Fr_pe_1','WPN','WPE','Dlt','Rsw','LWP','Fr_mode_1'};
    for k = 1:numel(wp)
        add_line(ss, [wp{k} '/1'], sprintf('WpManager/%d',k), 'autorouting','on');
    end
    lv = {'Fr_pn_2','Fr_pe_2','LCN','LCE','LRD','URf','Pc','Fr_beta_1','Kcr'};
    for k = 1:numel(lv)
        add_line(ss, [lv{k} '/1'], sprintf('LoiterVF/%d',k), 'autorouting','on');
    end
    add_line(ss,'LoiterVF/3','TurnCount/1','autorouting','on');   % theta
    add_line(ss,'LoiterVF/2','TurnCount/2','autorouting','on');   % r
    add_line(ss,'LRD2/1',    'TurnCount/3','autorouting','on');
    add_line(ss,'Fr_mode_2/1','TurnCount/4','autorouting','on');

    % --- 출력 포트 : 순서를 미션 상자의 입력 순서와 **같게** 맞춘다 --------
    ot = {'psi_los','WpManager',1; 'psi_lo','LoiterVF',1; ...
          'at_loiter','WpManager',4; 'at_end','WpManager',5; 'turns','TurnCount',1};
    for k = 1:size(ot,1)
        add_line(ss, sprintf('%s/%d', ot{k,2}, ot{k,3}), [ot{k,1} '/1'], 'autorouting','on');
    end

    % --- 로깅용 태그 -----------------------------------------------------
    lt = {'WpManager',2,'y_e'; 'WpManager',3,'idx'; ...
          'LoiterVF',2,'r_lo'; 'TurnCount',1,'turns'};
    for k = 1:size(lt,1)
        add_block('simulink/Signal Routing/Goto', [ss '/Go_' lt{k,3}], ...
                  'Position', [1000 200+(k-1)*60 1080 222+(k-1)*60], ...
                  'GotoTag', lt{k,3}, 'TagVisibility','global');
        add_line(ss, sprintf('%s/%d', lt{k,1}, lt{k,2}), ['Go_' lt{k,3} '/1'], ...
                 'autorouting','on');
    end

    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 미션 상태기계 (Stateflow)
% =====================================================================
function addMissionFSM(m, x, y)
% 2단 · MISSION — 지금 무엇을 할 차례인지 정하고, 그에 맞는 지령을 고른다.
%
%   포트   at_loiter, turns, at_end, psi_los, psi_lo  ->  psi_ref, gate
%
%   안에 들어가는 것
%     MissionFSM  Stateflow 상태기계. WpFollow -> Loiter -> Finish
%     ModeSwitch  상태에 맞는 선수각 지령을 고른다
%     ModeDly     mode 를 한 스텝 늦춰 유도부로 되먹인다 (대수 루프 차단)
%
%   유도는 두 지령을 **둘 다** 계산해 내놓고, 고르는 일은 여기서만 한다.
%   그래서 "판단"과 "유도"가 색으로도 갈린다 — 보라와 파랑.
    ss = add_subsys(m, 'Mission', [x y x+190 y+170], ...
                    {'psi_los','psi_lo','at_loiter','at_end','turns'}, ...
                    {'psi_ref','gate'}, gnc_colour('mission'));
    add_block('sflib/Chart', [ss '/MissionFSM'], 'Position', [x y x+220 y+180]);

    rt = sfroot;
    ch = rt.find('-isa','Stateflow.Chart','Path',[ss '/MissionFSM']);
    ch.ActionLanguage = 'MATLAB';
    ch.ChartUpdate    = 'DISCRETE';
    ch.SampleTime     = 'Ts_ctrl';

    ins = {'at_loiter','turns','req_turns','at_end'};
    for k = 1:numel(ins)
        d = Stateflow.Data(ch);
        d.Name = ins{k}; d.Scope = 'Input'; d.Port = k;
    end
    o = Stateflow.Data(ch);
    o.Name = 'mode'; o.Scope = 'Output'; o.Port = 1;

    s1 = Stateflow.State(ch);
    s1.Name = 'WpFollow';
    s1.LabelString = ['WpFollow' newline 'en: mode = 1;'];
    s1.Position = [70 90 210 70];

    s2 = Stateflow.State(ch);
    s2.Name = 'Loiter';
    s2.LabelString = ['Loiter' newline 'en: mode = 2;'];
    s2.Position = [70 310 210 70];

    s3 = Stateflow.State(ch);
    s3.Name = 'Finish';
    s3.LabelString = ['Finish' newline 'en: mode = 3;'];
    s3.Position = [430 90 210 70];

    % 기본 전이
    td = Stateflow.Transition(ch);
    td.Destination = s1;
    td.DestinationOClock = 0;
    td.SourceEndPoint = [175 35];
    td.MidPoint       = [175 62];

    % WpFollow -> Loiter
    t1 = Stateflow.Transition(ch);
    t1.Source = s1;  t1.SourceOClock = 6;
    t1.Destination = s2;  t1.DestinationOClock = 0;
    t1.LabelString = '[at_loiter > 0.5]';
    t1.MidPoint = [120 240];

    % Loiter -> WpFollow
    t2 = Stateflow.Transition(ch);
    t2.Source = s2;  t2.SourceOClock = 3;
    t2.Destination = s1;  t2.DestinationOClock = 3;
    t2.LabelString = '[turns >= req_turns]';
    t2.MidPoint = [350 245];

    % WpFollow -> Finish
    t3 = Stateflow.Transition(ch);
    t3.Source = s1;  t3.SourceOClock = 3;
    t3.Destination = s3;  t3.DestinationOClock = 9;
    t3.LabelString = '[at_end > 0.5]';
    t3.MidPoint = [355 125];

    % --- 모드 스위치 : 상태에 맞는 선수각 지령을 고른다 ------------------
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/ModeSwitch'], 'Position', [x y x+180 y+150]);
    setFcn(ss, 'ModeSwitch', [ ...
'function [psi_ref, gate] = ModeSwitch(mode, psi_los, psi_lo)'          newline ...
'%#codegen'                                                             newline ...
'% Pick the heading command that belongs to the current mission state.' newline ...
'%   mode 1  waypoint following  -> LOS'                                newline ...
'%   mode 2  loitering           -> vector field'                       newline ...
'%   mode 3  finished            -> stop'                               newline ...
'if mode > 2.5'                                                         newline ...
'    psi_ref = psi_los;'                                                newline ...
'    gate    = 0;'                                                      newline ...
'elseif mode > 1.5'                                                     newline ...
'    psi_ref = psi_lo;'                                                 newline ...
'    gate    = 1;'                                                      newline ...
'else'                                                                  newline ...
'    psi_ref = psi_los;'                                                newline ...
'    gate    = 1;'                                                      newline ...
'end']);

    % --- 요구 회전수는 설정값이다. 상자 안에 둔다 -----------------------
    add_block('simulink/Sources/Constant', [ss '/Req'], ...
              'Position', [x-160 y+260 x-70 y+290], 'Value','loiter_turns');

    % --- 배선 -----------------------------------------------------------
    add_line(ss,'at_loiter/1','MissionFSM/1','autorouting','on');
    add_line(ss,'turns/1',    'MissionFSM/2','autorouting','on');
    add_line(ss,'Req/1',      'MissionFSM/3','autorouting','on');
    add_line(ss,'at_end/1',   'MissionFSM/4','autorouting','on');

    add_line(ss,'MissionFSM/1','ModeSwitch/1','autorouting','on');
    add_line(ss,'psi_los/1',   'ModeSwitch/2','autorouting','on');
    add_line(ss,'psi_lo/1',    'ModeSwitch/3','autorouting','on');

    add_line(ss,'ModeSwitch/1','psi_ref/1','autorouting','on');
    add_line(ss,'ModeSwitch/2','gate/1','autorouting','on');

    % --- mode 되먹임 ----------------------------------------------------
    %   FSM 이 낸 mode 가 유도부(WpManager·TurnCount)의 입력으로 돌아간다.
    %   그대로 두면 대수 루프다. 한 스텝(0.05 s) 늦춰 끊는다.
    add_block('simulink/Discrete/Unit Delay', [ss '/ModeDly'], ...
              'Position', [x+380 y+300 x+455 y+340], ...
              'InitialCondition','1', 'SampleTime','Ts_ctrl');
    add_line(ss,'MissionFSM/1','ModeDly/1','autorouting','on');

    % 태그로 내보낸다 — 최상위에서 From 하나가 받아 유도부로 넣는다
    add_block('simulink/Signal Routing/Goto', [ss '/Go_mode'], ...
              'Position', [x+520 y+310 x+600 y+332], ...
              'GotoTag','mode', 'TagVisibility','global');
    add_line(ss,'ModeDly/1','Go_mode/1','autorouting','on');

    lt = {'ModeSwitch',1,'psi_ref'; 'ModeSwitch',2,'gate'};
    for k = 1:2
        add_block('simulink/Signal Routing/Goto', [ss '/Go_' lt{k,3}], ...
                  'Position', [x+520 y+400+(k-1)*45 x+600 y+400+(k-1)*45+22], ...
                  'GotoTag', lt{k,3}, 'TagVisibility','global');
        add_line(ss, sprintf('%s/%d', lt{k,1}, lt{k,2}), ['Go_' lt{k,3} '/1'], ...
                 'autorouting','on');
    end

    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 2단 · INNER LOOP — 7·8주차와 완전히 같다
% =====================================================================
function addInnerLoop(m, x, y)
    ss = [m '/InnerLoop'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+190 y+170]);

    in = {'psi_ref','gate','u_ref','psi','r','u'};
    for k = 1:numel(in)
        add_block('simulink/Sources/In1', [ss '/' in{k}], ...
                  'Position', [40 60+(k-1)*80 75 60+(k-1)*80+30], 'Port', num2str(k));
    end

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/HeadingErr'], 'Position', [200 60 340 130]);
    setFcn(ss, 'HeadingErr', [ ...
'function e = HeadingErr(psi_ref, psi)'                          newline ...
'%#codegen'                                                      newline ...
'% Shortest signed angle, wrapped to [-pi, pi).'                 newline ...
'd = psi_ref - psi;'                                             newline ...
'e = atan2(sin(d), cos(d));']);

    add_block('simulink/Math Operations/Gain', [ss '/Kp_psi'], ...
              'Position', [410 60 460 100], 'Gain','Kp_psi');
    add_block('simulink/Math Operations/Gain', [ss '/Kd_rate'], ...
              'Position', [410 240 460 280], 'Gain','-Kd_psi');
    add_block('simulink/Math Operations/Sum', [ss '/SumN'], ...
              'Position', [560 110 590 150], 'Inputs','++');
    add_block('simulink/Discontinuities/Saturation', [ss '/SatN'], ...
              'Position', [650 110 690 150], ...
              'UpperLimit','2*F_max*half_beam', 'LowerLimit','-2*F_max*half_beam');

    add_line(ss,'psi_ref/1','HeadingErr/1','autorouting','on');
    add_line(ss,'psi/1',    'HeadingErr/2','autorouting','on');
    add_line(ss,'HeadingErr/1','Kp_psi/1','autorouting','on');
    add_line(ss,'r/1',        'Kd_rate/1','autorouting','on');
    add_line(ss,'Kp_psi/1', 'SumN/1','autorouting','on');
    add_line(ss,'Kd_rate/1','SumN/2','autorouting','on');
    add_line(ss,'SumN/1','SatN/1','autorouting','on');

    add_block('simulink/Math Operations/Product', [ss '/Gate'], ...
              'Position', [200 380 235 420]);
    add_block('simulink/Math Operations/Sum', [ss '/SurgeErr'], ...
              'Position', [300 385 330 415], 'Inputs','+-');
    add_block('simulink/Continuous/PID Controller', [ss '/PI_u'], ...
              'Position', [400 370 490 430]);
    set_param([ss '/PI_u'], 'Controller','PI', ...
        'TimeDomain','Discrete-time', 'SampleTime','Ts_ctrl', ...
        'P','Kp_u', 'I','Ki_u', 'LimitOutput','on', ...
        'UpperSaturationLimit','2*F_max', 'LowerSaturationLimit','-2*F_max', ...
        'AntiWindupMode','clamping');

    add_line(ss,'u_ref/1','Gate/1','autorouting','on');
    add_line(ss,'gate/1', 'Gate/2','autorouting','on');
    add_line(ss,'Gate/1','SurgeErr/1','autorouting','on');
    add_line(ss,'u/1',   'SurgeErr/2','autorouting','on');
    add_line(ss,'SurgeErr/1','PI_u/1','autorouting','on');

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/Alloc'], 'Position', [760 230 910 340]);
    setFcn(ss, 'Alloc', [ ...
'function [FL, FR] = Alloc(X, N, half_beam, Fmax)'                newline ...
'%#codegen'                                                       newline ...
'FL = X/2 + N/(2*half_beam);'                                     newline ...
'FR = X/2 - N/(2*half_beam);'                                     newline ...
'if FL >  Fmax, FL =  Fmax; end'                                  newline ...
'if FL < -Fmax, FL = -Fmax; end'                                  newline ...
'if FR >  Fmax, FR =  Fmax; end'                                  newline ...
'if FR < -Fmax, FR = -Fmax; end']);

    add_block('simulink/Sources/Constant', [ss '/HB'], ...
              'Position', [620 460 710 490], 'Value','half_beam');
    add_block('simulink/Sources/Constant', [ss '/FM'], ...
              'Position', [620 510 710 540], 'Value','F_max');
    add_block('simulink/Sinks/Out1', [ss '/FL'], 'Position',[980 250 1015 280], 'Port','1');
    add_block('simulink/Sinks/Out1', [ss '/FR'], 'Position',[980 310 1015 340], 'Port','2');

    add_line(ss,'PI_u/1','Alloc/1','autorouting','on');
    add_line(ss,'SatN/1','Alloc/2','autorouting','on');
    add_line(ss,'HB/1',  'Alloc/3','autorouting','on');
    add_line(ss,'FM/1',  'Alloc/4','autorouting','on');
    add_line(ss,'Alloc/1','FL/1','autorouting','on');
    add_line(ss,'Alloc/2','FR/1','autorouting','on');

    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 3단 · THRUSTERS
% =====================================================================
function addThrusters(m, x, y)
    ss = [m '/Thrusters'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+170 y+120]);

    add_block('simulink/Sources/In1', [ss '/FL_cmd'], 'Position',[40 60 75 90],  'Port','1');
    add_block('simulink/Sources/In1', [ss '/FR_cmd'], 'Position',[40 140 75 170],'Port','2');

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/F2n'], 'Position', [170 70 320 160]);
    setFcn(ss, 'F2n', [ ...
'function n_cmd = F2n(FL, FR, k, n_max)'                              newline ...
'%#codegen'                                                           newline ...
'% Inverse propeller law:  F = k*n*|n|  ->  n = sign(F)*sqrt(|F|/k)'  newline ...
'F = [FL; FR];'                                                       newline ...
'n_cmd = zeros(2,1);'                                                 newline ...
'for i = 1:2'                                                         newline ...
'    ni = sign(F(i)) * sqrt(abs(F(i))/k);'                            newline ...
'    if ni >  n_max, ni =  n_max; end'                                newline ...
'    if ni < -n_max, ni = -n_max; end'                                newline ...
'    n_cmd(i) = ni;'                                                  newline ...
'end']);

    add_block('simulink/Sources/Constant', [ss '/Kp'], ...
              'Position',[40 250 130 280], 'Value','k_prop');
    add_block('simulink/Sources/Constant', [ss '/Nm'], ...
              'Position',[40 300 130 330], 'Value','n_max');
    add_block('simulink/Discrete/Discrete Transfer Fcn', [ss '/MotorLag'], ...
              'Position',[380 85 500 145]);
    set_param([ss '/MotorLag'], 'Numerator','Ts_ctrl/tau_n', ...
              'Denominator','[1, Ts_ctrl/tau_n - 1]', 'SampleTime','Ts_ctrl');

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/n2F'], 'Position', [560 70 700 160]);
    setFcn(ss, 'n2F', [ ...
'function [FL, FR] = n2F(n, k)'                                  newline ...
'%#codegen'                                                      newline ...
'FL = k * n(1) * abs(n(1));'                                     newline ...
'FR = k * n(2) * abs(n(2));']);

    add_block('simulink/Sinks/Out1', [ss '/FL'], 'Position',[780 70 815 100], 'Port','1');
    add_block('simulink/Sinks/Out1', [ss '/FR'], 'Position',[780 130 815 160],'Port','2');
    add_block('simulink/Sinks/Out1', [ss '/n'],  'Position',[780 190 815 220],'Port','3');

    add_line(ss,'FL_cmd/1','F2n/1','autorouting','on');
    add_line(ss,'FR_cmd/1','F2n/2','autorouting','on');
    add_line(ss,'Kp/1','F2n/3','autorouting','on');
    add_line(ss,'Nm/1','F2n/4','autorouting','on');
    add_line(ss,'F2n/1','MotorLag/1','autorouting','on');
    add_line(ss,'MotorLag/1','n2F/1','autorouting','on');
    add_line(ss,'Kp/1','n2F/2','autorouting','on');
    add_line(ss,'n2F/1','FL/1','autorouting','on');
    add_line(ss,'n2F/2','FR/1','autorouting','on');
    add_line(ss,'MotorLag/1','n/1','autorouting','on');

    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 4단 · MOTION MODEL
% =====================================================================
function addMotionModel(m, x, y)
    ss = [m '/MotionModel'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+210 y+200]);

    in = {'FL','FR','p'};   % 앞의 둘만 신호. p 는 설정이라 상자 안에 둔다
    for k = 1:2
        add_block('simulink/Sources/In1', [ss '/' in{k}], ...
                  'Position', [40 60+(k-1)*70 75 60+(k-1)*70+30], 'Port', num2str(k));
    end

    % 선체 계수는 신호가 아니라 설정이다. 상자 안에 둔다
    add_block('simulink/Sources/Constant', [ss '/p'], ...
              'Position', [40 220 130 250], ...
              'Value', '[m_usv; Izz; Xu; Xuu; Yv; Yvv; Nr; Nrr; half_beam]');

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/EOM'], 'Position', [200 60 380 240]);
    setFcn(ss, 'EOM', [ ...
'function xdot = EOM(s, FL, FR, p)'                                      newline ...
'%#codegen'                                                              newline ...
'% 3-DOF WAM-V equations of motion, NED.'                                newline ...
'% Coefficients come straight from the Gazebo VRX plugins.'              newline ...
'u = s(1); v = s(2); r = s(3); psi = s(6);'                              newline ...
'm=p(1); Izz=p(2); Xu=p(3); Xuu=p(4); Yv=p(5); Yvv=p(6);'                newline ...
'Nr=p(7); Nrr=p(8); b_half=p(9);'                                        newline ...
''                                                                       newline ...
'X = FL + FR;'                                                           newline ...
'N = (FL - FR)*b_half;'                                                  newline ...
'Dx = (Xu + Xuu*abs(u))*u;'                                              newline ...
'Dy = (Yv + Yvv*abs(v))*v;'                                              newline ...
'Dn = (Nr + Nrr*abs(r))*r;'                                              newline ...
''                                                                       newline ...
'du = (X - Dx)/m + v*r;'                                                 newline ...
'dv = (  - Dy)/m - u*r;'                                                 newline ...
'dr = (N - Dn)/Izz;'                                                     newline ...
''                                                                       newline ...
'xdot = [du; dv; dr;'                                                    newline ...
'        u*cos(psi) - v*sin(psi);'                                       newline ...
'        u*sin(psi) + v*cos(psi);'                                       newline ...
'        r];']);

    add_block('simulink/Continuous/Integrator', [ss '/Integ'], ...
              'Position', [450 130 500 180], 'InitialCondition','x0');

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/States'], 'Position', [570 60 720 260]);
    setFcn(ss, 'States', [ ...
'function [pn, pe, psi, u, r, beta, chi, U] = States(s)'    newline ...
'%#codegen'                                                 newline ...
'u = s(1); v = s(2); r = s(3);'                             newline ...
'pn = s(4); pe = s(5); psi = s(6);'                         newline ...
'U    = sqrt(u*u + v*v);'                                   newline ...
'beta = atan2(v, u);'                                       newline ...
'c    = psi + beta;'                                        newline ...
'chi  = atan2(sin(c), cos(c));']);

    % --- 배치 : 한 줄에 EOM -> 1/s -> States. 포트 높이를 읽어서 맞춘다 ----
    ROW = 340;
    set_param([ss '/EOM'],    'Position', [280 140 460 540]);
    set_param([ss '/Integ'],  'Position', [560 ROW-15 590 ROW+15]);
    set_param([ss '/States'], 'Position', [680 100 840 580]);

    % 2~4번 입력(추력 둘 + 계수)을 각자 포트 높이로 옮겨 직선으로 잇는다
    row_feed(ss, 'EOM', [{''}, in]);

    add_line(ss, 'EOM/1',   'Integ/1');
    add_line(ss, 'Integ/1', 'States/1');

    % 상태 되먹임 — 화면을 가로지르는 대신 태그로 건너뛴다
    drop_tag(ss, 'Integ', 1, 'x_state', 280);
    b = port_xy(ss, 'EOM', 'Inport', 1);
    add_block('simulink/Signal Routing/From', [ss '/Fr_x_state'], ...
              'Position', [180 b(2)-11 250 b(2)+11], 'GotoTag','x_state');
    add_line(ss, 'Fr_x_state/1', 'EOM/1');

    % 출력 포트를 States 의 포트 높이에 맞춘다 -> 여덟 선이 전부 직선
    out = {'pn','pe','psi','u','r','beta','chi','U'};
    for k = 1:numel(out)
        q = port_xy(ss, 'States', 'Outport', k);
        add_block('simulink/Sinks/Out1', [ss '/' out{k}], ...
                  'Position', [940 q(2)-7 970 q(2)+7], 'Port', num2str(k));
        add_line(ss, sprintf('States/%d',k), [out{k} '/1']);
    end
end

% =====================================================================
% 5단 · ANIMATE
% =====================================================================
function addAnimate(m, x, y)
% 실시간 그림 — 포트 없는 서브시스템 하나로 묶는다.
%
%   태그 순서가 곧 W09_animate 의 인자 순서다 (뒤에 t, en 이 붙는다).
%   turns 를 빠뜨리면 t 자리에 turns 가 들어가고 t 는 비어, 모델을 돌리는 순간
%   "입력 인수가 부족합니다" 로 멈춘다 (2026-09-17 확인).
    add_animate_box(m, {'pn','pe','psi','mode','turns'}, 'W09_animate', '', ...
                    [x y], 'Ts_ctrl');
end

% =====================================================================
% 앞단 배선 (두 모델 공통)
%   설정값은 각 상자 안에 있다. 최상위에 남는 것은 되먹임뿐이다.
% =====================================================================
function wireFront(m)
    F(m,'pn','a',   40,  65);
    F(m,'pe','a',   40, 110);
    F(m,'beta','a', 40, 155);
    F(m,'mode','a', 40, 200);

    add_line(m,'Fr_pn_a/1',  'Guidance/1','autorouting','on');
    add_line(m,'Fr_pe_a/1',  'Guidance/2','autorouting','on');
    add_line(m,'Fr_beta_a/1','Guidance/3','autorouting','on');
    add_line(m,'Fr_mode_a/1','Guidance/4','autorouting','on');

    % 유도 -> 미션 : 다섯 줄이 그대로 넘어간다
    % 유도 출력과 미션 입력의 **순서가 같다**. 다섯 선이 전부 직선이 된다
    for k = 1:5
        add_line(m, sprintf('Guidance/%d',k), sprintf('Mission/%d',k), 'autorouting','on');
    end

    % 내부루프 입력 : 미션 출력 둘 + 목표 속도 + 자세·속도 되먹임 셋
    C(m,'URf2','u_ref', 1500, 560);
    F(m,'psi','d', 1500, 620);
    F(m,'r',  'd', 1500, 660);
    F(m,'u',  'd', 1500, 700);
    add_line(m,'Mission/1','InnerLoop/1','autorouting','on');
    add_line(m,'Mission/2','InnerLoop/2','autorouting','on');
    add_line(m,'URf2/1',   'InnerLoop/3','autorouting','on');
    add_line(m,'Fr_psi_d/1','InnerLoop/4','autorouting','on');
    add_line(m,'Fr_r_d/1',  'InnerLoop/5','autorouting','on');
    add_line(m,'Fr_u_d/1',  'InnerLoop/6','autorouting','on');
end

% =====================================================================
% 로깅
% =====================================================================
function addLogging(m, x, y)
% 로깅 — 포트 없는 서브시스템 하나로 묶는다. W09_plot.m 이 이 변수들을 읽는다.
    sig = {'pn','pe','psi','psi_ref','y_e','idx','mode','turns','gate','u','beta','r_lo','FL','FR'};
    add_logging_box(m, sig, sig, [x y], 'Ts_ctrl');
end

% =====================================================================
% 오프라인 모델
% =====================================================================
function build_offline()
    m = 'W09_0_offline'; fresh(m);
    set_param(m, 'SolverType','Fixed-step', 'SolverName','ode4', ...
                 'FixedStep','Ts_ctrl', 'StopTime','700', 'SimulationMode','normal');

    addGuidance(m, 300, 60);
    addMissionFSM(m, 800, 620);   % Mission 상자 — ModeSwitch·ModeDly 까지 안에 있다
    addInnerLoop(m, 1750, 560);
    wireFront(m);
    addThrusters(m, 2050, 570);
    addMotionModel(m, 2350, 560);

    add_line(m,'InnerLoop/1','Thrusters/1','autorouting','on');
    add_line(m,'InnerLoop/2','Thrusters/2','autorouting','on');
    add_line(m,'Thrusters/1','MotionModel/1','autorouting','on');
    add_line(m,'Thrusters/2','MotionModel/2','autorouting','on');

    G(m,'FL', 2250, 800);  G(m,'FR', 2250, 840);  G(m,'nprop', 2250, 880);
    add_line(m,'Thrusters/1','Go_FL/1','autorouting','on');
    add_line(m,'Thrusters/2','Go_FR/1','autorouting','on');
    add_line(m,'Thrusters/3','Go_nprop/1','autorouting','on');

    tags = {'pn','pe','psi','u','r','beta','chi','U'};
    for k = 1:numel(tags)
        G(m, tags{k}, 2620, 560+(k-1)*40);
        add_line(m, sprintf('MotionModel/%d',k), ['Go_' tags{k} '/1'], 'autorouting','on');
    end

    addAnimate(m, 2620, 940);
    addLogging(m, 3080, 60);

    note(m,'n1', ['W09 실습 A  —  웨이포인트 + 로이터링 (Gazebo 불필요)' newline ...
        'WpManager(LOS) 와 LoiterVF 를 MissionFSM 이 골라 쓴다.' newline ...
        'WpFollow -> Loiter -> WpFollow -> Finish' newline ...
        '실행 전 >> W09_setup'], 300, -120);

    save_system(m); close_system(m);
    fprintf('  W09_0_offline  생성\n');
end

% =====================================================================
% VRX 연동 모델
% =====================================================================
function build_vrx()
    m = 'W09_1_vrx'; fresh(m);
    load_system('ros2lib');
    set_param(m, 'SolverType','Fixed-step', 'SolverName','FixedStepDiscrete', ...
                 'FixedStep','Ts_ctrl', 'StopTime','inf', 'SimulationMode','normal');

    addGuidance(m, 300, 60);
    addMissionFSM(m, 800, 620);   % Mission 상자 — ModeSwitch·ModeDly 까지 안에 있다
    addInnerLoop(m, 1750, 560);
    wireFront(m);
    addThrusters(m, 2050, 570);

    % --- 4단 · 추력 발행 (운동모델 = Gazebo) -----------------------------
    add_cmd_publisher(m, [2350 470], ...
        {'/wamv/thrusters/left/thrust','/wamv/thrusters/right/thrust'}, 'Ts_ctrl');
    add_line(m,'InnerLoop/1','Thrusters/1','autorouting','on');
    add_line(m,'InnerLoop/2','Thrusters/2','autorouting','on');
    add_line(m,'Thrusters/1','CmdPublisher/1','autorouting','on');
    add_line(m,'Thrusters/2','CmdPublisher/2','autorouting','on');

    G(m,'FL', 2250, 860);  G(m,'FR', 2250, 900);  G(m,'nprop', 2250, 940);
    add_line(m,'Thrusters/1','Go_FL/1','autorouting','on');
    add_line(m,'Thrusters/2','Go_FR/1','autorouting','on');
    add_line(m,'Thrusters/3','Go_nprop/1','autorouting','on');

    % --- 5단 · 항법 (ENU -> NED 변환) -----------------------------------
    navCode = [ ...
'function [pn, pe, psi, u, r, beta, chi, U] = Nav(ex, ey, qx, qy, qz, qw, bx, by, wz, orgN, orgE)' newline ...
'%#codegen'                                                                 newline ...
'% Gazebo/ROS uses ENU with a body frame of x-forward, y-LEFT, z-UP.'       newline ...
'% Marine control uses NED with x-forward, y-STARBOARD, z-DOWN.'            newline ...
'% 첫 메시지가 도착하기 전에는 Subscribe 가 0 으로 채운 버스를 낸다.'       newline ...
'% 그대로 쓰면 위치가 스폰 원점만큼(약 568 m) 튀어 로그 첫 점이 망가진다.'  newline ...
'if ex == 0 && ey == 0'                                                     newline ...
'    pn = 0; pe = 0; psi = 0; u = 0; r = 0; beta = 0; chi = 0; U = 0;'      newline ...
'    return'                                                                newline ...
'end'                                                                       newline ...
'pn = ey - orgN;'                                                           newline ...
'pe = ex - orgE;'                                                           newline ...
'yaw_enu = atan2(2*(qw*qz + qx*qy), 1 - 2*(qy*qy + qz*qz));'                newline ...
'p   = pi/2 - yaw_enu;'                                                     newline ...
'psi = atan2(sin(p), cos(p));'                                              newline ...
'u = bx;  v = -by;  r = -wz;'                                               newline ...
'U    = sqrt(u*u + v*v);'                                                   newline ...
'beta = atan2(v, u);'                                                       newline ...
'c    = psi + beta;'                                                        newline ...
'chi  = atan2(sin(c), cos(c));'];

    add_pose_subscriber(m, [2710 970], ...
        '/wamv/sensors/position/ground_truth_odometry', 'Ts_ctrl', navCode, ...
        {'pn','pe','psi','u','r','beta','chi','U'});

    tags = {'pn','pe','psi','u','r','beta','chi','U'};
    for k = 1:numel(tags)
        G(m, tags{k}, 2950, 970+(k-1)*45);
        add_line(m, sprintf('PoseSubscriber/%d',k), ['Go_' tags{k} '/1'], 'autorouting','on');
    end

    addAnimate(m, 2950, 1340);
    addLogging(m, 3400, 60);

    note(m,'n1', ['W09 실습 C  —  VRX 연동 (Gazebo 필요)' newline ...
        'Guidance -> Mission -> Inner Loop -> Thrusters -> Gazebo -> Navigation' newline ...
        '유도부·미션·내부루프·게인은 W09_0_offline 과 완전히 같다.' newline ...
        '운동모델만 Gazebo 로 바뀐다.' newline ...
        '실행 전: (1) W09_setup  (2) VRX 기동  (3) 페이싱을 RTF 에 맞출 것'], 300, -120);

    save_system(m); close_system(m);
    fprintf('  W09_1_vrx      생성\n');
end

function addThrusterPublisher(m, side, tag, x, y)
    add_block('ros2lib/Blank Message', [m '/Blank' tag], ...
              'Position', [x y+70 x+100 y+110]);
    set_param([m '/Blank' tag], 'entityType','std_msgs/Float64', ...
              'messageType','std_msgs/Float64', 'SampleTime','Ts_ctrl');
    add_block('simulink/Signal Routing/Bus Assignment', [m '/Asg' tag], ...
              'Position', [x+160 y x+220 y+115]);
    set_param([m '/Asg' tag], 'AssignedSignals','data');
    add_block('ros2lib/Publish', [m '/Pub' tag], ...
              'Position', [x+290 y+35 x+390 y+75]);
    set_param([m '/Pub' tag], 'topicSource','Specify your own', ...
              'topic', ['/wamv/thrusters/' side '/thrust'], ...
              'messageType','std_msgs/Float64');
    add_line(m, ['Blank' tag '/1'], ['Asg' tag '/1'], 'autorouting','on');
    add_line(m, ['Asg'   tag '/1'], ['Pub' tag '/1'], 'autorouting','on');
end
