function build_w09_models()
% BUILD_W09_MODELS  9주차 Simulink 모델 2개를 생성한다.
%
%     W09_0_offline.slx   오프라인 — Gazebo 없이 돈다
%     W09_1_vrx.slx       VRX 연동
%
%   임무:  웨이포인트 항주  →  지정한 점에서 로이터링  →  다시 웨이포인트
%   이 전환을 Stateflow 상태기계가 관리한다.
%
%   구조
%     WpManager  ─┐
%     LoiterVF   ─┼→ ModeSwitch → Inner Loop → Thrusters → 운동모델
%     TurnCount  ─┤
%     MissionFSM ─┘   (Stateflow)
%
%   7·8주차에서 그대로 가져온 것
%     InnerLoop, Thrusters, MotionModel, Animate, LOS, LoiterVF, TurnCount
%   새로 만든 것
%     MissionFSM (Stateflow), WpManager, ModeSwitch
%
%   실행 전에 반드시 >> W09_setup 을 먼저 실행할 것.

    here = fileparts(mfilename('fullpath'));
    cd(here);

    if evalin('base', '~exist(''loiter_wp'',''var'')')
        error('먼저 W09_setup 을 실행하십시오.');
    end

    build_offline();
    build_vrx();


    % 배치와 색을 정리한다. 선은 직선 또는 직각으로만 다시 그린다.
    slxList = dir('*.slx');
    for k = 1:numel(slxList)
        [~, mName] = fileparts(slxList(k).name);
        try, tidy_layout(mName); tidy_layout(mName); catch, end
    end
    fprintf('\n완료. 생성된 모델:\n');
    d = dir('W09_*.slx');
    for k = 1:numel(d), fprintf('  %s\n', d(k).name); end
end

% =====================================================================
% 공통 헬퍼
% =====================================================================
function fresh(m)
    try, close_system(m, 0); catch, end
    if exist([m '.slx'],'file'), delete([m '.slx']); end
    new_system(m);
end

function setFcn(sys, path, code)
    S  = sfroot;
    ch = S.find('-isa','Stateflow.EMChart','Path',[sys '/' path]);
    ch.Script = code;
end

function C(m, name, value, x, y)
    add_block('simulink/Sources/Constant', [m '/' name], ...
              'Position', [x y x+95 y+30], 'Value', value);
end

function F(m, tag, sfx, x, y)
    add_block('simulink/Signal Routing/From', [m '/Fr_' tag '_' sfx], ...
              'Position', [x y x+70 y+25], 'GotoTag', tag);
end

function G(m, tag, x, y)
    add_block('simulink/Signal Routing/Goto', [m '/Go_' tag], ...
              'Position', [x y x+80 y+25], 'GotoTag', tag);
end

function note(m, tag, txt, x, y)
    add_block('built-in/Note', [m '/' tag], 'Position',[x y x y], 'Text', txt);
end

% =====================================================================
% 1단 · 유도 — 웨이포인트 관리 + LOS + 로이터 벡터필드
% =====================================================================
function addGuidance(m, x, y)

    % ---- 웨이포인트 관리 + LOS (7주차 유도를 확장한 것) ----
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [m '/WpManager'], 'Position', [x y x+200 y+240]);
    setFcn(m, 'WpManager', [ ...
'function [psi_los, y_e, idx, at_loiter, at_end] = WpManager( ...'          newline ...
'         pn, pe, wp_n, wp_e, Delta, R, loiter_wp, mode, idx_prev)'         newline ...
'%#codegen'                                                                 newline ...
'% Waypoint bookkeeping plus LOS guidance (week 7).'                        newline ...
'%   idx = index of the leg START. The leg runs wp(idx) -> wp(idx+1).'      newline ...
'%   The index only advances while the mission is in waypoint mode,'        newline ...
'%   so a loiter never makes the boat skip a leg.'                          newline ...
''                                                                          newline ...
'n = numel(wp_n);'                                                          newline ...
'k = min(max(idx_prev, 1), n-1);'                                           newline ...
''                                                                          newline ...
'xk  = wp_n(k);    yk  = wp_e(k);'                                          newline ...
'xk1 = wp_n(k+1);  yk1 = wp_e(k+1);'                                        newline ...
''                                                                          newline ...
'pi_p = atan2(yk1 - yk, xk1 - xk);'                                         newline ...
'y_e  = -(pn - xk)*sin(pi_p) + (pe - yk)*cos(pi_p);'                        newline ...
'psi_los = pi_p - atan(y_e / Delta);'                                       newline ...
''                                                                          newline ...
'd_next  = sqrt((xk1 - pn)^2 + (yk1 - pe)^2);'                              newline ...
'reached = d_next <= R;'                                                    newline ...
''                                                                          newline ...
'% arriving at the loiter waypoint, and arriving at the last one'           newline ...
'if reached && ((k+1) == loiter_wp)'                                        newline ...
'    at_loiter = 1;'                                                        newline ...
'else'                                                                      newline ...
'    at_loiter = 0;'                                                        newline ...
'end'                                                                       newline ...
'if reached && (k == n-1)'                                                  newline ...
'    at_end = 1;'                                                           newline ...
'else'                                                                      newline ...
'    at_end = 0;'                                                           newline ...
'end'                                                                       newline ...
''                                                                          newline ...
'% advance only in waypoint mode'                                           newline ...
'if (mode < 1.5) && reached && (k < n-1)'                                   newline ...
'    idx = k + 1;'                                                          newline ...
'else'                                                                      newline ...
'    idx = k;'                                                              newline ...
'end']);

    add_block('simulink/Discrete/Unit Delay', [m '/IdxDly'], ...
              'Position', [x+60 y+290 x+135 y+325], ...
              'InitialCondition','1', 'SampleTime','Ts_ctrl');
    add_line(m,'WpManager/3','IdxDly/1','autorouting','on');
    add_line(m,'IdxDly/1','WpManager/9','autorouting','on');

    % ---- 로이터 벡터필드 (8주차 그대로) ----
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [m '/LoiterVF'], 'Position', [x y+390 x+200 y+590]);
    setFcn(m, 'LoiterVF', [ ...
'function [psi_lo, r, theta] = LoiterVF(pn, pe, cn, ce, rd, vd, pc, beta, kcrab)' newline ...
'%#codegen'                                                                newline ...
'% Circular-orbit vector field guidance.'                                  newline ...
'%   Jung, Lim, Lee, Bang, "Unmanned Aircraft Vector Field Path Following' newline ...
'%   with Arrival Angle Control", eq. (9) and (13).'                       newline ...
'%   pc > 0 clockwise, pc < 0 counter-clockwise.'                          newline ...
''                                                                         newline ...
'dn = pn - cn;'                                                            newline ...
'de = pe - ce;'                                                            newline ...
'r     = sqrt(dn*dn + de*de);'                                             newline ...
'theta = atan2(de, dn);'                                                   newline ...
'if r < 1e-6, r = 1e-6; end'                                               newline ...
''                                                                         newline ...
'N = sqrt((r - rd)^2 + (pc*r)^2);'                                         newline ...
'if N < 1e-9, N = 1e-9; end'                                               newline ...
'r_dot   = -vd * (r - rd) / N;'                                            newline ...
'rth_dot =  vd * pc * r   / N;'                                            newline ...
''                                                                         newline ...
'vfN = r_dot*cos(theta) - rth_dot*sin(theta);'                             newline ...
'vfE = r_dot*sin(theta) + rth_dot*cos(theta);'                             newline ...
''                                                                         newline ...
'chi_d  = atan2(vfE, vfN);'                                                newline ...
'p      = chi_d - kcrab*beta;'                                             newline ...
'psi_lo = atan2(sin(p), cos(p));']);

    % ---- 회전수 (모드가 로이터일 때만 센다) ----
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [m '/TurnCount'], 'Position', [x+300 y+640 x+500 y+850]);
    setFcn(m, 'TurnCount', [ ...
'function [turns, th_out, acc_out, armed] = TurnCount( ...'                newline ...
'         theta, r, rd, mode, th_prev, acc_prev, armed_prev)'              newline ...
'%#codegen'                                                                newline ...
'% Count laps, but only while the mission is loitering (mode 2).'          newline ...
'% Leaving loiter mode resets the counter, so a second loiter later'       newline ...
'% starts from zero again.'                                                newline ...
''                                                                         newline ...
'th_out = theta;'                                                          newline ...
''                                                                         newline ...
'if mode < 1.5 || mode > 2.5'                                              newline ...
'    turns = 0; acc_out = 0; armed = 0;'                                   newline ...
'    return'                                                               newline ...
'end'                                                                      newline ...
''                                                                         newline ...
'tol = 0.05*rd + 1;'                                                       newline ...
'if armed_prev < 0.5'                                                      newline ...
'    acc_out = 0;'                                                         newline ...
'    if abs(r - rd) <= tol'                                                newline ...
'        armed = 1;'                                                       newline ...
'    else'                                                                 newline ...
'        armed = 0;'                                                       newline ...
'    end'                                                                  newline ...
'else'                                                                     newline ...
'    armed = 1;'                                                           newline ...
'    d = theta - th_prev;'                                                 newline ...
'    d = atan2(sin(d), cos(d));'                                           newline ...
'    acc_out = acc_prev + d;'                                              newline ...
'end'                                                                      newline ...
'turns = abs(acc_out) / (2*pi);']);

    dn = {'ThDly','AccDly','ArmDly'};
    for k = 1:3
        add_block('simulink/Discrete/Unit Delay', [m '/' dn{k}], ...
                  'Position', [x+340 y+900+(k-1)*50 x+415 y+935+(k-1)*50], ...
                  'InitialCondition','0', 'SampleTime','Ts_ctrl');
    end
    add_line(m,'TurnCount/2','ThDly/1','autorouting','on');
    add_line(m,'TurnCount/3','AccDly/1','autorouting','on');
    add_line(m,'TurnCount/4','ArmDly/1','autorouting','on');
    add_line(m,'ThDly/1', 'TurnCount/5','autorouting','on');
    add_line(m,'AccDly/1','TurnCount/6','autorouting','on');
    add_line(m,'ArmDly/1','TurnCount/7','autorouting','on');
end

% =====================================================================
% 미션 상태기계 (Stateflow)
% =====================================================================
function addMissionFSM(m, x, y)
    add_block('sflib/Chart', [m '/MissionFSM'], 'Position', [x y x+220 y+180]);

    rt = sfroot;
    ch = rt.find('-isa','Stateflow.Chart','Path',[m '/MissionFSM']);
    ch.ActionLanguage = 'MATLAB';
    ch.ChartUpdate    = 'DISCRETE';
    ch.SampleTime     = 'Ts_ctrl';

    ins = {'at_loiter','turns','req_turns','at_end'};
    for k = 1:numel(ins)
        d = Stateflow.Data(ch);
        d.Name = ins{k}; d.Scope = 'Input'; d.Port = k;
    end
    o = Stateflow.Data(ch);
    o.Name = 'mode'; o.Scope = 'Output'; o.Port = 1;

    s1 = Stateflow.State(ch);
    s1.Name = 'WpFollow';
    s1.LabelString = ['WpFollow' newline 'en: mode = 1;'];
    s1.Position = [70 90 210 70];

    s2 = Stateflow.State(ch);
    s2.Name = 'Loiter';
    s2.LabelString = ['Loiter' newline 'en: mode = 2;'];
    s2.Position = [70 310 210 70];

    s3 = Stateflow.State(ch);
    s3.Name = 'Finish';
    s3.LabelString = ['Finish' newline 'en: mode = 3;'];
    s3.Position = [430 90 210 70];

    % 기본 전이
    td = Stateflow.Transition(ch);
    td.Destination = s1;
    td.DestinationOClock = 0;
    td.SourceEndPoint = [175 35];
    td.MidPoint       = [175 62];

    % WpFollow -> Loiter
    t1 = Stateflow.Transition(ch);
    t1.Source = s1;  t1.SourceOClock = 6;
    t1.Destination = s2;  t1.DestinationOClock = 0;
    t1.LabelString = '[at_loiter > 0.5]';
    t1.MidPoint = [120 240];

    % Loiter -> WpFollow
    t2 = Stateflow.Transition(ch);
    t2.Source = s2;  t2.SourceOClock = 3;
    t2.Destination = s1;  t2.DestinationOClock = 3;
    t2.LabelString = '[turns >= req_turns]';
    t2.MidPoint = [350 245];

    % WpFollow -> Finish
    t3 = Stateflow.Transition(ch);
    t3.Source = s1;  t3.SourceOClock = 3;
    t3.Destination = s3;  t3.DestinationOClock = 9;
    t3.LabelString = '[at_end > 0.5]';
    t3.MidPoint = [355 125];
end

% =====================================================================
% 모드 스위치 — 어떤 유도를 쓸지 고른다
% =====================================================================
function addModeSwitch(m, x, y)
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [m '/ModeSwitch'], 'Position', [x y x+180 y+150]);
    setFcn(m, 'ModeSwitch', [ ...
'function [psi_ref, gate] = ModeSwitch(mode, psi_los, psi_lo)'          newline ...
'%#codegen'                                                             newline ...
'% Pick the heading command that belongs to the current mission state.' newline ...
'%   mode 1  waypoint following  -> LOS'                                newline ...
'%   mode 2  loitering           -> vector field'                       newline ...
'%   mode 3  finished            -> stop'                               newline ...
'if mode > 2.5'                                                         newline ...
'    psi_ref = psi_los;'                                                newline ...
'    gate    = 0;'                                                      newline ...
'elseif mode > 1.5'                                                     newline ...
'    psi_ref = psi_lo;'                                                 newline ...
'    gate    = 1;'                                                      newline ...
'else'                                                                  newline ...
'    psi_ref = psi_los;'                                                newline ...
'    gate    = 1;'                                                      newline ...
'end']);
end

% =====================================================================
% 2단 · INNER LOOP — 7·8주차와 완전히 같다
% =====================================================================
function addInnerLoop(m, x, y)
    ss = [m '/InnerLoop'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+190 y+170]);

    in = {'psi_ref','gate','u_ref','psi','r','u'};
    for k = 1:numel(in)
        add_block('simulink/Sources/In1', [ss '/' in{k}], ...
                  'Position', [40 60+(k-1)*80 75 60+(k-1)*80+30], 'Port', num2str(k));
    end

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/HeadingErr'], 'Position', [200 60 340 130]);
    setFcn(ss, 'HeadingErr', [ ...
'function e = HeadingErr(psi_ref, psi)'                          newline ...
'%#codegen'                                                      newline ...
'% Shortest signed angle, wrapped to [-pi, pi).'                 newline ...
'd = psi_ref - psi;'                                             newline ...
'e = atan2(sin(d), cos(d));']);

    add_block('simulink/Math Operations/Gain', [ss '/Kp_psi'], ...
              'Position', [410 60 460 100], 'Gain','Kp_psi');
    add_block('simulink/Math Operations/Gain', [ss '/Kd_rate'], ...
              'Position', [410 240 460 280], 'Gain','-Kd_psi');
    add_block('simulink/Math Operations/Sum', [ss '/SumN'], ...
              'Position', [560 110 590 150], 'Inputs','++');
    add_block('simulink/Discontinuities/Saturation', [ss '/SatN'], ...
              'Position', [650 110 690 150], ...
              'UpperLimit','2*F_max*half_beam', 'LowerLimit','-2*F_max*half_beam');

    add_line(ss,'psi_ref/1','HeadingErr/1','autorouting','on');
    add_line(ss,'psi/1',    'HeadingErr/2','autorouting','on');
    add_line(ss,'HeadingErr/1','Kp_psi/1','autorouting','on');
    add_line(ss,'r/1',        'Kd_rate/1','autorouting','on');
    add_line(ss,'Kp_psi/1', 'SumN/1','autorouting','on');
    add_line(ss,'Kd_rate/1','SumN/2','autorouting','on');
    add_line(ss,'SumN/1','SatN/1','autorouting','on');

    add_block('simulink/Math Operations/Product', [ss '/Gate'], ...
              'Position', [200 380 235 420]);
    add_block('simulink/Math Operations/Sum', [ss '/SurgeErr'], ...
              'Position', [300 385 330 415], 'Inputs','+-');
    add_block('simulink/Continuous/PID Controller', [ss '/PI_u'], ...
              'Position', [400 370 490 430]);
    set_param([ss '/PI_u'], 'Controller','PI', ...
        'TimeDomain','Discrete-time', 'SampleTime','Ts_ctrl', ...
        'P','Kp_u', 'I','Ki_u', 'LimitOutput','on', ...
        'UpperSaturationLimit','2*F_max', 'LowerSaturationLimit','-2*F_max', ...
        'AntiWindupMode','clamping');

    add_line(ss,'u_ref/1','Gate/1','autorouting','on');
    add_line(ss,'gate/1', 'Gate/2','autorouting','on');
    add_line(ss,'Gate/1','SurgeErr/1','autorouting','on');
    add_line(ss,'u/1',   'SurgeErr/2','autorouting','on');
    add_line(ss,'SurgeErr/1','PI_u/1','autorouting','on');

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/Alloc'], 'Position', [760 230 910 340]);
    setFcn(ss, 'Alloc', [ ...
'function [FL, FR] = Alloc(X, N, half_beam, Fmax)'                newline ...
'%#codegen'                                                       newline ...
'FL = X/2 + N/(2*half_beam);'                                     newline ...
'FR = X/2 - N/(2*half_beam);'                                     newline ...
'if FL >  Fmax, FL =  Fmax; end'                                  newline ...
'if FL < -Fmax, FL = -Fmax; end'                                  newline ...
'if FR >  Fmax, FR =  Fmax; end'                                  newline ...
'if FR < -Fmax, FR = -Fmax; end']);

    add_block('simulink/Sources/Constant', [ss '/HB'], ...
              'Position', [620 460 710 490], 'Value','half_beam');
    add_block('simulink/Sources/Constant', [ss '/FM'], ...
              'Position', [620 510 710 540], 'Value','F_max');
    add_block('simulink/Sinks/Out1', [ss '/FL'], 'Position',[980 250 1015 280], 'Port','1');
    add_block('simulink/Sinks/Out1', [ss '/FR'], 'Position',[980 310 1015 340], 'Port','2');

    add_line(ss,'PI_u/1','Alloc/1','autorouting','on');
    add_line(ss,'SatN/1','Alloc/2','autorouting','on');
    add_line(ss,'HB/1',  'Alloc/3','autorouting','on');
    add_line(ss,'FM/1',  'Alloc/4','autorouting','on');
    add_line(ss,'Alloc/1','FL/1','autorouting','on');
    add_line(ss,'Alloc/2','FR/1','autorouting','on');

    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 3단 · THRUSTERS
% =====================================================================
function addThrusters(m, x, y)
    ss = [m '/Thrusters'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+170 y+120]);

    add_block('simulink/Sources/In1', [ss '/FL_cmd'], 'Position',[40 60 75 90],  'Port','1');
    add_block('simulink/Sources/In1', [ss '/FR_cmd'], 'Position',[40 140 75 170],'Port','2');

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/F2n'], 'Position', [170 70 320 160]);
    setFcn(ss, 'F2n', [ ...
'function n_cmd = F2n(FL, FR, k, n_max)'                              newline ...
'%#codegen'                                                           newline ...
'% Inverse propeller law:  F = k*n*|n|  ->  n = sign(F)*sqrt(|F|/k)'  newline ...
'F = [FL; FR];'                                                       newline ...
'n_cmd = zeros(2,1);'                                                 newline ...
'for i = 1:2'                                                         newline ...
'    ni = sign(F(i)) * sqrt(abs(F(i))/k);'                            newline ...
'    if ni >  n_max, ni =  n_max; end'                                newline ...
'    if ni < -n_max, ni = -n_max; end'                                newline ...
'    n_cmd(i) = ni;'                                                  newline ...
'end']);

    add_block('simulink/Sources/Constant', [ss '/Kp'], ...
              'Position',[40 250 130 280], 'Value','k_prop');
    add_block('simulink/Sources/Constant', [ss '/Nm'], ...
              'Position',[40 300 130 330], 'Value','n_max');
    add_block('simulink/Discrete/Discrete Transfer Fcn', [ss '/MotorLag'], ...
              'Position',[380 85 500 145]);
    set_param([ss '/MotorLag'], 'Numerator','Ts_ctrl/tau_n', ...
              'Denominator','[1, Ts_ctrl/tau_n - 1]', 'SampleTime','Ts_ctrl');

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/n2F'], 'Position', [560 70 700 160]);
    setFcn(ss, 'n2F', [ ...
'function [FL, FR] = n2F(n, k)'                                  newline ...
'%#codegen'                                                      newline ...
'FL = k * n(1) * abs(n(1));'                                     newline ...
'FR = k * n(2) * abs(n(2));']);

    add_block('simulink/Sinks/Out1', [ss '/FL'], 'Position',[780 70 815 100], 'Port','1');
    add_block('simulink/Sinks/Out1', [ss '/FR'], 'Position',[780 130 815 160],'Port','2');
    add_block('simulink/Sinks/Out1', [ss '/n'],  'Position',[780 190 815 220],'Port','3');

    add_line(ss,'FL_cmd/1','F2n/1','autorouting','on');
    add_line(ss,'FR_cmd/1','F2n/2','autorouting','on');
    add_line(ss,'Kp/1','F2n/3','autorouting','on');
    add_line(ss,'Nm/1','F2n/4','autorouting','on');
    add_line(ss,'F2n/1','MotorLag/1','autorouting','on');
    add_line(ss,'MotorLag/1','n2F/1','autorouting','on');
    add_line(ss,'Kp/1','n2F/2','autorouting','on');
    add_line(ss,'n2F/1','FL/1','autorouting','on');
    add_line(ss,'n2F/2','FR/1','autorouting','on');
    add_line(ss,'MotorLag/1','n/1','autorouting','on');

    Simulink.BlockDiagram.arrangeSystem(ss);
end

% =====================================================================
% 4단 · MOTION MODEL
% =====================================================================
function addMotionModel(m, x, y)
    ss = [m '/MotionModel'];
    add_block('built-in/Subsystem', ss, 'Position', [x y x+210 y+200]);

    in = {'FL','FR','p'};
    for k = 1:numel(in)
        add_block('simulink/Sources/In1', [ss '/' in{k}], ...
                  'Position', [40 60+(k-1)*70 75 60+(k-1)*70+30], 'Port', num2str(k));
    end

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/EOM'], 'Position', [200 60 380 240]);
    setFcn(ss, 'EOM', [ ...
'function xdot = EOM(s, FL, FR, p)'                                      newline ...
'%#codegen'                                                              newline ...
'% 3-DOF WAM-V equations of motion, NED.'                                newline ...
'% Coefficients come straight from the Gazebo VRX plugins.'              newline ...
'u = s(1); v = s(2); r = s(3); psi = s(6);'                              newline ...
'm=p(1); Izz=p(2); Xu=p(3); Xuu=p(4); Yv=p(5); Yvv=p(6);'                newline ...
'Nr=p(7); Nrr=p(8); b_half=p(9);'                                        newline ...
''                                                                       newline ...
'X = FL + FR;'                                                           newline ...
'N = (FL - FR)*b_half;'                                                  newline ...
'Dx = (Xu + Xuu*abs(u))*u;'                                              newline ...
'Dy = (Yv + Yvv*abs(v))*v;'                                              newline ...
'Dn = (Nr + Nrr*abs(r))*r;'                                              newline ...
''                                                                       newline ...
'du = (X - Dx)/m + v*r;'                                                 newline ...
'dv = (  - Dy)/m - u*r;'                                                 newline ...
'dr = (N - Dn)/Izz;'                                                     newline ...
''                                                                       newline ...
'xdot = [du; dv; dr;'                                                    newline ...
'        u*cos(psi) - v*sin(psi);'                                       newline ...
'        u*sin(psi) + v*cos(psi);'                                       newline ...
'        r];']);

    add_block('simulink/Continuous/Integrator', [ss '/Integ'], ...
              'Position', [450 130 500 180], 'InitialCondition','x0');

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [ss '/States'], 'Position', [570 60 720 260]);
    setFcn(ss, 'States', [ ...
'function [pn, pe, psi, u, r, beta, chi, U] = States(s)'    newline ...
'%#codegen'                                                 newline ...
'u = s(1); v = s(2); r = s(3);'                             newline ...
'pn = s(4); pe = s(5); psi = s(6);'                         newline ...
'U    = sqrt(u*u + v*v);'                                   newline ...
'beta = atan2(v, u);'                                       newline ...
'c    = psi + beta;'                                        newline ...
'chi  = atan2(sin(c), cos(c));']);

    out = {'pn','pe','psi','u','r','beta','chi','U'};
    for k = 1:numel(out)
        add_block('simulink/Sinks/Out1', [ss '/' out{k}], ...
                  'Position', [800 60+(k-1)*45 840 60+(k-1)*45+30], 'Port', num2str(k));
        add_line(ss, sprintf('States/%d',k), [out{k} '/1'], 'autorouting','on');
    end
    for k = 1:3
        add_line(ss, [in{k} '/1'], sprintf('EOM/%d', k+1), 'autorouting','on');
    end
    add_line(ss,'EOM/1','Integ/1','autorouting','on');
    add_line(ss,'Integ/1','States/1','autorouting','on');
    add_line(ss,'Integ/1','EOM/1','autorouting','on');
end

% =====================================================================
% 5단 · ANIMATE
% =====================================================================
function addAnimate(m, x, y)
    F(m,'pn','v',   x, y);
    F(m,'pe','v',   x, y+40);
    F(m,'psi','v',  x, y+80);
    F(m,'mode','v', x, y+120);
    F(m,'turns','v',x, y+160);
    add_block('simulink/Sources/Digital Clock', [m '/Clk'], ...
              'Position', [x y+200 x+50 y+230], 'SampleTime','Ts_ctrl');
    C(m,'Anim','animate', x, y+250);

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [m '/Animate'], 'Position', [x+150 y x+300 y+260]);
    setFcn(m, 'Animate', [ ...
'function ok = Animate(pn, pe, psi, mode, turns, t, en)'               newline ...
'%#codegen'                                                            newline ...
'coder.extrinsic(''W09_animate'');'                                    newline ...
'ok = 1;'                                                              newline ...
'if en > 0.5'                                                          newline ...
'    W09_animate(pn, pe, psi, mode, turns, t);'                        newline ...
'end']);

    add_block('simulink/Sinks/Terminator', [m '/AnimEnd'], ...
              'Position', [x+350 y+115 x+375 y+140]);

    add_line(m,'Fr_pn_v/1',   'Animate/1','autorouting','on');
    add_line(m,'Fr_pe_v/1',   'Animate/2','autorouting','on');
    add_line(m,'Fr_psi_v/1',  'Animate/3','autorouting','on');
    add_line(m,'Fr_mode_v/1', 'Animate/4','autorouting','on');
    add_line(m,'Fr_turns_v/1','Animate/5','autorouting','on');
    add_line(m,'Clk/1', 'Animate/6','autorouting','on');
    add_line(m,'Anim/1','Animate/7','autorouting','on');
    add_line(m,'Animate/1','AnimEnd/1','autorouting','on');
end

% =====================================================================
% 앞단 배선 (두 모델 공통)
% =====================================================================
function wireFront(m)
    F(m,'pn','a', 40,  65);
    F(m,'pe','a', 40, 110);
    C(m,'WPN','wp_north',   40, 155);
    C(m,'WPE','wp_east',    40, 200);
    C(m,'Dlt','Delta',      40, 245);
    C(m,'Rsw','R_LOS',      40, 290);
    C(m,'LWP','loiter_wp',  40, 335);
    F(m,'mode','a', 40, 385);

    add_line(m,'Fr_pn_a/1','WpManager/1','autorouting','on');
    add_line(m,'Fr_pe_a/1','WpManager/2','autorouting','on');
    add_line(m,'WPN/1','WpManager/3','autorouting','on');
    add_line(m,'WPE/1','WpManager/4','autorouting','on');
    add_line(m,'Dlt/1','WpManager/5','autorouting','on');
    add_line(m,'Rsw/1','WpManager/6','autorouting','on');
    add_line(m,'LWP/1','WpManager/7','autorouting','on');
    add_line(m,'Fr_mode_a/1','WpManager/8','autorouting','on');

    % 로이터 벡터필드 입력
    F(m,'pn','b', 40, 460);
    F(m,'pe','b', 40, 505);
    C(m,'LCN','loiter_cn',     40, 550);
    C(m,'LCE','loiter_ce',     40, 595);
    C(m,'LRD','loiter_radius', 40, 640);
    C(m,'URf','u_ref',         40, 685);
    C(m,'Pc', 'p_c',           40, 730);
    F(m,'beta','b', 40, 780);
    C(m,'Kcr','crab_comp',     40, 825);

    add_line(m,'Fr_pn_b/1','LoiterVF/1','autorouting','on');
    add_line(m,'Fr_pe_b/1','LoiterVF/2','autorouting','on');
    add_line(m,'LCN/1','LoiterVF/3','autorouting','on');
    add_line(m,'LCE/1','LoiterVF/4','autorouting','on');
    add_line(m,'LRD/1','LoiterVF/5','autorouting','on');
    add_line(m,'URf/1','LoiterVF/6','autorouting','on');
    add_line(m,'Pc/1', 'LoiterVF/7','autorouting','on');
    add_line(m,'Fr_beta_b/1','LoiterVF/8','autorouting','on');
    add_line(m,'Kcr/1','LoiterVF/9','autorouting','on');

    % 회전수
    F(m,'mode','c', 40, 890);
    add_line(m,'LoiterVF/3','TurnCount/1','autorouting','on');
    add_line(m,'LoiterVF/2','TurnCount/2','autorouting','on');
    add_line(m,'LRD/1','TurnCount/3','autorouting','on');
    add_line(m,'Fr_mode_c/1','TurnCount/4','autorouting','on');

    % 미션 FSM
    C(m,'Req','loiter_turns', 640, 720);
    add_line(m,'WpManager/4','MissionFSM/1','autorouting','on');   % at_loiter
    add_line(m,'TurnCount/1','MissionFSM/2','autorouting','on');   % turns
    add_line(m,'Req/1',      'MissionFSM/3','autorouting','on');
    add_line(m,'WpManager/5','MissionFSM/4','autorouting','on');   % at_end

    % 모드 스위치
    add_line(m,'MissionFSM/1','ModeSwitch/1','autorouting','on');
    add_line(m,'WpManager/1', 'ModeSwitch/2','autorouting','on');
    add_line(m,'LoiterVF/1',  'ModeSwitch/3','autorouting','on');

    % 태그
    % mode 는 단위지연을 거쳐 되먹인다.
    % FSM 출력이 WpManager·TurnCount 입력으로 돌아가므로 그대로 두면 대수 루프가 된다.
    % 한 스텝(0.05 s) 늦게 보는 것뿐이라 동작에는 영향이 없다.
    add_block('simulink/Discrete/Unit Delay', [m '/ModeDly'], ...
              'Position', [1060 395 1135 430], ...
              'InitialCondition','1', 'SampleTime','Ts_ctrl');
    add_line(m,'MissionFSM/1','ModeDly/1','autorouting','on');
    G(m,'mode',   1180, 400);
    G(m,'turns',   640, 900);
    G(m,'psi_ref',1500, 240);
    G(m,'gate',   1500, 280);
    G(m,'y_e',     300, 330);
    G(m,'idx',     300, 370);
    G(m,'r_lo',    300, 640);
    add_line(m,'ModeDly/1','Go_mode/1','autorouting','on');
    add_line(m,'TurnCount/1', 'Go_turns/1','autorouting','on');
    add_line(m,'ModeSwitch/1','Go_psi_ref/1','autorouting','on');
    add_line(m,'ModeSwitch/2','Go_gate/1','autorouting','on');
    add_line(m,'WpManager/2', 'Go_y_e/1','autorouting','on');
    add_line(m,'WpManager/3', 'Go_idx/1','autorouting','on');
    add_line(m,'LoiterVF/2',  'Go_r_lo/1','autorouting','on');

    % 내부루프 입력
    F(m,'psi','d', 1500, 620);
    F(m,'r',  'd', 1500, 660);
    F(m,'u',  'd', 1500, 700);
    C(m,'URf2','u_ref', 1500, 560);
    add_line(m,'ModeSwitch/1','InnerLoop/1','autorouting','on');
    add_line(m,'ModeSwitch/2','InnerLoop/2','autorouting','on');
    add_line(m,'URf2/1',      'InnerLoop/3','autorouting','on');
    add_line(m,'Fr_psi_d/1','InnerLoop/4','autorouting','on');
    add_line(m,'Fr_r_d/1',  'InnerLoop/5','autorouting','on');
    add_line(m,'Fr_u_d/1',  'InnerLoop/6','autorouting','on');
end

% =====================================================================
% 로깅
% =====================================================================
function addLogging(m, x, y)
    sig = {'pn','pe','psi','psi_ref','y_e','idx','mode','turns','gate','u','beta','r_lo','FL','FR'};
    for k = 1:numel(sig)
        yy = y + (k-1)*55;
        F(m, sig{k}, 'log', x, yy+3);
        b = [m '/log_' sig{k}];
        add_block('simulink/Sinks/To Workspace', b, ...
                  'Position', [x+130 yy x+230 yy+30]);
        set_param(b, 'VariableName', ['log_' sig{k}], ...
                     'SaveFormat','Timeseries', 'SampleTime','Ts_ctrl');
        add_line(m, ['Fr_' sig{k} '_log/1'], ['log_' sig{k} '/1'], 'autorouting','on');
    end
end

% =====================================================================
% 오프라인 모델
% =====================================================================
function build_offline()
    m = 'W09_0_offline'; fresh(m);
    set_param(m, 'SolverType','Fixed-step', 'SolverName','ode4', ...
                 'FixedStep','Ts_ctrl', 'StopTime','700', 'SimulationMode','normal');

    addGuidance(m, 300, 60);
    addMissionFSM(m, 800, 620);
    addModeSwitch(m, 1180, 200);
    addInnerLoop(m, 1750, 560);
    wireFront(m);
    addThrusters(m, 2050, 570);
    addMotionModel(m, 2350, 560);

    C(m,'Par','[m_usv; Izz; Xu; Xuu; Yv; Yvv; Nr; Nrr; half_beam]', 2050, 760);
    add_line(m,'InnerLoop/1','Thrusters/1','autorouting','on');
    add_line(m,'InnerLoop/2','Thrusters/2','autorouting','on');
    add_line(m,'Thrusters/1','MotionModel/1','autorouting','on');
    add_line(m,'Thrusters/2','MotionModel/2','autorouting','on');
    add_line(m,'Par/1',      'MotionModel/3','autorouting','on');

    G(m,'FL', 2250, 800);  G(m,'FR', 2250, 840);  G(m,'nprop', 2250, 880);
    add_line(m,'Thrusters/1','Go_FL/1','autorouting','on');
    add_line(m,'Thrusters/2','Go_FR/1','autorouting','on');
    add_line(m,'Thrusters/3','Go_nprop/1','autorouting','on');

    tags = {'pn','pe','psi','u','r','beta','chi','U'};
    for k = 1:numel(tags)
        G(m, tags{k}, 2620, 560+(k-1)*40);
        add_line(m, sprintf('MotionModel/%d',k), ['Go_' tags{k} '/1'], 'autorouting','on');
    end

    addAnimate(m, 2620, 940);
    addLogging(m, 3080, 60);

    note(m,'n1', ['W09 실습 A  —  웨이포인트 + 로이터링 (Gazebo 불필요)' newline ...
        'WpManager(LOS) 와 LoiterVF 를 MissionFSM 이 골라 쓴다.' newline ...
        'WpFollow -> Loiter -> WpFollow -> Finish' newline ...
        '실행 전 >> W09_setup'], 300, -120);

    save_system(m); close_system(m);
    fprintf('  W09_0_offline  생성\n');
end

% =====================================================================
% VRX 연동 모델
% =====================================================================
function build_vrx()
    m = 'W09_1_vrx'; fresh(m);
    load_system('ros2lib');
    set_param(m, 'SolverType','Fixed-step', 'SolverName','FixedStepDiscrete', ...
                 'FixedStep','Ts_ctrl', 'StopTime','inf', 'SimulationMode','normal');

    addGuidance(m, 300, 60);
    addMissionFSM(m, 800, 620);
    addModeSwitch(m, 1180, 200);
    addInnerLoop(m, 1750, 560);
    wireFront(m);
    addThrusters(m, 2050, 570);

    addThrusterPublisher(m, 'left',  'L', 2350, 470);
    addThrusterPublisher(m, 'right', 'R', 2350, 650);
    add_line(m,'Thrusters/1','AsgL/2','autorouting','on');
    add_line(m,'Thrusters/2','AsgR/2','autorouting','on');
    add_line(m,'InnerLoop/1','Thrusters/1','autorouting','on');
    add_line(m,'InnerLoop/2','Thrusters/2','autorouting','on');

    G(m,'FL', 2250, 860);  G(m,'FR', 2250, 900);  G(m,'nprop', 2250, 940);
    add_line(m,'Thrusters/1','Go_FL/1','autorouting','on');
    add_line(m,'Thrusters/2','Go_FR/1','autorouting','on');
    add_line(m,'Thrusters/3','Go_nprop/1','autorouting','on');

    add_block('ros2lib/Subscribe', [m '/OdomSub'], 'Position',[2350 1000 2480 1060]);
    set_param([m '/OdomSub'], 'topicSource','Specify your own', ...
        'topic','/wamv/sensors/position/ground_truth_odometry', ...
        'messageType','nav_msgs/Odometry', 'sampleTime','Ts_ctrl');

    add_block('simulink/Signal Routing/Bus Selector', [m '/Sel'], ...
              'Position',[2540 980 2590 1110]);
    set_param([m '/Sel'], 'OutputSignals', ...
        ['pose.pose.position.x,pose.pose.position.y,' ...
         'pose.pose.orientation.x,pose.pose.orientation.y,' ...
         'pose.pose.orientation.z,pose.pose.orientation.w,' ...
         'twist.twist.linear.x,twist.twist.linear.y,twist.twist.angular.z']);

    add_block('simulink/Sinks/Display', [m '/IsNew'], 'Position',[2540 920 2620 950]);
    add_line(m,'OdomSub/1','IsNew/1','autorouting','on');
    add_line(m,'OdomSub/2','Sel/1','autorouting','on');

    C(m,'OrgN','origin_north', 2540, 1170);
    C(m,'OrgE','origin_east',  2540, 1215);

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
              [m '/Nav'], 'Position',[2710 970 2880 1190]);
    setFcn(m, 'Nav', [ ...
'function [pn, pe, psi, u, r, beta, chi, U] = Nav(ex, ey, qx, qy, qz, qw, bx, by, wz, orgN, orgE)' newline ...
'%#codegen'                                                                 newline ...
'% Gazebo/ROS uses ENU with a body frame of x-forward, y-LEFT, z-UP.'       newline ...
'% Marine control uses NED with x-forward, y-STARBOARD, z-DOWN.'            newline ...
'% 첫 메시지가 도착하기 전에는 Subscribe 가 0 으로 채운 버스를 낸다.'       newline ...
'% 그대로 쓰면 위치가 스폰 원점만큼(약 568 m) 튀어 로그 첫 점이 망가진다.'  newline ...
'if ex == 0 && ey == 0'                                                     newline ...
'    pn = 0; pe = 0; psi = 0; u = 0; r = 0; beta = 0; chi = 0; U = 0;'      newline ...
'    return'                                                                newline ...
'end'                                                                       newline ...
'pn = ey - orgN;'                                                           newline ...
'pe = ex - orgE;'                                                           newline ...
'yaw_enu = atan2(2*(qw*qz + qx*qy), 1 - 2*(qy*qy + qz*qz));'                newline ...
'p   = pi/2 - yaw_enu;'                                                     newline ...
'psi = atan2(sin(p), cos(p));'                                              newline ...
'u = bx;  v = -by;  r = -wz;'                                               newline ...
'U    = sqrt(u*u + v*v);'                                                   newline ...
'beta = atan2(v, u);'                                                       newline ...
'c    = psi + beta;'                                                        newline ...
'chi  = atan2(sin(c), cos(c));']);

    for k = 1:9
        add_line(m, sprintf('Sel/%d',k), sprintf('Nav/%d',k), 'autorouting','on');
    end
    add_line(m,'OrgN/1','Nav/10','autorouting','on');
    add_line(m,'OrgE/1','Nav/11','autorouting','on');

    tags = {'pn','pe','psi','u','r','beta','chi','U'};
    for k = 1:numel(tags)
        G(m, tags{k}, 2950, 970+(k-1)*40);
        add_line(m, sprintf('Nav/%d',k), ['Go_' tags{k} '/1'], 'autorouting','on');
    end

    addAnimate(m, 2950, 1340);
    addLogging(m, 3400, 60);

    note(m,'n1', ['W09 실습 C  —  VRX 연동' newline ...
        '유도·FSM·내부루프·추진기는 W09_0_offline 과 완전히 같다.' newline ...
        '운동모델만 Gazebo 로 바뀐다.' newline ...
        '실행 전: (1) W09_setup  (2) VRX 기동  (3) 페이싱을 RTF 에 맞출 것'], 300, -130);

    save_system(m); close_system(m);
    fprintf('  W09_1_vrx      생성\n');
end

function addThrusterPublisher(m, side, tag, x, y)
    add_block('ros2lib/Blank Message', [m '/Blank' tag], ...
              'Position', [x y+70 x+100 y+110]);
    set_param([m '/Blank' tag], 'entityType','std_msgs/Float64', ...
              'messageType','std_msgs/Float64', 'SampleTime','Ts_ctrl');
    add_block('simulink/Signal Routing/Bus Assignment', [m '/Asg' tag], ...
              'Position', [x+160 y x+220 y+115]);
    set_param([m '/Asg' tag], 'AssignedSignals','data');
    add_block('ros2lib/Publish', [m '/Pub' tag], ...
              'Position', [x+290 y+35 x+390 y+75]);
    set_param([m '/Pub' tag], 'topicSource','Specify your own', ...
              'topic', ['/wamv/thrusters/' side '/thrust'], ...
              'messageType','std_msgs/Float64');
    add_line(m, ['Blank' tag '/1'], ['Asg' tag '/1'], 'autorouting','on');
    add_line(m, ['Asg'   tag '/1'], ['Pub' tag '/1'], 'autorouting','on');
end
