function build_w04_models()
% BUILD_W04_MODELS  4주차 3~5단계 Simulink 예제 모델 8개를 생성한다.
%
%   이 스크립트를 실행하면 아래 모델이 이 폴더에 만들어진다.
%     W04_1_straight.slx          직진
%     W04_2_turn.slx              시간에 따라 직진 -> 우선회 -> 좌선회
%     W04_3_heading.slx           헤딩 제어 (outer)
%     W04_4_inner_loop.slx        속도 + 헤딩 제어 (inner loop 완성)
%     W04_5_offline.slx           2단계 시나리오를 운동방정식으로
%     W04_3_heading_offline.slx   3단계와 같은 제어기, Gazebo 대신 운동방정식
%     W04_4_inner_loop_offline.slx 4단계와 같은 제어기, Gazebo 대신 운동방정식
%     W04_6_wrap.slx              +-180 deg 이음매. use_ssa 하나로 20 vs 340 deg
%
%   게인과 스위치 값은 전부 W04_setup.m 에 있다. 블록 안에 숫자가 아니라
%   Kp_psi · head_open · port_eff 가 적혀 있는 것이 정상이다.
%
%   3·4단계는 오프라인 쌍둥이가 있다. 제어기 · 배분기 블록은 같은 함수로 만든다.
%   바뀌는 것은 두 자리뿐이다.
%     VRX      : OdomSub -> Sel -> Quat2Yaw  ...  Alloc -> Blank/Asg/Pub (x2)
%     오프라인 : MotionModel (psi, r, u)     ...  Alloc -> MotionModel
%
%   모델이 깨졌을 때 이 스크립트를 다시 돌리면 원래대로 복구된다.
%
%   전제
%     - MATLAB R2024b + Simulink + ROS Toolbox
%     - VRX 가 ground_truth_odometry 를 발행하도록 설정되어 있을 것
%       (강의자료 4주차 B절 참조)

    here = fileparts(mfilename('fullpath'));
    addpath(fullfile(here, '..', '..', '_tools'));
    cd(here);
    load_system('ros2lib');
    if evalin('base', '~exist(''Kp_psi'',''var'')')
        evalin('base', 'W04_setup');
    end

    build_straight();
    build_turn();
    build_heading(false);
    build_inner_loop(false);
    build_offline();
    build_heading(true);
    build_inner_loop(true);
    build_wrap();


    % 배치와 색을 정리한다. 선은 직선 또는 직각으로만 다시 그린다.
    % dir 의 문자 클래스는 Windows 에서 먹지 않는다. 목록을 받아 이름으로 거른다
    slxList = dir('W04_*.slx');
    slxList = slxList(~cellfun(@isempty, regexp({slxList.name}, '^W04_[1-6]_', 'once')));   % 오프라인 쌍둥이 · wrap 포함
    for k = 1:numel(slxList)
        [~, mName] = fileparts(slxList(k).name);
        try

            tidy_model(mName);

            paint_roles(mName);        % 역할표는 _tools/gnc_roles.m 하나뿐이다

            check_colour(mName);

            %  통로를 옮길 수 없는 이름표 위 선은 블록을 비켜서 푼다
            %  (line-routing.md §9. arrangeSystem 이 소스를 통로 밑에 놓는 일이 있다)
            nudge_labels(mName);

            check_lines(mName, true);  % 일곱 항목이 전부 0 이 합격선

            export_model_pngs(mName);

        catch e, warning(e.message); end
    end
    fprintf('\n완료. 생성된 모델:\n');
    d = dir('W04_*.slx');
    for k = 1:numel(d), fprintf('  %s\n', d(k).name); end
end

% =====================================================================
% 공통 헬퍼
% =====================================================================
function addThrusterPublisher(m, side, tag, x, y)
% 추력 발행 3종 세트: Blank Message -> Bus Assignment -> Publish
    add_block('ros2lib/Blank Message', [m '/Blank' tag], ...
              'Position', [x y+70 x+100 y+110]);
    set_param([m '/Blank' tag], 'entityType','std_msgs/Float64', ...
              'messageType','std_msgs/Float64', 'SampleTime','0.05');
    add_block('simulink/Signal Routing/Bus Assignment', [m '/Asg' tag], ...
              'Position', [x+160 y x+220 y+115]);
    set_param([m '/Asg' tag], 'AssignedSignals','data');
    add_block('ros2lib/Publish', [m '/Pub' tag], ...
              'Position', [x+290 y+35 x+390 y+75]);
    set_param([m '/Pub' tag], 'topicSource','Specify your own', ...
              'topic', ['/wamv/thrusters/' side '/thrust'], ...
              'messageType','std_msgs/Float64');
    add_line(m, ['Blank' tag '/1'], ['Asg' tag '/1'], 'autorouting','on');
    add_line(m, ['Asg'   tag '/1'], ['Pub' tag '/1'], 'autorouting','on');
end

function setSolver(m)
    set_param(m, 'SolverType','Fixed-step', 'SolverName','FixedStepDiscrete', ...
                 'FixedStep','0.05', 'StopTime','inf', 'SimulationMode','normal');
end

function setFcn(m, name, code)
    S  = sfroot;
    fpos = get_param([m '/' name], 'Position');   % 포트가 생기며 블록이 멋대로 자란다
    ch = S.find('-isa','Stateflow.EMChart','Path',[m '/' name]);
    ch.Script = code;
    set_param([m '/' name], 'Position', fpos);    % 다시 놓아야 포트 위치가 저장 뒤와 같아진다 (사선 방지)
end

function note(m, txt, x, y)
    add_block('built-in/Note', [m '/note'], ...
              'Position', [x y x y], 'Text', txt);
end

function fresh(m)
    try, close_system(m, 0); catch, end
    if exist([m '.slx'],'file'), delete([m '.slx']); end
    new_system(m);
end

% =====================================================================
% 1단계 — 직진
% =====================================================================
function build_straight()
    m = 'W04_1_straight'; fresh(m);

    add_block('simulink/Sources/Constant', [m '/FL'], ...
              'Value','200', 'Position',[40 95 100 125]);
    add_block('simulink/Sources/Constant', [m '/FR'], ...
              'Value','200', 'Position',[40 275 100 305]);

    addThrusterPublisher(m, 'left',  'L', 200, 60);
    addThrusterPublisher(m, 'right', 'R', 200, 240);

    add_line(m,'FL/1','AsgL/2','autorouting','on');
    add_line(m,'FR/1','AsgR/2','autorouting','on');

    setSolver(m);
    note(m, sprintf(['[1단계] 직진\n' ...
        '좌우 추력을 같은 값(200 N)으로 발행한다.\n' ...
        'FL 과 FR 값을 바꿔 보고 배가 어떻게 반응하는지 관찰할 것.']), 40, 400);
    save_system(m); close_system(m,0);
    fprintf('  [OK] %s\n', m);
end

% =====================================================================
% 2단계 — 직진 / 우선회 / 좌선회
% =====================================================================
function build_turn()
    m = 'W04_2_turn'; fresh(m);

    add_block('simulink/Sources/Digital Clock', [m '/Clock'], ...
              'SampleTime','0.05', 'Position',[40 185 100 215]);
    add_block('simulink/User-Defined Functions/MATLAB Function', [m '/Scenario'], ...
              'Position',[150 165 280 235]);
    setFcn(m, 'Scenario', [ ...
        'function [FL, FR] = Scenario(t)' newline ...
        '%#codegen' newline ...
        '% Time-based thrust scenario [N]' newline ...
        'if t < 20' newline ...
        '    FL = 200;  FR = 200;   % go straight' newline ...
        'elseif t < 40' newline ...
        '    FL = 300;  FR =  50;   % turn starboard (right)' newline ...
        'elseif t < 60' newline ...
        '    FL =  50;  FR = 300;   % turn port (left)' newline ...
        'else' newline ...
        '    FL = 0;    FR = 0;     % stop' newline ...
        'end' newline]);

    addThrusterPublisher(m, 'left',  'L', 360, 60);
    addThrusterPublisher(m, 'right', 'R', 360, 240);

    add_line(m,'Clock/1','Scenario/1','autorouting','on');
    add_line(m,'Scenario/1','AsgL/2','autorouting','on');
    add_line(m,'Scenario/2','AsgR/2','autorouting','on');

    setSolver(m);
    set_param(m,'StopTime','80');
    note(m, sprintf(['[2단계] 직진 -> 우선회 -> 좌선회\n' ...
        '0~20s 직진 / 20~40s 우선회 / 40~60s 좌선회 / 60s~ 정지\n' ...
        '좌현 추력이 크면 뱃머리가 오른쪽으로 돈다.']), 40, 400);
    save_system(m); close_system(m,0);
    fprintf('  [OK] %s\n', m);
end

% =====================================================================
% 상태 읽기 블록 (3·4단계 공통)
% =====================================================================
function addOdomReader(m, withSpeed)
    add_block('ros2lib/Subscribe', [m '/OdomSub'], 'Position',[40 40 160 100]);
    set_param([m '/OdomSub'], 'topicSource','Specify your own', ...
              'topic','/wamv/sensors/position/ground_truth_odometry', ...
              'messageType','nav_msgs/Odometry', 'sampleTime','0.05');

    sig = ['pose.pose.orientation.x,pose.pose.orientation.y,' ...
           'pose.pose.orientation.z,pose.pose.orientation.w'];
    if withSpeed
        sig = [sig ',twist.twist.linear.x'];
    end
    %  요각속도는 **항상** 뽑는다. 헤딩 제어의 D 항이 이 값을 쓴다.
    %  맨 뒤에 붙이므로 앞의 포트 번호는 그대로다.
    sig = [sig ',twist.twist.angular.z'];
    iWz = 5 + double(withSpeed);

    add_block('simulink/Signal Routing/Bus Selector', [m '/Sel'], ...
              'Position',[210 40 220 140]);
    set_param([m '/Sel'], 'OutputSignals', sig);
    add_line(m,'OdomSub/2','Sel/1','autorouting','on');

    add_block('simulink/User-Defined Functions/MATLAB Function', [m '/Quat2Yaw'], ...
              'Position',[280 40 400 110]);
    setFcn(m, 'Quat2Yaw', [ ...
        'function [psi_ned, r] = Quat2Yaw(qx, qy, qz, qw, wz)' newline ...
        '%#codegen' newline ...
        '% ROS quaternion (ENU body) -> NED heading [rad] and yaw rate [rad/s]' newline ...
        'yaw_enu = atan2(2*(qw*qz + qx*qy), 1 - 2*(qy*qy + qz*qz));' newline ...
        'psi = pi/2 - yaw_enu;' newline ...
        'psi_ned = atan2(sin(psi), cos(psi));   % wrap to [-pi, pi]' newline ...
        '' newline ...
        '% psi_ned = pi/2 - yaw_enu  ->  d(psi_ned)/dt = -d(yaw_enu)/dt.' newline ...
        '% ENU is z-up and NED is z-down, so the turn direction flips.' newline ...
        'r = -wz;' newline]);
    for k = 1:4
        add_line(m, sprintf('Sel/%d',k), sprintf('Quat2Yaw/%d',k), 'autorouting','on');
    end
    add_line(m, sprintf('Sel/%d',iWz), 'Quat2Yaw/5', 'autorouting','on');
end

% =====================================================================
% 헤딩 제어기 (3·4단계 공통) — 독립 모듈 하나
% =====================================================================
function addHeadingCtrl(m, x, y)
% 헤딩 제어기를 **서브시스템 하나**로 만든다. 밖에서는 이 상자만 보인다.
%
%   입력  psi_ref [rad]    목표 선수각
%         psi     [rad]    지금 선수각
%         r       [rad/s]  지금 요각속도 (NED)
%   출력  N       [N*m]    요 모멘트 지령
%
%   제어식 — P 는 오차에, D 는 **요각속도에 직접**
%
%       N = Kp_psi * ssa(psi_ref - psi)  +  Ki_psi * INT(e)  +  Kd_psi * r
%
%   Kd_psi 는 **음수**다 (-400). 부호를 식 안에 넣지 않고 게인에 넣어 두면
%   블록 하나만 보고도 "브레이크가 걸려 있구나" 를 알 수 있다.
%
%   Ki_psi 는 기본 0 이다. 한쪽 추진기가 약할 때(port_eff < 1) PD 가 남기는
%   정상상태 오차를 없애는 자리이고, 그때만 켠다.
%
%   use_ssa 스위치 — HeadingErr 안의 if 한 줄
%       1 이면 ssa 로 접은 최단 오차, 0 이면 그냥 뺀 값이다. +-180 deg
%       이음매에서 20 deg 대신 340 deg 를 도는 것을 보이는 스위치다 (W04_6_wrap).
%
%   왜 오차를 미분하지 않는가
%       e = psi_ref - psi 이므로 de/dt = d(psi_ref)/dt - r 이고, 목표가 가만히
%       있는 동안에는 de/dt = -r 이다. 즉 -Kd*r 과 +Kd*de/dt 는 **같은 값**이다.
%       다만 목표가 계단으로 바뀌는 순간 de/dt 는 크게 튀고(미분 킥), r 은 배의
%       실제 회전이라 튀지 않는다. 같은 값을 더 얌전한 신호로 얻는 셈이다.
%
%   왜 마이너스인가
%       D 항은 **브레이크**다. 배가 왼쪽으로 돌고 있으면(r < 0) 그 회전을 멈추는
%       방향으로 모멘트를 내야 하므로 부호가 반대여야 한다. 마이너스를 빼면
%       감쇠가 Nr + Kd 에서 Nr - Kd 로 줄어 오버슈트가 커진다 (Kd = 400 에서 17 %,
%       4주차 1-7절·W04_heading_sign). 2차 항력 Nrr 이 버텨 발산까지는 가지 않는다.
%
%   MSS 툴박스의 demoOtterUSVHeadingControl 도 같은 구조다 (Fossen). 그쪽 D 항은
%   Kp*Td*(r_d - r) 인데, 목표 각속도 r_d = 0 이면 -Kp*Td*r 이다.

    s = add_subsys(m, 'HeadingCtrl', [x y x+150 y+90], ...
                   {'psi_ref','psi','r'}, {'N'}, gnc_colour('control'));

    %  use_ssa 가 0 이면 ssa 를 건너뛴다 — 같은 상자 안의 두 줄을 비교해 볼 것
    add_block('simulink/Sources/Constant', [s '/use_ssa_c'], ...
              'Value','use_ssa', 'Position',[60 260 160 290]);
    add_block('simulink/User-Defined Functions/MATLAB Function', [s '/HeadingErr'], ...
              'Position',[250 60 400 170]);
    setFcn(s, 'HeadingErr', [ ...
        'function e = HeadingErr(psi_ref, psi, use_ssa)' newline ...
        '%#codegen' newline ...
        '% Heading error [rad].' newline ...
        'd = psi_ref - psi;' newline ...
        'if use_ssa >= 0.5' newline ...
        '    % ssa : shortest signed angle, wrapped to (-pi, pi]' newline ...
        '    e = atan2(sin(d), cos(d));' newline ...
        'else' newline ...
        '    % no wrap : 170 deg -> -170 deg becomes -340 deg, not +20 deg' newline ...
        '    e = d;' newline ...
        'end' newline]);

    add_block('simulink/Math Operations/Gain', [s '/Kp_psi'], ...
              'Gain','Kp_psi', 'Position',[520 80 570 110]);
    add_block('simulink/Math Operations/Gain', [s '/Ki_psi'], ...
              'Gain','Ki_psi', 'Position',[520 170 570 200]);
    %  **이산** 적분기를 쓴다. VRX 쌍둥이는 FixedStepDiscrete 솔버라
    %  연속 적분기를 넣으면 "연속 상태가 포함되어 있다" 로 시뮬레이션이 막힌다.
    %  샘플 주기 0.05 s 는 오프라인(ode4/0.05)과 VRX 양쪽의 고정 스텝과 같다.
    add_block('simulink/Discrete/Discrete-Time Integrator', [s '/IntegN'], ...
              'InitialCondition','0', 'SampleTime','0.05', 'LimitOutput','on', ...
              'UpperSaturationLimit','N_max', 'LowerSaturationLimit','-N_max', ...
              'Position',[620 170 650 200]);
    add_block('simulink/Math Operations/Gain', [s '/Kd_rate'], ...
              'Gain','Kd_psi', 'Position',[520 340 570 370]);
    add_block('simulink/Math Operations/Sum', [s '/SumPD'], ...
              'Inputs','++', 'Position',[700 80 730 110]);
    add_block('simulink/Math Operations/Sum', [s '/SumN'], ...
              'Inputs','++', 'Position',[790 80 820 110]);
    add_block('simulink/Discontinuities/Saturation', [s '/SatN'], ...
              'UpperLimit','N_max', 'LowerLimit','-N_max', ...
              'Position',[880 80 920 110]);

    add_line(s,'psi_ref/1',  'HeadingErr/1','autorouting','on');
    add_line(s,'psi/1',      'HeadingErr/2','autorouting','on');
    add_line(s,'use_ssa_c/1','HeadingErr/3','autorouting','on');
    add_line(s,'HeadingErr/1','Kp_psi/1','autorouting','on');
    add_line(s,'HeadingErr/1','Ki_psi/1','autorouting','on');
    add_line(s,'Ki_psi/1','IntegN/1','autorouting','on');
    add_line(s,'r/1',      'Kd_rate/1','autorouting','on');
    add_line(s,'Kp_psi/1', 'SumPD/1','autorouting','on');
    add_line(s,'Kd_rate/1','SumPD/2','autorouting','on');
    add_line(s,'SumPD/1',  'SumN/1','autorouting','on');
    add_line(s,'IntegN/1', 'SumN/2','autorouting','on');
    add_line(s,'SumN/1',   'SatN/1','autorouting','on');
    add_line(s,'SatN/1',   'N/1','autorouting','on');

    note(s, sprintf(['헤딩 제어기 — P 는 오차에, D 는 요각속도에\n' ...
        '\n' ...
        '    N = Kp_psi * e  +  Ki_psi * INT(e)  +  Kd_psi * r\n' ...
        '    e = ssa(psi_ref - psi)   (use_ssa = 0 이면 그냥 뺀 값)\n' ...
        '\n' ...
        'Kd_psi 가 음수(-400)인 것이 브레이크다. 돌고 있는 방향의 반대로 낸다.\n' ...
        '부호를 빼면 감쇠가 Nr - Kd 로 줄어 오버슈트가 커진다 (17 %%).\n' ...
        '\n' ...
        '목표가 가만히 있으면 de/dt = -r 이므로 오차 미분과 값이 같다.\n' ...
        '다만 목표가 계단으로 바뀔 때 de/dt 는 튀고 r 은 튀지 않는다.\n' ...
        '\n' ...
        'Ki_psi 는 기본 0 이다. 한쪽 추진기가 약할 때(port_eff < 1)\n' ...
        'PD 가 남기는 정상상태 오차를 없애는 자리다.\n' ...
        '적분기에는 +-N_max 포화가 걸려 있다 (clamping 안티와인드업).\n' ...
        '\n' ...
        '값은 전부 W04_setup.m — Kp_psi = 800, Kd_psi = -400.\n' ...
        '근거는 4주차 극배치 절과 W04_pole_place.m.']), 200, 430);
end

% =====================================================================
% 배분기 (3·4단계 공통) — 차동 추력배분 + 포화
% =====================================================================
function addAllocator(m, x, y)
    add_block('simulink/User-Defined Functions/MATLAB Function', [m '/Alloc'], ...
              'Position',[x y x+140 y+70]);
    setFcn(m, 'Alloc', [ ...
        'function [FL, FR] = Alloc(X, N)' newline ...
        '%#codegen' newline ...
        '% Differential thrust allocation for the 2-thruster WAM-V' newline ...
        '%   X : surge force  [N]' newline ...
        '%   N : yaw moment   [N*m], positive turns to starboard' newline ...
        'B_half = 1.027135;      % half distance between thrusters [m]' newline ...
        'Fmax   = 250;           % thrust limit per thruster [N]' newline ...
        'FL = X/2 + N/(2*B_half);' newline ...
        'FR = X/2 - N/(2*B_half);' newline ...
        'FL = max(min(FL, Fmax), -Fmax);' newline ...
        'FR = max(min(FR, Fmax), -Fmax);' newline]);
end

% =====================================================================
% 오프라인 운동모델 (3·4단계 쌍둥이 공통) — Gazebo 자리를 대신한다
%   입력 FL, FR [N]   출력 psi [rad], r [rad/s], u [m/s]
%   식과 계수는 3주차 1-8 절 · W03_0_offline 과 같다.
%   초기 선수각은 VRX 스폰과 같게 32.7 deg (3주차 3-1 좌표 검산)
% =====================================================================
function addMotionModel(m, x, y, psi0)
%   PSI0  초기 선수각을 rad 로 적은 문자열. 생략하면 VRX 스폰과 같은 32.7 deg
    if nargin < 4 || isempty(psi0), psi0 = '32.7*pi/180'; end
    s = add_subsys(m, 'MotionModel', [x y x+150 y+110], ...
                   {'FL','FR'}, {'psi','r','u'}, gnc_colour('plant'));
    add_block('simulink/User-Defined Functions/MATLAB Function', [s '/EOM'], ...
              'Position',[200 40 340 160]);
    setFcn(s, 'EOM', [ ...
'function xdot = EOM(s, FL, FR)'                                        newline ...
'%#codegen'                                                             newline ...
'% 3-DOF WAM-V equations of motion, NED (3주차 1-8 절).'                  newline ...
'%   s = [u v r x_n y_n psi]'''                                          newline ...
'm = 211;  Izz = 653;  Xu = 100;  Xuu = 150;  Yv = 100;  Yvv = 100;'    newline ...
'Nr = 800;  Nrr = 800;  b_half = 1.027135;'                             newline ...
'u = s(1); v = s(2); r = s(3); psi = s(6);'                             newline ...
'X = FL + FR;'                                                          newline ...
'N = (FL - FR)*b_half;'                                                 newline ...
'du = (X - (Xu + Xuu*abs(u))*u)/m + v*r;'                               newline ...
'dv = (  - (Yv + Yvv*abs(v))*v)/m - u*r;'                               newline ...
'dr = (N - (Nr + Nrr*abs(r))*r)/Izz;'                                   newline ...
'xdot = [du; dv; dr;'                                                   newline ...
'        u*cos(psi) - v*sin(psi);'                                      newline ...
'        u*sin(psi) + v*cos(psi);'                                      newline ...
'        r];']);
    add_block('simulink/Continuous/Integrator', [s '/Integ'], ...
              'Position',[400 80 440 120], ...
              'InitialCondition',['[0;0;0;0;0;' psi0 ']']);
    add_block('simulink/User-Defined Functions/MATLAB Function', [s '/States'], ...
              'Position',[500 40 620 160]);
    setFcn(s, 'States', [ ...
'function [psi, r, u] = States(s)'                                      newline ...
'%#codegen'                                                             newline ...
'% Quat2Yaw 와 같은 출력 — 선수각은 [-pi, pi] 로 접는다'                   newline ...
'psi = atan2(sin(s(6)), cos(s(6)));'                                    newline ...
'r = s(3);'                                                             newline ...
'u = s(1);']);
    add_line(s,'FL/1','EOM/2','autorouting','on');
    add_line(s,'FR/1','EOM/3','autorouting','on');
    add_line(s,'EOM/1','Integ/1','autorouting','on');
    add_line(s,'Integ/1','EOM/1','autorouting','on');
    add_line(s,'Integ/1','States/1','autorouting','on');
    add_line(s,'States/1','psi/1','autorouting','on');
    add_line(s,'States/2','r/1','autorouting','on');
    add_line(s,'States/3','u/1','autorouting','on');
end

function setSolverOffline(m)
    % 연속 적분기가 있으므로 ode4. 스텝은 VRX 모델과 같은 0.05 s
    set_param(m, 'SolverType','Fixed-step', 'SolverName','ode4', ...
                 'FixedStep','0.05', 'StopTime','40', 'SimulationMode','normal');
end

function addLog(m, src, name, x, y)
    % To Workspace — W04_step_compare 가 VRX 와 오프라인을 같은 이름으로 꺼낸다
    b = [m '/log_' name];
    add_block('simulink/Sinks/To Workspace', b, 'Position',[x y x+90 y+26]);
    set_param(b, 'VariableName',['log_' name], 'SaveFormat','Timeseries', 'SampleTime','0.05');
    add_line(m, src, ['log_' name '/1'], 'autorouting','on');
end

% =====================================================================
% 3단계 — 헤딩 제어  (offline = true 이면 오프라인 쌍둥이)
% =====================================================================
function build_heading(offline)
    if offline
        m = 'W04_3_heading_offline'; fresh(m);
        addMotionModel(m, 780, 200);
        sPsi = 'MotionModel/1';  sR = 'MotionModel/2';
    else
        m = 'W04_3_heading'; fresh(m);
        addOdomReader(m, false);
        sPsi = 'Quat2Yaw/1';  sR = 'Quat2Yaw/2';
    end

    add_block('simulink/Sources/Constant', [m '/psi_ref_deg'], ...
              'Value','psi_ref_deg', 'Position',[40 200 130 230]);
    add_block('simulink/Math Operations/Gain', [m '/deg2rad'], ...
              'Gain','pi/180', 'Position',[160 200 200 230]);
    addHeadingCtrl(m, 300, 185);

    %  제어기를 통째로 건너뛰는 스위치. head_open = 1 이면 계단 모멘트를 직접 준다
    add_switch_box(m, 'OpenLoop', [500 185 640 275], {'N_ctrl','N_raw'}, 'head_open', ...
        struct('name','N_step', 'lib','simulink/Sources/Constant', ...
               'params',{{'Value','N_open'}}, 'fed',false, 'w',55, 'h',30), ...
        gnc_colour('control'), sprintf([ ...
        '제어기를 쓸 것인가, 요 모멘트를 직접 줄 것인가\n' ...
        '\n' ...
        '  head_open = 0   HeadingCtrl 이 낸 모멘트 (폐루프)\n' ...
        '  head_open = 1   N_open [N m] 을 그대로 (개루프)\n' ...
        '\n' ...
        '개루프로 두고 Scope 를 보면 선수각이 **끝없이 올라간다.**\n' ...
        '일정 모멘트 -> 일정 선회율 -> psi 는 멈추지 않는다.\n' ...
        '배가 이미 적분기를 하나 갖고 있다는 뜻이다 (dpsi/dt = r).\n' ...
        '\n' ...
        '  >> W04_heading_compare(''open'')']));

    add_block('simulink/Sources/Constant', [m '/X_const'], ...
              'Value','X_head', 'Position',[430 340 510 370]);

    addAllocator(m, 700, 210);
    add_line(m,'X_const/1','Alloc/1','autorouting','on');
    add_line(m,'HeadingCtrl/1','OpenLoop/1','autorouting','on');
    add_line(m,'OpenLoop/1','Alloc/2','autorouting','on');
    add_line(m,'psi_ref_deg/1','deg2rad/1','autorouting','on');
    add_line(m,'deg2rad/1', 'HeadingCtrl/1','autorouting','on');
    add_line(m,sPsi,'HeadingCtrl/2','autorouting','on');
    add_line(m,sR,  'HeadingCtrl/3','autorouting','on');

    %  좌현 추진기를 약하게 만드는 자리. port_eff = 1 이면 아무 일도 안 한다
    add_block('simulink/Math Operations/Gain', [m '/PortEff'], ...
              'Gain','port_eff', 'Position',[880 200 930 236]);
    add_line(m,'Alloc/1','PortEff/1','autorouting','on');

    if offline
        add_line(m,'PortEff/1','MotionModel/1','autorouting','on');
        add_line(m,'Alloc/2',  'MotionModel/2','autorouting','on');
    else
        addThrusterPublisher(m, 'left',  'L', 1000, 150);
        addThrusterPublisher(m, 'right', 'R', 1000, 320);
        add_line(m,'PortEff/1','AsgL/2','autorouting','on');
        add_line(m,'Alloc/2',  'AsgR/2','autorouting','on');
    end

    % 관찰용
    add_block('simulink/Sinks/Scope', [m '/Scope_psi'], 'Position',[430 60 480 110]);
    set_param([m '/Scope_psi'],'NumInputPorts','2');
    add_line(m,sPsi,'Scope_psi/1','autorouting','on');
    add_line(m,'deg2rad/1','Scope_psi/2','autorouting','on');
    addLog(m, sPsi, 'psi', 1200, 60);
    addLog(m, 'PortEff/1', 'FL', 1200, 110);
    addLog(m, 'Alloc/2',   'FR', 1200, 160);
    addLog(m, sR,          'r',  1200, 210);
    addLog(m, 'OpenLoop/1','N',  1200, 260);

    if offline
        setSolverOffline(m);
        note(m, sprintf(['[3단계 오프라인] 헤딩 제어 — Gazebo 대신 운동방정식\n' ...
            'W04_3_heading 과 HeadingCtrl · OpenLoop · Alloc 이 같은 함수로 만들어졌다.\n' ...
            'OdomSub/Quat2Yaw 와 Publish 자리에 MotionModel 하나가 있다.\n' ...
            '초기 선수각 32.7 deg 는 VRX 스폰과 같다. 40 초가 1 초 안쪽에 끝난다.\n' ...
            '\n' ...
            '스위치는 전부 W04_setup.m 에 있다.\n' ...
            '  head_open = 0/1   폐루프 / 개루프 (OpenLoop 상자)\n' ...
            '  use_ssa   = 0/1   ssa 끔 / 켬     (HeadingCtrl 안)\n' ...
            '  port_eff  = 0.7   좌현 추진기를 30 %% 약하게 (PortEff 게인)\n' ...
            '  Ki_psi    > 0     port_eff 가 남긴 오차를 I 로 지운다\n' ...
            '\n' ...
            '  >> W04_heading_compare(''open''|''Kp''|''Kd''|''Ki''|''wrap'')\n' ...
            '비교: >> W04_step_compare(3)']), 40, 520);
        save_system(m); close_system(m,0);
        fprintf('  [OK] %s\n', m);
        return
    end
    setSolver(m);
    note(m, sprintf(['[3단계] 헤딩 제어\n' ...
        '목표 선수각(psi_ref_deg)을 바꿔 가며 스텝응답을 본다.\n' ...
        'Scope_psi 에 실제 헤딩과 목표 헤딩이 함께 그려진다.\n' ...
        '\n' ...
        '제어기는 HeadingCtrl 상자 하나다. 더블클릭하면 안이 보인다.\n' ...
        '  N = Kp_psi * ssa(psi_ref - psi) + Ki_psi * INT(e) + Kd_psi * r\n' ...
        '게인은 전부 W04_setup.m 에 있다. 오프라인 쌍둥이와 **같은 변수**다.\n' ...
        'Kp_psi, Kd_psi 를 조정해 오버슈트와 정정시간을 비교할 것.\n' ...
        '먼저 W04_3_heading_offline 으로 숫자를 적어 두고 VRX 를 켠다.']), 40, 520);
    save_system(m); close_system(m,0);
    fprintf('  [OK] %s\n', m);
end

% =====================================================================
% 4단계 — 속도 + 헤딩 (inner loop)
% =====================================================================
function build_inner_loop(offline)
    if offline
        m = 'W04_4_inner_loop_offline'; fresh(m);
        addMotionModel(m, 780, 230);
        sPsi = 'MotionModel/1';  sR = 'MotionModel/2';  sU = 'MotionModel/3';
    else
        m = 'W04_4_inner_loop'; fresh(m);
        addOdomReader(m, true);          % twist.twist.linear.x 까지 뽑음
        sPsi = 'Quat2Yaw/1';  sR = 'Quat2Yaw/2';  sU = 'Sel/5';
    end

    % --- 헤딩 루프 ---
    add_block('simulink/Sources/Constant', [m '/psi_ref_deg'], ...
              'Value','psi_ref_deg', 'Position',[40 200 130 230]);
    add_block('simulink/Math Operations/Gain', [m '/deg2rad'], ...
              'Gain','pi/180', 'Position',[160 200 200 230]);
    addHeadingCtrl(m, 300, 185);

    % --- 속도 루프 ---
    add_block('simulink/Sources/Constant', [m '/u_ref'], ...
              'Value','1.5', 'Position',[40 320 130 350]);
    add_block('simulink/Math Operations/Sum', [m '/SumU'], ...
              'Inputs','+-', 'Position',[210 320 240 350]);
    add_block('simulink/Discrete/Discrete PID Controller', [m '/PI_u'], ...
              'Position',[290 310 370 360]);
    set_param([m '/PI_u'], 'Controller','PI', 'P','300', 'I','40', ...
              'SampleTime','0.05', 'LimitOutput','on', ...
              'UpperSaturationLimit','500', 'LowerSaturationLimit','-500', ...
              'AntiWindupMode','clamping');

    addAllocator(m, 570, 240);
    add_line(m,'psi_ref_deg/1','deg2rad/1','autorouting','on');
    add_line(m,'deg2rad/1', 'HeadingCtrl/1','autorouting','on');
    add_line(m,sPsi,'HeadingCtrl/2','autorouting','on');
    add_line(m,sR,  'HeadingCtrl/3','autorouting','on');
    add_line(m,'u_ref/1','SumU/1','autorouting','on');
    add_line(m,sU,'SumU/2','autorouting','on');
    add_line(m,'SumU/1','PI_u/1','autorouting','on');
    add_line(m,'PI_u/1','Alloc/1','autorouting','on');
    add_line(m,'HeadingCtrl/1','Alloc/2','autorouting','on');

    if offline
        add_line(m,'Alloc/1','MotionModel/1','autorouting','on');
        add_line(m,'Alloc/2','MotionModel/2','autorouting','on');
    else
        addThrusterPublisher(m, 'left',  'L', 780, 180);
        addThrusterPublisher(m, 'right', 'R', 780, 350);
        add_line(m,'Alloc/1','AsgL/2','autorouting','on');
        add_line(m,'Alloc/2','AsgR/2','autorouting','on');
    end

    % 관찰용
    add_block('simulink/Sinks/Scope', [m '/Scope_u'], 'Position',[430 60 480 110]);
    set_param([m '/Scope_u'],'NumInputPorts','2');
    add_line(m,sU,'Scope_u/1','autorouting','on');
    add_line(m,'u_ref/1','Scope_u/2','autorouting','on');

    add_block('simulink/Sinks/Scope', [m '/Scope_psi'], 'Position',[430 120 480 170]);
    set_param([m '/Scope_psi'],'NumInputPorts','2');
    add_line(m,sPsi,'Scope_psi/1','autorouting','on');
    add_line(m,'deg2rad/1','Scope_psi/2','autorouting','on');
    addLog(m, sPsi, 'psi', 1000, 60);
    addLog(m, sU,   'u',   1000, 110);
    addLog(m, 'Alloc/1', 'FL', 1000, 160);
    addLog(m, 'Alloc/2', 'FR', 1000, 210);

    if offline
        setSolverOffline(m);
        note(m, sprintf(['[4단계 오프라인] 속도 + 헤딩 — Gazebo 대신 운동방정식\n' ...
            'W04_4_inner_loop 과 HeadingCtrl · PI_u · Alloc 이 같은 함수로 만들어졌다.\n' ...
            'OdomSub/Sel/Quat2Yaw 와 Publish 자리에 MotionModel 하나가 있다.\n' ...
            '초기 선수각 32.7 deg (VRX 스폰), 초기 속도 0.\n' ...
            '비교: >> W04_step_compare(4)']), 40, 500);
        save_system(m); close_system(m,0);
        fprintf('  [OK] %s\n', m);
        return
    end
    setSolver(m);
    note(m, sprintf(['[4단계] 속도 + 헤딩 (inner loop)\n' ...
        'u_ref [m/s] 와 psi_ref_deg [deg] 를 각각 바꿔 가며 응답을 본다.\n' ...
        '속도는 ground_truth_odometry 의 twist.twist.linear.x 를 그대로 쓴다.\n' ...
        '\n' ...
        '제어기는 상자 두 개다 — HeadingCtrl (요 모멘트), PI_u (전진력).\n' ...
        'HeadingCtrl 의 D 항은 요각속도 r 을 직접 되먹인다 (-Kd*r).\n' ...
        'PI_u 는 안티와인드업(clamping)이 켜져 있다.']), 40, 500);
    save_system(m); close_system(m,0);
    fprintf('  [OK] %s\n', m);
end

% =====================================================================
% 6단계 — +-180 deg 이음매. 스위치 하나로 두 번 Run 한다
%
%   170 deg 에서 -170 deg 로 가라고 시킨다. 최단 거리는 20 deg 다.
%   그런데 그냥 빼면 -170 - 170 = -340 deg 가 나온다.
%   배는 그 말을 곧이곧대로 듣고 **반대쪽으로 340 deg** 를 돈다.
%
%   시계에서 11시 -> 1시는 2시간이지 10시간이 아니다. ssa 가 그 계산이다.
% =====================================================================
function build_wrap()
    m = 'W04_6_wrap'; fresh(m);

    add_block('simulink/Sources/Constant', [m '/psi_ref_deg'], ...
              'Value','psi_ref_wrap_deg', 'Position',[40 200 150 230]);
    add_block('simulink/Math Operations/Gain', [m '/deg2rad'], ...
              'Gain','pi/180', 'Position',[190 200 230 230]);
    addHeadingCtrl(m, 320, 185);

    %  제자리에서 돌기만 한다 — 전진 추력 0. 도는 각도만 보면 되기 때문이다
    add_block('simulink/Sources/Constant', [m '/X_const'], ...
              'Value','0', 'Position',[430 340 510 370]);

    addAllocator(m, 560, 210);
    addMotionModel(m, 780, 200, 'psi0_deg*pi/180');

    add_line(m,'psi_ref_deg/1','deg2rad/1','autorouting','on');
    add_line(m,'deg2rad/1','HeadingCtrl/1','autorouting','on');
    add_line(m,'MotionModel/1','HeadingCtrl/2','autorouting','on');
    add_line(m,'MotionModel/2','HeadingCtrl/3','autorouting','on');
    add_line(m,'X_const/1','Alloc/1','autorouting','on');
    add_line(m,'HeadingCtrl/1','Alloc/2','autorouting','on');
    add_line(m,'Alloc/1','MotionModel/1','autorouting','on');
    add_line(m,'Alloc/2','MotionModel/2','autorouting','on');

    add_block('simulink/Sinks/Scope', [m '/Scope_psi'], 'Position',[430 60 480 110]);
    set_param([m '/Scope_psi'],'NumInputPorts','2');
    add_line(m,'MotionModel/1','Scope_psi/1','autorouting','on');
    add_line(m,'deg2rad/1',    'Scope_psi/2','autorouting','on');
    addLog(m, 'MotionModel/1', 'psi', 1000, 60);
    addLog(m, 'MotionModel/2', 'r',   1000, 110);
    addLog(m, 'HeadingCtrl/1', 'N',   1000, 160);

    setSolverOffline(m);
    set_param(m, 'StopTime','30');
    note(m, sprintf(['[6단계] +-180 deg 이음매 — 스위치 하나로 두 번 Run\n' ...
        '\n' ...
        '  초기 선수각 psi0_deg        = 170 deg\n' ...
        '  목표 선수각 psi_ref_wrap_deg = -170 deg\n' ...
        '  최단 거리는 20 deg 다.\n' ...
        '\n' ...
        '  >> use_ssa = 1;  sim(''W04_6_wrap'')    20 deg 만 돈다\n' ...
        '  >> use_ssa = 0;  sim(''W04_6_wrap'')    반대쪽으로 340 deg 를 돈다\n' ...
        '  >> W04_setup                          기본값(1)으로 되돌리기\n' ...
        '\n' ...
        '스위치는 HeadingCtrl 안의 HeadingErr 한 줄이다. 더블클릭해 볼 것.\n' ...
        '  use_ssa = 1  e = atan2(sin(d), cos(d))   d 를 (-180, 180] 로 접는다\n' ...
        '  use_ssa = 0  e = d = psi_ref - psi       -340 deg 가 그대로 들어간다\n' ...
        '\n' ...
        '전진 추력은 0 이다. 제자리에서 도는 각도만 본다.\n' ...
        '  >> W04_heading_compare(''wrap'')   두 경우의 총 회전각을 재서 표로']), 40, 470);
    save_system(m); close_system(m,0);
    fprintf('  [OK] %s\n', m);
end

% =====================================================================
% 5단계 · 오프라인 WAM-V — Gazebo 없이 같은 실험을 한다
%
%   앞의 네 모델은 추력을 ROS 2 토픽으로 내보내고 Gazebo 가 배를 움직였다.
%   이 모델은 그 자리에 WAM-V 운동방정식을 직접 넣는다.
%   시나리오 블록은 2단계(W04_2_turn)와 글자 하나까지 같다.
%   바뀌는 것은 뒷단뿐이다.
%
%     W04_2_turn    : Scenario -> Blank/Assign/Publish -> Gazebo
%     W04_5_offline : Scenario -> MotorLag -> MotionModel -> Scope
% =====================================================================
function build_offline()
    m = 'W04_5_offline'; fresh(m);

    % --- 1단 · 시나리오 (2단계와 같은 코드) ---------------------------
    add_block('simulink/Sources/Digital Clock', [m '/Clock'], ...
              'SampleTime','0.05', 'Position',[40 185 100 215]);
    add_block('simulink/User-Defined Functions/MATLAB Function', [m '/Scenario'], ...
              'Position',[150 165 280 235]);
    setFcn(m, 'Scenario', [ ...
        'function [FL, FR] = Scenario(t)' newline ...
        '%#codegen' newline ...
        '% Time-based thrust scenario [N] - identical to W04_2_turn' newline ...
        'if t < 20' newline ...
        '    FL = 200;  FR = 200;   % go straight' newline ...
        'elseif t < 40' newline ...
        '    FL = 300;  FR =  50;   % turn starboard (right)' newline ...
        'elseif t < 60' newline ...
        '    FL =  50;  FR = 300;   % turn port (left)' newline ...
        'else' newline ...
        '    FL = 0;    FR = 0;     % stop' newline ...
        'end' newline]);

    % --- 2단 · 추진기 (모터 1차 지연) ---------------------------------
    add_block('simulink/Signal Routing/Mux', [m '/MuxF'], ...
              'Inputs','2', 'Position',[340 175 345 225]);
    add_block('simulink/Discrete/Discrete Transfer Fcn', [m '/MotorLag'], ...
              'Position',[400 175 520 225]);
    set_param([m '/MotorLag'], 'Numerator','0.05/0.30', ...
              'Denominator','[1, 0.05/0.30 - 1]', 'SampleTime','0.05');

    % --- 3단 · WAM-V 운동모델 -----------------------------------------
    add_block('simulink/User-Defined Functions/MATLAB Function', [m '/EOM'], ...
              'Position',[580 140 760 260]);
    setFcn(m, 'EOM', [ ...
'function xdot = EOM(s, F)'                                              newline ...
'%#codegen'                                                              newline ...
'% 3-DOF WAM-V equations of motion in NED.'                              newline ...
'% Every coefficient below is taken from the Gazebo VRX plugins, so'     newline ...
'% this model and the simulator answer the same question the same way.'  newline ...
'%   drag : wamv_gazebo_dynamics_plugin.xacro (SimpleHydrodynamics)'     newline ...
'%   mass : 211 kg = 180 hull + 2x15 engines + 2x0.5 propellers'         newline ...
'%   added mass is zero in VRX (xDotU = yDotV = nDotR = 0)'              newline ...
'%   s = [u v r x_n y_n psi]    F = [FL; FR]'                                newline ...
''                                                                       newline ...
'mm  = 211;    Izz = 653;'                                               newline ...
'Xu  = 100;    Xuu = 150;'                                               newline ...
'Yv  = 100;    Yvv = 100;'                                               newline ...
'Nr  = 800;    Nrr = 800;'                                               newline ...
'b   = 1.027135;          % half beam of the aft thrusters [m]'          newline ...
''                                                                       newline ...
'u = s(1); v = s(2); r = s(3); psi = s(6);'                              newline ...
''                                                                       newline ...
'% differential thrust -> surge force and yaw moment'                    newline ...
'X = F(1) + F(2);'                                                       newline ...
'N = (F(1) - F(2))*b;'                                                   newline ...
''                                                                       newline ...
'Dx = (Xu + Xuu*abs(u))*u;'                                              newline ...
'Dy = (Yv + Yvv*abs(v))*v;'                                              newline ...
'Dn = (Nr + Nrr*abs(r))*r;'                                              newline ...
''                                                                       newline ...
'du = (X - Dx)/mm + v*r;     % rigid-body Coriolis'                      newline ...
'dv = (  - Dy)/mm - u*r;'                                                newline ...
'dr = (N - Dn)/Izz;'                                                     newline ...
''                                                                       newline ...
'xdot = [du; dv; dr;'                                                    newline ...
'        u*cos(psi) - v*sin(psi);'                                       newline ...
'        u*sin(psi) + v*cos(psi);'                                       newline ...
'        r];']);

    add_block('simulink/Continuous/Integrator', [m '/Integ'], ...
              'Position',[820 175 870 225], 'InitialCondition','[0;0;0;0;0;0]');

    add_block('simulink/User-Defined Functions/MATLAB Function', [m '/States'], ...
              'Position',[930 130 1080 270]);
    setFcn(m, 'States', [ ...
'function [x_n, y_n, psi_deg, u, r_deg] = States(s)'          newline ...
'%#codegen'                                                 newline ...
'% Pull the numbers we want to look at out of the state.'   newline ...
'x_n = s(4);'                                                newline ...
'y_n = s(5);'                                                newline ...
'psi_deg = s(6)*180/pi;'                                    newline ...
'u  = s(1);'                                                newline ...
'r_deg = s(3)*180/pi;']);

    % --- 4단 · 관찰 -----------------------------------------------------
    add_block('simulink/Sinks/Scope', [m '/Scope_u'],   'Position',[1160 100 1200 140]);
    add_block('simulink/Sinks/Scope', [m '/Scope_psi'], 'Position',[1160 180 1200 220]);
    add_block('simulink/Sinks/XY Graph', [m '/Track'],  'Position',[1160 270 1220 330]);
    set_param([m '/Track'],'xmin','-20','xmax','120','ymin','-40','ymax','60');

    nm = {'x_n','y_n','psi','u','r'};
    for k = 1:numel(nm)
        b = [m '/log_' nm{k}];
        add_block('simulink/Sinks/To Workspace', b, ...
                  'Position',[1160 380+(k-1)*50 1260 410+(k-1)*50]);
        set_param(b,'VariableName',['log_' nm{k}], ...
                    'SaveFormat','Timeseries','SampleTime','0.05');
    end

    % --- 배선 -----------------------------------------------------------
    add_line(m, 'Clock/1', 'Scenario/1', 'autorouting','on');
    add_line(m, 'Scenario/1', 'MuxF/1', 'autorouting','on');
    add_line(m, 'Scenario/2', 'MuxF/2', 'autorouting','on');
    add_line(m, 'MuxF/1', 'MotorLag/1', 'autorouting','on');
    add_line(m, 'MotorLag/1', 'EOM/2', 'autorouting','on');
    add_line(m, 'EOM/1', 'Integ/1', 'autorouting','on');
    add_line(m, 'Integ/1', 'EOM/1', 'autorouting','on');
    add_line(m, 'Integ/1', 'States/1', 'autorouting','on');
    add_line(m, 'States/4', 'Scope_u/1', 'autorouting','on');
    add_line(m, 'States/3', 'Scope_psi/1', 'autorouting','on');
    add_line(m, 'States/2', 'Track/1', 'autorouting','on');     % y (동쪽) 를 가로축으로
    add_line(m, 'States/1', 'Track/2', 'autorouting','on');     % x (북쪽) 를 세로축으로
    for k = 1:numel(nm)
        add_line(m, sprintf('States/%d',k), ['log_' nm{k} '/1'], 'autorouting','on');
    end

    set_param(m, 'SolverType','Fixed-step', 'SolverName','ode4', ...
                 'FixedStep','0.05', 'StopTime','80', 'SimulationMode','normal');
    note(m, sprintf(['[5단계] 오프라인 WAM-V — Gazebo 없이 같은 실험\n' ...
        '시나리오 블록은 2단계(W04_2_turn)와 완전히 같다.\n' ...
        '뒤에 Publish 대신 WAM-V 운동방정식이 붙어 있다.\n' ...
        '0~20s 직진 / 20~40s 우선회 / 40~60s 좌선회 / 60s~ 정지\n' ...
        '계수는 전부 Gazebo VRX 플러그인에서 가져온 값이다.\n' ...
        '실행 뒤 >> W04_offline_plot 으로 그림을 본다.']), 40, 660);
    save_system(m); close_system(m,0);
    fprintf('  [OK] %s\n', m);
end
